influxdata/chronograf

ui/src/tempVars/components/TemplateControl.tsx

Closes #3912
It was checking for role of editor around the entire label instead of just the cog.
Move the authorization check to only include the cog and not the entire temp var label.

Make template variable names visible to visitors

---

ui/src/logs/containers/LogsPage.tsx
ui/src/reusable_ui/types/index.ts

This PR adds a marker on the histogram with the current timestamp. This is part of the enhancement to tie the Logs Histogram to the Logs Table.

Add timestamp marker to histogram

---

ui/src/tempVars/utils/replace.ts
ui/test/tempVars/utils/replace.test.ts

Closes #3853 
The [templateReplace](https://github.com/influxdata/chronograf/blob/5734a8eda7397cbcbc01755c6aeb4b6f6ab2e74a/ui/src/tempVars/utils/replace.ts#L53-L60) accepts a query string with embedded template variables, and a list of templates used to replace those variables.
For example, given the query `SHOW MEASUREMENTS ON ":db:"` and the template `:db: = telegraf`, the `templateReplace`d query string should be `SHOW MEASUREMENTS ON "telegraf"`.
Here's another example:
- The query string is again `SHOW MEASUREMENTS ON ":db:"`
- The templates are
- `:db: = :otherDb:` (this can be defined by the user in CSV and Map templates)
- `:otherDb: = telegraf`
This query should also be replaced as `SHOW MEASUREMENTS ON "telegraf"`. A slightly less contrived example is given in #3853.
Due to the …

Use sorted templates in query template replacement

---

.bumpversion.cfg
bolt/cell.go
bolt/client.go
integrations/server_test.go
mocks/cells.go
mocks/store.go
server/cellsv2.go
server/cellvs2_test.go
server/mux.go
server/routes.go
server/routes_test.go
server/server.go
server/stores.go
server/swagger.json
server/swagger_v2.yml
v2/cell.go
v2/cell_test.go
v2/error.go

This PR introduces a `cells` API for directly interacting with cells. Cells are now a separate resource from dashboards. This was done under `v2`. This work was done in progression towards a `v2` dashboards API.
TODO

Add v2 cells API to chronograf

---

ui/src/logs/components/LogsTable.tsx

Closes #3931 
Function dealing with vertical scroll was always setting ScrollLeft to 0. 
Dont set scrollLeft in the function dealing with vertical scroll.

Fix horizontal scrolling in logs table

---

ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/time_series/TimeSeries.tsx

Closes #3937 
editQueryStatus was not being passed to the new timeSeries

Pass editQueryStatus to the timeseries component

---

ui/src/tempVars/utils/graph.ts
ui/test/tempVars/utils/graph.test.ts

The recent template variable hydration refactors (#3924, #3950, 9eb897cce63fe090bf66af10ff246e75e97cde0f) broke our support for `Map` template variables. 
From a user perspective, the issue presents like this:
Internally, the issue is that we don't propagate `Map` template variable selections (e.g. `selected` and `localSelected` state) correctly during template variable rehydration. 
This PR addresses the issue by splitting our resolution of template variable selections into two cases: query-backed template variables, and non-query backed template variables. The non-query backed selection resolution now handles `Map` selections appropriately.

Ensure Map templates track selections

---

CHANGELOG.md
ui/src/tempVars/utils/replace.ts
ui/test/tempVars/utils/replace.test.ts

Closes #3979 
Template variables used within regexes would not replace correctly when the query contained a `/` before the regex in the query, e.g. the following query breaks:
```
SELECT last("max") from (SELECT max("total")/1073741824 FROM "telegraf".."mem" WHERE "cluster_id" = :Cluster_Id: AND (host =~ /.*data.*/ OR host =~ /tot-.*-(3|4)/) GROUP BY time(1s), host)
```
This commit rewrites the logic for replacing template variables. It uses an iterative approach, since the `RegExp.match` used in the past has shown to be too unpredictable.

Fix template variable replacement within regexes

---

ui/src/shared/components/SingleStat.tsx

Prevent Single Stat Text With Descenders From Clipping

---

CHANGELOG.md
ui/src/shared/graphs/helpers.ts

Closes #3992
add a small margin top to push dygraph legend down if the dygraph legend is rendering at the top of the graph instead of the bottom

Easier to get into hover legend

---

CHANGELOG.md
ui/src/shared/components/HistogramChart.tsx
ui/src/shared/components/HistogramChartBars.tsx
ui/src/utils/svg.ts

Closes #3968
The `HistogramChart` uses SVG `clip-path=url(#some-element-id)` properties in it's implementation. With basepath enabled, Chronograf rewrites all instances of `url(` as `url(/basepath` when serving assets, which breaks these usages of `clip-path`.
This commit introduces a utility to properly encode urls in `clip-path` properties using a hacky workaround (dynamically render `url(` client-side so it's never rewritten by Chronograf). While we could address the issue server side (in `server/url_prefixer.go`), it's likely not worth it given the looming Chronograf 2.0 epoch.
See also https://github.com/influxdata/chronograf/pull/3402

Fix histogram overflow issue when using basepath

---

ui/src/logs/actions/index.ts
ui/src/logs/containers/LogsPage.tsx

If no current source for log viewer, use default

---

CHANGELOG.md
ui/src/dashboards/containers/DashboardsPage.tsx
ui/src/types/dashboards.ts

Closes #4032
Exported dashboard cells have links to sources which contain the source's id but it does not contain any other information about the sources.
Create an object that maps the names of sources to their ids and export that under the meta section of the export file.

Add a mapping of sources ids and names to dashboard export

---

ui/src/logs/constants/index.ts

Closes# 4035
Windows for log viewer needed to be larger increments
Update time range values

Update log viewer time ranges

---

CHANGELOG.md
ui/src/kapacitor/components/RuleGraph.tsx

Closes #3973
The hover line was not showing up in alert rule. 
Connect rule graph to redux store.

Connect Rule Graph to redux store to set hover time on hover

---

ui/src/logs/components/LogsTable.tsx

Fixes showing truncated value in application filter tooltip

Show full value in filter tooltip

---

ui/src/shared/components/Layout.tsx
ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/time_series/TimeSeries.tsx
ui/src/types/layout.ts

Closes #3964 
Download CSV was disable in for cells that should be downloadable.
AutoRefresh used to take an optional handler to update a Cell's data using `grabDataForDownload`. These changes reintroduce that behavior into the TimeSeries component.

Fix cell CSV downloading

---

ui/src/dashboards/components/DashboardsPageContents.tsx
ui/src/reusable_ui/components/panel/Panel.scss
ui/src/reusable_ui/components/panel/Panel.tsx
ui/src/reusable_ui/components/panel/PanelBody.tsx
ui/src/reusable_ui/components/panel/PanelFooter.tsx
ui/src/reusable_ui/components/panel/PanelHeader.tsx

This work is a subset of https://github.com/influxdata/chronograf/issues/3946
Introducing a set of components that render panels. Panels are a fairly common UI element found in most of the index pages.
```
import Panel, {PanelType} from 'src/reusable_ui/components/panel/Panel'
<Panel type={PanelType.Solid}>
<Panel.Header title="Dashboards">
<button>+ Create Dashboard</button>
</Panel.Header>
<Panel.Body>
(Contents)
</Panel.Body>
</Panel>
```
The `Panel` component will throw an error if you try to pass in a child that is not `Panel.Header`, `Panel.Body`, or `Panel.Footer`.
I have implemented this set of components on the Dashboards Index page as an example of usage

Reusable Panel Component Family

---

ui/src/reusable_ui/components/Button/Button.scss
ui/src/reusable_ui/components/Button/index.tsx
ui/src/reusable_ui/components/dropdowns/Dropdown.scss
ui/src/reusable_ui/components/dropdowns/Dropdown.tsx
ui/src/reusable_ui/components/dropdowns/DropdownButton.scss
ui/src/reusable_ui/components/dropdowns/DropdownButton.tsx
ui/src/reusable_ui/components/form_layout/Form.scss
ui/src/reusable_ui/components/form_layout/Form.tsx
ui/src/reusable_ui/components/inputs/Input.scss
ui/src/reusable_ui/components/inputs/Input.tsx
ui/src/reusable_ui/components/overlays/Overlay.scss
ui/src/reusable_ui/components/overlays/OverlayTechnology.tsx
ui/src/reusable_ui/components/panel/Panel.scss
ui/src/reusable_ui/components/panel/Panel.tsx
ui/src/reusable_ui/components/slide_toggle/SlideToggle.scss
ui/src/reusable_ui/components/slide_toggle/SlideToggle.tsx
ui/src/reusable_ui/index.ts
ui/src/reusable_ui/styles.scss
ui/src/style/chronograf.scss

Cannot currently import `.scss` files directly into components without build failure
Keep all the `reusable_ui` stylesheets where they are, but instead of importing them into their components import them into the main stylesheet `chronograf.scss`. Also removing the now redundant module imports in each stylesheet.
For icing on the cake I have created `reusable_ui/index.ts` file that exports all the enums and components which should make usage easier

Update Reusable UI Style Imports

---

ui/src/reusable_ui/components/card_select/CardSelectCard.scss
ui/src/reusable_ui/components/card_select/CardSelectCard.tsx
ui/src/reusable_ui/components/card_select/CardSelectList.scss
ui/src/reusable_ui/components/card_select/CardSelectList.tsx
ui/src/reusable_ui/components/card_select/test/CardSelectCard.test.tsx
ui/src/reusable_ui/components/card_select/test/CardSelectList.test.tsx
ui/src/reusable_ui/components/card_select/test/__snapshots__/CardSelectCard.test.tsx.snap
ui/src/reusable_ui/components/card_select/test/__snapshots__/CardSelectList.test.tsx.snap
ui/src/reusable_ui/styles.scss
ui/src/types/cardSelect.ts

Adds card select components for use in forms.
The user needs to select a set of dashboard templates as part of the new source adding flow.
Create cards that act as checkboxes that the user can use to decide which dashboard templates they want to use.

Card select component

---

chronograf.go
influx/annotations.go
influx/annotations_test.go
server/annotations.go
server/annotations_test.go
server/swagger.json

Closes #4072
Still need to add tests:
And also:

Add support for user-defined annotation tags

---

ui/src/logs/components/LogsTable.tsx

Closes #4110 
Firefox displays a horizontal scrollbar that covers text.
Set `overflow-x` to `hidden` to hide the scroll bar. Since the width of the header grid is computed this remedies the issue without clipping header text.

Fix scrollbar blocking header names

---

ui/src/dashboards/components/import_dashboard_mappings/ImportDashboardMappings.tsx
ui/src/logs/components/expandable_message/ExpandableMessage.tsx
ui/src/reusable_ui/components/Button/index.tsx
ui/src/reusable_ui/components/card_select/CardSelectCard.tsx
ui/src/reusable_ui/components/dropdowns/Dropdown.tsx
ui/src/reusable_ui/components/dropdowns/DropdownButton.tsx
ui/src/reusable_ui/components/form_layout/Form.tsx
ui/src/reusable_ui/components/inputs/Input.tsx
ui/src/reusable_ui/components/overlays/OverlayTechnology.tsx
ui/src/reusable_ui/components/panel/Panel.tsx
ui/src/reusable_ui/components/slide_toggle/SlideToggle.tsx
ui/src/reusable_ui/components/wizard/ProgressConnector.tsx
ui/src/reusable_ui/components/wizard/WizardButtonBar.tsx
ui/src/reusable_ui/components/wizard/WizardController.tsx
ui/src/reusable_ui/components/wizard/WizardFullScreen.tsx
ui/src/reusable_ui/components/wizard/WizardProgressBar.tsx
ui/src/reusable_ui/components/wizard/WizardStep.tsx
ui/src/style/chronograf.scss

We shouldn't have to do this, but it fixes a nefarious CI build issue that has been haunting us of late. We should be able to revert this after [this](https://github.com/parcel-bundler/parcel/pull/1847) PR lands in our build too, Parcel.

Centralize Sass imports

---

ui/src/dashboards/actions/index.ts

Closes #4136
Clicking the "Add Cell" button added an empty cell to the dashboard, at which point the user would have to click on the edit button in order to open the Cell Editor Overlay in order to add information to the cell
Have the CEO open when the user clicks the "Add Cell" button by adding a call to the `showCellEditorOverlay` action in the `addDashboardCellAsync` action.

Call showCellEditorOverlay action when new cell added to dashboard

---

ui/src/logs/constants/index.ts
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/utils/timeBounds.ts

Closes #3970 
Clicking on the histogram did not clearly indicate the time bounds shifts and time option overlay changes taking place in the histogram. The histogram would also change scale when clicked.
Maintain scale to the user selected period and only shift (offset) histogram time bounds for clicks on bars outside the central region of the histogram.

Enhance histogram click behavior

---

ui/src/flux/apis/index.ts
ui/src/shared/apis/flux/metaQueries.ts

Closes #4040 
The api for flux changed and including the path and query params. This will account for those changes.
Contains a temporary solution for annotations not showing up in responses.

Update flux queries based on flux api changes

---

ui/src/dashboards/actions/cellEditorOverlay.ts
ui/src/dashboards/actions/index.ts
ui/src/dashboards/components/CellEditorOverlay.tsx
ui/src/dashboards/constants/index.ts
ui/src/dashboards/containers/DashboardPage.tsx
ui/src/dashboards/reducers/cellEditorOverlay.ts
ui/src/dashboards/utils/cellGetters.ts
ui/src/types/dashboards.ts
ui/test/dashboards/reducers/cellEditorOverlay.test.ts

Closes #4153
Clicking the "Add Cell" button would take the user to the Cell Editor Overlay but the new cell was already created, so that if the user clicked "cancel," there would already be a new empty cell in the dashboard.
Open the CEO without saving a new cell, then only save the new cell once a query has been added.

Prevent creating empty cell upon cancel in CEO

---

ui/src/reusable_ui/components/Button/index.tsx
ui/src/shared/components/AnnotationFilterControl.tsx
ui/src/shared/components/AnnotationFilterControlInput.tsx

Some minor tweaks to the `AnnotationFilterControl` and related components:
- Tab should cycle through inputs in correct order
- Blurring inputs should dismiss the suggestions popup always
- Clicking an input should show all suggestions, even when that input is non-empty

Annotations polish

---

ui/src/dashboards/components/DashboardsPageContents.tsx
ui/src/reusable_ui/components/dropdowns/MultiSelectDropdown.tsx
ui/src/reusable_ui/components/dropdowns/test/MultiSelectDropdown.test.tsx
ui/src/reusable_ui/components/dropdowns/test/__snapshots__/MultiSelectDropdown.test.tsx.snap
ui/src/reusable_ui/index.ts

This PR is a subset of the work described in https://github.com/influxdata/chronograf/issues/3946
`MultiSelectDropdown` works like the standard `Dropdown` component but with some modified and extended functionality.
You will need state to store the `selectedIDs` for the component
```
interface State {
selectedDropdownIDs: string[]
}
this.state = {
selectedDropdownIDs: [],
}
```
Then define your list of dropdown items as you would with the standard `Dropdown` component:
```
interface sampleItem {
id: string
text: string
}
const dropdownItems: sampleItem[] = [
{
id: 'sample-item-1',
text: 'Apple',
},
{
id: 'sample-item-2',
text: 'Banana',
},
{
id: 'sample-item-3',
text: 'Pineapple',
},
]
```
Now you need to write a handler function for the `onChange` prop. Unlike the standard `Dropdown` …

Introduce Multi-Select Dropdown Component

---

CHANGELOG.md
chronograf.go
filestore/protoboards.go
filestore/protoboards_test.go
mocks/protoboards.go
mocks/store.go
server/mux.go
server/protoboards.go
server/protoboards_test.go
server/server.go
server/stores.go

Closes #4080 
The user needed a way to instantiate dashboards from a template like structure during for example the onboarding wizard process. 
We implemented a API that can serve protoboards from .json files on the filesystem, in the /protoboards directory.

feat: protoboard api

---

ui/src/reusable_ui/components/wizard/WizardTextInput.tsx
ui/src/sources/components/KapacitorForm.tsx
ui/src/sources/components/SourceStep.tsx

Closes #
There was no password type input field in wizard
created a prop to make password type input fields

Add password input text field to WizardTextInput

---

CHANGELOG.md
ui/src/shared/actions/app.ts

Closes #4161 
Notification to user to `Press ESC to exit presentation mode` was not showing anymore.
Dispatch the `notify` action that generates the notification. This was probably lost in the notifications refactor.

fix: notify user to press esc upon entering presentation mode

---

CHANGELOG.md
ui/src/logs/utils/index.ts

Closes #4188 
The threshold for the number of results in the exponential back off for logs results was large enough that it slowed the user scrolling experience by issuing too many queries
See how low we could go by doing the results count limbo.

Update chunk size for logs table

---

CHANGELOG.md
ui/src/dashboards/containers/DashboardPage.tsx
ui/src/shared/actions/app.ts
ui/src/shared/constants/index.ts
ui/src/shared/reducers/app.ts
ui/src/types/actions/app.ts
ui/test/shared/reducers/app.test.ts

Closes #4138 
Template variable control bar was set to always start as closed and whether or not it was open was stored in component state.
Move aforementioned state out of component and into redux to persist.

Fix template variable control bar not persisting whether it was open

---

ui/src/reusable_ui/components/wizard/WizardTextInput.tsx
ui/src/sources/components/KapacitorStep.tsx
ui/src/sources/components/SourceStep.tsx

Closes #4198 
_Desired behavior_ 
On new source creation or when editing a source in the onboarding and connection wizards, when a user enters a url with hostname `http://hostname:port` for their influxdb source, we would like to automagically update their metaUrl hostname (on same wizard step), and their kapacitor hostname (on next wizard step) to match.
Add an onSubmit action to WizardTextInput, which is called onBlur or on keyboarding `enter`, with the input field text.
Add onSubmit action to the `url` WizardTextInput of sourceStep, which edits the metaUrl hostname to match the source hostname. 
Add syncHostnames function to constructor of kapacitorStep which checks and syncs hostname to source.

Add hostname syncing between source url, and kapacitor

---

CHANGELOG.md
ui/src/data_explorer/actions/view/index.ts

Closes #4199
Upon hitting `Submit Query` in the Data Explorer, no queries were successful, whether for regular or metaqueries.
Fix the faulty shape of the object sent to the `/queries` endpoint to match what's expected.

fix: pass correct fields to /queries to fix de submit query button

---

ui/src/shared/copy/notifications.ts
ui/src/sources/components/SourceStep.tsx

Closes #4197 
_What was the problem?_ 
The onboarding and connection wizards need to be able to display a metaUrl field -which is displayed if a source isEnterprise- before user clicks next on the sourceStep
Add to the onSubmit function of the url text field in sourceStep, so that when the url field is blurred the source is created or updated without alerting the user. The source returned from server has information on whether it isEnterprise, and if it is, the metaUrl field is displayed.

Add source creation to onSubmit on SourceStep

---

CHANGELOG.md
ui/src/logs/components/LogsTable.tsx
ui/src/logs/components/expandable_message/ExpandableMessage.tsx
ui/src/logs/components/logs_message/LogsMessage.scss
ui/src/logs/components/logs_message/LogsMessage.tsx
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/utils/matchSections.ts
ui/src/types/logs.ts
ui/test/logs/utils/matchSections.test.ts

Closes #4255 
It was hard to identify search filters being applied in the log viewer. A user might presume the UI was presenting stale results for a search query.
Adding color to the matched search expressions in the logs table helps the eye spot the term in the result and see the relevant log lines as a query runs.

Enhance logs search term highlighting

---

CHANGELOG.md
ui/src/logs/components/LogsSearchBar.tsx
ui/src/logs/components/LogsTable.tsx
ui/src/logs/components/loading_status/LoadingStatus.tsx
ui/src/logs/constants/index.ts
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/utils/table.ts
ui/src/style/pages/logs-viewer.scss
ui/src/types/logs.ts

Closes #4246 
It was unclear when the logs table was awaiting search results after a search filter was added. Table rows might appear to be stale.
Add a search status that is updated when a search is performed and render a corresponding loading message for no results, loading, or loaded table data.

Clear logs after search

---

ui/src/shared/components/AnnotationEditorForm.tsx
ui/src/shared/components/AnnotationTagEditorLi.tsx

Closes #4135
While in the `AnnotationEditorForm` the user would have to manually click the "add tag" button to create a new tag. 
Add an onKeyDown method so that when the user hits the "enter" key when they have finished adding the value for a tag, a new tag will be automatically created and the focus will be shifted to the tag key input. Empty tag key/value pairs are automatically filtered out before saving.

Add onKeyDown method to create new tag in annotation editor on enter

---

ui/src/logs/components/LogsHeader.tsx
ui/src/logs/containers/LogsPage.tsx

Inconsistent component name for LogViewerHeader, whereas all other components are prefixed with Logs, made it confusing to search for.
Rename component and file.

refactor: rename LogViewerHeader to LogsHeader for consistency

---

ui/src/shared/components/LayoutCellNote.tsx

This most likely is not a big issue, because restarting the chronograf server prevents this from happening, but just in case this PR adds a guard against nonexistent cell notes.

Guard against nonexistent note

---

ui/src/dashboards/components/DashboardEmpty.tsx

Closes #4270
The method to create a new cell in a dashboard was changed in another PR so that it now accepts a dashboard and an empty default cell, rather than a dashboard and a type. This had not yet been updated in the `DashboardEmpty` component, which was causing the application to encounter an error when the user tried to add a cell to an empty dashboard.
Change the call to `addDashboardCell` to use an empty cell.

Change addDashboardCall to use new default cell template

---

CHANGELOG.md
ui/src/dashboards/actions/cellEditorOverlay.ts
ui/src/dashboards/components/CellEditorOverlay.tsx
ui/src/dashboards/components/Visualization.tsx
ui/src/dashboards/containers/DashboardPage.tsx
ui/src/dashboards/reducers/cellEditorOverlay.ts
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/shared/components/TimeMachine/TimeMachineControls.tsx
ui/src/style/unsorted.scss
ui/test/dashboards/reducers/cellEditorOverlay.test.ts

Closes #4141 
Add time selector dropdown into time machine. Store state in redux.
The time selector will default to the time set for the dashboard. This time selector does not update the time for the entire dashboard.

Add timeSelectorDropdown to timeMachine

---

ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/time_series/TimeSeries.tsx

Closes #4252
When autorefresh was paused, hitting the "refresh" button didn't do anything. 
Passing a `manualRefresh` prop to the `TimeSeries` component from `RefreshingGraph` and calling a force update if this prop changes.

Add manualRefresh prop to TimeSeries component to fix refresh bug

---

ui/src/reusable_ui/components/card_select/CardSelectCard.scss
ui/src/reusable_ui/components/card_select/CardSelectCard.tsx
ui/src/reusable_ui/components/card_select/ProtoboardIcon.scss
ui/src/reusable_ui/components/card_select/ProtoboardIcon.tsx
ui/src/reusable_ui/components/card_select/test/__snapshots__/CardSelectCard.test.tsx.snap
ui/src/reusable_ui/components/grid_sizer/GridSizer.tsx
ui/src/style/chronograf.scss

Create generic icons for dashboards which are missing icons.
Dashboards without icons in their metadata need to be displayed in the dashboard selection step.
Create customizable icon with dashboard initial

Add generic dashboard selection icons

---

server/url_prefixer.go
ui/package.json
ui/parcel.js
ui/src/worker/JobManager.ts

- Rewrites `new Worker('./my/path')` paths server side to handle base path config (like other assets)
- This enables us to develop on `localhost:8080` again
- Displays a more friendly error when proxying to `localhost:8888` fails

Rewrite Worker script paths according to basepath

---

CHANGELOG.md
ui/src/dashboards/components/CellEditorOverlay.tsx
ui/src/dashboards/components/SourceSelector.tsx
ui/src/dashboards/containers/DashboardPage.tsx
ui/src/flux/components/BodyBuilder.tsx
ui/src/flux/components/DatabaseList.tsx
ui/src/flux/components/DatabaseListItem.tsx
ui/src/flux/components/ExpressionNode.tsx
ui/src/flux/components/FluxQueryBuilder.tsx
ui/src/flux/components/SchemaExplorer.tsx
ui/src/flux/components/TagList.tsx
ui/src/flux/components/TagListItem.tsx
ui/src/flux/components/TagValueList.tsx
ui/src/flux/components/TagValueListItem.tsx
ui/src/flux/containers/FluxPage.tsx
ui/src/flux/helpers/scriptBuilder.ts
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/test/flux/components/FluxQueryBuilder.test.tsx
ui/test/flux/containers/FluxPage.test.tsx

Closes: https://github.com/influxdata/applications-team-issues/issues/3 and https://github.com/influxdata/applications-team-issues/issues/4
Only InfluxQL queries could be created from the Cell Editor Overlay. Furthermore, there was some repetitiveness with shared/TimeMachine and flux/TimeMachine.
* Replace flux/TimeMachine with FluxQueryBuilder and use FluxQueryBuilder component in CEO
* Move helper functions to a utils files that can be used for both FluxPage and CEO
* Replace NotificationContext and FluxContext with passing props down

View flux editor in the CEO

---

ui/src/shared/graphs/helpers.ts

Take into account the graph's X & Y relative to the browser frame when positioning the legend
Also fixing a case in which the legend would render off the top of the screen
I broke the legend with #4296 
I fixed the fixing

Fix the legend for real

---

ui/src/dashboards/components/CellEditorOverlay.tsx
ui/src/dashboards/components/Dashboard.js
ui/src/dashboards/components/Visualization.tsx
ui/src/dashboards/containers/DashboardPage.tsx
ui/src/data_explorer/components/VisView.tsx
ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/hosts/containers/HostPage.js
ui/src/shared/components/Layout.tsx
ui/src/shared/components/LayoutRenderer.tsx
ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/shared/components/TimeMachine/TimeMachineControls.tsx
ui/src/shared/components/dropdown_auto_refresh/AutoRefreshDropdown.tsx
ui/src/shared/components/time_series/TimeSeries.tsx
ui/src/status/containers/StatusPage.tsx
ui/src/style/unsorted.scss
ui/src/utils/AutoRefresh.ts
ui/src/utils/AutoRefresher.ts

Closes #4140
Adds a control for the auto refresh interval to the CEO:
I did some refactoring here. It's probably easiest to review commit by commit.

Add auto refresh control to CEO

---

ui/src/shared/components/TimeMachine/InfluxQLQueryMaker.tsx

Just something tiny I noticed. Before:
After:

Remove redundant button from empty queries state

---

ui/src/kapacitor/components/RuleGraphDygraph.tsx

The rule graph on the _Alert Rule Builder_ page will not render. The following error is thrown in the console:
```
Uncaught TypeError: Cannot read property 'timeSeriesToDygraphResult' of null
at Wrapped.render (eval at hmrApply (runtime.js:737), <anonymous>:155:56)
at Wrapped.render (_task.js:85)
at finishClassComponent (_add-to-unscopables.js:2)
at updateClassComponent (_add-to-unscopables.js:2)
at beginWork (es6.array.iterator.js:35)
at performUnitOfWork (_meta.js:54)
at workLoop (_meta.js:54)
at HTMLUnknownElement.callCallback (_export.js:63)
at Object.invokeGuardedCallbackDev (_export.js:63)
at invokeGuardedCallback (_export.js:63)
```
The issue is some invalid property access in the `RuleGraphDygraph` component.
Solution: refactor lifecycle logic in the `RuleGraphDygraph` component.

Fix RuleGraphDygraph

---

ui/src/localStorage.ts

Script in data explorer didnt have a default value.
Give script a default value when pulling out of local storage.

Add default for data explorer script in local storage

---

ui/src/shared/components/AnnotationFilterControlInput.tsx

Closes #4251
These changes fix the following bug:
1. Type text into an `AnnotationFilterControl` that does not match any suggestions in the dropdown
2. Press enter
3. The string "undefined" gets selected
The fix is to fallback to exactly what text the user entered when selecting if no suggestion is available.

Fix annotation filter control undefined bug

---

ui/src/shared/components/TimeMachine/InfluxQLQueryMaker.tsx
ui/src/style/components/query-maker.scss

In the CEO/DE when you drag the Threesizer down the InfluxQL query builder becomes distorted and unusable
Wrap the query builder in a scroll container

Scroll Query Builder instead of Squish when bottom of DE/CEO is small

---

ui/src/reusable_ui/components/radio_buttons/RadioButtons.scss

Radio buttons rendering at 28.97 pixels causing a weird extra thick border on the bottom
Use a simpler way to handle borders on the buttons which ensures proper sizing

Fix subpixel height of Radio Buttons

---

ui/package.json
ui/src/shared/components/Dygraph.tsx
ui/src/shared/graphs/helpers.ts
ui/yarn.lock

Closes #4337
This PR makes a number of changes to the `Dygraph` component to avoid unnecessary rerenders.
- Only call `updateOptions` on the dygraph instance when options have changed, since updating the options triggers a redraw.
- Don't call `Dygraph#resize` on `Dygraph#componentDidUpdate`. Redrawing in response to a legitimate resize is already handled by the `ReactResizeDetector` child of a `Dygraph`. 
- Don't call dygraph private instance methods `resizeElements_` and `predraw_` in the resize method. They are expensive and also redudant since `resize` is called on the dygraph instance in `Dygraph#resize` as well.
- Memoize calls to `src/shared/parsing/getRangeForDygraph`, which can be expensive since it must traverse the entire time series.
- Extract the logic of what options to pass …

Refactor Dygraph component

---

ui/src/flux/components/FilterTagListItem.tsx
ui/src/flux/components/TagListItem.tsx
ui/src/flux/constants/builder.ts
ui/src/flux/constants/editor.ts
ui/src/shared/apis/flux/metaQueries.ts
ui/test/flux/ast/complex.ts
ui/test/flux/ast/walker.test.ts

Because changes in flux dbs are now referred to as buckets

Use bucket instead of db for flux queries

---

ui/src/dashboards/components/DashboardsPageContents.tsx
ui/src/dashboards/components/DashboardsTable.tsx
ui/src/dashboards/containers/DashboardsPage.tsx
ui/src/style/pages/dashboards.scss
ui/test/dashboards/components/DashboardsPage.test.tsx

Closes #4185
Adds a few more possible states to the dashboards page UI.
Loading:
Error: 
Previously the empty state showed in both these cases:

Add loading and error states to DashboardsPage

---

server/server.go

The `--pprof-enabled` flag was not being passed down to the mux.
Pass the flag to the mux.

fix(server): pass pprof enabled option down to NewMux properly

---

server/services.go

When adding or updating a flux service, regardless of whether your url was valid, it always returned a response saying it could not connect to the service, and therefore it could not get added.
Remove the pingFlux check when adding and updating a flux service. This does mean that if you have an incorrect url, it will allow you to make a connection. This is ok for now since flux will not be a separate service and this step will not be necessary.

Remove check for flux ping when adding and updating flux service

---

ui/src/reusable_ui/components/dropdowns/Dropdown.tsx

Changes the reusable UI `Dropdown` component to work like the `MultiDropdown` component. If no explicit `widthPixels` prop is passed, the dropdown will expand to the width of it's container.

Size Dropdown dynamically by default

---

ui/src/utils/buildQueriesForLayouts.ts

Closes #4368 
Queries that were not supported by the schema explorer (such as those with non-negative derivatives in the query) were getting additional where clauses added to the end of them.
This was caused by a change that was made to the way layouts buildingQueriesForLayouts. Instead of checking for the presence of a queryconfig, it was checking to see if queryConfig.db was empty.
Change that check back to just checking for queryconfig.

Fix adding additional where clauses on queries not supported by schema explorer

---

ui/src/shared/components/TimeMachine/TimeMachine.tsx

Deleting every query from the data explorer caused the page to crash.
Add a default of empty string to `querySource` so that calling `includes()` on `querySource` does not result in an error.

Add default empty string to querySource

---

ui/src/reusable_ui/components/page_layout/Page.scss
ui/src/style/components/tables.scss
ui/src/style/layout/page-subsections.scss
ui/src/style/theme/_panels.scss

Alert History & Host List pages were affected by #4339 
Give the flex layout harder constraints so it doesn't get too tall. Refactored some styles pertaining to alert history & hosts list pages

Prevent Page Contents from Exploding

---

ui/src/dashboards/components/CellEditorOverlay.tsx

Closes: https://github.com/influxdata/applications-team-issues/issues/55
When an influxQL source was selected before a query was written in the CEO, the source did not get saved to the cell. Instead, the CEO would open to "dynamic source" for that cell.
Using the source link from the query rather than the queryConfig object.

Fix InfluxQL source saving

---

ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/TableGraph.tsx

Co-authored-by: Brandon Farmer <bthesorceror@gmail.com>
Closes #4320 
There was a race condition when updating table graph in an editor. 
Refreshing graph will only force update TimeSeries if visualization options have changed and not just any time its in the editor. TableGraph will update any time its in the editor and not just if data is different.

Properly update tablegraph when in editor

---

ui/src/sources/components/KapacitorDropdown.tsx

Closes #4332 Add Kapacitor Connection opens wizard to Dashboards step
When the user clicks the Add new Kapacitor button it takes them to the correct wizard step.
When the user clicks the Add new Kapacitor button it takes them to the dashboard wizard step. This is because the step index was not updated when the dashboard step was added.
Correct the index from 1 to 2.

Correct wizard step index for Kapacitor Step

---

ui/src/flux/components/TimeMachineVis.tsx
ui/src/flux/containers/FluxPage.tsx
ui/src/shared/components/Layout.tsx
ui/src/shared/components/LayoutCell.tsx
ui/src/shared/components/LayoutCellMenu.tsx
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/shared/components/TimeMachine/TimeMachineControls.tsx
ui/src/style/pages/time-machine.scss
ui/src/types/flux.ts

Closes: https://github.com/influxdata/applications-team-issues/issues/54
Placing the `TimeMachineVis` component in the `LayoutCell` caused the Flux graph to overflow the cell. The raw data slide toggle also shifted the layout of components in `TimeMachine`.
Moving the raw data slide toggle to the header above `TimeMachine` in data explorer and CEO, and changing the slide toggle to an option in the pencil drop-down menu in the `LayoutCell`.

Move raw data toggle out of visualization in CEO/LayoutCell

---

CHANGELOG.md
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/reducers/index.ts

Closes #4335 
Update log search filters to add on the left rather than the right
Logs filters would be pushed on to the end of the logs filters list making it hard to find and correct a typo.
Add search filters to the left.

Update add filters to add to the left

---

CHANGELOG.md
ui/src/dashboards/components/CellEditorOverlay.tsx
ui/src/dashboards/components/SourceSelector.tsx
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/shared/components/TimeMachine/TimeMachineControls.tsx
ui/src/style/components/source-selector.scss

Closes https://github.com/influxdata/applications-team-issues/issues/45
When "dynamic source" was selected in the CEO, the user could not switch between Flux and InfluxQL without switching sources in the dropdown.
Add a toggle for Flux/InfluxQL that appears next to the `SourceDropdown` only if "dynamic source" is selected and the current source supports Flux.

Toggle for Flux/InfluxQL for dynamic source in CEO

---

ui/src/dashboards/components/SourceSelector.tsx
ui/src/shared/components/TimeMachine/TimeMachine.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/9
If the user selected "dynamic source," it was not clear whether or not a Flux service could be used.
If the dynamic source being used does not support Flux, then the Radio button to toggle Flux/InfluxQL becomes disabled and a tooltip appears to alert the user that the source does not support Flux.

Add tooltip for dynamic source that does not support flux

---

ui/src/shared/components/TimeMachine/TimeMachine.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/58
When opening an existing cell w/ a Flux query in the CEO, the save button was disabled.
Set the `currentService` in the CEO when TimeMachine mounts.

Update service in CEO when Time Machine renders

---

CHANGELOG.md
ui/src/alerts/components/AlertsTable.tsx
ui/src/alerts/components/AlertsTableRow.tsx
ui/test/alerts/components/AlertsTableRow.test.tsx

Closes #4342 
Invalid data from InfluxDB (such as if `level` was `null`), would cause the Alerts Table on the Status Page to error out.
- Check for `null` on any data point values passed to Alerts Table and render an mdash (`–`) if so.
- Refactor AlertsTable rows into AlertsTableRow component for clarity and ease of testing.

Render null data point values in Alerts Table as mdashes

---

CHANGELOG.md
ui/src/dashboards/components/InfluxQLEditor.tsx
ui/src/dashboards/components/ReactCodeMirror.tsx

Closes #2265 
Focuses dashboard query editor on mount 
Query editor props would be out of sync with codemirror editor
Check when focus prop was different from editor.hasFocus and then focus the editor

Autofocus dashboard query editor

---

CHANGELOG.md
ui/src/dashboards/components/InfluxQLEditor.tsx

Closes #4412 
Query editor would flicker a stale value after an update 
Prevent updating immediately after the submission. It also focuses the query after the active editor tab changes.

Fix query editor flickering on update

---

CHANGELOG.md
ui/src/dashboards/components/InfluxQLEditor.tsx

Closes #4427 
Closes #4412
A bug in the `isSubmitted` logic for `getDerivedStateFromProps` in the InflxuQLEditor prevented query updates from generated statements that have the same query config id, but also, the `isSubmitted` status was changing to true before a submission had completed causing `getDerivedStateFromProps` to replace editor text with a stale props query causing a flicker of old text.
Remove the bad `getDerivedStateFromProps`  condition and update query submission to await the `promise` of the wrapped `props.onUpdate`.

Fix query editor rejecting updates

---

ui/src/data_explorer/components/DEHeader.tsx
ui/src/reusable_ui/components/page_layout/PageHeaderLeft.tsx
ui/src/reusable_ui/components/page_layout/PageHeaderRight.tsx
ui/src/side_nav/containers/SideNav.tsx

Closes #4387 
Use proper page header components in Data Explorer
Change `Data Explorer` to `Explore` in side nav

Fix the Tiniest Header

---

ui/src/dashboards/components/AxesOptions.tsx
ui/src/dashboards/components/DisplayOptions.tsx
ui/src/shared/components/ColorScaleDropdown.tsx
ui/src/shared/components/LineGraphColorSelector.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/68
When all the children of display options were disconnected from redux and recieved their props from parent components, the dropdown component was missed so editing the line color dropdown did not modify the line graphs.
Disconnect the selector from redux and pass down options and handlers from parents.

Fix Color dropdown

---

ui/src/dashboards/actions/index.ts
ui/src/dashboards/components/CellEditorOverlay.tsx
ui/src/dashboards/components/DisplayOptions.tsx
ui/src/dashboards/constants/cellEditor.ts
ui/src/data_explorer/components/SendToDashboardOverlay.tsx
ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/types/dataExplorer.ts

Closes #4143 
DE was was sending visualization to dashboard by only amending the query portion of the default cell, so visualization options were being set to defaults. 
Pass visualization options down to sendtodashboard component and override default cell with properties from visualization options.

Send Visualization Options from DE to Dashboard

---

ui/src/logs/components/LogsTable.tsx
ui/src/logs/containers/LogsPage.tsx
ui/src/style/pages/logs-viewer.scss

QueryResults stats from the top left of logs table were more noisy than helpful
Remove the query results stats from the logs table

Remove logs table query stats

---

ui/package.json
ui/src/localStorage.ts
ui/src/shared/copy/notifications.ts

_Problem:_
We store our redux app state in localStorage. Every commit potentially changes the schema of this stored state. If the schema changes, we can't use it to rehydrate the redux store reliably. 
_Solution:_
Clear localStorage every commit. We already clear localStorage (for the most part) every release, so this is for development and for users of the nightly release.
This is a step towards debugging https://github.com/influxdata/chronograf/issues/4340.

Clear localStorage state upon every commit

---

ui/src/logs/components/loading_status/LoadingStatus.tsx
ui/src/logs/containers/LogsPage.tsx
ui/src/types/logs.ts

Closes #4425 
Switching sources would not refetch data, namespace switching would not refetch data, and unmount would not stop searching
Handle a source or namespace change and then refetch logs for the new source. Cancel all search chunks on unmount.

Refetch logs after source update

---

ui/src/dashboards/constants/index.ts
ui/src/dashboards/utils/notes.ts
ui/src/data_explorer/components/SendToDashboardOverlay.tsx
ui/src/data_explorer/containers/DataExplorer.tsx

Closes #4443 
Send to dashboard dropdown in data explorer was breaking when there were no dashboards to send to. 
Added a "send to new dashboard" option to dropdown which creates a new dashboard to send cell to.

Send cell from DE to a new dashboard

---

CHANGELOG.md
ui/src/shared/components/GaugeChart.tsx
ui/src/shared/components/LineGraph.tsx
ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/SingleStat.tsx
ui/src/shared/parsing/flux/parseTablesByTime.ts
ui/src/shared/parsing/lastValues.ts
ui/src/worker/JobManager.ts
ui/src/worker/jobs/fluxTablesToDygraph.ts
ui/src/worker/jobs/fluxTablesToSingleStat.ts
ui/src/worker/worker.ts
ui/test/shared/components/GaugeChart.test.tsx
ui/test/shared/parsing/lastValues.test.ts

Closes #4114 
Support flux data in single stat, line graph + single stat, and gauge chart.
Update line graph to only take in one data prop instead of a type for each language.

Flux in single stat graph types

---

ui/src/flux/apis/index.ts
ui/src/shared/components/TimeMachine/CSVExporter.tsx
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/shared/components/TimeMachine/TimeMachineControls.tsx
ui/src/shared/utils/downloadTimeseriesCSV.ts

Closes https://github.com/influxdata/applications-team-issues/issues/49
When viewing a Flux query in the DE/CEO, clicking the “Export CSV” button will download the CSV for the query. The CSV is in the format returned by `fluxd`.
I also took the opportunity to refactor `ui/src/flux/apis/index.ts` a bit.

Enable exporting a CSV for Flux queries in the CEO

---

CHANGELOG.md
ui/src/logs/actions/index.ts

Closes #4293
Load `wrap` or `truncate` log config setting saved in local storage.
Log viewer would not attempt to save a `truncate` or `wrap` preference and would default to `truncate` after page refresh.
Restore the log viewer message truncation preference in local storage after fetching the log config from  the server.

Save log wrap/truncate setting

---

ui/src/logs/components/HistogramResults.tsx
ui/src/logs/containers/LogsPage.tsx

Histogram continues to say 'updating' when search status is NoResults
Adds a switch/case for the Histogram that includes a No Results message

Add No Results Message For Histogram

---

ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/shared/components/TimeMachine/TimeMachine.tsx

Retain source on data explorer between refreshes

---

ui/src/dashboards/actions/index.ts
ui/src/data_explorer/components/SendToDashboardOverlay.tsx
ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/shared/copy/notifications.ts
ui/test/data_explorer/containers/DataExplorer.test.tsx

Closes #4443 again!
Send to Dashboard queries for dashboards on didMount so that dashboards are up to date if new ones have been created. 
Successes will be displayed all together, and failures will be displayed one by one at resolution of sendcell promises.

Fix notifications and dashboard getting in send to dashboard. 

---

ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/shared/components/time_series/TimeSeries.tsx
ui/src/types/queries.ts
ui/src/utils/buildQueriesForGraphs.ts

Closes: https://github.com/influxdata/applications-team-issues/issues/8
If the user had a Flux query cell set to dynamic source and then connected to a source w/o Flux enabled, then they would see "no results" in their cell without an explanation.
Add a type to the Query model, and then show an error message saying "the current source does not support Flux" if the query's type is Flux but there is no Flux service to connect to. (This method will have to be changed when Flux is not a separate service.)

Add error message when current source doesn't support Flux

---

ui/src/sources/components/ConnectionWizard.tsx

Closes #4356 
Wizard would redirect to source being edited even if user only manipulated kapacitor connection.
Check whether source has been edited, by comparing source in props and in state.

Check if source has been edited to decide where to redirect at wizard close. 

---

ui/src/logs/actions/index.ts
ui/src/logs/containers/LogsPage.tsx

Clear results before fetching source
The histogram data was not being cleared when a new search was submitted
Clear the histogram data when clearing old search data to improve responsiveness. Clear old histogram data before awaiting new source/namespace.

Improve source/namespace switching experience

---

ui/src/shared/parsing/flux/response.ts

Closes https://github.com/influxdata/applications-team-issues/issues/69
Flux responses include `_start` and `_stop` in the group key. We don't use these columns anywhere, 
but we do use the group key to give individual time series a name. This results in very long names such as
```
_value[_start=2018-09-17T17:58:21.265021Z][_stop=2018-09-17T17:59:21.265021Z][_field=active][_measurement=mem][host=bertrand.local]
```
This PR excludes `_start` and `_stop` keys from our parsed representation of the group key, so that the names are more reasonable:
```
_value[_field=active][_measurement=mem][host=bertrand.local]
```

Exclude '_start' and '_stop' columns from group key

---

CHANGELOG.md
server/mux.go
server/server.go

This PR improves the loading performance of static assets on devices
with low CPU, such as a Raspberry Pi or another embedded devices.
Loading Chronograf (as in the home page), is painfully slow on a Raspberry Pi or Pi-zero. It takes minutes just to load several static assets.
This PR does two things:
(1) Adds an option to explicitly disable gzip compression of requested
assets. Aside from having little CPU resources, these devices often don't have the intrinsics available that are used in compression schemes. This can make compression very expensive on these CPUs.
(2) Avoids the very expensive URL prefix Handler wrapper if no base
path has been set, which was making many redundant reads and textual searches on the assets that were being …

Improve asset loading performance on low power devices

---

ui/src/flux/components/TableSidebarItem.tsx
ui/src/flux/components/TimeMachineTables.tsx

Co-authored-by: Chris Henn <chris@chrishenn.net>
Closes https://github.com/influxdata/applications-team-issues/issues/83
Tablegraph was getting remounted on every refresh.
Use a more stable name for tables rather than uuid.

Update TimeMachineTables to use table name as id instead of uuid

---

ui/src/shared/components/TableGraph.tsx
ui/src/shared/parsing/flux/response.ts
ui/src/types/flux.ts
ui/src/worker/jobs/fluxTablesToDygraph.ts

Closes https://github.com/influxdata/applications-team-issues/issues/84
When parsing flux tables, they were getting set to the date of the string that was returned. Now it converts the string to date and then to a number so its in the correct format for hovertime.

Change time field in flux table from Date to number to fix hover time

---

ui/src/dashboards/utils/tableGraph.ts
ui/src/shared/components/InvalidData.tsx
ui/src/shared/components/TableGraph.tsx
ui/src/types/series.ts
ui/src/utils/groupByTimeSeriesTransform.ts
ui/src/utils/timeSeriesTransformers.ts
ui/src/worker/JobManager.ts
ui/src/worker/jobs/timeSeriesToTableGraph.ts
ui/test/utils/timeSeriesTransformers.test.ts

Closes https://github.com/influxdata/applications-team-issues/issues/67
Closes #4485 
Updates the TableGraph to handle InfluxQL meta query responses
Transforming time series to table graph data were always adding an unnecessary time field to the meta query responses
Don't add time to a meta query and display invalid data if there are both data queries and meta queries

Fix meta query table

---

ui/src/style/pages/dashboards.scss

Closes #https://github.com/influxdata/applications-team-issues/issues/93
When hovering over an annotation close to the top right of a dashboard cell, the menu buttons would obscure the annotations tooltip that appears
Lower the z-index of the dashboard cell menu buttons to fall behind the annotations tooltip.

Change dash header button z index

---

ui/src/style/components/custom-time-range.scss
ui/src/style/modules/_variables.scss
ui/src/style/pages/dashboards.scss

Closes #4493
When the dashboard date picker overlay was opened to overlap with a cell, the cell's menu buttons would appear on top of the date picker, even though the overlay was meant to sit on top of the cells.
The overlay had a higher z-index than the cell menu buttons, but the overlay's parent had a lower z-index, which overruled in the css hierarchy. The solution was to increase the z-index of the date picker overlay's parent.

Increase z-index for time dropdown

---

ui/src/localStorage.ts
ui/src/shared/utils/TimeMachineContainer.ts
ui/test/shared/utils/TimeMachineContainer.test.ts

Just some minor chores to clean up after #4509. Mainly, porting over some [query config tests](https://github.com/influxdata/chronograf/blob/42a73792a21bb355fce893d316ebaaf0b0973e3d/ui/test/data_explorer/reducers/queryConfig.test.ts) to make use of the new `TimeMachine` state container.

Misc TimeMachineContainer cleanup

---

ui/src/data_explorer/constants/index.ts
ui/src/data_explorer/containers/DataExplorerPage.tsx
ui/src/localStorage.ts
ui/src/shared/constants/index.ts
ui/src/shared/utils/TimeMachineContainer.ts
ui/src/shared/utils/localStorage.ts

Previously, we used localStorage to persist state in the Data Explorer across page refreshes. The implementation used some Redux middleware to achieve this.
#4509 removed the use of Redux in the Data Explorer, and the localStorage persistence along with it. This PR adds back localStorage persistence to the Data Explorer.

Persist Data Explorer state to localStorage

---

ui/src/shared/components/TableGraph.tsx

Closes #4417 
To reproduce the issue:
1. Create a new table cell
2. Open up the CEO and edit the cell time format option
3. Save the cell
An uncaught exception is thrown in the `TableGraph` component and the table cell fails to render.
The error seems to stem most immediately from calculating a `NaN` column width in the table. Ultimately this `NaN` calculation originates from passing a null `influxQLQueryType` to the `computeFieldOptions` helper. By storing the appropriate `influxQLQueryType` on state and reusing it when necessary, the calculations functions as intended.

Avoid uncaught exception in TableGraph

---

ui/src/worker/JobManager.ts

Closes #4500 
Spin up 2 WebWorkers by default, unless we are in a browser that defines `navigator.hardwareConcurrency` (Chrome and Firefox do, Safari does not).

Fix issue loading Data Explorer in Safari

---

CHANGELOG.md
ui/src/logs/components/logs_message/LogsMessage.scss
ui/src/logs/components/logs_message/LogsMessage.tsx
ui/src/reusable_ui/components/Button/index.tsx

Closes #4505
Move logs button up to the right corner when expanded.
The button was in the lower right and could not be reached in longer log messages.
*  Move the log copy button to the upper right and turn it into an actual button to make it easier to spot.
*  Cancel click events on the copy button so that copying the log message doesn't open the popover for a long message.

Update logs copy button position

---

ui/src/flux/components/FilterTagListItem.tsx

Closes #4484
When the user clicked on the radio button to toggle between "=" and "!=" filter types, the tag key list item would simply close and would not switch the filter type. 
Change the onClick function to be an arrow function and remove the event handler sub-function. This does not fix the list item closing on click, but it does allow the user to toggle between "=" and "!=". The closing problem will be addressed in a separate PR

Fix filter type radio button in flux builder tag list dropdown 

---

ui/src/reusable_ui/components/wizard/WizardController.tsx
ui/src/reusable_ui/components/wizard/WizardFullScreen.tsx
ui/src/reusable_ui/components/wizard/WizardStep.tsx
ui/src/reusable_ui/components/wizard/test/WizardController.test.tsx
ui/src/reusable_ui/components/wizard/test/WizardFullScreen.test.tsx
ui/src/reusable_ui/components/wizard/test/WizardStep.test.tsx
ui/src/reusable_ui/components/wizard/test/__snapshots__/WizardController.test.tsx.snap
ui/src/sources/components/ConnectionWizard.tsx
ui/src/sources/components/SourceStep.tsx
ui/src/sources/containers/OnboardingWizard.tsx

Closes #4496  #4497 
- Added a switch orgs link for users using auth. 
- Added an additional 'skip' link on skippable wizard steps in onboarding wizard. 
- route user using auth to `/manageSources` page when wizard completed, or skipped.

Add switch org link and fix routing when auth is enabled in onboarding

---

ui/src/dashboards/components/CellEditorOverlay.tsx
ui/src/dashboards/containers/DashboardPage.tsx
ui/src/shared/utils/timeMachine.ts

Closes https://github.com/influxdata/applications-team-issues/issues/97
Previously, the CEO would check if a cell had a query and not allow the user to save a cell without a query, even for a note type cell.
Add a check for note type in the `isSaveable` function in the CEO. Additionally, move the `TimeMachineContainer` which holds the state for cell type to be above the CEO. This way, the `isSaveable` function is called every time the cell type changes.

Allow note cell without query

---

ui/src/dashboards/containers/DashboardsPage.tsx
ui/src/dashboards/utils/export.ts

Closes https://github.com/influxdata/applications-team-issues/issues/111
Dashboards were previously exported with Flux services, which have now been removed 
Use a Source link for both Flux and InfluxQL cells when exporting or importing a dashboard

Remove old flux services from dashboard export

---

ui/src/shared/decorators/errors.tsx

Github issues link was not encoded, so in some cases chrome would not allow you to go to the url.

Encode github issue url

---

ui/src/shared/components/TimeMachine/TimeMachineVisualization.tsx
ui/src/shared/utils/TimeMachineContainer.ts

Closes https://github.com/influxdata/applications-team-issues/issues/114
The threshold type was getting updated, but not used by the threshold colors
Update the thresholds list colors when updating threshold type

Fix changing threshold type

---

ui/src/flux/components/TimeMachineEditor.tsx
ui/src/shared/components/TimeMachine/FluxQueryMaker.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/115

Submit Flux script with Ctrl-Enter keybinding

---

ui/src/dashboards/utils/tableGraph.ts
ui/src/flux/components/TimeMachineTables.tsx
ui/src/flux/components/YieldFuncNode.tsx
ui/src/flux/components/YieldNodeVis.tsx
ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/TableGraph.tsx
ui/src/shared/components/TableGraphFormat.tsx
ui/src/shared/components/TableGraphTransform.tsx
ui/src/shared/components/time_series/TimeSeries.tsx

Connects https://github.com/influxdata/applications-team-issues/issues/102
Because time range getting updated caused a change in data, the async data transformations and the async transformations based on table visualization props were called. This was causing a race conditions so the previous data was getting set.
Extract functionality from table graphs into different functions. Keep track of the requests and only update state with the most recent request's result.

Table graph update time

---

ui/src/style/pages/dashboards.scss

Closes https://github.com/influxdata/applications-team-issues/issues/133
The loading state was not visible in the ceo and de since the dots were not being rendered in the correct location.
Fix location of loading dots inthe de and ceo.

Make loading dots visible on graphs in ceo and de

---

ui/src/dashboards/components/SourceSelector.tsx
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/shared/components/TimeMachine/TimeMachineControls.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/135
Currently, clicking on the radio button to toggle Flux on or off would switch the language even if you clicked on the one that was already selected.
Replace the toggle function with two separate function: one to turn Flux on, one to turn it off.

Replace toggleFlux with on/off functions

---

ui/src/shared/copy/notifications.ts

Closes https://github.com/influxdata/applications-team-issues/issues/136
The notification for a cell being sent to a dashboard from the Data Explorer (or an unsuccessful attempt to do so) was too short.
Set the notification duration to the default time for success and error notifications.

Change cell sent notification duration to default (5 seconds)

---

ui/src/data_explorer/components/SendToDashboardOverlay.tsx

Closes #4548
One of the items in the dashboard dropdown menu in the `SendToDashboard` overlay was missing a key prop, causing React to throw the error "each child in an array or iterator should have a unique 'key' prop.:"
Add a key prop to the 'divider' item in the dropdown.

Fix React 'key' warning in SendToDashboard overlay

---

ui/src/data_explorer/components/SendToDashboardOverlay.tsx

Closes: https://github.com/influxdata/applications-team-issues/issues/144
When sending a cell to a dashboard from the Data Explorer, users want to select the dashboard(s) before naming the cell. However, the "name cell" field was above the "target dashboards" field.
Switch the order of the "name cell" and "target dashboards" fields for a smoother user experience.

Switch order of cell name and target dashboard in send to dashboard

---

ui/src/shared/components/time_series/TimeSeries.tsx

Showing results for wrong time range

Fix returning results for wrong time range

---

ui/src/data_explorer/components/SendToDashboardOverlay.tsx

Closes: https://github.com/influxdata/applications-team-issues/issues/145
When sending a cell to a new dashboard from the Data Explorer, there was no way for the user to name this new dashboard. 
Add a field to name the new dashboard if the user selects "send to new dashboard."

Create field to name new dashboard from DE

---

ui/src/shared/copy/notifications.ts
ui/src/status/actions/index.ts

Closes: https://github.com/influxdata/chronograf/issues/4579
Previously, a notification popup would be shown if the news feed on the status page failed to load.
Remove the notification.

Remove notification for failing to fetch JSON feed

---

ui/src/flux/components/TableSidebar.tsx
ui/src/flux/components/TimeMachineTables.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/132
A little while back we switched to using a `FluxTable`'s `name` as an identifier in `TimeMachineTables`. We never updated some state keys to reflect this, which was confusing and likely resulted in the aforementioned bug. 
This PR fixes the bug and changes the state keys to reflect that a table's `name` is being stored, rather than it's `id`.

Fix missing selected state in TimeMachineTables

---

ui/src/shared/parsing/flux/parseTablesByTime.ts

Connects https://github.com/influxdata/applications-team-issues/issues/156
When using a query with aggregates, the _time column is left off and graphs dont know how to parse it so they display 'Cannot visualize data with this graph type'
If there is not _time, use _stop as the time field

Display data without _time column as graph

---

CHANGELOG.md
ui/src/logs/containers/LogsPage.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/162
Fix scroll to first row when live updating in logs table and in firefox
In firefox scroll positioning is async to create smoother scrolling, but this created a race where rendering and updating the scroll position got stuck at scrollTop `0` in the logs table.
Use `hasScrolled` to attempt to guard against the race in scrollTop position rendering and scroll firing. This allows logs to scroll, but still appears to stick a bit at the top on the first scroll. Note: firefox will continue to warn about this in the console with the following message:
```
This site appears to use a scroll-linked positioning effect. This may not work …
```

Fix logs vertical scroll

---

ui/src/dashboards/components/CellEditorOverlay.tsx
ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/shared/components/TimeMachine/FluxQueryMaker.tsx
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/shared/utils/TimeMachineContainer.ts
ui/src/shared/utils/timeMachine.ts

Closes: https://github.com/influxdata/applications-team-issues/issues/143
Previously, the user would need to click on the "Run Script" button when editing a Flux query in order for their changes to be reflected in the cell upon saving. However, any changes made to an InfluxQL query would be applied to the cell automatically when saved, leading to an inconsistent user experience. 
Add a state property called "draftScript" to keep track of the user's changes without running the query on for every change. This state is now used when saving the cell.

Add draftScript state to TimeMachine

---

ui/src/types/series.ts
ui/src/utils/groupByTimeSeriesTransform.ts
ui/src/worker/jobs/timeSeriesToTableGraph.ts
ui/test/utils/timeSeriesTransformers.test.ts

Closes https://github.com/influxdata/applications-team-issues/issues/164
When checking for metaqueries, it was assumed that if there was only one column, then that must be a metaquery; however, some metaqueries return multiple columns.
Instead check if time is one of the columns returned. If its not, then its a metaquery and we should parse differently and just use columns plus labels as the data returned.

Fix metaquery parsing for tables

---

ui/package.json
ui/src/flux/apis/index.ts
ui/src/flux/helpers/templates.ts
ui/src/shared/apis/query.ts
ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/TimeMachine/CSVExporter.tsx
ui/src/shared/components/time_series/TimeSeries.tsx
ui/src/shared/constants/index.ts
ui/src/shared/parsing/flux/durations.ts
ui/src/shared/utils/downloadTimeseriesCSV.ts
ui/src/tempVars/utils/replace.ts
ui/test/shared/parsing/flux/durations.test.ts
ui/test/shared/parsing/flux/durations.ts
ui/test/tempVars/utils/replace.test.ts
ui/yarn.lock

Closes https://github.com/influxdata/applications-team-issues/issues/157
Note that the template variable is `autoInterval` rather than `interval` for now. We can change it once https://github.com/influxdata/flux/issues/145 is fixed.

Add support for interval template variable in Flux queries

---

ui/src/dashboards/components/CellEditorOverlay.tsx
ui/src/shared/apis/query.ts
ui/src/shared/components/time_series/TimeSeries.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/166
Updates the TimeSeries component to not rely on storing/updating the latestUUID in state related to a request, and wraps API calls using `restartable` to ensure we always get the latest response.
Storing and updating state containing the latestUUID before fetching data lead to a race condition. Subsequent state updates could cause rendering that caused the latestUUID to be paired with stale data .
Use restartable to wrap requests.
----

Fix TimeSeries uuid race condition

---

ui/src/flux/apis/index.ts
ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/time_series/TimeSeries.tsx
ui/src/shared/parsing/flux/response.ts
ui/src/worker/JobManager.ts
ui/src/worker/jobs/fetchFluxData.ts
ui/test/shared/parsing/flux/constants.ts
ui/test/shared/parsing/flux/results.test.ts

Closes https://github.com/influxdata/applications-team-issues/issues/159
requests were failing silently and not being displayed to the user.
Display errors in the visualization area when errors occur.

Show errors instead of 'No Results' when error occurs

---

ui/src/shared/components/RefreshingGraph.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/181
After adding in showing errors instead of just showing no results, flux queries show an error when there is no script since that is technically not a valid query.
If there is no script for flux, then show the text for creating new queries instead of showing the error.

Update refreshing graph to not show error when there's no script

---

ui/src/reusable_ui/components/wizard/WizardProgressBar.tsx

Set all progress connectors to full if on final wizard step.
When the user skips to the final step the progress meter does not reflect completion.
Fill all bars if on completion step.

Set all progress connectors to full if on final wizard step.

---

CHANGELOG.md
ui/src/logs/components/expandable_message/ExpandableMessage.scss
ui/src/logs/components/expandable_message/ExpandableMessage.tsx
ui/src/logs/containers/LogsPage.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/182 https://github.com/influxdata/chronograf/issues/4610
Pauses live updating on click and wraps messages in popover.
Expanding a message did not include the message wrapping used for wrapped log messages. 
Clicking a message also did not pause the logs, allowing new logs to load, and then close a log message being viewed.
Add a `.message-wrap` that reflects the wrapping used for untruncated log lines. 
Clear the tailing interval and update scroll/liveUpdating state on message click.

Fix logs expansion handling

---

ui/src/flux/apis/index.ts
ui/src/shared/apis/flux/metaQueries.ts

The end point for querying via Flux has changed from `/v2/query` to `/api/v2/query`.

Update Flux query endpoint

---

ui/src/shared/graphs/helpers.test.ts
ui/src/shared/graphs/helpers.ts

Closes: https://github.com/influxdata/chronograf/issues/4614
Previously, the label for static legends would cut off everything until the last period in the label name. So if you had a label with a period in it, such as a url, it would only display the last few characters.
Change the regex used to strip the measurement from the label to capture everything up until the first period, rather than everything before the last period.

Change regex for static legend label to include up to first period

---

ui/src/shared/apis/flux/ast.ts
ui/src/shared/apis/flux/query.ts
ui/src/shared/apis/flux/suggestions.ts
ui/src/shared/components/TimeMachine/FluxQueryMaker.tsx
ui/src/shared/components/time_series/TimeSeries.tsx
ui/src/shared/parsing/flux/durations.ts
ui/src/shared/parsing/flux/response.ts
ui/src/shared/utils/downloadTimeseriesCSV.ts
ui/test/flux/apis/flux.test.ts

Just a minor little refactor of Flux fetching in preparation for #4030. Reorganizes the various Flux API utilities and separates the `getTimeSeries` and `getTimeSeriesRaw` utilities from logic to render template variables in Flux scripts.

Refactor Flux fetching

---

CHANGELOG.md
ui/src/logs/components/LogsTable.tsx
ui/src/logs/utils/table.ts
ui/src/shared/components/FancyScrollbar.tsx

Closes #4578
Set a minimum `Grid` width so `FancyScrollBar` (`react-custom-scrollbar` wrapper) to read the correct inner scroll width of the `Grid` and move the `Grid` bottom up high enough so that it's visible.
The FancyScrollBar was not displaying a correct scrollbar because the react virtualized `Grid` has a virtual width that is unavailable to FancyScrollBar. FancyScrollBar needs some child element that actually has the correct width in order to scroll.
This solution is to just make the Grid render it's full width and pay the penalty of rendering more columns than are visible as we'll only pay this rendering cost on visible rows.
I'll create a follow up issue to continue an investigation into a …

Fix logs scrollbar

---

ui/src/flux/helpers/autoComplete.ts

Closes https://github.com/influxdata/applications-team-issues/issues/167
An off-by-one error meant that we were attempting to provide parameter suggestions for a Flux function at the wrong time.
The helper that actually provides parameter suggestions assumes that it has been called with the appropriate state—since it wasn't, we hit some undefined behavior which manifested as an infinite loop.

Fix infinite loop bug in Flux autocompletions

---

CHANGELOG.md
bolt/internal/internal.go
bolt/org_config.go
bolt/org_config_test.go
integrations/server_test.go
ui/src/logs/actions/index.ts
ui/src/logs/constants/index.ts
ui/src/logs/utils/index.ts
ui/src/logs/utils/table.ts

Closes #4598 
Updates org config with a live migration to log viewer config to ensure it includes a hostname and includes hostname in the default fields for the org config.
Hostname was not present in the default fields for log viewer
Add hostname to org config.
----

Add logs hostname

---

ui/src/shared/utils/TimeMachineContainer.ts
ui/src/shared/utils/timeMachine.ts

Closes influxdata/applications-team-issues#196
Both the `CellEditorOverlay` and `DataExplorer` components store state in the `TimeMachineContainer`. These components reset the state upon mount, using data that is cached for each component in localStorage.
The `CellEditorOverlay` requires only certain pieces of cached data to be read from localStorage, while the `DataExplorer` wants all data stored in localStorage to be read.
This commit updates the utility used to fetch data from localStorage to be aware of this difference between the two components.

Fix issue with stale data in the CellEditorOverlay

---

ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/shared/components/TimeMachine/FluxQueryMaker.tsx
ui/src/shared/utils/TimeMachineContainer.ts

Closes https://github.com/influxdata/applications-team-issues/issues/180
Also fixes an issue where the Script Wizard would not execute the generated flux query after inserting it into the editor.

Fix query parameter resolution in Data Explorer

---

ui/src/dashboards/components/ReactCodeMirror.tsx
ui/src/flux/helpers/templates.ts
ui/src/shared/components/time_series/TimeSeries.tsx
ui/src/shared/constants/index.ts
ui/src/shared/utils/downloadTimeseriesCSV.ts
ui/src/tempVars/utils/replace.ts
ui/test/tempVars/utils/replace.test.ts

- Name variables involved to the auto group by calculation according to the correct units, and specify units for variables that were left ambiguous
- Use the same calculation in both InfluxQL queries and Flux queries
- Increase the level of detail yielded by the auto group by calculation. For now this was done by increasing [`DEFAULT_X_PIXELS`](https://github.com/influxdata/chronograf/blob/e486a61ae312e3d9b3b1763ba1b4ee8fa117f618/ui/src/shared/constants/index.ts#L10), but should be done by decreasing [`PIXELS_PER_POINT`](https://github.com/influxdata/chronograf/blob/e486a61ae312e3d9b3b1763ba1b4ee8fa117f618/ui/src/shared/constants/index.ts#L11) instead after influxdata/applications-team-issues#168 is fixed.
- You can experiment with alternative levels of detail by setting the key in …

Increase auto group by resolution

---

ui/src/dashboards/utils/cellGetters.ts
ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/shared/components/TimeMachine/InfluxQLQueryMaker.tsx
ui/src/types/queries.ts

Closes https://github.com/influxdata/applications-team-issues/issues/191
In de, when a query matching the url param could not be found, it would create a new query. It would give an id to the query config and not the query draft, which meant later down the line when trying to modify a query/query config, the correct query could not be found.
Additionally, the query in the text box was always rendering the :dashboardTime: temp var so rather than keeping the var, meaning the url param would never match what was in the box. This would make it so on every refresh, new queries would be created rather than using existing ones. 
Add the query to both the query and query config when creating a new query. 
When generating a query config, template …

Ensure de can find update query drafts correctly

---

ui/src/dashboards/containers/DashboardPage.tsx
ui/src/logs/components/LogsTable.tsx
ui/src/shared/components/FancyScrollbar.tsx
ui/src/shared/components/MultiGrid/MultiGrid.tsx
ui/src/shared/components/TimeMachine/RawFluxDataTable.tsx

Closes influxdata/applications-team-issues#189
Adds fancy scrollbars around the raw response grid
There were none
The solution was to add the scrollbars without causing the grid to render more columns/rows than are visible. This is achieved by styling the width/height  but allowing the table to have width/height set by autosizer. Also, some debugging revealed that scrollTop/scrollLeft were being redundantly updated in state if `onScroll` was added to the `Grid` itself. 
As a follow up a similar fix can be used to resolve: https://github.com/influxdata/applications-team-issues/issues/184

Add scrollbars to raw flux data table

---

ui/src/shared/components/threesizer/Threesizer.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/211
minimize and maximize buttons did not do anything since the division sizes were determined by division props and no longer changed based on state.
Use the onresize prop when handling max and min.

Fix minimize and maximize buttons

---

CHANGELOG.md
ui/src/dashboards/components/GaugeOptions.tsx
ui/src/dashboards/components/SingleStatOptions.tsx
ui/src/shared/components/MarkdownCell.scss

Closes https://github.com/influxdata/applications-team-issues/issues/197
Closes https://github.com/influxdata/applications-team-issues/issues/198
Remove the shadow positioned at the bottom of note cells. Remove the 5 character maximum for prefix and suffix fields located in Gauge and Single Stat options

Remove Markdown Shadows and Prefix/Suffix Limits

---

ui/src/flux/components/TimeMachineTables.tsx
ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/time_series/TimeSeries.tsx

Closes influxdata/applications-team-issues#168
To compute the auto group by template variables (`:interval:` and `autoInterval`), we need to measure the number of pixels in the _x_ dimension of a plot. Previously, we used a hardcoded value of `700` for this measurement. 
Now, the `RefreshingGraph` will measure the actual value, and the `TimeSeries` component will consume it.
I also took this opportunity to extract some getters from the `render` method of the `RefreshingGraph`, which has become quite unwieldy. Unfortunately, adding in the measurement logic has exasperated the issue 😞

Measure plot dimensions for auto group by queries

---

ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/TimeMachine/RawFluxDataTable.scss
ui/src/shared/components/TimeMachine/RawFluxDataTable.tsx
ui/src/shared/parsing/flux/response.ts
ui/src/style/components/graph.scss
ui/src/style/pages/dashboards.scss
ui/test/shared/components/RawFluxDataTable.test.tsx

Fixes some issues introduced by #4663.
Those issues were:
- The “Raw Data” table for Flux was empty
- Empty graph messages were clipped and off-center
The commit messages have some more detail.

Fix empty Raw Data table

---

ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/time_series/TimeSeries.tsx

Closes influxdata/applications-team-issues#201
We store a piece of state called `isFirstFetch` on the `TimeSeries` component. We use it to display a large loading spinner when a cell is first rendered and otherwise display a small loading spinner if the cell is refetching.
Due to a double render on the initial `TimeSeries` mount, this `isFirstFetch` state was quickly set to false. Thus instead of a loading spinner displaying initially, the no-data fallback of a note was displayed in each cell.
This PR fixes the double render. It also lifts and renames the `isFirstFetch` state from the `TimeSeries` component to the `RefreshingGraph`, which allows us to extract more presentational logic from the `TimeSeries` component.
Before:
After:

 Don't display fallback notes on initial fetch 

---

ui/src/flux/components/FieldList.tsx
ui/src/flux/components/MeasurementList.tsx
ui/src/flux/components/TagKeyList.tsx
ui/src/flux/components/TagValueList.tsx

Clicking on an error message in the schema explorer would close the entire bucket section that the error message was in.
Add an click handler with a call to `e.stopPropagation()` to the error message element. Also add an error message for tag keys.

Prevent error message from closing bucket in explorer

---

ui/src/dashboards/components/AxesOptions.tsx

Closes #[192](https://github.com/influxdata/applications-team-issues/issues/192) 
updating values in redux causes rerender that places cursor at the end of the word being edited, 
This change places suffix and prefix values in component state, and reads value of input from there.  Changes to value update both local state and state in redux.

Update suffix and prefix values in state as well as redux

---

ui/src/shared/components/time_series/TimeSeries.tsx

Closes #[222](https://github.com/influxdata/applications-team-issues/issues/222)
Re-execute queries when zoomedTimeRange has changed by re-executing queries when template values (which contain dashboardTime and upperDashboardTime) have changed. BONUS BUG FIX: will re-execute queries when template values are changed (which was not the case).

Re-execute queries when zoomedTimeRange has changed

---

ui/src/dashboards/components/CellEditorOverlay.tsx
ui/src/dashboards/components/SourceSelector.tsx
ui/src/data_explorer/components/SendToDashboardOverlay.tsx
ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/shared/components/Layout.tsx
ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/shared/components/TimeMachine/TimeMachineControls.tsx
ui/src/shared/components/TimeMachine/TimeMachineVisualization.tsx
ui/src/shared/utils/TimeMachineContainer.ts
ui/src/shared/utils/timeMachine.ts

Closes: https://github.com/influxdata/applications-team-issues/issues/199
Previously, the language type (InfluxQL or Flux) was obtained from the queryDrafts object. This created conflicting sources of truth, which resulted in a bug where if the user refreshed the page while on a Flux query in the Data Explorer and then switched to InfluxQL mode, the user would see their Flux query in the InfluxQL query builder.
Create a `queryType` property on the `TimeMachineContainer` component and use this as a single source of truth for the language type throughout the Data Explorer and Cell Editor Overlay.

Bugfix/Flux query in InfluxQL mode in DE

---

ui/src/logs/components/LogsTable.tsx
ui/src/logs/components/expandable_message/ExpandableMessage.scss
ui/src/logs/components/expandable_message/ExpandableMessage.tsx
ui/src/logs/components/expandable_message/ExpandedContainer.tsx
ui/src/shared/copy/notifications.ts

Closes https://github.com/influxdata/applications-team-issues/issues/214
The expandable message would render outside the bounds of the logs table and the message contents could overflow the max height.
- Make the expanded message render only the viewable width of the logs table
- Make the expanded message not render if width below 200px
- Make the expanded message use fancy scrollbars to scroll vertically

Add dynamic expanded message container

---

ui/src/flux/components/FluxEditor.tsx
ui/src/flux/components/FluxScriptEditor.tsx
ui/src/flux/components/flux_functions_toolbar/FluxFunctionsToolbar.scss
ui/src/flux/components/flux_functions_toolbar/FluxFunctionsToolbar.tsx
ui/src/flux/components/flux_functions_toolbar/FunctionCategory.tsx
ui/src/flux/components/flux_functions_toolbar/FunctionTooltip.tsx
ui/src/flux/components/flux_functions_toolbar/ToolbarFunction.tsx
ui/src/flux/components/flux_functions_toolbar/TooltipArguments.tsx
ui/src/flux/components/flux_functions_toolbar/TooltipDescription.tsx
ui/src/flux/components/flux_functions_toolbar/TooltipExample.tsx
ui/src/flux/components/flux_functions_toolbar/TooltipLink.tsx
ui/src/flux/components/flux_functions_toolbar/TransformToolbarFunctions.tsx
ui/src/flux/constants/functions.ts
ui/src/flux/constants/index.ts
ui/src/shared/components/TimeMachine/FluxQueryMaker.tsx
ui/src/shared/utils/TimeMachineContainer.ts
ui/src/style/chronograf.scss
ui/src/style/components/time-machine/flux-editor.scss
ui/src/types/flux.ts
ui/test/flux/components/FluxScriptEditor.test.tsx

Closes # influxdata/chronograf/issues/4628
Implement a toolbar to showcase a selection of the most commonly used functions with the ability to click to add them and quick access to documentation.
Users who don't know Flux need a way to know what functions are available and how to use them.
Implement a toolbar to showcase a selection of the most commonly used functions with the ability to click to add them and quick access to documentation.

Flux Functions Toolbar

---

ui/src/shared/components/TimeMachine/FluxScriptWizard.scss
ui/src/shared/components/TimeMachine/FluxScriptWizard.tsx

Flux editor styling tweaks

---

ui/src/shared/components/time_series/TimeSeries.tsx

Don't show double spinners on first graph load

---

CHANGELOG.md
ui/src/logs/containers/LogsPage.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/235
Render a page spinner as sources are being fetched
The logs page was visible but not responsive 
Add a page spinner as sources are being fetched.

Add logs page spinner

---

ui/src/shared/components/LayoutCell.tsx

Enables the use of `:dashboardTime:` in a cell title.

Enable using predefined temp vars in cell names

---

ui/src/logs/components/expandable_message/ExpandableMessage.tsx
ui/src/logs/components/expandable_message/ExpandedContainer.tsx
ui/src/shared/copy/notifications.ts

Closes https://github.com/influxdata/applications-team-issues/issues/241
Clicking on a log message no longer triggers a notification and will attempt to show the full message. The message will leave space to the left or right to allow one to peak at other columns while scrolling horizontally.
Clicking on a message would shrink or hide depending on how much width was viewable, but the ideal situation would be to see the maximum message width for the table size that allowed the user to still inspect other rows or columns while scrolling.
Remove the hidden message behavior and notification and pin the popover to the left, center, right, or message column to maximize the viewable width of the logs …

Fix logs message width

---

ui/src/shared/components/TableGraph.tsx

Closes influxdata/applications-team-issues#250
Fixes an issue in the `TableGraph` component where a string such as `02dec` would be interpreted as a number. This created visual inconsistencies when viewing a table of UUIDs, for example.

Fix table formatting of stringy numbers

---

ui/src/shared/components/InvalidData.tsx
ui/src/shared/components/LineGraph.tsx
ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/TimeMachine/TimeMachineVisualization.tsx

Closes #4719 
Metaquery responses in the Explorer when using InfluxQL would render a "invalid data" message, which did not indicate to the user how to resolve this matter. This PR adds a button that lets the user switch to a Table Graph visualization type in this case.

feat: add button to switch to table graph if data invalid

---

ui/src/style/components/table-graph.scss

Closes influxdata/applications-team-issues#252
Previously we would render a semi-transparent rectangle over the currently hovered entry in a table using a CSS `:after` technique. In Firefox, this blocked text selection events on the table entry so that a user could not copy/paste data from a table graph.
This commit changes the background color of hovered table entries instead overlaying a semi-transparent rectangle, so that text selection events are not blocked. This results in a slightly different but comparable aesthetic.
Before:
After:
cc design lords @alexpaxton @mavarius may I have your blessing :)

Enable text selection in table cells in Firefox

---

ui/src/reusable_ui/components/wizard/WizardController.tsx
ui/src/reusable_ui/components/wizard/WizardFullScreen.tsx
ui/src/reusable_ui/components/wizard/WizardOverlay.tsx
ui/src/reusable_ui/components/wizard/test/WizardController.test.tsx
ui/src/reusable_ui/components/wizard/test/WizardFullScreen.test.tsx
ui/src/sources/components/ConnectionWizard.tsx
ui/src/sources/containers/OnboardingWizard.tsx

Users should not be able to jump to the end of the wizard if a source has not been created or does not exist. We already prevent skipping/dismissing wizard by checking that a source is available, this PR creates an `isJumpingAllowed` prop, that also prevents jumping using the wizardController

Prevent step jumping in the wizard if no source

---

server/sources.go
ui/src/shared/actions/sources.ts

Closes https://github.com/influxdata/applications-team-issues/issues/245
Move flux link creation to the server
We are currently checking if flux is enabled on every source that we load from `getSources` at the top of the app.
Add the flux url logic to he backend and timeout if flux doesn't respond in 500ms.

fix(sources): call to GET /sources hanging

---

CHANGELOG.md
ui/src/dashboards/components/DashboardSwitcher.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/258
Update switcher link sorting to not use casing
Dashboard quick switching links used casing in `sortBy`  
lower case text before sorting

Fix switcher links case ordering

---

ui/src/dashboards/components/GraphTypeSelector.tsx
ui/src/shared/components/InvalidData.tsx
ui/src/shared/components/LineGraph.tsx
ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/SingleStat.tsx
ui/src/shared/components/TimeMachine/TimeMachineVisualization.tsx

Closes #4735
Previously, the single stat graph component would display "NaN" when the data returned empty or returned a non-number. 
This PR adds a check for the type of the data in the component, and renders an error message prompting the user to switch to a Table Graph if the data is not a number type.

Add check for undefined value in single stat component

---

ui/src/shared/components/Dygraph.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/256
old drawings of dygraph were still visible after redrawing
remove the old drawings

Clear old dygraphs before redrawing

---

ui/src/data_explorer/components/SendToDashboardOverlay.tsx

Previously, the list of dashboards in the `SendToDashboardOverlay` dropdown were in a random order. This PR sorts them alphabetically (ignoring upper/lower case).

Sort dashboard items in SendToDashboardOverlay by name

---

flux/client.go
server/flux.go
server/influx.go
server/mux.go
server/sources.go

The server treated all query requests as requests to influxql.  
Create a flux proxy link with a custom handler.

fix(flux): create unique link for querying flux

---

ui/src/shared/components/RefreshingGraph.tsx

Refreshing graph only updated if certain props changed. InView was changing but was not among those props so refreshing graph did not update. Since time series will only execute the queries for the cells that are inview, those cells who became in view but were not originally never had their queries run.
InView is now one of the props that cause refreshing graph to update.

Update refreshing graph if inView changes

---

ui/src/kapacitor/components/RuleGraph.tsx

Closes #4759
The `RuleGraph` was attempting to execute queries without first rendering the `:dashboardTime:` template variable. This resulted in a failed query and no data being displayed.
This commit ensures that the `:dashboardTime:` template variable is rendered with the appropriate data.

Fix issue with RuleGraph running unrendered query

---

CHANGELOG.md
ui/src/logs/components/LogsTable.tsx

Set scroll left to zero on new search 
Scroll left would not be reset on a new search
Set scroll left to 0 when a search is cleared

Reset scrollLeft on search

---

CHANGELOG.md
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/utils/fetchUntil.ts
ui/src/types/logs.ts

Fixes an issue where sometimes the loading more indicator does not hide after fetch loop is canceled
Fetch newer is the async iterator func in a fetch loop and cannot await the completion of the fetch loop since it awaiting will block the completion of the fetch loop.
- Remove the await on cancelAsync since calling cancelAsync will prevent further iteration.  
- Remove the cancelAsync method becuase it's a confusing/problematic
- Update pending newer/older chunk cancelation to cancel and then await the chunk to completion

Fix scroll loading indicator

---

CHANGELOG.md
ui/src/flux/constants/functions.ts

Signed-off-by: Lorenzo Fontana <lo@linux.com>
Use the right keys as flux espects them for the pivot function.
The `pivot` function generated by chronograf doesn't use the right named parameters for `columnKey` and `valueKey`.
Change the named parameters names!

fix(flux/pivot): specify the right named parameters for columnKey and valueKey

---

ui/src/admin/components/DatabaseRow.js
ui/src/admin/components/DatabaseTable.js

Closes #4801
When creating a new database, the UI is a bit confusing.  There are two "save" buttons (one for the DB and one for the RP).  I have decided to have the "create DB" ui exclusively create a database and a default retention policy.  Should a user want to add / manipulate the default retention policy after creation.
When the user hits "save" on an RP whose database has not yet been created we get various runtime errors.

fix(db-admin): only handle db state on db create

---

CHANGELOG.md
ui/src/data_explorer/components/SendToDashboardOverlay.tsx

Closes: https://github.com/influxdata/applications-team-issues/issues/266
Custom column names were not saved when a new table graph cell was created from the "Send to Dashboard" overlay in the Data Explorer.
Save `fieldOptions` to the cell when it is created.

Add fieldOptions when creating new cell from SendToDashboard

---

CHANGELOG.md
ui/src/hosts/utils/getCells.ts

Closes #4789
Chronograf includes a number of canned dashboards, whose cells are predefined and immutable. A cell in a canned dashboard is called a layout cell, and it has a slightly different schema than a cell in a user-defined dashboard (called a dashboard cell).
For legacy reasons, Chronograf is able to render a layout cell or dashboard cell using the same components via a mix of duck-typing and defensive programming. [#4488][0] attempted to unify the differences between the two possible cell schemas by converting a layout cell to a dashboard cell upon read. This schema conversion was error prone and incomplete.
One difference between a layout cell and dashboard cell that was not handled by the schema conversion involved the `groupbys` and `wheres` fields in a layout cell. In a …

Fix grouping in canned queries

---

ui/src/reusable_ui/components/wizard/WizardOverlay.tsx
ui/src/reusable_ui/components/wizard/test/__snapshots__/WizardOverlay.test.tsx.snap
ui/src/sources/components/ConnectionWizard.tsx

Closes #4784 
It was not possible to cancel and exit out of wizard steps that were designated as compulsory to continue to next wizard step. 
Added x-to-dismiss on upper right of wizard overlay, and removed `dismiss` links on wizard steps.

Remove dismiss text from and add x-to-dismiss to wizard overlay steps

---

canned/consul.json
canned/consul_leadership.json
canned/elasticsearch.json
canned/haproxy.json
canned/mongodb.json
canned/net.json
canned/new_apps.sh
canned/phpfpm.json
canned/ping.json
canned/rabbitmq.json
canned/riak.json
canned/varnish.json

Closes #4787 
Two things: first, normalize the case of the queries in the canned applications.  Second, apply the patch from April that missed several applications because the case was wrong.
I don't see evidence the test suite covers the canned apps, and the only modified apps I've tested are rabbitmq and ping, done by copying the modified versions over the 1.7.2 installation.  So somebody should look this over closely.

fix canned apps for template variables

---

CHANGELOG.md
ui/src/sources/components/DashboardStep.scss
ui/src/sources/components/DashboardStep.tsx

Closes #4803 
Theres no loading state on the dashboard step of the onboarding process.
Add loading state for both fetching initial protoboards and the loading suggestions state

Add loading state to protoboards onboarding step

---

CHANGELOG.md
ui/src/logs/containers/LogsPage.tsx

Closes #https://github.com/influxdata/applications-team-issues/issues/267
Makes `isLoadingNewer` part of the `LogsPage` state so the table will be re-rendered once the logs table has finished loading newer rows. This fixes a race condition where scrolling to the top of the logs table could cause scroll position to get stuck if the user did not scroll while new rows were being added.
Scroll position could get stuck because the update that signaled loading newer had completed was not causing the table to be rendered 
Move `isLoadingNewer` into the `LogsPage` state and update state once a fetch for newer data has completed.

Fix logs loading newer

---

CHANGELOG.md
ui/src/reusable_ui/components/wizard/WizardController.tsx
ui/src/reusable_ui/components/wizard/WizardFullScreen.tsx
ui/src/reusable_ui/components/wizard/WizardOverlay.tsx
ui/src/sources/components/ConnectionWizard.tsx

Closes #4842 
Previously, the "Add Kapacitor" step in the Connections Wizard could not be skipped.
Make the Kapacitor step skippable, as well as changing the Skip function to go to the next step rather than close the WizardOverlay.

Allow skipping add Kapacitor step

---

CHANGELOG.md
ui/src/logs/actions/index.ts
ui/src/logs/api/index.ts
ui/src/logs/utils/index.ts
ui/test/logs/actions/checkSyslogStatus.test.ts
ui/test/logs/apiMock.ts
ui/test/logs/utils/queryBuilder.test.ts

Closes #4851
Add quotes in meta query building that checks for syslog measurement  
Missing quotes in a query caused an unhandled error that made the log viewer appear to be stuck querying when it was not.
Update the query building to have quotes and the thunk action to handle the error with a status update so the log viewer doesn't appear to be stuck loading.

Fix logs query error

---

CHANGELOG.md
ui/src/flux/components/FluxScriptEditor.tsx
ui/src/style/components/code-mirror/_time-machine.scss
ui/src/style/components/threesizer.scss
ui/src/style/components/time-machine/flux-editor.scss

Closes #https://github.com/influxdata/chronograf/issues/4871
Remove overflow scroll strategy for code mirror threesizer contents wrapper 
Show scrollbars on mouse enter after width change
Multiple scrollbars were being rendered one for the threesizer contents overflow and one for code mirror overflow
CodeMirror scrollbars were not aware of resizes of the threesizer
- Update styling of the threesizer contents to be the full height of the vertical minus the height of threesize header 
- Add a mouse enter listener that checks for width/height changes

Fix flux editor scrollbars

---

CHANGELOG.md
ui/src/dashboards/components/rename_dashboard/RenameDashboard.scss
ui/src/reusable_ui/components/page_layout/Page.scss
ui/src/reusable_ui/components/page_layout/PageHeaderLeft.tsx
ui/src/reusable_ui/components/page_layout/PageHeaderRight.tsx

Closes https://github.com/influxdata/chronograf/issues/4870

Prevent cell renaming widget from pushing other header elements offscreen

---

CHANGELOG.md
ui/src/shared/components/MultiGrid/MultiGrid.tsx

- Omit scrollTop to grid properties
Co-authored-by: Palak Bhoojani <palak@influxdata.com>
Closes #4891

Properly set scroll to row for table graph

---

CHANGELOG.md
ui/src/sources/components/ConnectionWizard.tsx
ui/src/sources/components/KapacitorStep.tsx

Closes #4894
Kapacitor URLs were overwritten when moving between steps in the Connection Wizard.
Only sync the Kapacitor URL with the source URL when first adding a new Kapacitor. After that, keep the updated Kapacitor URL in the Connection Wizard.

Set kapacitor in ConnectionWizard and call syncHostnames for new kapacitors

---

CHANGELOG.md
ui/src/logs/components/LogsTable.tsx
ui/src/logs/utils/colors.ts
ui/src/shared/components/HistogramChartBars.tsx
ui/test/logs/utils/colors.test.ts

Closes #4862
Extract a util for `brightening` a color that guards against undefined colorValues. Similarly, update the color scale to go from `severity` => `default_severity_color_name` => `default_severity_color_value`.
It's unclear what the root cause of 4862 is. However, 4862 includes an error message regarding an attempt to brighten an undefined colorValue that could be fixed. 
Fix the `colorScale` returning a `colorName` instead of a color hex value when given just a severity level. Extract a color util that adds a guard against `d3-color` trying to brighten an undefined color value.

fix(logs): fix log color utils

---

CHANGELOG.md
ui/src/sources/components/SourceStep.tsx

Closes #4893 
When editing an enterprise source in the connection wizard, the meta node URL was overwritten with the default URL every time the source URL was updated.
Only update the meta node URL with the default URL if the source connection is new. Otherwise, if it is an existing connection being updated, use the URL from state.

Update hostname for meta urls for new sources only

---

CHANGELOG.md
ui/src/dashboards/utils/tableGraph.ts
ui/src/shared/components/OptIn.tsx
ui/src/shared/components/SingleStat.tsx
ui/src/shared/components/TableGraph.tsx
ui/src/shared/utils/decimalPlaces.ts
ui/test/shared/utils/decimalPlaces.test.ts

Closes #5058
Wrap calls to toFixed to handle edge cases in decimcalPlaces.digits
In a few places where `toFixed` is called on `decimalPlaces.digits` it looks like the digits were sometimes out of range: 0 - 100.  The number input also was not doing validation when keypressing was used so min and max went unvalidated.
Wrap the `toFixed` call and ensure that decimalPlaces digits is within the recommended inclusive range of `0 - 20`. Keypressing in the decimal input is now validated to be within range of min/max. However, the input element is still buggy and suffers from issues regarding state mgmt and various events making it hard to debug.

fix(ui): fix decimalPlaces with wrapper

---

CHANGELOG.md
server/cells.go
ui/src/dashboards/components/AxesOptions.tsx
ui/src/dashboards/constants/cellEditor.ts

Closes #4168
When unmarshalling a dashboard, the axis base was getting set to `10` if the value was `""`. This was a legacy feature from before raw was a y axis format option. Once raw (or "") became an option, this value was getting overwritten when saved into bolt.
Update the value for raw from `""` to `raw` so that it does not get changed to `10`.

Stop cells with raw/no format selected from getting changed to base 10

---

CHANGELOG.md
bolt/servers.go
bolt/servers_test.go
organizations/servers.go
organizations/servers_test.go
ui/src/kapacitor/utils/ActiveKapacitorFromSources.ts
ui/src/sources/components/KapacitorDropdown.tsx
ui/test/kapacitor/utils/ActiveKapacitorFromSources.ts

Closes #5061 
Use the first kapacitor present in a collection if none is active and only set the current organization kapacitors to active false.
When all kapacitors were active false the behavior was to render an empty page. Adding or updating a kapacitor connection would set active false for all other kapacitor connections without regard to org.
Use the first kapacitor connection as the active connection in collection when none are active. Scope reseting active fields to false to the current org.

fix: active kapacitor updating and ui defaults

---

CHANGELOG.md
ui/src/sources/components/KapacitorStep.tsx

Closes #5060
`setKapacitorDraft` was added as a prop to the KapacitorStep which is used in both the OnboardingWizard and the ConnectionWizard. The ConnectionWizard passes in the prop whereas the OnboardingWizard does not. Any time a user would edit info in the Kapacitor Form from the onboarding flow, they would get an error message.
Make it an optional prop and only use call that function if the function is passed in.

Fix error when editing kapacitor info in onboarding

---

ui/src/kapacitor/constants/index.ts
ui/src/kapacitor/utils/alertMessageValidation.ts
ui/src/types/kapacitor.ts
ui/test/kapacitor/utils/alertMessageValidation.test.ts

Closes #5090 
Alert rule message validation did not handle each kind of template block as described in the [go templating docs](https://golang.org/pkg/text/template/)
I fixed validation of `if/else` constructs and added validation for range, while, block and with.
###Notes
What this doesn't validate for is that all of the above mentioned blocks don't validate that they include an `end`.

fix(alert): message validation

---

CHANGELOG.md
ui/src/shared/components/OptIn.tsx

Closes #5099
There was a bug with visualization options in the data explorer/cell editor overlay in which typing into the "title" input for Line Controls did not update the field.
Add a type check in the `OptIn` component, so that the input value is only fit to a max/min if it is of type number.

fix(explorer): add type checking to AxesOptions

---

CHANGELOG.md
ui/src/flux/components/FluxEditor.tsx
ui/src/flux/components/FluxScriptEditor.tsx
ui/src/flux/components/flux_functions_toolbar/FluxFunctionsToolbar.tsx
ui/src/flux/helpers/scriptInsertion.ts
ui/src/shared/components/TimeMachine/FluxQueryMaker.tsx

Connects https://github.com/influxdata/influxdb/issues/12503
Functions get inserted at bottom of the script and not in relevant location
add it at cursor position or below line

Insert flux function at or below cursor line

---

ui/src/flux/helpers/scriptInsertion.ts

when adding a from or union function from the functions toolbar and then another one, it did not update the cursor for the next insert to the correct line.
account for the extra new line entered when inserting a from or union

fix cursor location after adding a function with a new line

---

ui/src/shared/components/TimeMachine/FluxQueryMaker.tsx

if you go to the flux script editor section without clicking the actual editor and then try to add a funciton by click on the tool bar, it will not get added to the script.
give an initial cursor position if none is provided by the editor.

ensure flux function gets added when no cursor

---

CHANGELOG.md
ui/src/tempVars/components/MapTemplateBuilder.tsx
ui/src/tempVars/utils/index.ts
ui/test/tempVars/utils/csvToMap.test.ts

Closes #5104 
Double quote the map values so that they can safely be parsed again.
We trim double quotes on map template values, but don't add double quotes back to the regenerated CSV to ensure it can be parsed.
Add test coverage for map values that are unquoted, single quoted and double quoted. One test case in particular demonstrates how single quoted values containing commas will need to be double quoted for correct parsing.

fix(ui/mapVarsToCSV): double quote map template values

---

CHANGELOG.md
ui/src/shared/components/MultiGrid/MultiGrid.tsx
ui/src/shared/components/TableGraph.tsx

Co-authored-by: Brandon Farmer <bthesorceror@gmail.com>
Co-authored-by: Palak Bhojani <palak@influxdata.com>
Closes #5124
When scrolling on a table (rather than scrolling on another cell), the scrolltop was not getting updated correctly.
Pass different props in based on whether the scrolling is externally controlled versus controlled by the user's scrolling.

Fix disappearing data in table graphs

---

CHANGELOG.md
ui/src/dashboards/components/CellEditorOverlay.tsx
ui/src/dashboards/containers/DashboardPage.tsx
ui/src/shared/utils/templates.ts

Closes #5134
The correct time range was being used for the dropdown in the ceo but the templates used to render the template variables in the query were that of the Dashboard and not relevant to the time in the ceo. 
The templates in the ceo should be the dashboard's templates and dashboardTime template variables created from the ceo's time range.

Fix ceo visualization not using ceo time range for query

---

etc/build.py
etc/scripts/post-install.sh

This change sets the ownership of directories on package generation with fpm instead that in post-install to make `rmp -V` pass.
For more details, see: influxdata/EAR#716

fix(package): make rpm verify pass after installation

---

etc/build.py
etc/scripts/post-install.sh
etc/scripts/pre-install.sh

This solves an issue with CentOS installation where the `chronograf` user is not existing when `fpm` is installing and setting ownership on directories.
The same issue was fixed in other projects, see:
- kapacitor: https://github.com/influxdata/kapacitor/pull/2205
- influxDB: https://github.com/influxdata/influxdb/pull/13397
- telegraf: https://github.com/influxdata/telegraf/pull/5783

fix(package): create chronograf user before install

---

flux/client.go
server/sources.go

Closes #5197
Fixes an issue with fetching source versions not timing out
Source version's were not fetched concurrently and did not timeout. This caused the browser to hang when one of many sources was experiencing connection delays.
Add a timeout to each source version fetch and timeout with a default of `"unknown"` after 1 second.

fix(server): timeout and fetch version concurrently

---

CHANGELOG.md
ui/src/shared/components/TableGraph.tsx

Closes #5112
Table graphs were calculating the table index for hoverTime based on stale sortedTimeVals copied to state once on the componentDidMount method, instead of updated sortedTimeVals that reflected user sort selections.

Fix scroll to row bug on table graphs

---

ui/src/shared/utils/downloadTimeseriesCSV.ts

Closes #5170
Changed papaparse json to csv unparse config to always wrap strings in quotes, so that inline commas can be distinguished from delimiter commas.

Reapply Configure papaparse to distinguish inline vs delimiter commas

---

ui/src/data_explorer/components/DEHeader.tsx
ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/shared/components/TableGraph.tsx

UTC / Local time zone selection works for both tables and all dygraph based visualizations.

feat: add time zone selector to data explorer

---

ui/src/dashboards/components/Dashboard.js

When a user creates a cell, they can create an InfluxQL query with the visual query builder. In this case, the query to execute is derived from the cell's query config. They can also enter a query manually, in which case the query config should be ignored.
If a user enters a query manually, we attempt to parse that query into a query config. If we are successful, then it doesn't matter whether we execute the query that was entered manually, or the query derived from the query config.
We can't always parse a query back into a query config, but we nonetheless have always been executing cell queries derived from a query config. This created the issue witnessed in #5131.
This commit changes that behavior; if a query has been entered manually, we will always respect it.
Closes #5131

Fix erroneous query manipulation

---

.github/stale.yml

This PR introduces bot that closes issues that have gone more than 90 days without any activity.

feat(.github): add stale bot config

---

ui/src/kapacitor/components/RuleGraph.tsx
ui/src/shared/components/time_series/TimeSeries.tsx
ui/src/worker/utils/index.ts

_Mostly copied over from https://github.com/influxdata/influxdb/pull/14374_
I'm a co-author of the [uuid npm module](https://github.com/kelektiv/node-uuid) which is being used in some places within the code base of influxdb.
I'm currently trying to understand real-world use cases of [time-based UUIDs ("v1 UUIDs")](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_1_(date-time_and_MAC_address)).
I found two occurrence where `v1` UUIDs were being used instead of `v4` UUIDs and I was wondering if this case really requires the semantically much more complex `v1` UUIDs or whether we could live equally well with purely random `v4` UUIDs? Please see my commit messages for more details.
At least the test suite still passes after my changes, so apparently this doesn't seem to …

Use v4 instead of v1 uuids

---

ui/package.json
ui/yarn.lock

Both `axios` and `lodash` are direct dependenies and therefore were
updated.
See https://github.com/influxdata/chronograf/network/alert/ui/yarn.lock/lodash/open and https://github.com/influxdata/chronograf/network/alert/ui/yarn.lock/axios/open
Closes #5238

security: upgrade axios and lodash to verious without known vulnerabilities

---

ui/src/shared/utils/TimeMachineContainer.ts

https://github.com/influxdata/EAR/issues/1019
Prevent DROP or DELETE's from being saved to local storage in the DataExplorer.  This is a ham-fisted way of preventing re-execution.

fix: drop delete

---

CHANGELOG.md
oauth2/github.go

When using github oauth, and the user has authorized access to > 10 orgs, a logic error is triggered where the first 10 orgs the user is a member of is retrieved over and over again until the api rate limit is hit. This prevents such a user from being able to login and leaves them with an exhausted github API rate limit.  There is also a secondary issue in that the error message is wrong (will fix on a separate PR).
```
time="2019-08-22T23:15:54Z" level=error msg="OAuth access to email address forbidden GET https://api.github.com/user/orgs?per_page=10: 403 API rate limit of 5000 still exceeded until 2019-08-23 00:11:18 +0000 UTC, not making remote request. [rate reset in 55m24s]"
time="2019-08-22T23:15:54Z" level=error …
```

fix github org pagination when user has > 10 orgs

---

server/swagger.json

This came up from https://github.com/influxdata/chronograf/issues/5291
where consumers of the API thought that they would be able to specify an
ID when a dashboard is created.

fix(server): add DashboardCreate object to swagger definition

---

CHANGELOG.md
ui/src/tempVars/constants/index.ts

Closes https://github.com/influxdata/chronograf/issues/5297

fix(data-explorer): always include upper dashboard time in query

---

.circleci/config.yml
.github/PULL_REQUEST_TEMPLATE
CHANGELOG.md
Makefile
etc/Dockerfile_build
etc/README.md
etc/build.py

Closes #5320
- Pins go to latest minor revision (e.g. `1.12.x` where `x` is currently `13`, but will soon be `14`)
- Updates the Python build script to always run `make dep` (passes `-B` to `make`). I was having issues where `go-bindata` wasn't being installed properly, and it looks like it's because `make` thought that there was nothing to run with `dep`

chore: pin go to latest minor go version

---

CHANGELOG.md
ui/src/shared/apis/flux/metaQueries.ts

Closes https://github.com/influxdata/chronograf/issues/5316
Flux started erroring on a query that used to work.
Use the v1 package.

fix(schema-explorer): update the flux schema explorer to use v1 package

---

CHANGELOG.md
ui/src/shared/components/Dygraph.tsx

Closes #5314
y-axis labels were disappearing. This is a band-aid to fall back to a known value for the y-axis

fix(ui): use the the available y-axis label

---

CHANGELOG.md
kapacitor/validate.go
kapacitor/validate_test.go

Closes https://github.com/influxdata/chronograf/issues/5332
Previously we used the heuristic of checking if `batch` was a substring of the tickscript. This caused an issue where the user had a regular script `batchsvc` in their tickscript. We instead use a slightly better heuristic which is to check for `batch|`, `batch `, or `batch\n`. This is not perfect, but should suffice. I had attempted to parse and walk the kapacitor ast, but the walk function exposed does not make this easy.

fix(kapacitor): use better heuristic than string contains `batch` when creating tasks

---

CHANGELOG.md
influx/query.go
influx/query_test.go

Closes https://github.com/influxdata/chronograf/issues/5330
When we added upperDashboard time to queries, it resulted in an invalid query config. To resolve this we treat dashboardTime and upperDashboardTime the same.

fix(influx): allow upperDashboardTime when generating query config

---

ui/src/utils/defaultQueryConfig.ts

Previously used the same template range for both kapacitor rules and data explorer. When we introduced upperDashboardTime to DE, we accidentally broke kapacitor rules. This fix, conditionally checks to see that the query config we are creating is a kapacitor rule query config and removed upperDashboardTime.

fix(defaultQueryConfig): if in rule remove upper dashboard time

---

go.mod
ui/package.json

Upgrade go to 1.13 in go.mod
Upgrade node-sass dependency to 4.13.0

chore: upgrade go and node-sass dependencies

---

CHANGELOG.md
ui/src/auth/Login.js

Closes #5333
Reverts previous change that auto-redirected back to ouath provider's login. You may now get off Mr. Bones' Wild Ride.
Testing instructions:
1. Set up github as an oauth provider for Chronograf: https://developer.github.com/apps/building-oauth-apps/creating-an-oauth-app/
1. Set up the local settings to look like this: ![p](https://user-images.githubusercontent.com/146112/71691160-77003e80-2d5b-11ea-97f7-b10000edb20a.png)
1. Make sure you're on this branch `bs_allow_logouts`
1. Launch chronograf using github as an oauth provider. `TOKEN_SECRET` can be any arbitrary string. I chose song lyrics. Replace the `$CHRONOGRAF_GH_CLIENT_ID` and `CHRONOGRAF_GH_CLIENT_SECRET` with the values that github gives you, or export those values as variables below. …

fix: allow signing out when using oauth

---

CHANGELOG.md
ui/jest.config.js
ui/src/logs/components/LogsTable.tsx

Closes #5337
This passes a default value to `colorLevel` to guard against an incorrect key being used.
This doesn't fix the underlying issue that the error reporter is wonky on the log viewer. I was able to tweak it so the error reporter looked good, but it involved moving `FancyScrollbars` to a different parent so it became the parent of an `AutoSizer` and that frankly made me very worried and uncomfortable. I'm very hesitant to change the structure of an application I don't understand well. So we're slapping the easy fix on this and if we see more issues of this cropping up, we'll address it then.

fix: log viewer uses a default if the mapped severity doesn't exist

---

CHANGELOG.md
ui/src/dashboards/actions/index.ts
ui/src/dashboards/components/CellEditorOverlay.tsx
ui/src/dashboards/components/DashboardHeader.tsx
ui/src/dashboards/containers/DashboardPage.tsx
ui/src/dashboards/containers/DashboardsPage.tsx
ui/src/dashboards/reducers/dashTimeV1.ts
ui/src/dashboards/selectors/index.tsx
ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/hosts/containers/HostPage.tsx
ui/src/hosts/containers/HostsPage.tsx
ui/src/localStorage.ts
ui/src/normalizers/dashboardRefresh.js
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/shared/components/TimeMachine/TimeMachineControls.tsx
ui/src/shared/components/dropdown_auto_refresh/AutoRefreshDropdown.tsx
ui/src/shared/constants/index.ts
ui/src/types/dashboards.ts
ui/src/types/index.ts
ui/src/types/localStorage.ts
ui/test/dashboards/reducers/dashTimeV1.test.js

Closes https://github.com/influxdata/chronograf/issues/4012
- User selects a refresh rate in the dashboard: the selection is persisted for that dashboard and a query parameter is added to the url.
- A url with custom query parameters is used to directly navigate to a dashboard: the dashboard sets the refresh rate, persists it, and updates the refresh dropdown based on a valid query parameter for refresh.

feat(ui): add query parameter for autofresh option in dashboards

---

chronograf.go
cmd/chronoctl/README.md
cmd/chronoctl/migrate.go
kv/org_config.go
mocks/org_config.go
noop/org_config.go
organizations/org_config.go

related #5062
per request from tim, this adds a command to migrate a db from bolt to etcd and visa versa. there is no promise that the options/functionality will not change, hence the 'beta' note. obviously there is also no guarantee that there will never be any data loss.
after several manual tests, i do have a high level of confidence in the functionality presented.
from the addition to the readme:
The `migrate` command allows you to migrate your chronograf configuration store. It is highly recommended that you make a backup of all databases involved before running a migration as there is no guarantee that there will be no data loss. When specifying an etcd endpoint, the URI must begin with `etcd://`. It is preferred that you prefix `bolt://` to an absolute path when specifying a local …

feat: add migrate command to chronoctl

---

server/server.go
ui/test/resources.ts
ui/test/shared/parsing/constants.ts

Addresses #5315
The headers should still be addressed so all other versions of chronograf can work, but this has Fixed It For Me:tm:

fix: use influxdata url that happens to have the correct cors headers

---

flux/client.go
server/sources.go

Closes #5357
Chronograf would fail to check for flux support if the influx was using self signed certs. Solved by passing the source's insecureSkipVerify setting to the flux client to be used in the checks.

fix: pass insecure cert settings to flux client

---

canned/apache.json
canned/haproxy.json
canned/influxdb_httpd.json
canned/influxdb_write.json
canned/kubernetes_pod_network.json
canned/memcached.json
canned/netstat.json
canned/nginx.json
canned/nsq_topic.json
canned/phpfpm.json
canned/redis.json

Closes #5358
changes non_negative_derivative calls in the json files in canned directory to include the 1s
`- non_negative_derivative(max("tcp_established"))
+ non_negative_derivative(max("tcp_established"), 1s)`

update non_negative_derivative calls to fix #5358

---

README.md
canned/bin.go
chronograf.go
filestore/dashboards.go
filestore/dashboards_test.go
server/builders.go

Closes #5364
This change allows .dashboard files with integer ids to be used without modification in chronograf 1.8

fix: allow backwards compatibility with filestore .dashboard files

---

CHANGELOG.md
chronograf.go
dist/dist.go
server/env.go
server/env_test.go
server/server.go
ui/mocks/shared/apis/env.ts
ui/src/index.tsx
ui/src/shared/actions/env.ts
ui/src/shared/apis/env.ts
ui/src/shared/reducers/env.ts
ui/src/shared/reducers/index.js
ui/src/side_nav/containers/SideNav.tsx
ui/src/store/configureStore.js
ui/src/types/actions/app.ts
ui/src/types/env.ts
ui/src/types/index.ts
ui/src/types/localStorage.ts
ui/yarn.lock

Closes #5370
Introduces a new option to disable rendering and serving of the hosts page.
`chronograf -H`, `chronograf --host-page-disabled`, or setting the following environment variable:
```sh
HOST_PAGE_DISABLED=true
```
* Start the chronograf go server with the envvar `HOST_PAGE_DISABLED` set to true.
* Simple way to do it: `HOST_PAGE_DISABLED=true go run ./cmd/chronograf/ -d`
* Go to any page in the app - the hosts page should be missing from the side nav
* Hit the hosts page directly `/sources/$sourceId/hosts`

WIP: feat(hostlist): add env variable to disable host list page

---

Makefile

Closes #5384
`go list` adds to go.mod (https://github.com/golang/go/issues/28014), while `go mod tidy` cleans it up causing churn in the go.mod file.
Use non-intrusive means to determine if we need to install the go application.

fix: don't use 'go list' to determine if a go application is installed

---

etc/build.py

Old script resulted in arm32 binaries, not executable on modern pure 64-bit arm processors.
This is minimal changes to correctly handle arm64
Problem is that existing code generates arm32 binaries not executable on many Armbian CPUs without arm32 support. This simple change instructs the compiler to target arm64.

Correct arm64

---

CONTRIBUTING.md
README.md

Updates versions in docs, and specifically link to node 10.13.0 lts

chore: update docs to be more clear about node and go versions

---

ui/src/flux/components/SourceDropdown.tsx
ui/src/reusable_ui/components/dropdowns/Dropdown.tsx
ui/src/tempVars/components/TemplateVariableEditor.tsx

Connects #5381
Fixes 75% of the issues above for a solid, passing, average C.
* Fixes z-index of source dropdown when the type is map or CSV
* Switching a source now re-runs the query but doesn't blow away current options.
* **Still left to do (but don't let it block this pr):** make query run on modal opening.

Bs source variable polish

---

cmd/chronoctl/genKey.go
cmd/chronoctl/token.go
go.mod
server/auth.go
server/auth_test.go
server/mux.go
server/server.go

This short-circuits any configured authentication, allowing a user with the correctly signed message to act against the api.
Closes #5387
--------------------------------------------------
Adds `chronoctl gen-keypair` to generate an rsa keypair.
Adds `chronoctl token --priv-key-file /path/to/private/key` to request and sign a message to authenticate with a chronograf started with a public key.
Adds `chronograf --pub-key-file /path/to/public/key` to enable token authentication for the owner of the keypair.
Start chronograf:
```sh
chronograf --pub-key-file="./chronograf-rsa.pub" # other oauth options
```
Get and use signed message as authorization token:
```sh
export SIGNATURE=$(chronoctl token --priv-key-file chronograf-rsa)
curl -H "Authorization: CHRONOGRAF-SHA256 ${SIGNATURE}" \ …
```

feat: add ability to authenticate single superadmin user

---

ui/src/status/components/JSONFeedReader.tsx
ui/src/types/status.ts

Closes #5416 
It seems the feed data structure has changed from having a single `author` to multiple `authors`, this accounts for that.

fix: handle change to news feed data structure

---

influx/influx.go

Closes #5423
If influxdb (>=1.7.9) was configured with `ping-auth-enabled`, chronograf would get 401's when pinging the source. This adds configured authentication to the request to resolve that.

fix: use auth settings when pinging source

---

ui/src/types/logs.ts

Closes #5435
_Code cleanup:_ Removed invalid import and duplicated type definitions

chore(ui): removed duplicated types + invalid import

---

CHANGELOG.md
cmd/chronoctl/main_test.go
cmd/chronoctl/token.go

Closes #5454
The `token` command had an option added with a bad default value causing the adding of the command to fail, which we silently ignored.
Remove the bad option default and add tests to ensure all subcommands stay available.

fix: token option issue

---

CHANGELOG.md
server/server.go
server/server_test.go

Closes #5450
If there were any missing oauth settings, chronograf would start without authentication.
If oauth settings are only partially added, an error is logged and chronograf fails to start.

fix: validate oauth settings prior to starting

---

CHANGELOG.md
oauth2/cookies.go
oauth2/google.go

also updates google oauth to use non-deprecated calls
Closes #5395 
jwts were expiring faster (5 mins) than a user cookie was which was logging users out if they closed chronograf browser sessions for longer than the 5 minutes.
Increase the refreshed timeout (refreshed each call to `/me`) to match the configured cookie lifespan.

fix: extend jwt expiration time to match cookie

---

CHANGELOG.md
oauth2/mux.go
oauth2/mux_test.go
server/server.go
server/server_test.go

Closes #5402
When using generic oauth provider with tls, you will get insecure cert errors.
Add a way to skip verifying those certs as well as pointing to a root ca that can be used to verify the "insecure" cert.

feat: add ability to ignore or verify self signed oauth certs

---

ui/src/shared/components/MultiGrid/MultiGrid.tsx

Closes #5465 
When scrolling through a table graph type, the left and right panels became misaligned
The [original fix](https://github.com/influxdata/chronograf/commit/c8ba74b441c4a648a371f3c2ae8f37686bb43eb1#diff-a5aa3b99aa7b563a84bca863d3b71a9dR399) missed adding back `SCROLLBAR_SIZE_BUFFER`
Chrome and Firefox respectively:
[The original EAR fix](https://github.com/influxdata/chronograf/pull/5429) remains intact:

fix: table graph panels should be aligned when scrolling

---

CHANGELOG.md
server/server.go
server/server_test.go

Closes #5473
Repro/verify with:
```sh
./chronograf \
--generic-auth-url abc123 \
--generic-token-url abc123 \
--generic-client-id abc123 \
--generic-client-secret abc123 \
--public-url abc123 \
-t abc123
```

fix: remove common public-url config from oauth validation check

---

CHANGELOG.md
go.mod
go.sum

Closes #5511 
When Chronograf is built using go 1.14 it crashes right on start, due to logger problem.
Updating _logrus_ to 1.6.0 (which in turn transiently updates _go-windows-terminal-sequences _ to 1.0.3) fixes that.

fix: crash on windows when built by go 1.14

---

ui/src/shared/components/TableGraphFormat.tsx

Closes #5457 
The sorting function is also called with an undefined sort column upon every refresh. When undefined is received, the table graph's default sorting is applied.
Change the state of the table sorting only upon a change of sorting key, ignore actions that want to sort by undefined columns (refresh).

fix(dashboard): keep table sorting on refresh

---

ui/src/shared/parsing/flux/response.ts
ui/src/worker/worker.ts

When I was trying to reproduce #4825, no Line Graph visualization was shown even for a simple query, the browser console did not help to trace down the issue.  It was really difficult to find out the root cause. There were two problems:
1. it was difficult to trace of what exactly failed because the trace to the failing code is hidden (in the worker)
1. no visualization was shown because I was using the latest influxDB1.8 docker, that returns CSV query results separated by \r\n, the parser then created lines with null data that then failed in the background worker job.
1. chore: log worker errors
1. repair the flux result parser to support also \r\n line separators sent from the latest 1.8 [influxdb …

fix(ui): report worker errors, better parse flux CSV results

---

CHANGELOG.md
ui/src/kapacitor/utils/alertMessageValidation.ts
ui/test/kapacitor/utils/alertMessageValidation.test.ts

Closes #5492 
{{.Time.Unix}} was reported as invalid in alert message template, although it is valid 
The UI message validator was enhanced to support {{.Time.Unix}} and {{.Time.UnixNano}}

fix(kapacitor/alert): support .Time.Unix message validation #5492

---

CHANGELOG.md
server/kapacitors.go
server/kapacitors_test.go
ui/src/index.tsx
ui/src/kapacitor/components/KapacitorRules.tsx
ui/src/kapacitor/components/KapacitorRulesTable.tsx
ui/src/kapacitor/components/TasksTable.tsx
ui/src/kapacitor/containers/KapacitorRulePage.tsx
ui/src/kapacitor/containers/KapacitorRulesPage.tsx
ui/src/kapacitor/containers/TickscriptPage.tsx
ui/test/kapacitor/components/KapacitorRulesTable.test.tsx
ui/test/kapacitor/components/TasksTable.test.tsx

Closes #5493
Ensure that there is at most one active kapacitor per source DB.
The `active kapacitor` from the dropdown is not reliably set in the chronograf server store (go part). The server-side active kapacitor is now always used when creating/updating kapacitor's rules or tickscripts.
1. Change API that activate kapacitor to deactivate existing active kapacitor(s).
2. Change UI routing paths of pages that create/update rules/tickscripts to include kapacitor ID and propagate it to nested react components

feat(kapacitor): repair management of kapacitor rules and tickscripts

---

CHANGELOG.md
ui/src/shared/components/TimeMachine/RawFluxDataTable.tsx
ui/src/shared/parsing/flux/response.ts

Closes #5476
Error when changing view from the empty graph to raw table data with data. It was caused by passing `-Infinity` to `Grid`
Make sure param for `Grid` is valid.

fix: Avoiding passing invalid number to Grid

---

ui/src/dashboards/utils/dashboardSwitcherLinks.ts

Closes #5474
When dashboard page is loading, the associated dashboard is undefined until it is fetched. Having an undefined dashboard (not yet known), https://github.com/influxdata/chronograf/blob/15bf39703f3ed0b3ef439fe39eb943836d557573/ui/src/dashboards/utils/dashboardSwitcherLinks.ts#L30 
fails on `activeDashboard.id`
The code already reacts upon undefined dashboard to return a new valid state, so I moved this section before checking `activeDashboard.id`

fix(dashboard): avoid undefined error when dashboard is not ready yet

---

ui/src/kapacitor/utils/alertMessageValidation.ts
ui/test/kapacitor/utils/alertMessageValidation.test.ts

Closes #5343
- {{.}} was not supported
- [global functions](https://golang.org/pkg/text/template/#hdr-Functions) were not supported
- [text trimming](https://golang.org/pkg/text/template/#hdr-Text_and_spaces) was not supported
- validation was enhanced to pass in such cases

fix(kapacitor/alert): accept valid templates 

---

CHANGELOG.md
ui/src/logs/utils/table.ts

Closes #5472
If no timestamp field is defined in the syslog measurement, point's time is used.  
Null values were shown as 1970-01-01...  
Null timestamp value is replaced by point's time value multiplied by 1_000_000 ( nanos are used by [telegram syslog input plugin](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/syslog/syslog.go#L382), but millis are used to represent time in the web UI )

fix(logs): fall back to point timestamp

---

CHANGELOG.md
ui/src/shared/components/TableGraph.tsx
ui/src/shared/decorators/errors.tsx
ui/src/worker/jobs/timeSeriesToTableGraph.ts
ui/test/worker/jobs/timeSeriesToTableGraph.test.tsx

Closes #5347
- when an error occurs, no error message is displayed to the user, since the Error component is inside an <AutoSizer> element of 0x0px size.
- if multiple queries return the same column name(s), invalid data are created for the table graph to display
- Added custom rendering of an error when it appears in TableGraph. It is now rendered inside an element with an absolute position, the table data are rendered this way to be visible.
- Columns in the merged data have unique names so that there is no name-clash anymore.

fix(TableGraph): merge query results with unique column names

---

CHANGELOG.md
ui/src/flux/constants/functions.ts

Along with the fix, this also proposal about improving the view on `csv.from` functions.
When someone filters `csv.from` she sees  2 (actually 4 because of a bug) `csv.from`, without any distinguisher.  She must place the cursor over each entry to see the difference.
Also, the first cvs.from from the `csv` package has two possible params, but there can be the only one argument used at a time, which is against other functions, where all params can/must be used. 
Closes #5523
_What was the problem?_ 
`cvs.from` was shown multiple times because of the duplicate key in the list
_What was the solution?_ 
Make each `cvs.from` unique.

fix: making each csv.from unique

---

CHANGELOG.md
ui/src/index.tsx

Closes #5382 
_What was the problem?_ Zooming out in presentation mode exits presentation mode
_What was the solution?_ disablePresenstationMode() event was dispatch every time location has been changed. Added filter to dispatch even only if path part changes

fix: zooming out stops presentation mode

---

CHANGELOG.md
protoboards/mysql.json

Closes #5552 
The display of counters isn't very useful, it can be far better to show the absolute change. For graphs like that I've used the non_negative_derivative to show this.
- [N/A] Tests pass

fix: make MySQL protoboard more useful by using derivatives

---

server/swagger.json

The external `statusFeed` parameter has been corrected.
_Briefly describe your proposed changes:_ Updating JSON feed URL
_What was the problem?_ Incorrect news feed URL
_What was the solution?_ Update news feed URL

fix: example statusFeed URL in swagger

---

CHANGELOG.md
Dockerfile

upgrade docker to use Alpine Linux to 3.12
Dockerfile is based on Alpine Linux 3.8, which is out of support. 
Upgrade to 3.12 + tested manually with 
```
make docker
- docker run --name cl --network host chronograf:latest 
- check that UI is running fine, do a simple adhoc query
```

chore: upgrade docker alpine to 3.12

---

CHANGELOG.md
ui/src/utils/groupByTimeSeriesTransform.ts
ui/test/utils/timeSeriesTransformers.test.ts

Closes #5502
The transformation that creates table data from InfluxDB response returns time series values that do not require a unique time. If there are more values for a specific time, there will be more rows of the same time with all the data for that time.
The transformation 'from influx responses to table data' groups table data by time and always updates an existing time item when found. This approach overrides existing data if there are more results for a specific time.
If the transformation is allowed to create time series with duplicate time (which is the case of table data), the existing item is updated only if it does not override data that were already set. If an override is detected, a …

fix(ui): show all query results in table view #5502

---

CHANGELOG.md
ui/src/kapacitor/components/LogItemKapacitorPoint.tsx

Closes #5481
Field/Tag values are now printed in tickscript logs.
The tag/field value was rendered as `{val}`, https://reactjs.org/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored ... so that no value is shown to the user
`{String(val)}`

fix(ui): show also bool tag/field values in tickscript editor logs

---

CHANGELOG.md
go.mod
go.sum
server/mux.go
server/server.go

Closes #4562
This PR allows to turn on HTTP basic access authentication so that all HTTP requests to chronograf are restricted to selected users. This is possible on CLI with `--htpasswd <path to .htpasswd file>` or with `HTPASSWD` environment variable.
The `.htpasswd` file contains users and their passwords, it is usually managed by the `htpasswd` utility, see https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/ to know more.
This type of authentication should be used in cases, in which OAuth integration is not possible.
**Warning**: When using basic authentication, the authorization rules of Chronograf are not enforced. Basic access authentication only controls who can access Chronograf, users are then super users.

feat(server): allow to configure basic access authentication

---

CHANGELOG.md
oauth2/cookies.go
oauth2/cookies_test.go
oauth2/mux_test.go
server/server.go

Closes #5395
Makes session inactivity duration configurable. 
Currently the default is 5 minutes and it could only go lower if session duration is below that value.

feat(session): make session inactivity duration configurable

---

.github/PULL_REQUEST_TEMPLATE

This PR adds [well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/) checkbox into github's pull request template.

chore(github): require well-formatted commit messages in PR template

---

CHANGELOG.md
ui/package.json
ui/yarn.lock

This PR upgrades `papaparse` in order to fix high-severity security issue https://github.com/advisories/GHSA-qvjc-g5vr-mfgr .

fix(ui): upgrade papaparse to 5.3.0

---

CHANGELOG.md
ui/src/kapacitor/components/AlertTabs.tsx
ui/src/kapacitor/components/config/OpsGenieConfig.tsx
ui/src/types/kapacitor.ts

Closes #5594 
UI enahnced to specify Opsgenie2 recovery actions

feat(kapacitor/opsgenie2): add recovery action

---

CHANGELOG.md
kapacitor/client.go
kapacitor/client_test.go

Closes #4304 
Chronograf tries to parse TICK script to determine if it can display it as an alert tule or a generic TICK script. If the parsing (to alert rule) fails, chronograf (since this PR) also tries to find a line with `var name = 'Rule Name')  to find a task name. If that also fails, the kapacitor task id is used, as it was before this PR.

fix(kapacitor): parse task name from TICKScript

---

CHANGELOG.md
ui/src/dashboards/components/rename_dashboard/RenameDashboard.scss

Closes #5593 #5296 
Caused by decimal width conversions, fixed by extending the dashboard name width by 1px

fix(dashboard): don't truncate dashboard name with lots of room

---

CHANGELOG.md
ui/src/style/external/codemirror.scss
ui/src/style/pages/tickscript-editor.scss

Closes #5037
Fixes layout so that the TICKscript editor is scrollable in Firefox. Firefox seems to compute the width of an editor element from the nested elements of the flex layout, even though the width of the parent element shall be used. Specifying width in _vw_ units fixes the issue and ensures that it does not affect other supported browsers.
Additionally, the following disturbing white box becomes transparent (black) in this PR (for all browsers):

fix(tickscript): repair editor scrolling

---

CHANGELOG.md
influx/influx.go
server/proxy.go

Closes #5583 
This PR ensures that a shared HTTP Transport is used in client connections from chronograf to connected InfluxDB databases and kapacitors. The shared transport is built on top of golang's [DefaultTransport](https://golang.org/pkg/net/http/#RoundTripper) that applies reasonable timeouts and system proxies.
No transport timeouts caused failing idle connections in AWS; no proxy can be configured; leaking transport in a kapacitor proxy that does not reuse existing transport (when InsecureSkipVerify)
Use shared transport(s), apply golang's defaults.

fix(servers): apply default timeouts in server connections

---

CHANGELOG.md
ui/src/shared/components/CustomTimeRange.js
ui/src/shared/components/TimeRangeDropdown.js

Closes #5602
- time is printed in the selected time zone (Local , UTC)
- time is picked in the selected time zone
- time rendering reacts upon change of the time zone

fix(ui): respect selected timezone in range picker

---

CHANGELOG.md
ui/src/shared/components/TimeMachine/CSVExporter.tsx
ui/src/shared/utils/downloadTimeseriesCSV.ts

Closes #5329
When the user executes an InfluxQL query and clicks the `CSV` button to download results as CSV, the CSV results contains a time column that is always formatted according ISO8601 with a time zone that is selected in UI (UTC or Local).

fix(ui):  export CSV with a time column formatted according to selected time zone

---

ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/parsing/index.ts
ui/src/utils/ajax.ts

Closes #5599
Default visualizations are not shown when no data is present + repair handling of network errors.
Default visualizations were shown when loading + no previous results.
Default visualizations are not shown when no data is present.

fix(ui): avoid blinking during dashboard refresh

---

kv/etcd/client.go
server/server.go
server/tls_options.go
server/tls_options_test.go

Closes #5576
This PR adds `--etcd-cert` and `--etcd-key` options to `chronograf` so that SSL/TLS client authentication can be used in communication with ETCD. Environment variables `ETCD_CERTIFICATE` and `ETCD_PRIVATE_KEY` can be used as well.

feat(etcd): allow to configure  ETCD with client certificate

---

ui/src/kapacitor/components/RuleGraphDygraph.tsx
ui/src/shared/components/FieldList.tsx
ui/src/utils/timeSeriesTransformers.ts

Closes #5561 
No dygraph is visualized when non-numerical data are detected.
String values cannot be visualized in dygraph, such data will not work in a tick script created by `Rule Alert Builder`
Detect non-numerical values and display a warning.

fix(alert rule): warn about unsupported data

---

kapacitor/ast.go
kapacitor/ast_test.go
kapacitor/vars.go
kapacitor/vars_test.go

Closes #5518 
When creating `whereFilter` variable in alert rule builder, join not-equal tag conditions with AND operator.
They were OR-ed, which is desired for `==` conditions, but it is not `!=`
Use AND when `!=` tag comparison operator is used.

fix(kapacitor): AND not equal conditions in where filter

---

ui/src/admin/containers/AdminInfluxDBPage.tsx

Closes #5614
InfluxDB Admin Page shows
```
These functions are not available for the currently selected InfluxDB Connection.
```
if non-v1 InfluxDB source is detected.

fix(ui): disable InfluxDB admin page if administration is not possible

---

flux/client.go
influx/authorization.go
influx/influx.go
server/flux.go
server/sources.go
ui/src/reusable_ui/components/wizard/WizardCheckbox.tsx
ui/src/shared/constants/index.ts
ui/src/sources/components/SourceStep.tsx

Closes #5617
* flux support is automatically detected also for v2 InfluxDB instances (OSS and cloud)
* org parameter is added from username in `/api/v2/query` requests
* token authentication is used, it is required for v2 `/api/v2/query`
* InfluxDB source wizard shows Organization + Token when v2 is detected.
* a new checkbox `InfluxDB v2` wad added to switch labels between v1 and v2 connections
* connection type (v1 vs v2) is automatically detected, a user can switch between v1 and v2 to adjust form labels (v1:username+password , v2: organization+token)
The schema part of flux explorer still uses the v1 API. It does not show all buckets of InfluxDB v2, but only v1-mapped. See https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/dbrp …

feat: support flux against InfluxDB v2 sources

---

CHANGELOG.md
ui/src/shared/parsing/flux/durations.ts

Closes #5623
A new current time was used across in partial functions
All partial functions share the same current time, it is now passed from outside.

fix(duration): repair relative computation of multiple ranges

---

CHANGELOG.md
ui/src/shared/query/helpers.js
ui/test/shared/query/helpers.test.js

Closes #5620
`:upperDashboardTime:` and `:dashboardTime:` placeholders were not recognized as time specified
`:upperDashboardTime:` and `:dashboardTime:` are considered as being timestamps when recognizing range type and creating a shifted query

fix(ui): repair visual comparison with time variables

---

CHANGELOG.md
chronograf.go
influx/authorization.go
server/flux.go
server/sources.go
server/sources_test.go
ui/src/admin/containers/AdminInfluxDBPage.tsx
ui/src/dashboards/components/SourceSelector.tsx
ui/src/flux/components/DatabaseList.tsx
ui/src/flux/components/FetchMeasurements.tsx
ui/src/flux/components/SchemaExplorer.tsx
ui/src/flux/helpers/scriptBuilder.ts
ui/src/shared/apis/flux/query.ts
ui/src/shared/components/TimeMachine/FluxQueryMaker.tsx
ui/src/shared/components/TimeMachine/FluxScriptWizard.tsx
ui/src/shared/components/time_series/TimeSeries.tsx
ui/src/shared/constants/index.ts
ui/src/shared/utils/fluxScriptWizard.ts
ui/src/sources/components/SourceStep.tsx

This PR lets the user choose whether to communicate with InfluxDB with v1 (basic) or v2 (token) authentication. It further improves #5617 in the following way:
1. v1 authentication is used by default, no changes are thus required when InfluxDB source upgrades from v1 to v2. The upgrade process creates v1 authentication credentials in v2.
1. The user can choose whether to use v1 (default) or v2 authentication when establishing a new connection or updating an existing one using the `InfluxDB v2 Auth` checkbox. The type of user-selected authentication is then persisted in the chronograf database and used in the communication with InfluxDB.
* v1 (unchecked) changes the UI to let the user enter `Username` and `Password` fields: 
* v2 (checked) let the user specify `Organization` and `Token`: …

feat: let user specify InfluxDB v2 authentication type and then fully use v2 flux

---

CHANGELOG.md
influx/influx.go
influx/influx_test.go
server/sources.go
server/sources_test.go
ui/src/sources/components/DashboardStep.tsx

Closes #5633
* Credentials are validated when creating or updating InfluxDB connection
* v1 auth: executes `SHOW DATABASES` InfluxQL query
* v2 auth: executes `buckets()` Flux query
* a possible server error message is shown in UI's notification center:
* `Dashboards` step in the connection wizard is not randomly stuck in a Loading state anymore

feat(ui): validate connection credentials

---

CHANGELOG.md
ui/src/flux/components/DatabaseList.tsx
ui/src/flux/components/SchemaExplorer.tsx
ui/src/shared/components/TimeMachine/FluxQueryMaker.tsx
ui/src/shared/components/TimeMachine/FluxScriptWizard.tsx

This PR repairs the way of how Flux buckets are retrieved in the Explorer UI for v1 InfluxDB sources. The v1 buckets are shown using a fully-qualified name ( `database/retentionPolicy`) that will also work after migration to InfluxDB v2.
Additionally, it does the same changes in the Flux Script Wizard when v1 Flux is used.
Use `buckets()` flux query under the hood so that a bucket name is the same after data migration to v2, it is "database/retentionPolicy".
Short names are offered, these short names AFAIK cannot be used after migration of v1 to v2.
v2 API is used to obtain bucket names, these are then fully qualified.

feat(ui): use fully qualified names of v1 buckets

---

server/databases.go
ui/src/admin/containers/QueriesPage.js
ui/src/shared/apis/databases.ts

Closes #5531
Some UI pages show no data for all databases when chronograf uses InfluxDB Enterprise connection with a user that does not have ReadData permission to one database. This PR repairs these pages to show data for the databases that can be read.
1. Admin/Databases: The databases that are shown by `SHOW DATABASES` and cannot be further inspected with `SHOW RETENTION POLICIES ON database` are logged in the server log and ignored in the returned database list.
2. Admin/Queries: Only the databases for which the user cannot execute `SHOW QUERIES` are now shown.
3. Explorer/Schema Explorer: Only databases with retention policies that can be read are already shown in 1.8.9, only the console log was improved herein.

fix(server): ignore databases that cannot be read

---

oauth2/generic.go
oauth2/generic_test.go

Closes #5399
Enhance processing of "user emails" response to support bitbucket's https://developer.atlassian.com/bitbucket/api/2/reference/resource/user/emails 
Bitbucket's `/emails` response was not recognized.
Support for bitbucket `/emails` response added and an example bitbucket response is unit-tested.

feat(oauth): support bitbucket primary email retrieval

---

ui/src/dashboards/components/ImportDashboardOverlay.tsx
ui/src/dashboards/components/import_dashboard_mappings/ImportDashboardMappings.tsx
ui/src/dashboards/utils/importDashboardMappings.ts
ui/src/tempVars/components/TemplateVariableEditor.tsx
ui/test/dashboards/components/ImportDashboardMappings.test.tsx
ui/test/dashboards/utils/importDashboardMappings.test.ts
ui/test/fixtures/index.ts

Closes #5645
* sources in variables are identified and remapped during dashboard import
* a missing variable is also identified and created
* variables are also shown in the mapping table
* when a variable source does not exist now a dynamic source is used (with an error message logged)
* source reference in variables were ignored during import and can then lead to an inconsistent state in the UI
* a variable that uses a source that was later deleted cannot be then changed in UI
* sources in variables are remapped during dashboard import
* when a variable source does not exist now a dynamic source is used (with an error message logged)

fix(ui/dashboard): repair import to remap also sources in variables

---

ui/src/logs/constants/index.ts
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/utils/fetchChunk.ts

Closes #5434
* Limit the count of empty fetches to at most 10 when extending the time interval for the Logs table.
* Show actual time interval when loading Logs table, it was not properly updated every 5 seconds when switching from the `date picker value` and `now`.
https://github.com/influxdata/chronograf/issues/5434#issuecomment-748915638
Limit the count of empty fetches to at most 10 when extending the time interval for the Logs table.

fix(ui/logs): stop log fetches after 10 empty cycles

---

server/influx.go
server/influx_test.go
ui/src/dashboards/components/InfluxQLEditor.tsx
ui/src/data_explorer/constants/index.ts
ui/src/shared/components/TimeMachine/InfluxQLQueryMaker.tsx
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/shared/components/dropdown_auto_refresh/autoRefreshOptions.ts
ui/src/shared/parsing/index.ts

Closes #5650 #5651
The InfluxQL command that is sent to chronograf (from the Explorer UI) can specify a database and retention policy to use for the next command with the USE command (already used in  `influx` tool ). Example:
```
USE telegraf ; DELETE FROM mem WHERE time < '2020-12-19T15:00:00Z'
```
_Metaquery Templates_ are enhanced with the following items
* `USE "db_name"; DROP MEASUREMENT "measurement_name"`
* `USE "db_name"; DROP SERIES FROM "measurement_name" WHERE "tag" = 'value'`
* `USE "db_name"; DELETE FROM "measurement_name" WHERE "tag" = 'value' AND time < '2020-01-01'`
Additionally, auto-refresh is always paused when a particular `Metaquery Template` is selected.
Certain InfluxQL commands, such as DELETE or …

feat: allow to set active database for InfluxQL commands

---

ui/src/logs/components/LogsTable.tsx
ui/src/logs/constants/index.ts
ui/src/logs/reducers/index.ts
ui/src/logs/utils/index.ts
ui/src/logs/utils/table.ts
ui/src/utils/influxql.ts

Closes #3839
Log Viewer shows a tooltip with a precise nanosecond timestamp of a Syslog message.
The visible timestamps were not the same as reported to Syslog. They lose precision during JSON parsing of query results in the browser transport layer. Today's nanosecond timestamps are always bigger to fit into javascript number. 
Log Viewer queries were changed to include also `timestamp % 1000000`, which gets nanoseconds in a particular millisecond. A precise timestamp (nanos) is then computed in the UI code as String(Math.floor(timestamp/1000000)) + String(timestamp % 1000000).padStart(6,0) and better shown to the user in a tooltip.

fix(ui/logs): show timestamp with full nanosecond precision

---

ui/package.json
ui/src/shared/apis/index.ts
ui/src/utils/ajax.ts
ui/yarn.lock

This PR upgrades Axios library to 0.21.1 in order to fix https://nvd.nist.gov/vuln/detail/CVE-2020-28168 .

fix(ui): upgrade axios to fix CVE-2020-28168

---

ui/src/data_explorer/components/SendToDashboardOverlay.tsx

Closes #5351
`Send to Dashboard` button now requires the `InfluxQL` query to be non-empty. It does not require any fields to be explicitly specified in the query anymore. If `Send to Dashboard` cannot succeed, a message with a `Back` button is displayed.
`Send to Dashboard` button in a modal popup was always disabled when no query fields were detected, it won't let the user succeed without any visible reason. For example, queries such as `SHOW DATABASES` or `SELECT * FROM ...` do not describe any specific field, but they are still valid and properly visualized. The original restriction to require specific fields comes from the early days, where such a restriction might make sense. Today's implementation simply requires a …

fix(ui/explore): repair Send to Dashboard functionality

---

CHANGELOG.md
ui/src/dashboards/components/SourceSelector.tsx
ui/src/shared/components/QuestionMarkTooltip.tsx
ui/src/style/components/react-tooltips.scss

Closes #5670
1. Allow to mouse over question tooltips.
2. Make tooltip content clickable.
3. Add a link to docs when 1.8 flux is not enabled

feat(ui): add documentation link when 1.8 flux is not installed

---

CHANGELOG.md
ui/src/worker/jobs/timeSeriesToDygraph.ts
ui/src/worker/worker.ts

Closes #5666
1. worker error messages are logged in a way so that reported errors could be better reproduced next time
1. influxQL meta query results cannot be parsed to a line-chart data (as a fact), do not log this as an error and let the UI signalize it in a standard way, which is:

fix(ui): do not log failure during line visualization of meta query results

---

CHANGELOG.md
ui/src/kapacitor/apis/index.js
ui/src/kapacitor/containers/TickscriptPage.tsx

Closes #5657
* log stream is programmatically aborted when the Tickscript page is being destroyed
* abort errors are not logged in the Tickscript page, they are expected to happen as a part of normal workflow

fix(ui/kapacitor): dispose log stream when Tickscript editor page is closed

---

CHANGELOG.md
ui/src/flux/helpers/recordProperty.ts
ui/src/shared/apis/flux/metaQueries.ts
ui/src/shared/utils/TimeMachineContainer.ts
ui/test/flux/helpers/recordProperty.test.ts

Closes #5262
Generates property expression is `r.key` only if key contains only `A-Za-z0-9_` characters, otherwise it is `r.["key"]`

fix(ui): generate correct flux property expressions

---

CHANGELOG.md
ui/src/logs/components/LogsFilterBar.tsx
ui/src/logs/components/OptionsOverlay.tsx
ui/src/logs/containers/LogsPage.tsx
ui/src/style/pages/logs-viewer.scss

Closes #5355
* URL query parameter `table` hides histogram in the Logs page, for example:`http://localhost:8080/logs?table`
* Allow to hide histogram in its top-right area (eye-closed button): 
* Allow to show histogram from the top-right area of logs table (bar-chart button):

feat(ui): Allow to show/hide histogram in Log Viewer

---

CHANGELOG.md
ui/src/localStorage.ts
ui/src/logs/actions/index.ts
ui/src/logs/containers/LogsPage.tsx

Closes #5544
* list of namespaces (database + retention policy pair) is fetched whever Log Viewer page is opened
* it is also verified that the current namespace exists, the default namespace is selected otherwise
* allow clearing local storage with `?clearLocalStorage` query, such as `http://localhost:8080/logs?clearLocalStorage
* list of databases was not refreshed from the server, local storage was used
* fetch the list on open of Log Viewer

fix(ui): repair stale database list in Log Viewer

---

CHANGELOG.md
ui/src/data_explorer/constants/index.ts

Closes #5661
This PR adds the following Metaquery Templates to Explorer UI:
* https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-field-keys
* https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-subscriptions
* https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-shards
* https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-shard-groups
* https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-queries
* https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-grants
* https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#explain
* https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#explain-analyze

feat(ui/explore): add more meta query templates

---

CHANGELOG.md
ui/src/data_explorer/components/FieldListItem.tsx
ui/src/shared/components/FieldList.tsx
ui/src/shared/components/MeasurementList.tsx
ui/src/shared/components/QueryBuilderFilter.tsx
ui/src/shared/reducers/helpers/fields.js
ui/test/shared/components/MeasurementList.test.tsx

Closes #5528
A new Filter was added to the Fields column of InfluxQL query builder:
If no field is aggregated the filter UI appears in the Fields column header, otherwise it appears at the bottom of the Fields column:
All selected fields are always displayed (independently on the filter value), the filter is case insensitive and matches any character sequence in a field name:

feat(ui): allow to filter fields in query builder

---

CHANGELOG.md
oauth2/github.go
server/server.go

Closes #5483
This PR allows configuring `github` base URL using `GH_URL` environment variable or `--github-url` flag for chronograf cli. Users can then setup OAuth with github enterprise servers that have different URL (for example `https://github.domain.io`)
OAuth integrations with github always use `https://github.com` base URL.
Users can specify custom github URL.

feat(oauth/github): allow to specify URL for github enterprise

---

CHANGELOG.md
ui/src/shared/apis/metaQuery.js

Closes #5715
When no tag keys are available for a measurement, an empty dataset is quickly returned without executing a failing query
`SHOW TAG VALUES FROM "autogen"."whatever" WITH KEY IN ()`

fix(ui): do not fetch tag values when no measurement tags are available

---

CHANGELOG.md
server/users.go
server/users_test.go
ui/src/admin/components/chronograf/AllUsersTableRow.tsx
ui/src/admin/components/chronograf/UsersTableRow.tsx

Closes #5720 
Chronograf user roles might reference an organization that was already deleted. The UI then fails to render `All Users` page of chronograf administration UI. This PR ensures that roles that reference an unknown organization (already deleted) are simply ignored in UI.
Additionally, a user update removes all existing user roles that reference an unknown organization.

fix(ui): filter out roles with unknown organization reference

---

CHANGELOG.md
server/builders.go
server/flux.go
ui/src/shared/apis/flux/query.ts

Closes #5723
* the server's flux proxy accepts an actual version of the InfluxDB source that client knows from the `sources` response that always re-fetches server versions
* a server passed on CLI has an `unknown` version to explicitly inform that we don't know the version, the actual version is detected during runtime (if the InfluxDB is running), 
The UI detects flux support from its server's `sources` response, it uses the persisted servers and updates their versions using live "pings" to know they actual versions. The flux proxy uses only the persisted version (the version from the last create/update) to know whether flux is supported.
The actual source version is passed to Flux proxy, so it …

fix(server): detect actual flux support in flux proxy

---

CHANGELOG.md
ui/src/admin/actions/influxdb.js
ui/src/admin/components/QueriesTable.js
ui/src/admin/constants/index.js
ui/src/admin/containers/QueriesPage.js
ui/src/admin/reducers/influxdb.js
ui/src/style/pages/admin.scss
ui/src/utils/influxDuration.ts
ui/test/admin/reducers/influxdb.test.js
ui/test/utils/influxDuration.test.ts

Closes #5668
1. The queries are by default sorted by time *descending*, so that the one with the longest exec time always appears on top
1. The table with queries can be sorted by *time* (by default descending) or *database* (ascending by default)
1. The page has a new header, like the other InfluxDB administration pages. It shows the count of databases (to fill in an empty space).
1. The user can control the refresh interval of the queries page, the same way as it is in the Data Explorer.

feat(ui/admin/queries): Improve InfluxDB Admin | Queries page

---

CHANGELOG.md
server/builders.go
server/server.go

Closes #5725
This PR allows to setup InfluxDB v2 connection from chronograf command line, with the help of the following CLI options:
InfluxDBOrg      string `long:"influxdb-org" description:"Organization for your InfluxDB v2 instance" env:"INFLUXDB_ORG"`
InfluxDBToken    string `long:"influxdb-token" description:"Token for your InfluxDB v2 instance" env:"INFLUXDB_TOKEN"`

feat(server): allow to setup influxdb v2 connection on CLI

---

CHANGELOG.md
chronograf.go
server/env.go
server/env_test.go
server/server.go
ui/src/dashboards/containers/DashboardPage.tsx
ui/src/index.tsx
ui/src/shared/apis/env.ts
ui/src/shared/components/dropdown_auto_refresh/AutoRefreshDropdown.tsx
ui/src/shared/components/dropdown_auto_refresh/autoRefreshOptions.ts
ui/test/shared/components/dropdown_auto_refresh/autoRefreshOptions.test.ts

Closes #5734
Chronograf can be started with custom auto-refresh intervals, which are merged into the default auto-refresh intervals (in a time-sorted order)
```
CustomAutoRefresh string `long:"custom-auto-refresh" description:"Adds custom auto refresh options using semicolon separated list of label=milliseconds pairs" env:"CUSTOM_AUTO_REFRESH"`
```
Examples`:
```bash
export CUSTOM_AUTO_REFRESH="500ms=500;1s=1000"
./chronograf 
``` 
```bash
export CUSTOM_AUTO_REFRESH="500ms=500;1s=1000"
./chronograf --custom-auto-refresh "500ms=500;1s=1000"
``` 
both extends auto-refresh interval options in Dashboards and Data Explorer:

feat: allow to add custom auto refresh intervals

---

CHANGELOG.md
go.mod
go.sum
kapacitor.go
kapacitor/alerts_test.go
server/swagger.json
ui/src/kapacitor/components/AlertTabs.tsx
ui/src/kapacitor/components/HandlerOptions.js
ui/src/kapacitor/components/config/BigPandaConfig.tsx
ui/src/kapacitor/components/config/ServiceNowConfig.tsx
ui/src/kapacitor/components/config/index.js
ui/src/kapacitor/components/handlers/BigPandaHandler.js
ui/src/kapacitor/components/handlers/index.js
ui/src/kapacitor/constants/index.ts
ui/src/shared/parsing/parseHandlersFromConfig.js
ui/src/types/kapacitor.ts

Closes #5674
This PR adds 
__BigPanda Configuration UI__
__BigPanda Alert configuration UI__
It also:
* provides serialization/parsing of BigPanda alert properties from/to TICKScript (server side)
* updates swagger

feat: add BigPanda UI

---

CHANGELOG.md
ui/src/data_explorer/components/SendToDashboardOverlay.tsx
ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/shared/components/TimeMachine/TimeMachine.tsx

Closes #5703
1. Use query from an active tab OOTB
2. Let the user choose whether to send the active query, or all queries
* only the query from the first query tab was used, without letting the user know
* it was not clear what is exactly being sent to a dashboard
* active tab query is used, it is a default option
* the user can choose whether to send only an active query or all queries

feat(ui): allow to send multiple queries to dashboard

---

CHANGELOG.md
server/influx.go
server/mux.go
ui/src/data_explorer/actions/view/write.ts
ui/src/data_explorer/apis/index.ts
ui/src/data_explorer/components/WriteDataForm.tsx
ui/src/data_explorer/components/WriteDataHeader.tsx
ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/shared/components/DatabaseDropdown.tsx

Closes #5745
This PR changes the Explorer's Write Data Form to use InfluxDB v2 write API when the Explorer's Flux tab is selected. Users can still write to a database (using V1 write API) with InfluxQL tab selected. 
As a consequence, this PR also allows to write data to InfluxDB v2 without the need to do V1 DBRP mappings.

feat(ui/explorer): use v2 write API with buckets when Flux tab is selected 

---

.circleci/config.yml
CHANGELOG.md
CONTRIBUTING.md
README.md
etc/Dockerfile_build
etc/build.py
go.mod

This PR upgrades golang to 1.16, changes the build image to use golang 1.16 and produce also darwin-arm64 builds.

chore: upgrade golang to 1.16, add macOS arm64 build

---

.circleci/config.yml
CHANGELOG.md
etc/Dockerfile_build
etc/build.py
etc/scripts/docker/run.sh

Closes #5755 
Upgrade build.py to use python3 at chronograf build time.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
To avoid differences in the builds between circle-ci and non circle ci environments, usage of python3 seems to be a good step to achieve deterministic builds across environments.
- [-] Tests pass
- [-] swagger.json updated (if modified Go structs or …

chore(python3): Upgrade builder to python3 to avoid python2 lts

---

CHANGELOG.md
filestore/dashboards.go
filestore/dashboards_test.go
filestore/filestore.go
filestore/templates_test.go

Closes #5756 #5477
* Add ability to load dashboard of an exported data format
* Load dashboard file as a text template (it was wrongly html, fixes #5477)
* Exported dashboard is not properly loaded as a resource on chronograf startup (#5756)
* Dashboard is not properly loaded as a resource on chronograf startup (#5477)
* Support also data format of an exported dashboard. (#5756)
* Load dashboard file as a text template (#5477)

fix(server): load exported dashboard as a resource

---

CHANGELOG.md
server/dashboards.go
server/dashboards_test.go
server/templates.go
ui/src/tempVars/components/TemplateVariableEditor.tsx

Closes #5757
* server side validates that template variable names are unique within a dashboard  
* `Create` or `Update` update button is disabled if a different variable of the same name already exists

fix: enforce unique dashboard variable names

---

CHANGELOG.md
ui/src/dashboards/utils/cellGetters.ts

Closes #5766
If an explorer's page `query` URL parameter can't be parsed to a query config (i.e. something that can be manipulated with additional UI controls), the original (from URL parameter) query is kept as-is. It now works fine the same way as if the query is hand-edited in the UI.

fix(ui): keep original influxQL query if it can't be converted to queryConfig

---

CHANGELOG.md
ui/src/flux/components/FluxScriptEditor.tsx
ui/src/index.tsx
ui/src/kapacitor/actions/view/index.js
ui/src/kapacitor/apis/index.js
ui/src/kapacitor/components/FluxTasksTable.tsx
ui/src/kapacitor/components/KapacitorRules.tsx
ui/src/kapacitor/components/LogItemFluxTask.tsx
ui/src/kapacitor/components/LogsTableRow.tsx
ui/src/kapacitor/constants/tableSizing.ts
ui/src/kapacitor/containers/FluxTaskPage.tsx
ui/src/kapacitor/containers/KapacitorRulesPage.tsx
ui/src/kapacitor/containers/TickscriptPage.tsx
ui/src/kapacitor/index.js
ui/src/kapacitor/reducers/fluxTasks.js
ui/src/kapacitor/reducers/index.js
ui/src/shared/copy/notifications.ts
ui/src/style/chronograf.scss
ui/src/style/components/code-mirror/_time-machine.scss
ui/src/style/pages/fluxtask-detail.scss
ui/src/types/kapacitor.ts
ui/test/kapacitor/components/KapacitorRules.test.tsx
ui/test/kapacitor/reducers/fluxTasks.test.js

Closes #5663
Add Flux Tasks UI (when enabled in kapacitor config and generally supported (1.6+))
- list flux tasks + delete a flux task, change task status
- show task details with highlighted flux script + copy to clipboard, change task status
- show task logs with friendly task run names (appear after timestamp in a log row)

feat(ui): Flux tasks

---

CHANGELOG.md
ui/src/kapacitor/components/HandlerOptions.js
ui/src/kapacitor/components/KapacitorRule.tsx
ui/src/kapacitor/components/RuleHandlers.tsx
ui/src/kapacitor/components/handlers/AlertaHandler.js
ui/src/kapacitor/components/handlers/BigPandaHandler.js
ui/src/kapacitor/components/handlers/EmailHandler.js
ui/src/kapacitor/components/handlers/HandlerActions.tsx
ui/src/kapacitor/components/handlers/KafkaHandler.tsx
ui/src/kapacitor/components/handlers/OpsgenieHandler.js
ui/src/kapacitor/components/handlers/Pagerduty2Handler.tsx
ui/src/kapacitor/components/handlers/PagerdutyHandler.js
ui/src/kapacitor/components/handlers/PushoverHandler.js
ui/src/kapacitor/components/handlers/SensuHandler.js
ui/src/kapacitor/components/handlers/ServiceNowHandler.js
ui/src/kapacitor/components/handlers/SlackHandler.js
ui/src/kapacitor/components/handlers/TalkHandler.js
ui/src/kapacitor/components/handlers/TeamsHandler.js
ui/src/kapacitor/components/handlers/TelegramHandler.js
ui/src/kapacitor/components/handlers/VictoropsHandler.js
ui/src/kapacitor/components/handlers/ZenossHandler.js

Closes #2620 #5768
`Send Test Event` button added to every alert handler section that supports it:
It performs the same job as the kapacitor configuration's `Send Test Event` handler, but the visible additional UI options are also used in the notification. The naming inconsistencies in kapacitor (tickscript, config and testing properties of the same semantics have slightly different names) are also solved in this PR.

feat(ui): Allow to test Alert handlers

---

CHANGELOG.md
ui/src/kapacitor/components/TickscriptEditorControls.tsx
ui/src/shared/components/MultiSelectDBDropdown.js
ui/src/shared/components/MultiSelectDropdown.js
ui/src/style/theme/_dropdowns.scss

Closes #5773
TICKScript's "Select Databases" dropdown menu is aligned to the right side of the dropdown and expands to the left so that even long database names are visible.

fix(ui/tickscript): make db names visible

---

CHANGELOG.md
Dockerfile

Closes #5762
chronograf default options are specified using environment variables.
Users that specify custom command-line options cannot know that they have to add the default options from a Docker file, so they don't and are then surprised to lose the defaults.
The defaults are specified in environment variables.

fix(docker): use environment variables to specify default chronograf arguments

---

CHANGELOG.md
ui/src/shared/components/SingleStat.tsx

Closes #5782 
Set `svg` element as a `Flex` item.
The Safari didn't render `SingleStat` cell - https://www.google.com/search?rls=en&q=svg+text+safari+flex.
Set `style: block` to `svg` elemenent.

fix: displaying SingleStat in Safari

---

.circleci/config.yml
CHANGELOG.md
etc/build.py
etc/scripts/docker/run.sh

Fixes #5790 
Follow-on for influxdata/influxdb#21749

fix(build): rename arm rpms with yum-compatible names

---

CHANGELOG.md
kapacitor/client.go

Closes #5403
A task name is taken from a `name` variable when defined.

feat(kapacitor): name tickscript after a name variable when defined

---

CHANGELOG.md
go.mod
go.sum

This PR upgrades `bluemonday` library in order to fix a security issue that is better described in https://github.com/influxdata/chronograf/security/dependabot/go.mod/github.com%2Fmicrocosm-cc%2Fbluemonday/closed

fix(security): upgrade bluemonday to resolve CVE-2021-29272

---

CHANGELOG.md
LICENSE_OF_DEPENDENCIES.md
go.mod
go.sum
influx/authorization.go
influx/influx_test.go
oauth2/cookies_test.go
oauth2/generic.go
oauth2/jwt.go
oauth2/oauth2.go
oauth2/oauth2_test.go

This PR replaces `github.com/dgrijalva/jwt-go` with `github.com/golang-jwt/jwt/v4` in order to fix a security issue that is better described in https://github.com/influxdata/chronograf/security/dependabot/go.mod/github.com%2Fdgrijalva%2Fjwt-go/closed

fix(security): upgrade jwt  to resolve CVE-2020-26160

---

CHANGELOG.md
ui/src/data_explorer/containers/DataExplorer.tsx

Closes #5795
This PR contains makes sure that the browser history is not extended without a change in influxQL/flux query.

fix(ui): avoid useless browser history change in explorer

---

CHANGELOG.md
ui/src/kapacitor/apis/index.js

This PR fixes retrieval of all flux tasks.
The pagination `after` parameter was lost in the communication with the kapacitor proxy. At most 500 tasks are then returned by the proxy.
The proxy `path` parameter is URI encoded, so that it is properly read by kapactior proxy

fix(kapacitor): repair paginated retrieval of flux tasks

---

CHANGELOG.md
chronograf.go
kapacitor/client.go
server/swagger.json
ui/src/kapacitor/actions/view/index.js
ui/src/kapacitor/components/Tickscript.tsx
ui/src/kapacitor/components/TickscriptEditor.tsx
ui/src/kapacitor/components/TickscriptEditorConsole.tsx
ui/src/kapacitor/components/TickscriptEditorControls.tsx
ui/src/kapacitor/components/TickscriptHeader.tsx
ui/src/kapacitor/components/TickscriptSave.tsx
ui/src/kapacitor/containers/KapacitorRulePage.tsx
ui/src/kapacitor/containers/TickscriptPage.tsx
ui/src/style/pages/tickscript-editor.scss
ui/src/types/kapacitor.ts

Closes #5547
A task that is created from a template becomes read-only in chronograf, because it can't be changed by chronograf in kapacitor.
- there is no option to Save the script
- there are no controls that allow to change db or task type
- editor is read-only
- editor console clearly indicates that the task was created from a template
- task variables (when defined) are printed in editor console (applies to any tickscript)
When listing the tasks, kapacitor unfortunately does not inform whether the task was created from a template or not.  Even a templated task must be then tried to be parsed as an alert rule until kapacitor is enhanced (or a version of kapacitor without the enhancement is used). If a templated task is recognixed as an alert rule (should be a rare/edge case), it also …

fix(kapacitor): make templated kapacitor task read-only

---

CHANGELOG.md
ui/src/kapacitor/components/TasksTable.tsx

This PR visually distinguishes tasks that were created from a template in a chronograf task list. 
__Before this PR__
and before influxdata/kapacitor#2621 is merged:
1. A template task is processed on the chronograf server-side to check if it is a rule. It is never in fact.
1. If a template task is recognized as a chronograf rule, it falsely appears under Alert Rules section.
2. A template task correctly appears in a TICKScripts section. It is however not distinguished from regular tasks that are editable, a template task is not.
__After this PR__
and  after influxdata/kapacitor#2621 is merged:
1. A template task is never processed on the chronograf server-side to check if it is a rule. It cannot appear in Alert Rules section.
2. Tickscript of a template task is visually recognized. It is …

feat(tasks): distinguish template tasks in task list

---

yarn.lock

This PR upgrades  `caniuse-lite`, UI build process warns about an outdated version:
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
```

chore: upgrade caniuse-lite

---

CHANGELOG.md
ui/src/flux/helpers/templates.ts
ui/src/shared/components/time_series/TimeSeries.tsx
ui/test/flux/helpers/templates.test.ts

Closes #5814
When zooming a cell, a cell's flux query is rerun with zoomed time interval parameters, the same way as the InfluxQL query already does.
The time interval of a zoomed area was not applied to a flux query, zoom functionality thus only zoomed data for computed for the whole time range.
A zoomed action re-fetches the data with zoom time range.

fix(ui): update time range in flux queries on dashboard zoom

---

CHANGELOG.md
ui/src/store/configureStore.js

Closes #5742
Inactive window/tab is forced to reload whenever the user logs out or changes the organization. This is done with the help of `window.localStorage` that holds current organization, browser tabs and windows are subscribed to organization changes.
User's data including the current organization are part of the session between the chronograf UI and chronograf server. This session is shared between browser tabs/windows. Whenever the user change the organization, logs-in, log-out, the session changes but the other windows/tabs are not informed. At the end, it results in phantom data beeing shown in the inactive windows and random errors.
A change of an active organization, as well as user …

fix(ui): enforce one organization between browser tabs

---

CHANGELOG.md
ui/src/shared/parsing/flux/durations.ts
ui/test/shared/parsing/flux/durations.ts

Closes #5810
Repair calculation of time window (duration) from a flux script so that it counts with `v.timeRangeStart` and `v.timeRangeStop` member expressions.
`v.windowPeriod` was not computed and failed to a default (3ms). The root cause is that `range(start: v.timeRangeStart)` contains a member expression `v.timeRangeStart` that is not supported.
Simple member expressions are now recognized when calculating the time window of the query.

fix(ui): repair calculation of flux query minDuration

---

CHANGELOG.md
Makefile
etc/Dockerfile_build
go.mod

This PR upgrades golang to 1.17.1

chore: upgrade golang to 1.17.1

---

CHANGELOG.md
ui/package.json
ui/src/worker/Database.ts
ui/src/worker/JobManager.ts
ui/src/worker/utils/index.ts
yarn.lock

Closes #5817
The code detects whether IndexedDB is available. If it is not, the payload data between workers and the UI are posted in messages. There was probably a good reason for using IndexedDB to exchange messages, it can save memory and avoid OOM when workers/UI are under pressure. IndexedDB is thus still a default choice to avoid regression issues on all currently working browsers.
IndexDB cannot be opened when in private mode (Firefox), the UI application fails on it. I may be eventually supported once https://bugzilla.mozilla.org/show_bug.cgi?id=1639542 is implemented.
Fallback to a standard message exchange when IndexedDB is not available.

feat(ui): support Firefox in private mode

---

CHANGELOG.md
ui/src/worker/jobs/fluxTablesToDygraph.ts
ui/test/shared/parsing/flux/constants.ts
ui/test/shared/parsing/flux/dygraph.test.ts

Closes #5820
When a FLUX CSV response contains no value, the associated dygraph transformation returns `null` value for that time. This can happen when with `window`-ed data that can create empty values.
`0` is returned when no _value is defined. UI renders a wrong zero value in such places.
`null` value is returned when _value is not defined, it behaves the same way as InfluxQL result transformation.

fix(ui/flux): skip missing values in line chart instead of returning zeros

---

CHANGELOG.md
ui/src/store/configureStore.js

Closes #5826
The detection of multiple tabs with different chronograf organizations in 1.9.1 was wrong, it is fixed herein.

fix(ui): repair multiple tabs organization sync

---

CHANGELOG.md
ui/src/admin/containers/QueriesPage.js

Closes #5827
This PR adds `CSV download` button to `InfluxDB Admin`/`Queries` page. 
- the download button is always enabled, it is consistent with the Explorer CSV download functionality
- user-visible data is always downloaded with the same ordering that appears on the page
- downloaded filename looks like `2021-11-01-18-25-55 Chronograf Queries.csv`
The file content looks like this:
```csv
database,query,duration
"my-bucket","SHOW QUERIES",387µs
"mydb","SHOW QUERIES",41µs
"telegraf","SHOW QUERIES",40µs
"_internal","SHOW QUERIES",33µs
"chronograf","SHOW QUERIES",20µs
"taskrun","SHOW QUERIES",17µs
```

feat(ui): add download button on query management page

---

CHANGELOG.md
kapacitor/client.go
ui/src/kapacitor/components/Tickscript.tsx
ui/src/kapacitor/components/TickscriptEditorControls.tsx
ui/src/kapacitor/components/TickscriptID.tsx
ui/src/kapacitor/components/TickscriptNameEditor.tsx
ui/src/kapacitor/containers/TickscriptPage.tsx
ui/src/kapacitor/utils/changeTaskName.ts
ui/src/style/pages/tickscript-editor.scss
ui/test/kapacitor/utils/changeTaskName.test.ts

This PR allows the user to rename TICKscript. TICKScript name is newly editable the same way as a dashboard name is.
Chronograf server already extracts the TICKscript name from the `name` variable within the script itself (alerts already behave this way). If no `name` variable is present, tickscript's ID is used. This PR internally inserts or modifies the `name` variable in the script upon a name change. The TICKScript thus must be saved to persist the change, the user is already warned about unsaved changes when exiting without saving, which is already consistent with all other types of changes on the page (editor, type, rd-rp).
Requested by https://github.com/influxdata/feature-requests/issues/178

feat: allow to rename TICKscript

---

CHANGELOG.md
cmd/chronoctl/token.go
flux/client.go
influx/influx.go
kapacitor/client.go
server/server.go
util/http.go

This PR changes the configuration of HTTP clients to use a default client configuration that honors HTTP proxy settings from the [environment](https://pkg.go.dev/net/http#ProxyFromEnvironment). All places that missed such configuration were repaired
- chronoctl tool's token command
- server's OAuth client
- kapacitor client
- flux client
Additionality, the campground is cleaner herein so that it avoids circular dependencies and `staticcheck` errors.

fix(server): use proxy from environment in HTTP clients

---

server/sources.go

This PR adds remote IP to logs when ping fails.

fix: log remote URL when ping fails

---

CHANGELOG.md
ui/src/worker/JobManager.ts
ui/src/worker/utils/index.ts

Closes #5844 
#5818 introduces a fix that changes the communication between the browser's main thread and background workers, it accidentally caused this defect. 'Key not found in database' error appears in browser's console and some random dashboard cells are not showing the data.
The result of an asynchronous computation between a worker and the main browser thread is passed in these steps
1. generate a unique response ID
2. asynchronously write (a possibly huge) response to the browser's indexedDB under the generated ID
3. asynchronously let the main thread know that the requested computation is finished and the result can be retrieved using the ID
4. browser main thread fetches the response by ID and updates UI components
The issue is that the code did not wait …

fix(ui): repair retrieval of worker responses

---

CHANGELOG.md
server/mux.go

Absolute path to swagger.json in the served docs route did not respect BASE_PATH from config.
Changed to relative path to resolve.

fix(server): respect BASE_PATH when serving API docs

---

ui/package.json
yarn.lock

Closes #5855
JSDOM could be possibly used in tests, but is not. Passing tests acknowledge removal.

chore(ui): remove jsdom

---

CHANGELOG.md
ui/src/flux/components/DatabaseList.tsx
ui/src/flux/components/DatabaseListItem.tsx
ui/src/flux/components/FetchFields.tsx
ui/src/flux/components/FetchMeasurements.tsx
ui/src/flux/components/FetchTagKeys.tsx
ui/src/flux/components/FieldList.tsx
ui/src/flux/components/MeasurementList.tsx
ui/src/flux/components/SchemaExplorer.tsx
ui/src/flux/components/SchemaExplorerTree.tsx
ui/src/flux/components/SchemaItemCategories.tsx
ui/src/flux/components/SchemaItemCategory.tsx
ui/src/flux/components/TagKeyList.tsx
ui/src/flux/components/TagKeyListItem.tsx
ui/src/flux/components/TagValueList.tsx
ui/src/flux/helpers/rangeArguments.ts
ui/src/flux/helpers/recordProperty.ts
ui/src/shared/apis/flux/metaQueries.ts
ui/src/shared/components/TimeMachine/FluxQueryMaker.tsx
ui/src/shared/components/TimeMachine/fluxQueryBuilder/apis/fluxQueries.ts
ui/src/shared/components/TimeMachine/fluxQueryBuilder/util/generateFlux.ts
ui/src/shared/components/TimeRangeDropdown.js
ui/src/shared/components/TimeRangeLabel.tsx
ui/test/flux/helpers/rangeAguments.test.ts
ui/test/shared/components/TimeMachine/fluxQueryBuilder/util/generateFlux.test.ts

Closes #5849
Flux Schema Explorer shows data in the user-selected time range and also reacts upon change of the time range. Schema tree shows that its data are controlled by a selected time range, 
Additionally
-  a deprecated [flux v1](https://docs.influxdata.com/flux/v0.x/stdlib/influxdata/influxdb/v1/) package is not used, functions from flux universe are used instead. 
- schema metadata fetcher is refactored and simplified
The explorer always used -30d as a time range to show schema data. It caused high latencies or timeouts in the schema queries over huge data sets. 
The user can choose the time range for showing the Schema Explorer data and thus reduce the time required for schema queries.

feat(ui): use time range in flux Schema Explorer 

---

CHANGELOG.md
ui/src/index.tsx
ui/src/kapacitor/actions/view/index.js
ui/src/kapacitor/apis/fluxTasks.ts
ui/src/kapacitor/apis/index.js
ui/src/kapacitor/components/KapacitorRules.tsx
ui/src/kapacitor/containers/FluxTaskPage.tsx
ui/src/kapacitor/containers/FluxTasksPage.tsx
ui/src/kapacitor/containers/KapacitorRulesPage.tsx
ui/src/kapacitor/containers/KapacitorScopedPage.tsx
ui/src/kapacitor/index.js
ui/src/kapacitor/utils/activeKapacitorFromSources.ts
ui/src/kapacitor/utils/errorMessage.ts
ui/src/side_nav/components/NavItems.tsx
ui/src/side_nav/containers/SideNav.tsx
ui/src/sources/components/KapacitorStep.tsx
ui/src/utils/ajax.ts
ui/src/utils/useDebounce.ts
ui/test/kapacitor/utils/ActiveKapacitorFromSources.ts

This PR separates/moves kapacitor's flux task list from the alerts page to a separate page, it is a required pre-requisite to #5460.
- `Flux Tasks` is a new menu item in the side bar:
- The page contains a table of Flux Tasks that was before on the Alert Rules page
- The Page let the user also filter Flux tasks by name and perform a manual Refresh
- Flux tasks are available since Kapacitor 1.6 and must be enabled in its config, the UI
- Exiting a page of a particular Flux Task editor returns the user to the Flux Tasks page (was Alert Rules)
Additionally, the sidebar was fixed so that `Alerting` is highlighted when flux tasks, kapactior alert tule or TICKScript pages are shown.

feat(ui): separate flux tasks list from alerts

---

CHANGELOG.md
kapacitor/client.go
kapacitor/kapa_client.go
kapacitor/kapa_client_test.go
server/kapacitors.go
server/swagger.json

This PR enhances API that returns Alert Rules so that the UI can better and quickly respond. This PR is a part of a solution to #5460, the API now supports
- `limit` query parameter that can limit the result size and thus reduce the time that is spent during analysis of TICKscripts
- `pattern` query parameter that can filter alert rules to have a specific string value in alert rule names
- `parse` query parameter can turn off TICKScript parsing when set to `0` so that just TICKScipts can be returned much quicker
Tests were enhanced and swagger updated.

feat(server): optimize Alert Rules API

---

CHANGELOG.md
ui/package.json
ui/src/shared/components/Dygraph.tsx
yarn.lock

This PR upgrades react-resize-detector to the latest version.

chore(ui): upgrade react-resize-detector

---

CHANGELOG.md
ui/src/shared/components/DropdownMenu.tsx
ui/src/shared/components/TimeMachine/fluxQueryBuilder/TagSelector.tsx
ui/src/shared/components/TimeMachine/fluxQueryBuilder/actions/tags.ts
ui/src/shared/components/TimeMachine/fluxQueryBuilder/actions/thunks.ts
ui/src/shared/components/TimeMachine/fluxQueryBuilder/apis/fluxQueries.ts
ui/src/shared/components/TimeMachine/fluxQueryBuilder/apis/queryBuilderFetcher.ts
ui/src/shared/components/TimeMachine/fluxQueryBuilder/reducers/tags.ts
ui/src/shared/components/TimeMachine/fluxQueryBuilder/types/index.ts
ui/test/shared/components/TimeMachine/fluxQueryBuilder/reducers/tags.test.ts

Closes #5853
- the user can load more tag keys if the shown list is truncated
- the user can load more tag values if the shown list is truncated
- all buckets are always shown
The lists are initially limited to 200 values, and their size is incremented by 200 upon user request

feat(fluxWizard): allow to load more keys/values when showing truncated results

---

CHANGELOG.md
ui/src/shared/components/QueryStatus.tsx
ui/src/utils/ajax.ts
ui/src/worker/jobs/get.ts
ui/src/worker/jobs/proxy.ts

This PR enhances reporting of InfluxQL errors.
Parse and propagate InfluxQL (and also other HTTP) error messahes properly to UI
1.9.3 does not explain invalid InfluxQL query:

fix(ui): propagate all InfluxQL error messages to UI

---

CHANGELOG.md
ui/src/kapacitor/components/KapacitorRule.tsx
ui/src/kapacitor/components/Tickscript.tsx
ui/src/kapacitor/components/TickscriptHeader.tsx
ui/src/kapacitor/containers/TickscriptPage.tsx
ui/src/types/kapacitor.ts
ui/test/kapacitor/components/TickscriptHeader.test.tsx

This is PR is built on top of #5871 to contribute to a solution to #5460 .  It adds a new `Alert Rule Builder` button on the TICKscript page for a new TICKscript and all TICKscripts that are compatible with Alert Rule Builder UI.
* it is visually recommended to use Alert Rule Builder for compatible TICKscripts (blue button)
* the same button appears (in default colour) when creating a new TICKscript
* No `Alert Rule Builder` button appears if the TICKscript cannot be edited (not compatible) with the builder UI 
The `Save` action in Alert Builder UI lands in the `TICKscripts` page if the user browsed the TICKscript from the TICKscripts page. The new TICKscripts page thus provides complete management of all types of Alert Rules and the existing `Alert Rules` page (that suffers from …

feat(ui): TICKscript page can open Alert Rule Builder

---

ui/src/shared/components/TimeMachine/fluxQueryBuilder/TagSelector.tsx
ui/src/shared/components/TimeMachine/fluxQueryBuilder/actions/thunks.ts
ui/src/shared/parsing/flux/durations.ts

This PR improves the flux query builder so that
1. `_measurement` and `_field` tag selectors are initially pre-selected
2. search placeholders are improved
before this PR, it was:

fix(ui): prefer field when adding a new tag selector

---

ui/src/shared/parsing/flux/durations.ts
ui/test/shared/parsing/flux/durations.ts

This PR improves detection of the time range to include numbers in the flux [range](https://docs.influxdata.com/flux/v0.x/stdlib/universe/range/) function. `start` and `stop` parameters can be supplied as a number to represent seconds since epoch.
- improve implementation
- add test
An example query:
```
from(bucket: "my-bucket/autogen")
|> range(start: 0)
|> filter(fn: (r) => r["_measurement"] == "measurement000")
```
Silently failed in the browser console with `failed to analyze query` message.

fix(ui): allow to parse flux range parameter as a number

---

CHANGELOG.md
ui/src/flux/components/FluxEditor.tsx
ui/src/shared/components/TimeMachine/FluxQueryMaker.tsx
ui/src/shared/components/TimeMachine/fluxQueryBuilder/FluxQueryBuilder.tsx

The button that switches to Flux editor is herein `Script Editor` (was Query Editor). The buttons that switche to Flux builder are herein `Script Builder` (was `Query Builder`)

fix(ui/flux): rename Query Editor to Script Editor, Query Builder to Script Builder

---

CHANGELOG.md
ui/src/shared/components/TimeMachine/fluxQueryBuilder/FluxQueryBuilder.tsx
ui/src/shared/components/TimeMachine/fluxQueryBuilder/TagSelector.tsx
ui/src/shared/components/TimeRangeDropdown.js
ui/src/shared/components/TimeRangeLabel.tsx
ui/src/style/components/custom-time-range.scss

Closes #5880
- non-empty Tag Selector lists are accompanied with the last entry showing `keys/values depend on time range`, empty lists already contain a message `No tag keys (values) found in the selected time range`
- every text that references the time range visualizes Time Range dropdown on click and has a title showing the actual time range

feat(ui/flux): highlight that Script Builder keys/values depend on the selected time range

---

CHANGELOG.md
cmd/chronograf/main.go
dist/dist.go

Closes #5884
This PR makes sure that `chronograf --version` reports the correct version even if it is not built from a git repository or a CI process, both of them supply the version with extra flags to `go build`. The default chronograf version is now taken from `ui/package.json` that is newly packed into the binary.

fix(server): report correct chronograf version

---

dist/dist_test.go

This PR makes sure that chronograf can read its version from packed bindata.

chore(server): test non-empty dist version

---

CHANGELOG.md
ui/src/admin/containers/QueriesPage.js

Closes influxdata/EAR#3002
'SHOW QUERIES' failure reason(s) are now shown in the UI.
If there is no data to show, `CSV export` button and the Queries table is not displayed, only the errors are.

fix(ui): show failure reason on queries page

---

CHANGELOG.md
ui/src/side_nav/containers/SideNav.tsx
yarn.lock

Closes #5891
`Alert Rules` is herein the first and the default item of the Alertin side menu, as it was in 1.9.3.
Moreover this PR updates `caniuse-lite` that is used during UI build to install required polyfills.

fix(ui): reorder Alerting side menu

---

CHANGELOG.md
ui/src/shared/components/TimeMachine/fluxQueryBuilder/AggregationSelector.tsx

Closes #5889
This PR changes the Flux Script Builder so that the aggregation function is optional.

feat(ui): make aggregation function optional in Flux Query Builder

---

CHANGELOG.md
ui/src/flux/helpers/autoComplete.ts
ui/src/style/components/code-mirror/_time-machine.scss

This PR enhances the Flux editor to show suggestions of the built-in `v` object properties:
The color of all object references (including 'v') also changed, is not red anymore.

feat(ui/flux): autocomplete builtin 'v' object in Flux editor

---

ui/cypress/integration/queryBuilder.test.ts

This PR 
- removes unnecessary parts of the queryBuilder test set

fix: aggregate function no error pop up

---

.github/workflows/chronograf-cypress-tests.yaml

This PR fixes github action to use node 16, i.e. the same version that is already used during CI build. Upgrade to node 16 was  already done in https://github.com/influxdata/chronograf/pull/5875, before github actions were introduced. 
This upgrade is required in order to continue with dependency upgrades for the next version of chronograf. Github actions fail on node 14 with
```
Run make
cd ui && yarn --no-progress --no-emoji
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error @typescript-eslint/eslint-plugin@5.17.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "14.15.0"
error Found incompatible module. …
```

fix(ci): upgrade github action to use node 16

---

influx/influx.go

InfluxDB 2.2.0 reports its version as  `v2.2.0`, but some tools expected the version to look like `2.2.0`. Chronograf fortunately handles both version formats properly, the code that makes it happen was commented in this PR to know that also the newest InfluxDB requires extra care in version processing.

chore: strip 'v' prefix from InfluxDB version

---

.github/workflows/chronograf-cypress-tests.yaml

This PR `cron` to trigger github workflow execution, `push to master` is the trigger herein.

chore: replace gh workflow cron by push

---

.github/workflows/chronograf-cypress-tests.yaml
.github/workflows/resources/kind-config.yaml
ui/cypress/local-chronograf-influxdb-enterprise.sh

This PR makes sure that a started InfluxDB enterprise has both meta and data services accessible.
This PR utilizes the newest influxdb-enterprise helm chart to expose meta and data services as node-ports and then map these ports to `kind control plane` so that these services are accessible to tests.  
InfluxDB meta service was not accessible, so it was not possible to use/test chronograf administration of InfluxDB users, permissions, and roles.
1. influxdata/helm-charts#468 allows customizing the way how meta service is exposed
2. install influxdb-enteprise helm chart  with node port k8s services at predefined ports
3. expose node ports to test environment via kind cluster configuration

fix(ci): expose InfluxDB enterprise meta service in tests 

---

CHANGELOG.md
ui/src/admin/components/UserAdminDropdown.tsx
ui/src/admin/components/UserPermissionsDropdown.tsx
ui/src/admin/components/UserRow.tsx
ui/src/admin/components/UsersTable.js
ui/src/types/auth.ts
ui/src/types/influxAdmin.ts

This PR is a part of a solution to #5834. It fixes the way how OSS admin users are assigned, making a user an administrator previously reset all other database-level grants, it does not after this PR. Moreover, the Users UI changed to make clear that an administrator status is managed (it was ALL permission before this PR).
The concept of user controls that let change the administrator status remain the same (as the previous change of permissions). The user has to select/deselect YES checkbox and then clieck `Apply`:

feat(ui): manage InfluxDB OSS admin users

---

CHANGELOG.md
ui/src/dashboards/utils/tableGraph.ts
ui/src/shared/components/TableGraph.tsx
ui/src/shared/parsing/flux/response.ts

Closes #5857
Table visualization always parses string data to detect if they are numbers and display them as numbers even when they were never meant to represent numbers.
1. Flux result parsers were enhanced to produce numbers for columns that are described as numbers (was string before).   InfluxQL results already contain numbers in number columns.
2. Change table visualization to render numbers only when numbers appear.
As a regression, columns that contain number data that were originally written as a string cannot be now visualized as numbers in a table visualization.

fix(ui): repair table visualization to keep string data as-is

---

CHANGELOG.md
ui/src/sources/components/SourceStep.tsx

Closes #5912
TLS server certificate/hostname verification is tuned off during detection of InfluxDB server type, it is just to know whether to show `Meta Service URL` input filed.
`Meta Service URL` was not shown when connecting to InfluxDB Enterprise with chronograf untrusted certificate. 
Turn off server certification verification during InfluxDB type detection in the 'Add Source' wizard, ... and only for the detection.

fix(ui): skip TLS server verification during dry-run

---

ui/src/admin/components/DatabaseManager.js
ui/src/admin/components/RolesTable.js
ui/src/admin/components/UsersTable.js
ui/src/admin/containers/influxdb/AdminInfluxDBScopedPage.tsx
ui/src/admin/containers/influxdb/AdminInfluxDBTab.tsx
ui/src/admin/containers/influxdb/QueriesPage.tsx
ui/src/shared/components/SubSections.tsx
ui/src/style/layout/page-subsections.scss
ui/src/style/pages/admin.scss
ui/src/types/shared.ts

This PR reorganizes InfluxDB administration pages to occupy full page width, so there is more space for longer texts (such as queries) and a table-style role/permission management (as requested by https://github.com/influxdata/chronograf/issues/5834). InfluxDB administration tabs are newly organized at the top of the page.
**BEFORE THIS PR**:
**THIS PR**:

feat(ui): change layout of InfluxDB administration pages to occupy full page width

---

CHANGELOG.md
ui/src/admin/containers/influxdb/RolesPage.tsx
ui/src/admin/containers/influxdb/UsersPage.tsx
ui/src/admin/containers/influxdb/util/computeEffectiveDBPermissions.ts
ui/test/admin/containers/influxdb/util/computeEffectiveDBPermissions.test.ts

This PR ensures that effective user permissions (including permissions from user roles) are shown on the Users Page.
The example above demonstrates effective permissions in action:
- `test1` role grants Write on [_internal,a,b] databases, user `lojza` has only this role and no extra granted permissions
- `test2` role grants Read on [a,b] databases, user `pavel` has only this role and no extra granted permissions
-  effective permissions for user `pepa` are shown, they represent user granted permissions (Write on x3 database) and all permissions granted by assigned roles (test1, test2)
It is a part of the solution to https://github.com/influxdata/chronograf/issues/5834

feat(ui): show effective user permissions on Users page

---

ui/src/admin/containers/influxdb/QueriesPage.tsx

This PR properly aligns header buttons on `Queries` page to the right, it is a side defect of 1.10 new Role/User management.

fix(ui): fix alignment of buttons on Queries page

---

CHANGELOG.md
ui/src/admin/containers/influxdb/AdminInfluxDBScopedPage.tsx
ui/src/admin/containers/influxdb/AdminInfluxDBTabbedPage.tsx

This PR adds a refresh button to InfluxDB pages for users, roles, and databases. It does not add a refresh button to Queries pages, a different reload mechanism is used therein.

feat(ui): add refresh button to InfluxDB Users/Roles/Databases

---

ui/src/admin/components/influxdb/CreateRoleDialog.tsx
ui/src/admin/components/influxdb/CreateUserDialog.tsx
ui/src/admin/containers/influxdb/UserPage.tsx
ui/src/reusable_ui/components/inputs/Input.tsx

This PR disables auto-complete for Create User and Create Role dialogs, so the administrator is not prompted to remember/use entered values.
Additionally, it contains a small fix on UserPage that avoids state changes on an unmouted component.

fix(ui): do not autocomplete create user/role dialogs

---

.circleci/config.yml
.github/workflows/chronograf-cypress-tests.yaml
CHANGELOG.md
etc/Dockerfile_build
etc/scripts/docker/run.sh

Closes #5928 
This PR upgrades golang to 1.18.3

fix(security): upgrade golang to 1.18.3

---

CHANGELOG.md
ui/src/kapacitor/components/RuleGraphDygraph.tsx

Closes #5935
Repairs detection of unsupported values for Dygraph visualization.
The detection treated `false` unsupported value as a supported value
Alert rule builder works only with number values, so it now strictly requires that there is no (`undefined`) unsupported value in the query, in such a case the UI (already) shows:

fix(ui): detect unsupported value properly

---

ui/src/admin/actions/influxdb.js
ui/src/admin/containers/influxdb/AdminInfluxDBScopedPage.tsx

This PR fixes error handling in InfluxDB administration, no UI functionality is available after loading failure of users, roles, databases, or permissions.
Data loading exceptions are caught in the code and shown to the user (that can retry the loading with a refresh icon button):
Errors during data loading were displayed as UI notifications, React rendering then continued with invalid data and errors start to happen on invalid data without a real explanation.

fix(ui/admin): require successful data loading in influxdb admin pages

---

CHANGELOG.md
flux/client.go
flux/client_test.go
influx/influx.go
influx/influx_test.go
server/influx.go
server/influx_test.go
util/path.go
util/path_test.go

Closes #5096 
This PR changes the communication with InfluxDB so that a configured InfluxDB connection URL path is preserved as a context path when calling InfluxDB APIs. It works fine with InfluxDB OSS. InfluxDB Enterprise connections still must be configured without a context path (a proxy path), the cluster design requires doing so.
InfluxDB Connection URL context path was ignored, and paths of InfluxDB APIs were directly used.
API paths are appended to the configured InfluxDB connection path.

feat(server): support InfluxDB behind proxy under subpath

---

ui/cypress/integration/admin_influxdb.test.ts
ui/src/admin/actions/influxdb.js
ui/src/admin/components/influxdb/MultiDBSelector.tsx
ui/src/admin/containers/influxdb/RolePage.tsx
ui/src/admin/containers/influxdb/RolesPage.tsx
ui/src/admin/containers/influxdb/UserPage.tsx
ui/src/admin/containers/influxdb/UsersPage.tsx
ui/src/admin/reducers/influxdb.js
ui/src/localStorage.ts
ui/src/reusable_ui/components/slide_toggle/SlideToggle.tsx
ui/src/types/localStorage.ts
ui/test/admin/reducers/influxdb.test.js

Closes #5942
This PR improves/fixes filters on Admin / InfluxDB Users/Roles page so that:
- the state of `Show Users` / `Show Roles` slide toggles is remembered in the browser local storage (survives browser restart)
- the state of users/roles filter text and selected databases is remembered across InfluxDB admin pages, it is reset every time the admin data is loaded (whenever visiting InfluxDB admin pages from non-admin pages, or after clicking the refresh button)

feat(ui/admin): remember state of influxdb users/roles filters

---

CHANGELOG.md
ui/src/admin/components/chronograf/AllUsersTable.js
ui/src/admin/components/chronograf/OrganizationsTable.js
ui/src/admin/components/chronograf/ProvidersTable.js
ui/src/admin/components/chronograf/UsersTable.js
ui/src/alerts/components/AlertsTable.tsx
ui/src/dashboards/components/GaugeOptions.tsx
ui/src/kapacitor/components/HandlerTabs.tsx
ui/src/logs/components/SeverityOptions.tsx
ui/src/shared/components/DygraphLegend.tsx
ui/src/shared/components/SourceIndicator.tsx
ui/src/shared/components/SubSections.tsx
ui/src/shared/components/Tags.tsx
ui/src/shared/components/TagsAddButton.tsx
ui/src/shared/components/ThresholdsList.tsx
ui/src/shared/components/threesizer/DivisionMenu.tsx
ui/src/tempVars/components/TemplatePreviewList.tsx

Closes #5946
This PR makes sure that stable react keys are used in React lists. See #5946 for details.

fix(ui): use stable component keys

---

ui/src/admin/components/influxdb/CreateRoleDialog.tsx
ui/src/admin/components/influxdb/CreateUserDialog.tsx
ui/src/style/theme/_buttons.scss

Closes #5952
- focused buttons are highlighted so that the user knows that they can be pressed
- User/Role creation dialog reacts upon Enter in input fields to trigger user/role creation
- It was not visible that a button received focus (after a keyboard TAB navigation) so the user didn't know that a button can be pressed (Enter or Space key).
- Enter key did not confirm the dialog.

Allow keyboard-only user/role creation

---

ui/src/admin/containers/influxdb/AdminInfluxDBScopedPage.tsx

Closes #5951 
Detection of unsupported administration was not applied.

fix(ui): show unsupported administration against 2.x InfluxDB

---

ui/src/shared/components/Dropdown.tsx
ui/src/shared/components/DropdownMenu.tsx
ui/src/shared/components/DropdownMenuItem.tsx
ui/src/style/theme/_dropdowns.scss

This PR fixes the dropdown menu so that
- page URL is not changed on item click
- highlighted only opened dropdown
- rely upon CSS `:hover` highlighting unless using Dropdown in auto-complete mode
Especially the latter is an optimization that is required to stabilize Cypress tests. Before this PR, chronograf administration dropdown menus were magically replaced in DOM before with the first highlight in the menu.

fix(ui): optimize dropdown menu to avoid items re-rendering

---

CHANGELOG.md
ui/cypress/integration/admin_influxdb.test.ts
ui/src/admin/actions/influxdb.js
ui/src/admin/components/influxdb/ConfirmDiscardDialog.tsx
ui/src/admin/containers/influxdb/AdminInfluxDBTabbedPage.tsx
ui/src/admin/containers/influxdb/RolePage.tsx
ui/src/admin/containers/influxdb/UserPage.tsx
ui/src/reusable_ui/components/overlays/Overlay.scss
ui/src/shared/components/SubSections.tsx
ui/src/style/pages/admin.scss

Closes #5953
Main administration tabs (Databases, Users, Roles, Queries) are added to User/Role detail page in this PR. Additionally, `Apply Changes` takes the user to the list of user/roles upon success.
When a tab is clicked and there are unsaved changes on the detail page, the user has to confirm that these changes will be discarded.

feat(ui): Add InfluxDB admin tabs to user/role detail page

---

CHANGELOG.md
chronograf.go
influx/annotations.go
influx/annotations_test.go
server/annotations.go
server/annotations_test.go
server/swagger.json
ui/src/shared/components/AnnotationEditorForm.tsx
ui/src/shared/components/AnnotationPoint.tsx
ui/src/shared/components/AnnotationSpan.tsx
ui/src/shared/components/ColorDropdown.tsx
ui/src/shared/constants/thresholds.ts
ui/src/types/annotations.ts

Closes #5605
This PR enhances annotation model, API, and UI so that the user can choose annotation color (which was always white before this PR).

feat(ui): allow to customize annotation color

---

ui/src/admin/components/chronograf/AllUsersTableRow.tsx

Closes #5978
The table row re-renders upon any change of the user structure.
The row did not re-render when user's superAdmin status changed. It was caused by some relict from the past, which excluded superAdmin status from re-rendering. The rows were however completely replaced upon any change in 1.9.4, the buggy code was thus never effective. Cypress tests were hard to do with frequent useless replacements of rows in DOM. #5947 fixed it and ensured that row DOM elements are updated upon changes. As a side-effect, the forgotten wrong behavior of optimized row rendering becomes effective.
Re-rerender row on change of the user, including superAdmin status.

fix(ui): repair rendering of AllUsersTableRow

---

CHANGELOG.md
ui/src/shared/components/MarkdownCell.scss

Closes #5973
Markdown cell content can be selected and copied in this PR.

fix(ui): make markdown cell content selectable

---

CHANGELOG.md
ui/src/shared/components/Dropdown.tsx
ui/src/shared/components/DropdownInput.tsx

Closes #5971
The current dropdown value is shown when the dropdown is opened (with empty search term) in the search input. The input value is selected so that 
- it can be quickly copied to clipboard
- any keystroke in the input will delete the selected value (and possibly starts with typing an actual search term)

feat(ui): select current value in dropdown search input

---

ui/src/admin/components/chronograf/AllUsersTableHeader.tsx
ui/src/admin/components/chronograf/AllUsersTableRow.tsx
ui/src/admin/containers/influxdb/RolesPage.tsx
ui/src/reusable_ui/components/slide_toggle/SlideToggle.tsx
ui/src/reusable_ui/components/wizard/WizardCheckbox.tsx

This PR:
- changes an attribute's name from dataTest to testId to preserve naming consistency

chore(ui): rename dataTest attribute

---

.circleci/config.yml
.github/workflows/chronograf-cypress-tests.yaml
CHANGELOG.md
etc/Dockerfile_build
etc/scripts/docker/run.sh

Closes #5989 
This PR upgrades golang to 1.18.4

chore(build): upgrade golang to 1.18.4

---

Makefile

This PR removes GO111MODULE env settings from Makefile. It is not required anymore, go modules are turned on since go 1.16 (chronograf now uses 1.18).

chore: remove GO111MODULE=on from Makefile

---

CHANGELOG.md
server/mux.go
ui/src/dashboards/utils/createDBRP.ts
ui/src/dashboards/utils/protoboardSuggestion.ts
ui/src/shared/copy/notifications.ts
ui/src/sources/components/DashboardStep.tsx

This PR makes it possible to use pre-defined dashboards when setting up a new InfluxDB v2 connection. When a database is not available in a v2 connection (missing V1 DBRP mapping), the implementation tries to create a v1 DBRP mapping so that the existing InfluxQL dashboards (and dashboard suggestions) work properly. 
When a V2 connection is specified (InfluxDB v2 Auth is selected)
and the user presses `Next`, the implementation then tries to suggest dashboards. Newly in this PR, if it detects that there is no `telegraf` database, it attempts to create a v1 DBRP mapping for a v2 bucket of the same name as the database. If such a bucket exists and the DBRP mapping can be created, it creates a database and notifies a user with a message:
The `suggested dashboards` functionality immediately …

feat: setup DBRP mapping automatically for a v2 connection

---

CHANGELOG.md
ui/src/shared/parsing/flux/parseTablesByTime.ts
ui/test/shared/parsing/flux/dygraph.test.ts
ui/test/shared/parsing/flux/parseTablesByTime.test.ts

This PR simplifies labels of flux-based line charts.
A label value before this PR
```
_value[_start=2022-08-17T06:54:02.67759815Z][_stop=2022-08-17T07:54:02.657Z][_field=numSeries][_measurement=database][database=_internal][hostname=66fec3b3194f]
```
is herein simplified to
```
numSeries measurement=database database=_internal hostname=66fec3b3194f
```
with a help of the following rules
- `_field` value is used in place of `_value` string, it just shows the field that was measured
- `_start`, `_stop` and `_field` groups keys are removed from the label
- `measurement` is used in place of `_measurement`
- + queries that do have no `_value` and `_field` columns are also handled properly

feat(ui): simplify flux labels

---

CHANGELOG.md
server/url_prefixer.go
server/url_prefixer_test.go

Fixes #6000
This PR excludes JS files from preprocessing that is applied when chronograf UI is served under a specific subpath.
Chronograf 1.10 comes with a new build system that produces different JS files comparing to chronograf 1.9 . These JS files do not need any further changes even if chronograf is served under specific  BASEPATH.
Exclude js files from BASEPATH handling.

fix: repair UI served under BASEPATH

---

.circleci/config.yml

This implements remote artifact signing which is more secure than the previous signing method. This no longer requires CircleCI to have a duplicate of the GPG signing key.

chore: use remote package signing

---

CHANGELOG.md
ui/package.json
ui/src/shared/components/TemplateDrawer.tsx
yarn.lock

Closes #6007
Closes #6009
Closes #6011
Closes #6013
Closes #6017
Closes #6031
Closes #6034
Closes #6037
Closes #6038
Closes #6039
Closes #6044
Closes #6048
Closes #6051
Closes #6052
Closes #6053
Closes #6055
I might have missed a few issues describing the same error.
Replace FunctionComponent by Component in the `TemplateDrawer` to restore compatibility with `react-onclickoutside`
Error when typing a colon: `Cannot read properties of undefined (reading 'getInstance')`
Replacing FunctionComponent by Component, setting properties and adding a render function.

fix: avoid error on typing colon

---

CHANGELOG.md
ui/src/hosts/apis/index.ts

Closes #6059
_What was the problem?_ Wrong interval
_What was the solution?_ Interval changed from `10s` to `10m`

Change 10s to 10m in query

---

.circleci/config.yml
.github/workflows/chronograf-cypress-tests.yaml
CHANGELOG.md
etc/Dockerfile_build
etc/scripts/docker/run.sh

Closes https://github.com/influxdata/edge/issues/509

chore(build): upgrade Go to 1.20.10

---

.circleci/config.yml

Remove "--dryrun" from S3 upload.

fix: sign artifacts in subdirectories

---

.circleci/config.yml

This updates `package-sign` and `package-upload-signatures` so that the signatures are uploaded into a flat directory. This resolves the issue where `package-upload-signatures` was attempting to re-create the directory structure underneath `/tmp/workspace/build`.

fix: flatten artifact signatures

---

CHANGELOG.md
server/influx.go
server/influx_test.go

Fixes https://github.com/influxdata/EAR/issues/5278
For InfluxQL metaqueries to work with Cloud Serverless, active database needs to be set (via `db` HTTP query parameter). Current version only supports settings active via `USE` clause.
This PR adds sets active database using value of  `ON` clause if present in the query and no db was set with `USE`.

fix: set active database from query

---

.github/workflows/chronograf-cypress-tests.yaml

This PR updates the `actions/upload-artifact` to version 4. Version 2 is deprecated and has been causing failures in our pipeline, as illustrated below:
[View the failing job](https://github.com/influxdata/chronograf/actions/runs/10838113150/job/30075606637)
For more information, please refer to the [GitHub Changelog](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/).

fix: use new version of actions/upload-artifact

---

.circleci/config.yml
.github/workflows/chronograf-cypress-tests.yaml
etc/Dockerfile_build
etc/scripts/docker/run.sh
go.mod
server/protoboards_test.go

Closes https://github.com/influxdata/edge/issues/739
This PR also updates our Ubuntu image to the same versions used in InfluxDB ([reference](https://github.com/influxdata/influxdb/blob/54d209d0bff44f3ebdc8f3f5bfdd9873268cbb93/.circleci/config.yml#L311)) due to the end of life (EOL) of the current version. For more information, see:
https://app.circleci.com/pipelines/github/influxdata/chronograf/1685/workflows/f67ccad1-abbe-4a3f-8691-a7ea37e2a1df/jobs/20114
https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177

chore(build): upgrade Go to 1.22.7

---

ui/package.json
yarn.lock

This will address https://github.com/influxdata/chronograf/security/dependabot/125 as well as some older alerts that were dismissed as 4.21.1 brings in some refreshed devDependencies.

chore(ui): update to use express 4.21.1

---

CHANGELOG.md
ui/src/shared/components/TimeMachine/fluxQueryBuilder/apis/fluxQueries.ts
ui/test/flux/components/fluxQueries.test.ts

Related to [EAR #5426](https://github.com/influxdata/EAR/issues/5426)
Workaround for query adjustment for InfluxDB 1 didn't count with InfluxDB Enterprise
Check also Enterprise build

fix: version detection

---

CHANGELOG.md

Delete point about upgrade to GO 1.22.11.
No need to report unreleased support for upgrades to older releases of GO
Remove the point about support for GO 1.22.11
- [na] Any changes to `etc/Dockerfile_build` have been pushed to DockerHub, and the changes have been added to `.circleci/config.yml`
- [na ] swagger.json updated (if modified Go structs or API)

docs: remove older unreleased upgrade notice for go

---

CHANGELOG.md
ui/src/shared/apis/query.ts
ui/src/shared/components/time_series/TimeSeries.tsx

Closes #6128
Added a check for missing `queryConfig` in queries originating from the Host page.

fix: Handle missing queryConfig in Host page queries

---

.github/workflows/chronograf-cypress-tests.yaml

Closes #6140
Replace unmaintained `addnab/docker-run-action` with pure `docker run`

fix: replace unmaintained docker-run action (#6140)
