Dockerfile
README.md
circle.yml

• Clean up my mkdir in Dockerfile by using VOLUME
• Update to go 1.7.3
• Push to quay.io with SHA tag on master builds
• Mention the alpha docker image on quay.

Quay docker circle

---

README.md

I thought it would be helpful to include a version section in the README to give people an idea about the status of the project.

Add section about versioning to README

---

server/server.go

Update reporting tag to use chronograf-ng

---

ui/src/shared/components/LayoutRenderer.js

Graphs were running off the screen, which was absolutely maddening to me. Fixed with a higher order component provided by react-grid-layout

Provide width to react grid layout

---

server/exploration.go
server/kapacitors.go
server/layout.go
server/mappings.go
server/mux.go
server/proxy.go
server/server.go
server/service.go
server/sources.go

Connect #588 
Very little information is given when there are problems.
In lieu of adding error messages in the UI, I've added error logging to the server.

Add server error logging

---

circle.yml
etc/build.py
etc/scripts/docker/build.sh
etc/scripts/docker/pull.sh
etc/scripts/docker/run.sh

This adds a deployment pipeline to the Circle configuration, where all tags trigger a release build. This PR also changes the build script output format to be more structured.

Add deployment process to Circle

---

circle.yml

Fix Docker pushes on merges to master

---

canned/netstat.json
canned/processes.json

Update processes and netstat to be system app

---

docs/auth.md

Add note to auth.md

---

docs/use_cases.md

Fix image links in use_cases

---

CONTRIBUTING.md
README.md
etc/Dockerfile_build

Update to go 1.7.4

---

CHANGELOG.md
docs/LAYOUT.md
ui/src/hosts/containers/HostPage.js
ui/src/shared/components/LayoutRenderer.js
ui/src/shared/components/LineGraph.js
ui/src/shared/components/SingleStat.js
ui/src/shared/parsing/lastValues.js
ui/src/side_nav/components/SideNav.js
ui/src/side_nav/containers/SideNavApp.js
ui/src/style/enterprise_style/hosts.scss

Connect #605 
Want the ability to see a the last value returned from a series.
Introduce the single stat visualization.

Visualization: SINGLE STAT

---

docs/release.md

Add information about how to make releases

---

ui/src/CheckSources.js
ui/src/shared/actions/sources.js
ui/src/shared/reducers/index.js
ui/src/shared/reducers/sources.js
ui/src/sources/containers/CreateSource.js
ui/src/sources/containers/ManageSources.js
ui/src/sources/containers/SourceForm.js
ui/src/store/configureStore.js

Connect #510 
Sources are hard to change between pages if they're modified.
Use redux. This will fix the outstanding issue where users can't connect to a newly created source without reloading the page.
First time working with redux, so I'd like eyes on this. Pretty boiler-platey, but not sure if there's a way to get rid of the excessive mapDispatchToProps etc.
It's also possible that I'm overengineering this, and using redux is adding unnecessary complexity, so feedback would be appreciated.
This will also fix #603

store sources in redux

---

CHANGELOG.md

Update changelog for 1.1.0-beta1

---

ui/src/kapacitor/components/DataSection.js
ui/src/kapacitor/components/KapacitorRule.js
ui/src/kapacitor/components/RuleGraph.js
ui/src/kapacitor/components/RuleHeader.js

Connect #624 
User could not adjust the visualization time range in the Kapacitor Rule creation page
Include said functionality

Add time range selection to RulePage

---

server/users.go

Update teapot to be informational

---

circle.yml

Switch to new build image

---

README.md

Update to 1.1.0-beta2

---

CHANGELOG.md

1. [#624](https://github.com/influxdata/chronograf/issues/624): Add time range selection to kapacitor alert rules
1. Update Go to 1.7.4
1. [#664](https://github.com/influxdata/chronograf/issues/664): Fix Content-Type of single-page app to always be text/html
1. [#671](https://github.com/influxdata/chronograf/issues/671): Fix multiple influxdb source freezing page

Add CHANGELOG for beta2

---

ui/src/style/enterprise_style/theme-dark.scss

**Problem:** #652 
**Solution:**

Fix Input Text Selection 

---

ui/spec/utils/timeSeriesToDygraphSpec.js
ui/src/chronograf/components/Panel.js
ui/src/chronograf/components/PanelBuilder.js
ui/src/chronograf/components/PanelList.js
ui/src/chronograf/components/Visualization.js
ui/src/chronograf/components/Visualizations.js
ui/src/chronograf/containers/DataExplorer.js
ui/src/shared/components/Dygraph.js
ui/src/shared/components/LineGraph.js
ui/src/shared/constants/index.js
ui/src/utils/timeSeriesToDygraph.js

Connect #619 
While in an Exploration in the DE, with multiple query tabs, it is difficult to differentiate which series belong to which query. 
Highlight all series for an active query.

Highlight series

---

README.md

Add note about necessary plugins

---

ui/src/chronograf/components/Panel.js
ui/src/chronograf/components/QueryTabItem.js

Prefer "InfluxQL" over "Raw Text"

Use InfluxQL instead of Raw Text

---

README.md

Add link to beta3 blog

---

chronograf.go
server/server.go

Add server uptime reporting

---

canned/apps.go
server/mux.go
server/redoc.go
server/server.go
server/swagger.go

Miscellaneous lint cleanup

---

ui/src/dashboards/apis/index.js
ui/src/dashboards/containers/DashboardsPage.js
ui/src/dashboards/index.js
ui/src/index.js
ui/src/side_nav/components/SideNav.js

Connect #612 
Users would like to view a list of the dashboards available.
This adds a dashboards index page as well as updates the side nav to have a link to said dashboards index page.

Implement Dashboard Index Page

---

CHANGELOG.md
README.md

So far this just updates the version number in the README.

Update version to beta4

---

CHANGELOG.md
canned/mongodb.json

Fix #693
The MongoDB layout was not displaying because it was corrupted. 
Fixed the layout.  <soapbox>Layouts are too difficult to use right now.  It is too easy to get them wrong. </soapbox>

Fix mongo layout to remove extra fields

---

CHANGELOG.md
README.md
canned/rabbitmq.json

Add rabbitmq canned dash

---

CHANGELOG.md

Add changelog for 706 and 707

---

server/kapacitors.go
server/sources.go
server/swagger.json

Connect #471
If a source was deleted, the kapacitor resource and rules in associated kapacitor resource were not deleted.
Kapacitor and rules will also be removed now.  
However, the actual kapacitor tasks stored in kapacitor are _NOT_ removed.

Update source remove to also remove kapacitor and rules resources

---

ui/src/hosts/components/HostsTable.js

add sort by status on hosts page

---

ui/src/kapacitor/components/HipChatConfig.js
ui/src/kapacitor/components/PagerDutyConfig.js
ui/src/kapacitor/components/TelegramConfig.js

Remove checkboxes

---

circle.yml
etc/build.py

I also gussied up the look of the markdown release architectures.

Update circle builds of release tags to upload docker containers to quay

---

ui/src/alerts/components/AlertsTable.js

add links to hosts in alerts table

---

ui/src/sources/components/SourceForm.js

Fix not being able to add new source

---

CHANGELOG.md
README.md

Update changelog and release notes to beta6

---

ui/src/kapacitor/constants/index.js

Fix copy and templated string

---

ui/src/alerts/components/AlertsTable.js

Connect #773
Code was just copied and pasted from older filtering done in the hosts page.  I don't think it ever worked.
Typing in the input was also a bit choppy / laggy.  Debouncing the filtering function seems to have resolved the issue.

Fix alert filter

---

ui/src/kapacitor/components/AlertOutputs.js
ui/src/kapacitor/components/TalkConfig.js

Connect #736 
No GUI for Talk alert endpoint
Add one

Introduce Talk alert config

---

ui/spec/utils/timeSeriesToDygraphSpec.js
ui/src/utils/timeSeriesToDygraph.js

Reverts influxdata/chronograf#799

Revert "Bugfix/legend data order"

---

ui/spec/utils/timeSeriesToDygraphSpec.js
ui/src/utils/timeSeriesToDygraph.js

Reverts influxdata/chronograf#804

Revert "Revert "Bugfix/legend data order""

---

etc/build.py

Update build script to output JSON for website and MD for GH

---

CHANGELOG.md
README.md
canned/net.json
canned/new_apps.sh
canned/procstat.json

Connect #777
Need layout for telegraf's `inputs.procstat` collection.

Add procstat layout 

---

ui/src/kapacitor/containers/KapacitorPage.js

@rkuchan requested that there be default input values for kapacitor configuration.  This should do the trick.

Add default values for kapacitor config

---

CONTRIBUTING.md
README.md
circle.yml
etc/Dockerfile_build
etc/README.md

Update to Go version 1.7.5: https://github.com/golang/go/issues?q=milestone%3AGo1.7.5

Update to Go version 1.7.5

---

CHANGELOG.md
README.md
ui/src/kapacitor/components/AlertOutputs.js
ui/src/kapacitor/components/OpsGenieConfig.js
ui/src/style/chronograf.scss
ui/src/style/components/input-tag-list.scss

Connect #737 
No OpsGenie GUI
Add one

OpsGenie Alert Config

---

ui/src/kapacitor/components/TelegramConfig.js
ui/src/style/theme/theme-dark.scss

Connect #640 
Incorrect request body format sent to Kapacitor.
Fix format sent to Kapacitor.

Fix format sent to Kapacitor for Telegram.

---

server/swagger.json

Update dashboard swagger  to use LayoutQuery instead of a string

---

circle.yml
etc/build.py

MD5 is not collision-resistant.
Switching to SHA256

Update release builds to use SHA256 as well as MD5

---

ui/src/style/components/multi-select-dropdown.scss

CSS Usability Fix

---

etc/build.py

similar to https://github.com/influxdata/telegraf/issues/1704

always force the file inside the tarball owned by root

---

ui/src/dashboards/apis/index.js
ui/src/dashboards/containers/DashboardPage.js

Connect #615 
Users can now switch dashboards via dropdown.

change dashboards via dropdown

---

ui/package.json
ui/spec/utils/timeSeriesToDygraphSpec.js
ui/src/utils/timeSeriesToDygraph.js
ui/yarn.lock

Connect #799 
Connect #785 
Connect #745
The new timeSeriesToDygraph function was slow af
Bug fixes and performance improvements.

Time series to dygraph refactor

---

CHANGELOG.md
kapacitor/client.go
server/kapacitors.go
server/mux.go
server/swagger.json
ui/spec/kapacitor/reducers/rulesSpec.js
ui/src/kapacitor/actions/view/index.js
ui/src/kapacitor/apis/index.js
ui/src/kapacitor/containers/KapacitorRulesPage.js
ui/src/kapacitor/reducers/rules.js
ui/src/style/theme/theme-dark.scss

Connect #238 
Connect #847 
Kapacitor alerts are able to be disabled.
Checkbox in the alert manager to enable/disable an alert.

Change rule status

---

ui/src/style/pages/data-explorer/query-builder.scss
ui/src/style/pages/data-explorer/query-editor.scss

Empty states in the query builder look much nicer now

DE Empty State Polish

---

CHANGELOG.md

Update changelog for 1.2.0-beta2

---

server/sources.go

Update chronograf sources response

---

ui/spec/data_explorer/reducers/timeRangeSpec.js
ui/spec/data_explorer/reducers/uiSpec.js
ui/src/data_explorer/containers/DataExplorer.js
ui/src/data_explorer/reducers/index.js
ui/src/data_explorer/reducers/timeRange.js
ui/src/data_explorer/reducers/ui.js
ui/src/localStorage.js

Query configs not scoped to data explorer.
Create a reducer for DE state, and handle scoping of configs there.

Deui reducer

---

CHANGELOG.md
canned/docker.json
canned/docker_blkio.json
canned/docker_net.json

Connect #
Not enough docker stats
Add more

Add more docker stats

---

CHANGELOG.md

Update changelog for 1.2.0-beta3

---

docs/INSTALLATION.md

Updates the Telegraf version on the INSTALLATION page from 1.2.0 to 1.2.1.

Update Telegraf version to 1.2.1

---

canned/apache.json
canned/consul.json
canned/cpu.json
canned/disk.json
canned/docker.json
canned/influxdb_httpd.json
canned/influxdb_write.json
canned/mem.json
canned/memcached.json
canned/mongodb.json

Connect #778 
Graphs should always have units.  
So, I've added some to our y-axis.

Update apache, consul, cpu, disk, docker, mem with y-axis labels

---

canned/consul_agent.json

Add consule agent stats

---

canned/consul_cluster.json
canned/consul_election.json
canned/consul_http.json
canned/consul_leadership.json
canned/consul_serf_events.json

Add consul statsd cluster health dashboard

---

chronograf.go
enterprise/enterprise.go
enterprise/meta.go
enterprise/meta_test.go
enterprise/mocks_test.go
enterprise/roles.go
enterprise/roles_test.go
enterprise/users.go
enterprise/users_test.go
server/admin.go
server/swagger.json

Connect #934 
Influx Enterprise does not return the roles associated with a user.
Get all roles and associate them with the user before responding

Update InfluxEnterprise users to return their roles

---

ui/src/hosts/components/HostsTable.js

#855 - don't show "loading hosts" after hosts have been loaded

---

enterprise/roles.go
enterprise/users.go
server/admin.go
server/admin_test.go

During a `PATCH` to /users and `/roles` permissions were being overridden.
Check if permissions were nil before using.

Fix users and roles PATCH removing all permissions

---

ui/spec/admin/reducers/adminSpec.js
ui/src/admin/actions/index.js
ui/src/admin/apis/index.js
ui/src/admin/components/AdminTabs.js
ui/src/admin/components/DeleteRow.js
ui/src/admin/components/RoleRow.js
ui/src/admin/components/RolesTable.js
ui/src/admin/components/UserRow.js
ui/src/admin/components/UsersTable.js
ui/src/admin/containers/AdminPage.js
ui/src/admin/reducers/admin.js

Add delete confirmation component, optimistic delete in reducer, async & AJAX call, and reducer tests.
Re: #932

EW Admin Delete Confirmation Component

---

ui/spec/admin/reducers/adminSpec.js
ui/src/admin/actions/index.js
ui/src/admin/components/AdminTabs.js
ui/src/admin/components/FilterBar.js
ui/src/admin/components/RolesTable.js
ui/src/admin/components/UsersTable.js
ui/src/admin/containers/AdminPage.js
ui/src/admin/reducers/admin.js

Add filtering capability to users and roles admin pages.
Connect: #934 #932

Add filtering capability to users and roles admin pages.

---

ui/src/admin/components/AdminTabs.js
ui/src/admin/components/FilterBar.js
ui/src/admin/components/UsersTable.js

Remove roles on OSS and refactor tabs

Remove roles on OSS and refactor tabs

---

LICENSE

799 Market Street, Suite 400
San Francisco, CA 94103

Update location of InfluxData in the LICENSE file

---

ui/.eslintrc
ui/src/admin/actions/index.js
ui/src/admin/apis/index.js
ui/src/admin/components/AdminTabs.js
ui/src/admin/components/RoleRow.js
ui/src/admin/components/RolesTable.js
ui/src/admin/containers/AdminPage.js
ui/src/shared/components/MultiSelectDropdown.js

Connect #937 
Connect #933
This currently only supports the updating of global permissions i.e. permissions not scoped to a specific database.

Feature/937 feature/933 updating users and permissions for a role

---

ui/src/admin/components/RoleRow.js

Roles broke because some roles don't have a users key at all, currently.
Handle no users.

Fix roles bug when no users

---

CHANGELOG.md
README.md
canned/mesos.json

Add mesos canned

---

ui/spec/admin/reducers/adminSpec.js
ui/src/admin/actions/index.js
ui/src/admin/apis/index.js
ui/src/admin/components/AdminTabs.js
ui/src/admin/components/UserRow.js
ui/src/admin/components/UsersTable.js
ui/src/admin/containers/AdminPage.js
ui/src/admin/reducers/admin.js
ui/src/side_nav/components/SideNav.js

Feature/ populate perms from server

---

server/users.go

Update user's roles validation

---

ui/spec/admin/reducers/adminSpec.js
ui/src/admin/actions/index.js
ui/src/admin/apis/index.js
ui/src/admin/constants/index.js
ui/src/admin/reducers/admin.js
ui/src/shared/constants/index.js

Fix data flow from server back into multiselect, add tests

---

CHANGELOG.md
README.md

Updates for the beta5 release.

Update Changelog and Readme for beta5

---

ui/src/admin/components/FilterBar.js
ui/src/shared/components/MultiSelectDropdown.js
ui/src/style/pages/admin.scss

Just some minor stuff
- Fixed error in console from Multi Select Dropdowns from a `<li>` being used outside of `<ul>`
- Multiselects stay bright blue when they are opened in admin tables
- Proper capitalization for what is passed into `FilterBar` so it will print `Filter Users…` and `Create User` instead of `users`

Admin Polish

---

server/server.go

Fix reporting stats to update uptime

---

ui/src/dashboards/containers/DashboardsPage.js
ui/src/kapacitor/components/KapacitorRules.js

Connect #1045 
Added a `Create Dashboard` button to the Dashboards index view

Create Dashboard Button

---

ui/src/dashboards/apis/index.js
ui/src/dashboards/constants/index.js
ui/src/dashboards/containers/DashboardsPage.js

Introduce create dashbaord

---

CHANGELOG.md
server/dashboards.go
server/dashboards_test.go
server/swagger.json
ui/spec/dashboards/reducers/uiSpec.js
ui/src/dashboards/actions/index.js
ui/src/dashboards/apis/index.js
ui/src/dashboards/components/DashboardHeader.js
ui/src/dashboards/constants/index.js
ui/src/dashboards/containers/DashboardPage.js
ui/src/dashboards/reducers/ui.js
ui/src/shared/components/NameableGraph.js

Create a new dashboard cell; Fix remaining bugs with Overlay

---

ui/src/dashboards/actions/index.js
ui/src/dashboards/apis/index.js
ui/src/dashboards/components/Dashboard.js
ui/src/dashboards/containers/DashboardPage.js
ui/src/dashboards/reducers/ui.js
ui/src/shared/components/LayoutRenderer.js
ui/src/shared/components/NameableGraph.js

Connect #1057
Users should be able to delete a cell from a dashboard.
Add a button to the dropdown so users can delete the dashboard

NameableGraph Dropdown now contains an active Delete button

---

CHANGELOG.md
ui/spec/dashboards/reducers/uiSpec.js
ui/src/dashboards/actions/index.js
ui/src/dashboards/components/DashboardHeader.js
ui/src/dashboards/components/DashboardHeaderEdit.js
ui/src/dashboards/containers/DashboardPage.js
ui/src/dashboards/reducers/ui.js
ui/src/index.js

Connect #1062
The Save button in Dashboard Edit mode is nonfunctional.
- Add functional Save and Cancel buttons to Dashboard Edit mode.

Save and Cancel edits to dashboard name

---

CHANGELOG.md
README.md

Update docs for beta6 release

---

CHANGELOG.md

The bugfixes in the unreleased section of the changelog were actually part of the beta6 release.
Put the bugfixes in the right section!

Fix beta6 bug fixes entries

---

ui/src/admin/components/DatabaseManager.js
ui/src/admin/components/DatabaseRow.js
ui/src/admin/components/DatabaseTable.js
ui/src/admin/containers/DatabaseManagerPage.js
ui/src/utils/formatting.js

Fix DBRP page bugs

---

ui/src/admin/components/DatabaseTable.js
ui/src/admin/components/DatabaseTableHeader.js

Connect #1086 
Did not check database delete code when using checkmark.
[This line](https://github.com/influxdata/chronograf/pull/1099/files#diff-88ff763ae2b1817f24ad705eaf8c57b7R75) fixes it.  Apologies for muddling the move of the component with the bugfix.
To do so :)

Bugfix delete database

---

CHANGELOG.md
README.md

Connect #
Release not prepped
Prep the release

Changelog and known issues from readme update for beta7

---

docs/INSTALLATION.md

I forgot to update the version in the installation doc 😱

Update version in installation page

---

CHANGELOG.md
ui/src/dashboards/components/CellEditorOverlay.js
ui/src/dashboards/containers/DashboardPage.js
ui/src/data_explorer/components/Visualization.js

Connect #1084 
Cell names weren't being passed to the visualization editor.
Pass the name property through to the Visualization component.

Fix visualizations not showing graph name

---

LICENSE_OF_DEPENDENCIES.md
ui/package.json
ui/src/alerts/apis/index.js
ui/src/alerts/components/AlertsTable.js
ui/src/alerts/containers/AlertsApp.js
ui/src/shared/components/CustomTimeRange.js
ui/src/style/chronograf.scss
ui/src/style/components/custom-time-range.scss
ui/src/style/mixins/mixins.scss
ui/src/style/theme/theme-dark.scss
ui/yarn.lock

Connect #1030 
We get all the alerts since the beginning of time.  This causes the browser to hangup and crash and is generally a 💩  experience.
Having a default timeRange and the ability for a user to update the timeRange gets us 80% of the way there.

Alert time range

---

CHANGELOG.md
ui/src/kapacitor/components/TelegramConfig.js
ui/src/kapacitor/copy.js
ui/src/shared/components/QuestionMarkTooltip.js
ui/src/style/components/react-tooltips.scss

Connect #921
Telegram configuration has proved to be confusing for users.
See [this list](https://github.com/influxdata/chronograf/issues/921#issuecomment-290509249) for all the changes.
The most notable change is the addition of the [QuestionMarkTooltip component](https://github.com/influxdata/chronograf/pull/1135/files#diff-2d47a77591e6830c64d476c9a4a92910). Places an inline `?` on the page, which reveals a tooltip on hover. The tooltip remains in view while you're hovering over the `?`, or on the tooltip itself. This allows us to mouse over the tooltip and click any links contained within the tooltip:

Clean up Kapacitor Alert configuration for Telegram

---

CHANGELOG.md
ui/src/admin/components/ChangePassRow.js
ui/src/admin/components/DatabaseRow.js
ui/src/admin/components/DatabaseTableHeader.js
ui/src/admin/components/FilterBar.js
ui/src/admin/components/QueriesTable.js
ui/src/admin/components/UsersTable.js
ui/src/dashboards/components/DashboardHeader.js
ui/src/dashboards/containers/DashboardsPage.js
ui/src/data_explorer/containers/Header.js
ui/src/kapacitor/copy.js
ui/src/shared/components/GraphTips.js
ui/src/shared/components/LayoutRenderer.js
ui/src/shared/components/NameableGraph.js
ui/src/shared/components/QuestionMarkTooltip.js
ui/src/shared/components/SourceIndicator.js
ui/src/style/chronograf.scss
ui/src/style/components/graph-tips.scss
ui/src/style/components/react-tooltips.scss
ui/src/style/components/source-indicator.scss
ui/src/style/pages/admin.scss
ui/src/style/pages/dashboards.scss
ui/src/style/pages/data-explorer/visualization.scss
ui/src/style/theme/theme-dark.scss
ui/src/style/unsorted.scss

- Fix for #1083 
- Fixes for #1127
- Aesthetic adjustments to DB Management design
- Fix for #1097 
- Fix for #1106

Some Amount of Polish

---

CHANGELOG.md
ui/src/data_explorer/components/Table.js

Connect #1123
Data explorer sometimes looks like this:
Make it look like this:

widen single column to entire table width (#1123)

---

ui/src/dashboards/containers/DashboardPage.js

Connect #1196
With the Redux dashboard state refactor, `handleUpdatePosition` was no longer adequately updating the position/size of a cell.
Make a new dashboard, and send it to both the Redux store and the server.

Repair Dashboard Layout Changes

---

ui/src/style/pages/dashboards.scss

Promote stacking context of .dash-graph--options

---

CHANGELOG.md
ui/src/dashboards/constants/index.js

Connect #1126
The query did not include a database
Include a database in the query

Server validates that queries include database + rp

---

CHANGELOG.md
ui/src/dashboards/constants/index.js

Fuller DefaultCell; Reference DefaultCell in DefaultDashboard

---

CHANGELOG.md
ui/src/App.js
ui/src/shared/actions/notifications.js
ui/src/shared/components/Notifications.js
ui/src/sources/components/SourceForm.js
ui/src/sources/containers/CreateSource.js
ui/src/sources/containers/SourcePage.js
ui/src/style/unsorted.scss

Connect #1145, #1174
The initial "add source" form (when loading the app with no source) does not allow for enterprise sources, or offer unsafe ssl connections.
The code for that form and the form on the sources page are separate code, when they're doing essentially the same thing. I changed stuff so that they both use the same component, which makes the aforementioned missing features available.
This also resolves a separate issue (#1174) where, after failing to create a new source, the form broke.
Stuff I'm not happy with:
- could probably be DRY'd more

Initial source options

---

.gitattributes
CHANGELOG.md
README.md
docs/INSTALLATION.md

Clarify a few issues

---

CHANGELOG.md
server/server.go

Google login doesnt work because looking for the wrong env variable
Change code to look for correct variable

Fix env var name for Google client secret

---

CHANGELOG.md
ui/src/dashboards/components/Dashboard.js
ui/src/dashboards/containers/DashboardPage.js
ui/src/style/pages/dashboards.scss

Connect #1052 
We currently don't have an empty state for a Dashboard. We allow you to delete the final cell in the dashboard, but the dashboard will just appear blank.

Add default display for an empty dashboard

---

CHANGELOG.md
README.md
docs/INSTALLATION.md

Updates for beta9

---

ui/src/dashboards/components/TemplateQueryBuilder.js
ui/src/dashboards/components/TemplateVariableManager.js
ui/src/dashboards/components/TemplateVariableRow.js
ui/src/dashboards/components/TemplateVariableTable.js
ui/src/style/components/template-variables-manager.scss
ui/src/style/layout/page-header.scss
ui/src/style/pages/dashboards.scss
ui/src/style/pages/overlay-technology.scss

- Ended up bailing on the flex box table approach, was having trouble getting things to scale nicely. Also wanted some columns fixed width and some grow-to-fit and that was taking me way too long to tackle
- Split off some of the styles in `pages/dashboards.scss` into their own sheets

Template manager polish

---

ui/src/dashboards/components/CellEditorOverlay.js
ui/src/data_explorer/components/VisView.js
ui/src/data_explorer/components/Visualization.js

CellEditorOverlay accepted templates from Dashboard, but did not pass them through Visualization and VisView down to AutoRefresh.
Wire it up!

Visualization passes thru templates to AutoRefresh

---

ui/src/shared/components/Dropdown.js

A similar function got lost in one of our merge conflict resolutions
Add it back

Dropdown onClick opens it and executes parent's onClick

---

ui/src/dashboards/components/Dashboard.js
ui/src/style/components/template-control-bar.scss
ui/src/style/layout/page-header.scss
ui/src/style/modules/mixins.scss
ui/src/style/pages/dashboards.scss

- No labels, confusing
- Labels
- Design tested with a lot of variables, works on small screens or with a lot of variables
it wraps:
Fancy colored dropdowns:

Template Control Bar Polish

---

CHANGELOG.md
README.md
docs/INSTALLATION.md

Prep for beta10 release

---

CHANGELOG.md
ui/src/style/chronograf.scss
ui/src/style/layout/overlay.scss
ui/src/style/layout/page.scss
ui/src/style/pages/overlay-technology.scss

No reason why this can’t or shouldn’t be done, it is a modal after all

Make overlay technology full screen

---

CHANGELOG.md
ui/src/shared/actions/sources.js
ui/src/shared/apis/index.js
ui/src/shared/reducers/sources.js
ui/src/sources/components/InfluxTable.js
ui/src/sources/containers/ManageSources.js

Connect #1323
You can't delete kapacitor configs right now.
Add a button in the dropdown to do it :3

add ability to delete kapacitor config

---

CHANGELOG.md
README.md

Updates for 1.3.0~rc1

---

CHANGELOG.md
ui/src/data_explorer/components/MeasurementList.js
ui/src/style/components/dygraphs.scss

Resolve bugs: 1424, 1425, & 1431

---

CHANGELOG.md
ui/src/admin/containers/AdminPage.js
ui/src/sources/containers/ManageSources.js
ui/src/sources/containers/SourcePage.js

Add SourceIndicator to Configuration and Admin pages

---

ui/src/kapacitor/components/config/SlackConfig.js

remove test button from slack config

---

CHANGELOG.md
README.md

Updates for 1.3.0

---

circle.yml
etc/Dockerfile_build

Update to Go 1.8.1 and Node 6.10.3

---

.bumpversion.cfg
README.md
docs/release.md

Connect #1446
We have several files that need to be updated each time we do a release.
Using `bumpversion` it'll update README.md, server/swagger.json, and ui/package.json.

Add bumpversion to help script releases

---

etc/build.py

Correct license in build/packaging script

---

CHANGELOG.md

Changelog should list pulls

---

.github/PULL_REQUEST_TEMPLATE

Connect #
Some changelog entries link to the issue instead of the PR.
Add a small clarification to the PR template.

Clarify changelog update requirement

---

etc/build.py

Update release to use `Platform` rather than `Arch`

---

CHANGELOG.md
ui/spec/data_explorer/reducers/queryConfigSpec.js
ui/src/utils/queryTransitions.js

Revert auto func

---

.bumpversion.cfg
CHANGELOG.md
README.md
server/swagger.json
ui/package.json

Update version and changelog for v1.3.2.0

---

CHANGELOG.md
server/swagger.json
ui/src/data_explorer/components/VisView.js
ui/src/external/dygraph.js
ui/src/shared/components/Dygraph.js
ui/src/shared/components/LayoutRenderer.js
ui/src/shared/components/LineGraph.js
ui/src/shared/data/graphTypes.hson

Connect #1557 
We don't have bar graphs in Chronograf.
Add the bar graphs, using plotter example, and integrating the option into our application logic and Dygraph updater.

Introduce Bar Graph as an option for graph types

---

ui/src/kapacitor/components/config/TelegramConfig.js

just a tiny update of a href link to point to the good version of documentation

Update link to the latest documentation version

---

oauth2/generic.go
server/server.go

Generic OAuth provider should have a redirect URL
Build RedirectURL from PublicURL

Add redirect url to generic oauth

---

CHANGELOG.md
ui/src/hosts/apis/index.js

Connect #1649
InfluxQL was incorrect and written inconsistently
Fix the InfluxQL

Fix broken cpu reporting on hosts page and normalize InfluxQL

---

CHANGELOG.md
kapacitor/client.go
kapacitor/client_test.go

Connect #1343 
Enable / disable could get out of sync on Rules Page.  The chronograf server assumed that all updated rules would want to be enabled.
Rules must first be disabled before being updated.  So, when updating a kapacitor rule, check its status and only 'enable' it if it was previously enabled.

Fix enable / disable bug

---

CHANGELOG.md
ui/src/dashboards/actions/index.js
ui/src/dashboards/components/Dashboard.js
ui/src/dashboards/components/TemplateControlBar.js
ui/src/dashboards/containers/DashboardPage.js
ui/src/dashboards/reducers/ui.js
ui/src/dashboards/utils/templateVariableQueryGenerator.js

Connect #1551 
If the values of a template variable are updated those changes were never updated.
Update tempVars on dashboard mount.
This made me sad but @cryptoquick has written PHP and he's actually totally fine with the way this looks

Refresh templates on dashboard load

---

CHANGELOG.md
ui/src/side_nav/containers/SideNav.js
ui/src/sources/containers/ManageSources.js
ui/src/style/unsorted.scss

Find better home for version number

---

server/server.go

Connect #1675 
The syntax for using custom links was not fully clear.
Flesh out the description for use of custom links in the Chronograf server's help section, i.e. `./chronograf --help`, and provide an example of using multiple custom links.

Improve description of custom link use, and give example

---

ui/src/style/layout/overlay.scss

Connect #1670 
File uploader overlay is off center
File uploader overlay is centered

Center file upload overlay

---

ui/src/dashboards/components/Dashboard.js
ui/src/hosts/containers/HostPage.js
ui/src/shared/components/ContextMenu.js
ui/src/shared/components/CustomTimeIndicator.js
ui/src/shared/components/LayoutRenderer.js
ui/src/shared/components/NameableGraph.js
ui/src/shared/components/NameableGraphHeader.js
ui/src/status/containers/StatusPage.js

Connect: none, hotfix, broken on master
A regression was introduced when the custom time range indicator code was added.
Fix issue on both homepage and status page where custom time range indicator data is not present on the cell's query.

Custom Time Range Indicator Hotfix

---

ui/.eslintrc
ui/package.json
ui/src/utils/influxql.js
ui/yarn.lock

Connect #
We need to know when prettier needs to be prettiest.
Add it to an eslint rule.

Add prettier to an eslint rule.

---

ui/src/dashboards/containers/DashboardPage.js
ui/src/dashboards/reducers/ui.js
ui/src/shared/components/CustomTimeRangeDropdown.js
ui/src/shared/components/LayoutRenderer.js
ui/src/shared/components/NameableGraphHeader.js

Prettier test

---

CHANGELOG.md
ui/src/shared/components/DygraphLegend.js
ui/src/style/pages/dashboards.scss

Connect #1710 
Connect #1704
- Snip toggle does not highlight when active
- Custom time indicator does not move over when adjacent dropdown arrow is gone in presentation mode
- Snip toggle highlights when active
- Custom time indicator slides into corner of cell in presentation mode

Misc UI Fixes

---

CHANGELOG.md
ui/src/data_explorer/components/WriteDataBody.js
ui/src/style/components/write-data-form.scss

Connect #1774 
Inserting all this data into a small box made people 😢 
Make people 😸  with a larger area to drag, drop, and write their inserts!

Embiggen the write data form

---

CHANGELOG.md
ui/package.json

How to merge the README.md manually, to preserve the copy changes on the right and the `v1.3.7.0` header on the left?
Connect #

WIP 1.3.6.x

---

CHANGELOG.md
ui/src/kapacitor/components/config/PagerDutyConfig.js

fix json key in pagerduty update

---

CHANGELOG.md
ui/src/shared/components/CustomTimeRange.js
ui/src/style/components/custom-time-range.scss

Connect #1696 
Hey man, I want to type in my times!
Okay, here's a text input for you to type in your lower and upper bounds.  Enjoy!
Extra credit isn't just for school anymore.  It's for Chronograf's calendar inputs!  Now, a user cannot select an upper time that is lower than their lower bound and vice versa!

FEATURE:  Typee calendar (with extra credit)

---

CHANGELOG.md
ui/src/admin/components/DatabaseRow.js
ui/src/admin/components/DatabaseTable.js

Connect #1932 
- Table cell sizing feels wonky
- Adjusted to more desirable proportions

Fix Sizing of Table in Admin > Databases

---

CHANGELOG.md
ui/src/external/dygraph.js
ui/src/kapacitor/containers/KapacitorPage.js
ui/src/shared/components/Dygraph.js
ui/src/shared/graphs/helpers.js

Connect #1811 
The vertical marker AKA crosshair on the graph lingers around after mousing out of the graph 
Make them go away!
I also took this as an opportunity to clean up the Dygraph component as a whole

BUGFIX: crosshair remove

---

CHANGELOG.md
enterprise/meta.go
enterprise/meta_test.go

Signed-off-by: Nathan Haugo <nhaugo@gmail.com>
connect #1948

Fix return code when not talking to enterprise leader

---

circle.yml

Update circle to add latest tag to point releases rather than master

---

influx/influx.go

Add header check for upcoming influxdb builds.

Add check for enterprise build type header

---

ui/package.json
ui/src/shared/components/Layout.js
ui/src/shared/components/LayoutRenderer.js
ui/src/shared/components/LineGraph.js
ui/src/shared/components/RefreshingGraph.js
ui/src/shared/components/WidgetCell.js
ui/src/shared/graphs/helpers.js
ui/src/style/pages/dashboards.scss
ui/src/utils/influxql.js
ui/yarn.lock

Connect #2005 
Imperative code, old patters, multiple render, and calls to `window` and `document` all in one component.  This made the `LayoutRenderer` a pain to reason about and work in.
Refactor the above to a more declarative React-stlye component:
- Extracting multiple render functions into separate SFC's. 
- Removed unnecessary lifecycle methods that attached functions to `window`
- Using fat arrow properties for `this` binding
- Remove custom events to `document`
- And much, much more!

REFACTOR: Layout Renderer and Line Graph

---

CHANGELOG.md
ui/src/sources/components/SourceForm.js
ui/src/style/theme/bootstrap-theme.scss

Connect #2032 
- It was unclear to some users that the placeholder text in inputs was placeholder text
- The way default values are communicated in the source connection form is somewhat confusing
- Update the theme such that all text inputs have italic placeholder text
- Change the placeholder text in the source connection form to be a call to action
- Add a button in the source form that sets "default" values for `sourceURL` and `sourceName`
- Refactor `SourceForm` to latest component pattern

UI IMPROVEMENT: Improve UX in Source Form

---

ui/src/dashboards/components/CellEditorOverlay.js
ui/src/dashboards/components/OverlayControls.js
ui/src/data_explorer/components/TagList.js
ui/src/shared/components/MeasurementList.js
ui/src/style/unsorted.scss

Connect #1088 
@alexpaxton is going to tweak some of the styles for the dropdown.  The entire row of the dropdown `<li>` isn't clickable.

Source cell cleanup for 1.3.9.x

---

ui/src/dashboards/components/CellEditorOverlay.js
ui/src/dashboards/components/OverlayControls.js
ui/src/data_explorer/components/TagList.js
ui/src/shared/components/MeasurementList.js
ui/src/style/unsorted.scss

Source cell cleanup

---

CHANGELOG.md
ui/src/data_explorer/components/QueryMaker.js
ui/src/data_explorer/containers/DataExplorer.js
ui/src/utils/influxql.js

Connect #1815 
There's been a need to share queries in the data explorer using a URL.
Add Data Explorer InfluxQL query and location query synchronization, so DE queries can be shared via a a URL.

Add Data Explorer InfluxQL query and location query synchronization

---

CHANGELOG.md
ui/spec/dashboards/reducers/dashTimeV1Spec.js
ui/spec/data_explorer/utils/influxql/selectSpec.js
ui/spec/normalizers/dashboardTimeSpec.js
ui/src/dashboards/actions/index.js
ui/src/dashboards/components/CellEditorOverlay.js
ui/src/dashboards/components/QueryMaker.js
ui/src/dashboards/constants/index.js
ui/src/dashboards/containers/DashboardPage.js
ui/src/dashboards/reducers/dashTimeV1.js
ui/src/data_explorer/containers/DataExplorer.js
ui/src/localStorage.js
ui/src/normalizers/dashboardTime.js
ui/src/normalizers/id.js
ui/src/store/configureStore.js
ui/src/utils/buildQueriesForGraphs.js
ui/src/utils/influxql.js

FEATURE: Persist dashboard time ranges per dashboard

---

CHANGELOG.md
ui/src/admin/actions/index.js
ui/src/admin/containers/AdminPage.js
ui/src/admin/containers/DatabaseManagerPage.js

Connect #2089 
The proper error messages were commented out :face_palm:
Uncomment them
There's a bit of cleanup organization of props, the part that actually needs reviewing is [just this](https://github.com/influxdata/chronograf/commit/37553cbf703beaf118ba11b226c4c6b0bfca3001)

BUGFIX: Bad error messages for RP creation and DB creation

---

bolt/users.go
bolt/users_test.go
chronograf.go
enterprise/users.go
enterprise/users_test.go
influx/users.go
influx/users_test.go
mocks/users.go
server/auth.go
server/auth_test.go
server/me.go
server/me_test.go
server/mux.go
server/sources.go
server/sources_test.go
server/users.go
server/users_test.go

Role based authorization

---

ui/src/status/fixtures.js

Connect #2148 
The status page wasn't showing graph data for alerts.
Fix fields to fit new format.

Fix status page

---

ui/src/dashboards/containers/DashboardPage.js

Connect #2151 
Dashboard was double keyed
Fix shape passed to `updateDashboard` action creator

Fix broken update of dashboards and TVs

---

ui/src/shared/components/DatabaseList.js

Connect #
The database list is really a database and retention policy list
Include `Retention Policy` in the copy
This is what @alexpaxton and I have settled on.  Everything else was just too long or looked worse
@gunnaraasen, what do you think?

Update database list to include retention

---

etc/Dockerfile_build

Update Go and Node to 1.9.2 and 6.11.5

---

bolt/organizations.go
bolt/organizations_test.go
chronograf.go

The PR ensure's that organization names are unique. This is not necessary for the application to function correctly, but has a better user experience.
Connect #2178

Ensure unique organization names.

---

chronograf.go
server/me.go
server/me_test.go

Remove CurrentOrganization from chronograf.User
Connect #2177

Add CurrentOrganization & Organizations to me resp

---

server/users.go
server/users_test.go

Prevent duplicate organization roles in user CRUD

---

server/users.go
server/users_test.go

This solves #2237, however this should be revisited for #2207
Connect #2237

Allow SuperAdmins to promoted and demoted

---

CHANGELOG.md
Gopkg.lock
kapacitor/client.go
kapacitor/client_test.go
kapacitor/operators.go
kapacitor/tickscripts.go
kapacitor/triggers.go
kapacitor/vars.go
ui/src/kapacitor/components/Relative.js
ui/src/kapacitor/components/Threshold.js
ui/src/kapacitor/constants/index.js
vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
vendor/github.com/google/go-cmp/cmp/cmpopts/sort_go17.go
vendor/github.com/google/go-cmp/cmp/cmpopts/sort_go18.go
vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
vendor/github.com/google/go-cmp/cmp/cmpopts/util_test.go

Connect #1997 
Chronograf was not checking an error condition, dereferencing a pointer and panicing.
Check the error and validate the input data.
Numerous empty values or values with single quotes could cause these errors.

Fix kapacitor task panic where error condition was not checked

---

ui/src/admin/components/chronograf/OrganizationsTable.js
ui/src/admin/containers/OrganizationsPage.js
ui/src/admin/index.js
ui/src/index.js
ui/src/side_nav/components/UserNavBlock.js
ui/src/side_nav/containers/SideNav.js
ui/src/style/layout/sidebar.scss

Connect #2286  
Removes `Manage Organizations` button from `AdminChronografPage` and introduces `OrganizationsPage` with identical functionality.
Not currently wired up to the router

Dedicated Organizations Page

---

CHANGELOG.md
ui/src/data_explorer/components/Table.js

DE tab names include measurement and all tag values

---

ui/src/sources/components/InfluxTable.js
ui/src/sources/components/SourceForm.js
ui/src/sources/containers/SourcePage.js

Connect #2276 
- Not always clear what org you are currently signed into
- Include name of current organization in `/manage-sources`
- Update copy to give the user stronger context in `/manage-sources`
- Include name of current organization in `InfluxTable`

Multitenancy UI Helpful Copy

---

ui/src/CheckSources.js

Scope auth logic beneath isUsingAuth

---

ui/src/shared/constants/index.js
ui/src/sources/components/SourceForm.js
ui/src/sources/constants/index.js

Source form role selection

---

ui/src/auth/Login.js
ui/src/auth/Purgatory.js
ui/src/auth/PurgatoryAuthItem.js
ui/src/shared/components/SplashPage.js
ui/src/side_nav/components/UserNavBlock.js
ui/src/style/pages/auth-page.scss

Connect #2308 
Connect #2241 
- It is possible to actually be trapped in Purgatory
- When you switch orgs, your resources (sources, etc.) are not refreshed, so you get error messages and can't use the app
- List all of the organizations a user belongs to with corresponding Login buttons
- Refresh the app after successfully switching organizations (via Purgatory or SideNav UserNavBlock)

Switch Organizations from Purgatory

---

server/users.go
server/users_test.go

Connect #2236 
Connect #2233 
Connect #2229

Multitenancy disallow null org on user

---

CHANGELOG.md
enterprise/meta.go
enterprise/meta_test.go
enterprise/users.go
server/swagger.json

Connect #2021 
Would remove all permissions before setting permissions
Removes just the permissions no longer wanted and adds only those permissions that don't exist.

Update enterprise users and roles to remove diffs instead of all

---

ui/package.json
ui/webpack/devConfig.js

Connect #
Webpack didn't clean up old build files.
Now it does.

Fix Webpack File Cleanup of old source files

---

server/users.go
server/users_test.go

Connect #2468 
Previously, Admins were unable to update any fields on a SuperAdmin. This PR introduces a check so that admins may update a SuperAdmins roles, but not their SuperAdmin status.

Allow Admin to update a SuperAdmin's Roles

---

README.md

Update README to mention /docs and reformat

---

ui/src/style/pages/auth-page.scss

Connect #2486 
- When there are multiple login buttons the spacing is unappealing
- Ensure pleasing margins when the number of buttons is variable

Login Button Spacing Fix

---

integrations/server_test.go
integrations/utils.go

Connect #2494 
This PR introduces a fully functioning version of the Chronograf API in an integration style Go test. 
It is intended to be a catchall place for things that are harder to catch with unit tests.

Add initial API integration tests

---

CHANGELOG.md
ui/src/alerts/components/AlertsTable.js
ui/src/hosts/components/HostRow.js
ui/src/hosts/components/HostsTable.js
ui/src/hosts/containers/HostsPage.js
ui/src/kapacitor/components/LogsTable.js
ui/src/kapacitor/containers/TickscriptPage.js
ui/src/shared/components/InfiniteScroll.js
ui/src/style/components/kapacitor-logs-table.scss
ui/src/style/components/tables.scss

Connect #2425 
Poor performance of pages with many many of items on them.
Create a vertical infinite scroll component for items of consistent height that updates on window resize, new props / items added, and of course, windows over items on scroll. It basically doesn't render any items outside the viewable area, and maintains scroll position with spacer divs above and below the visible scrolled area.
Used for Alerts Table, Hosts Page, and Tickscript Logs.

Infinite Scroll

---

CHANGELOG.md
ui/src/side_nav/components/UserNavBlock.js
ui/src/style/layout/sidebar.scss

Repair rendering bug in Firefox

---

ui/src/admin/constants/index.js
ui/src/style/components/react-tooltips.scss

Connect #2532
Verbiage of tool tip should not be boolean logic
Change text

Fix tool tip verbiage and master the art of css

---

ui/src/sources/components/SourceForm.js
ui/src/sources/containers/SourcePage.js

Connect #2523 
https://github.com/influxdata/chronograf/pull/2569

Switch orgs from manage sources rebased

---

ui/src/admin/containers/AdminChronografPage.js

Load admin's organizations when loading users table

---

integrations/server_test.go
server/users.go
server/users_test.go

Signed-off-by: Michael de Sa <mjdesa@gmail.com>
Connect #2602

Reference known issue #2601 in Admin creating SuperAdmin response

---

ui/src/shared/middleware/errors.js

Connect #2519 
Not @stevebang approved
Is now @stevebang approved

Bug fix/rename login to log in

---

ui/spec/admin/reducers/influxdbSpec.js
ui/src/admin/actions/influxdb.js
ui/src/admin/reducers/influxdb.js
ui/src/utils/formatting.js

Days is a valid duration value

---

CHANGELOG.md
server/cells.go
server/cells_test.go
server/influx.go
server/mux.go
server/queries.go
server/server_test.go

Connect #2595
Query config was not returned correctly on update of a single cell
Refactor and test the cell response to keep original query config.

Fix cell replacement to return query config

---

filestore/dashboards.go
filestore/environ.go
filestore/environ_test.go
filestore/templates.go
filestore/templates_test.go

Add env var golang templates to filestore rendering

---

.bumpversion.cfg
CHANGELOG.md
README.md
server/swagger.json
ui/package.json

Update CHANGELOG and versions to prep for 1.4.0.0-rc1

---

integrations/server_test.go

Update integration test to timeout in 5 seconds rather than 0.1

---

CHANGELOG.md

Add changelog for 2369

---

CHANGELOG.md
ui/src/shared/components/DygraphLegend.js

Connect #2680 
Series points with no value cluttering up the legend as per conversation with @timhallinflux 
Remove them from the legend

Remove no-value from list

---

CHANGELOG.md
ui/src/kapacitor/components/KapacitorForm.js
ui/src/sources/components/InfluxTable.js
ui/src/sources/components/SourceForm.js
ui/src/sources/containers/SourcePage.js

Connect #2686 
- Our current terminology surrounding InfluxDB connections is hazy
- It seems like you can modify an InfluxDB instance when you can only connect to it
- Rename `Source` to `Connection` as suggested in the issue
- Rename `Kapacitor Config` to `Kapacitor Connection`

Improve Sources Nomenclature

---

README.md

Connect #2713 
Links in the README pointed to 1.3
Links now point to 1.4 documentation

Update README links to point to 1.4 documentation

---

.bumpversion.cfg
CHANGELOG.md
README.md
server/swagger.json
ui/package.json

Release notes for 1.4.0.1 not included in master
cherry-picked and handled merge conflicts

Fix/release notes 1.4.0.1

---

CHANGELOG.md
etc/scripts/chronograf.service

Connect #2165
We were using cli options in the systemd service file
Remove the cli options and replace them with env vars

Change cli options to env args

---

ui/src/kapacitor/containers/KapacitorPage.js

Kapacitor page allows users to add spaces to kapacitor name

---

CHANGELOG.md
circle.yml
etc/Dockerfile_build
etc/README.md

Connect #
Security issues in go 1.9.3
https://github.com/golang/go/issues/23673
Upgrade to 1.9.4

Update to go 1.9.4

---

ui/src/admin/components/chronograf/AllUsersTable.js
ui/src/admin/components/chronograf/AllUsersTableRowNew.js
ui/src/admin/containers/chronograf/AllUsersPage.js
ui/src/admin/reducers/chronograf.js

Global Users page bug fixes

---

Dockerfile
Makefile
cmd/chronoctl/main.go
etc/build.py

I think this is all that is needed as a follow up to https://github.com/influxdata/chronograf/pull/2781
connect #2744

Add chronoctl to build.py and Dockerfile

---

cmd/chronoctl/add.go

Connect #2744 
I was liar. It is oauth2 not oauth.
Change it to oauth2.

Change oauth to oauth2 in scheme flag

---

.gitignore
circle.yml

No files were copied
copy the files

Copy chronoctl to current directory in circle.yml

---

ui/src/index.js

Closes #2793
Race conditions, man.

Wait until after authentication to match routes

---

ui/src/shared/components/DygraphLegend.js

Display series with 0 value in the legend

---

chronograf.go
filestore/kapacitors.go
filestore/sources.go
integrations/testdata/example.kap
server/sources.go

Fix/New sources CLI and Deprecation

---

influx/annotations.go
influx/annotations_test.go
influx/authorization.go
influx/influx.go
influx/influx_test.go
influx/lineprotocol.go
influx/lineprotocol_test.go
influx/now.go
mocks/response.go
server/annotations.go
server/annotations_test.go

Adding tests for annotations store

Annotation tests

---

CHANGELOG.md
server/dashboards.go
ui/src/dashboards/actions/index.js
ui/src/dashboards/containers/DashboardPage.js
ui/src/dashboards/reducers/ui.js

Save only selected template variable values in dashboard

---

CHANGELOG.md
server/cells.go
server/cells_test.go
server/dashboards_test.go

Resolves #2845 
The axes were not getting saved to the db when bounds was an empty array.
Change empty bounds from [] to ["", ""].

Y axis labels are maintained in Dashboard Cells

---

CHANGELOG.md
ui/src/shared/components/GaugeChart.js
ui/src/shared/components/LayoutCell.js
ui/src/shared/components/RefreshingGraph.js

Closes #2695 
- Resizing any cell in a dashboard causes any gauge type cell to think it is being resized
- Give gauges the ability to detect whether their parent cell is the one currently being resized

Fix Gauge Resizing Bug

---

CHANGELOG.md
server/sources.go

Connect #2854 
There's a typo and wrong url.
Typo is corrected and url excluded.

Update --new-sources log line

---

influx/templates.go
influx/templates_test.go
server/queries_test.go

Ensure backwards compat for old GROUP BY :interval:

---

ui/webpack/dev.config.js

Slimmer webpack output

---

ui/src/dashboards/components/AxesOptions.js
ui/src/dashboards/components/GaugeOptions.js
ui/src/dashboards/components/GraphOptionsCustomizableColumn.js
ui/src/dashboards/components/GraphOptionsCustomizeColumns.js
ui/src/dashboards/components/GraphOptionsSortBy.js
ui/src/dashboards/components/GraphOptionsTextWrapping.js
ui/src/dashboards/components/GraphOptionsThresholdColoring.js
ui/src/dashboards/components/GraphOptionsThresholds.js
ui/src/dashboards/components/GraphOptionsTimeAxis.js
ui/src/dashboards/components/GraphOptionsTimeFormat.js
ui/src/dashboards/components/SingleStatOptions.js
ui/src/dashboards/components/TableOptions.js
ui/src/dashboards/graphics/graph.js
ui/src/shared/components/InputClickToEdit.js
ui/src/shared/components/TableGraph.js
ui/src/style/chronograf.scss
ui/src/style/components/ceo-display-options.scss
ui/src/style/components/input-click-to-edit.scss
ui/src/style/components/table-graph.scss
ui/src/style/theme/_form-elements.scss

- Table graph controls need styles
- Visualization type selector needs SVG for table graphs

First Pass at Table Graph Styles

---

ui/src/kapacitor/containers/KapacitorPage.js

Fix url not being captured in kapacitor form

---

docs/auth.md

Connect #2946
Oauth documentation link was pointing to a page that no longer existed.
Update link.

Update oauth documentation link to non broken link

---

ui/package.json
ui/webpack/dev.config.js
ui/yarn.lock

you gotta `yarn install`
Connect #2954
No stacktrace
Much more helpful

Upgrade eslint-loader for linting error visibility

---

Makefile

https://facebook.github.io/jest/docs/en/cli.html#runinband
Connect #

Make js tests run faster in our CI process

---

ui/src/admin/containers/chronograf/AllUsersPage.js

Closes #2988 
Incorrect import of notification action
Fix the import

Fix import of notifications

---

ui/src/admin/containers/chronograf/AllUsersPage.tsx
ui/src/types/auth.tsx
ui/src/types/index.tsx
ui/test/admin/containers/chronograf/AllUsersPage.test.tsx
ui/test/resources.ts

Closes #2988 
This page had a simple import bug that was quickly resolved by fixing an import.  This would have been caught with the simplest of tests just asserting that the component rendered.
Convert the component to TypeScript and add first test for this component.

Conversion of AllUsersPage to TypeScript add initial test

---

ui/src/admin/components/chronograf/AllUsersTableRow.js
ui/src/admin/components/chronograf/ProvidersTable.js
ui/src/admin/components/chronograf/ProvidersTableRow.js
ui/src/admin/components/chronograf/ProvidersTableRowNew.tsx
ui/src/shared/components/Dropdown.js
ui/src/shared/components/DropdownHead.js
ui/src/shared/components/DropdownInput.js
ui/src/shared/components/Tags.js
ui/src/style/components/input-tag-list.scss
ui/src/style/theme/_tables.scss
ui/src/style/unsorted.scss

Closes #2986 
Closes #2951 
Closes #2813 
- Dashboard switching dropdown wraps text too much
- Tag list of organizations looks broken
- Delete button in `All Users` table says "Remove" and doesn't look urgent enough
- Provider mappings table alignment is off
- Fix the above

Misc. Polish

---

ui/src/dashboards/components/GraphOptionsFixFirstColumn.tsx
ui/test/dashboards/components/GraphOptionsFixFirstColumn.test.tsx

Style Fix First Column Table Option

---

ui/src/dashboards/components/GraphOptionsCustomizableColumn.tsx
ui/src/dashboards/components/GraphOptionsFixFirstColumn.tsx
ui/src/dashboards/components/GraphOptionsTimeFormat.tsx
ui/src/data_explorer/components/CustomCell.tsx
ui/src/kapacitor/components/KapacitorForm.tsx
ui/src/kapacitor/components/KapacitorFormInput.tsx
ui/src/shared/components/ConfirmButtons.tsx
ui/src/shared/components/DatabaseList.tsx
ui/src/shared/components/DatabaseListItem.tsx
ui/src/shared/components/InputClickToEdit.tsx
ui/src/shared/components/MeasurementList.tsx
ui/src/shared/components/MeasurementListFilter.tsx
ui/src/shared/components/MeasurementListItem.tsx
ui/src/shared/components/Tabs.tsx
ui/src/shared/components/TagList.tsx

Fix linter errors in some tsx files

---

ui/tslint.json

Update sorting rules

---

ui/package.json
ui/src/kapacitor/components/AlertOutputs.tsx
ui/tslint.json
ui/webpack/dev.config.js
ui/webpack/prod.config.js

Beauty is pain

---

ui/package.json

Remove progress from prod build

---

ui/src/dashboards/components/GraphOptionsCustomizableField.tsx
ui/src/dashboards/components/GraphOptionsCustomizeFields.tsx
ui/src/style/chronograf.scss
ui/src/style/components/ceo-display-options.scss
ui/src/style/components/customize-fields.scss
ui/test/dashboards/components/GraphOptionsCustomizeFields.test.tsx

Connect #1686  
- Moved styles for this component to own stylesheet `style/components/customize-fields`
- Made the entire label clickable for usability
- Added HTML `title` to each label with more explicit copy
- Using FancyScroll

Polish Customizable Fields UI

---

ui/src/dashboards/components/GraphOptionsFixFirstColumn.tsx

Connect #1686
https://github.com/influxdata/chronograf/issues/1686#issuecomment-375497409
- Changed copy to be "Lock"

Change "Fix First Column" to "Lock First Column"

---

ui/src/dashboards/components/GraphOptionsTimeFormat.tsx
ui/src/style/components/react-tooltips.scss

Connect #1686 
Clicking on the question mark in the Time Format label of Table Options in CEO did not take you to the link suggested.

Table Time Formatting guide link opens link

---

server/swagger.json

Update Swagger with Tables info

---

ui/src/dashboards/components/GraphOptionsTimeFormat.tsx
ui/src/dashboards/components/TableOptions.tsx
ui/src/shared/components/TableGraph.js
ui/src/shared/constants/tableGraph.js
ui/test/dashboards/components/GraphOptionsCustomizableField.test.tsx
ui/test/dashboards/components/GraphOptionsCustomizeFields.test.tsx
ui/test/dashboards/components/GraphOptionsFixFirstColumn.test.tsx
ui/test/dashboards/components/GraphOptionsSortBy.test.tsx
ui/test/dashboards/components/GraphOptionsTimeFormat.test.tsx
ui/test/dashboards/components/TableOptions.test.tsx
ui/test/shared/components/TableGraph.test.tsx
ui/test/utils/timeSeriesToDygraph.test.js

Connect #1686 
Table graph did not have test for important functionality
Tests were created and updated.

Table Graph tests

---

ui/src/shared/components/AnnotationTooltip.js

Connect #3081 
Annotation and legend format dates are different
Change it!

Change annotation date format to: YYYY/MM/DD

---

CHANGELOG.md
ui/src/dashboards/containers/DashboardPage.js
ui/src/shared/actions/annotations.js
ui/src/shared/apis/annotation.js

Support custom time range in annotations api wrapper

---

README.md

Some of the wording in the "From Source" installation instructions were unclear.
Reworded and restructured the steps to be a little clearer.

Update from source installation

---

CHANGELOG.md
ui/src/dashboards/actions/index.js

Connect #2950
When clicking edit on template variable once changes are not persisted
Adjust template variable values filtering to send proper data to chronograf api

Ensure that template variables always save

---

server/swagger.json

Related to #2123 
This PR provides updates to `swagger.json` for Chronograf 1.4.0.0/1.4.3.0 concepts, including the following:

Update Swagger for most multiorganization & multiuser changes

---

canned/cpu.json

We run quite a bit of nice’d processes along with kernel space load, this fixes the CPU usage charts to reflect actual utilization. 
See: https://github.com/influxdata/chronograf/issues/2430

Don't just base CPU on `user`

---

ui/src/dashboards/utils/templateVariableQueryGenerator.js

Surround temp var query params with quotes

---

.bumpversion.cfg
CHANGELOG.md
README.md
server/swagger.json
ui/package.json

Update for 1.4.3.1

---

ui/package.json
ui/src/CheckSources.tsx
ui/src/data_explorer/containers/DataExplorerPage.tsx
ui/tsconfig.json
ui/yarn.lock

Add @types/react-router to dev dependencies

---

CHANGELOG.md
kapacitor/client_test.go
kapacitor/triggers.go
server/kapacitors.go

- New rules default to a blank id
- Check for blank id before adding stateChangesOnly
Closes #2921

Only add stateChangesOnly to new rules

---

CHANGELOG.md
server/me.go

Requests to /me and deleting organization can result in a race condition
Closes #3091

If a org is missing then don't add it to list

---

CHANGELOG.md
ui/src/data_explorer/reducers/queryConfigs.js
ui/src/shared/components/MeasurementListItem.tsx
ui/src/shared/components/TagList.tsx
ui/src/shared/components/TagListItem.tsx
ui/test/shared/components/MeasurementList.test.tsx
ui/test/shared/components/MeasurementListItem.test.tsx

Applies to:
- Data Explorer
- CEO
Closes #

Allows users to close a measurement they have open

---

ui/src/shared/components/Dygraph.js

Fix legend sticking around when opening CEO

---

CHANGELOG.md
ui/src/admin/actions/influxdb.js
ui/src/shared/copy/notifications.js

Send notification when rp creation returns a failure

---

ui/src/alerts/components/AlertsTable.js
ui/src/alerts/containers/AlertsApp.js
ui/src/dashboards/components/AxesOptions.js
ui/src/dashboards/components/CellEditorOverlay.tsx
ui/src/dashboards/components/DashboardHeaderEdit.js
ui/src/dashboards/components/DashboardSwitcher.js
ui/src/dashboards/components/DashboardsPageContents.js
ui/src/dashboards/components/DisplayOptions.js
ui/src/dashboards/components/GaugeOptions.js
ui/src/dashboards/components/GraphOptionsCustomizableField.tsx
ui/src/dashboards/components/GraphOptionsTimeFormat.tsx
ui/src/dashboards/components/MeasurementDropdown.js
ui/src/dashboards/components/QueryTextArea.js
ui/src/dashboards/components/SingleStatOptions.js
ui/src/dashboards/components/TableOptions.tsx
ui/src/dashboards/components/TagKeyDropdown.js
ui/src/dashboards/components/Threshold.tsx
ui/src/dashboards/components/VisualizationName.js
ui/src/dashboards/components/template_variables/Row.js
ui/src/dashboards/containers/DashboardPage.js
ui/src/dashboards/containers/DashboardsPage.js

Add error handling to dashboard components

---

ui/src/data_explorer/components/FieldListItem.js
ui/src/data_explorer/components/QueryEditor.js
ui/src/data_explorer/components/QueryMakerTab.tsx
ui/src/data_explorer/components/Table.js
ui/src/data_explorer/components/Visualization.js
ui/src/data_explorer/components/WriteDataForm.js
ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/data_explorer/containers/DataExplorerPage.tsx
ui/src/hosts/components/HostRow.js
ui/src/hosts/components/HostsTable.js
ui/src/hosts/components/SearchBar.js
ui/src/hosts/containers/HostPage.js
ui/src/hosts/containers/HostsPage.js
ui/src/ifql/components/FuncArg.tsx
ui/src/ifql/components/FuncArgInput.tsx
ui/src/ifql/components/FuncArgs.tsx
ui/src/ifql/components/FuncListItem.tsx
ui/src/ifql/components/FuncNode.tsx
ui/src/ifql/components/FuncSelector.tsx
ui/src/ifql/components/TimeMachine.tsx
ui/src/ifql/components/TimeMachineEditor.tsx
ui/src/ifql/containers/IFQLPage.tsx

Data explorer error handling

---

ui/src/dashboards/components/TemplateControlDropdown.tsx
ui/src/dashboards/constants/templateControlBar.js
ui/src/shared/components/Dropdown.js
ui/src/shared/decorators/errors.tsx

Fixes adding template variables breaks dashboard

---

ui/src/dashboards/components/DashboardEmpty.tsx

Prevent users with permissions less than EDITOR from adding a new cell from the empty dashboard menu

Wrap DashboardEmpty with Authorized

---

ui/src/style/components/resizer.scss
ui/src/style/pages/dashboards.scss

Dots overflow outside draggable handle
Resizer has strange extra rectangle in background

Polish Some Small Details

---

ui/src/dashboards/components/GraphOptionsCustomizableField.tsx
ui/src/kapacitor/components/KapacitorForm.tsx
ui/src/kapacitor/components/KapacitorFormSkipVerify.tsx

Move KapacitorForm to class based component

---

ui/src/shared/decorators/errors.tsx

Show proper name for components with error handling

---

ui/src/CheckSources.tsx

Guard against missing me

---

ui/src/shared/decorators/errors.tsx

Creates decorator for custom error messages and swaps default error handling to use that with error component class. Also adds debugging flag to ensure that the error component is always rendered.

Extendable error handling

---

CHANGELOG.md
ui/src/kapacitor/apis/index.js

Fix base path for kapacitor logs

---

CHANGELOG.md
ui/src/shared/constants/colorOperations.js

Closes #3223
Change color when value is greater than or equal to a threshold
The way the UI handles thresholds is slightly unexpected
See above description

Improve Threshold UX

---

ui/src/dashboards/reducers/ui.js

Only update template variables that are not csv type

---

ui/src/shared/components/TableGraph.js

replace sortField and sortDirection everywhere

---

ui/src/shared/components/LineGraph.js

Fixes line graph data with strings errors

---

ui/src/dashboards/utils/tableGraph.ts

Return correct value in column for falsey data

---

ui/src/ifql/components/BodyBuilder.tsx
ui/src/ifql/components/ExpressionNode.tsx
ui/src/ifql/containers/IFQLPage.tsx
ui/src/style/components/func-node.scss

Brings feature parity back to CRUD for function nodes and adds support for variables.

Moar Variables

---

bolt/internal/internal.go
ui/src/shared/components/Layout.js
ui/src/shared/components/LayoutRenderer.js
ui/src/shared/components/RefreshingGraph.js

Fix backend defaults for decimal places

---

ui/src/dashboards/components/Threshold.tsx

Fixes inputting negative numbers from gauges

---

CHANGELOG.md
ui/src/dashboards/components/TemplateControlBar.tsx
ui/src/dashboards/components/TemplateControlDropdown.tsx
ui/src/dashboards/containers/DashboardPage.js
ui/test/dashboards/components/TemplateControlBar.test.tsx

Disable temp var dropdowns for viewers when auth enabled

---

CHANGELOG.md
ui/src/shared/components/Dygraph.js

Always populate ylabel on dygraph

---

ui/src/dashboards/components/TemplateControlDropdown.tsx

Fixes boolean logic for template var dropdowns

---

ui/src/utils/groupByTimeSeriesTransform.js

Closes #3387
Performance enhancements for group by

Prefer pushing to array over spread for speed

---

ui/src/shared/components/Tags.tsx

Fix delete confirmation copy for Tags in kapacitor configs

---

ui/src/ifql/components/BodyBuilder.tsx
ui/src/ifql/components/FuncArgsPreview.tsx
ui/src/ifql/components/FuncNode.tsx
ui/src/ifql/components/FuncSelector.tsx
ui/src/ifql/components/VariableName.tsx
ui/src/style/components/threesizer.scss
ui/src/style/components/time-machine/add-func-button.scss
ui/src/style/components/time-machine/ifql-builder.scss
ui/src/types/ifql.ts

Organize IFQL argument summaries and variable tooltips

---

CHANGELOG.md
kapacitor/client.go
server/kapacitors.go
ui/src/kapacitor/components/TasksTable.tsx
ui/src/kapacitor/containers/TickscriptPage.tsx

Fixes issue with saving tickscript name

---

ui/src/utils/wrappers.ts
ui/test/utils/wrappers.test.ts

Add wrapper for correctly typing the result of lodash get

Add typescript wrapper for lodash get

---

ui/src/alerts/containers/AlertsApp.tsx

Fix typo in AlertsApp componentsDidMount

---

ui/src/kapacitor/components/TasksTable.tsx

Fixes users disabling rules from tickscript table

---

ui/src/dashboards/components/DashboardSwitcher.js

Closes #3075
Quick select dropdown was not scrollable and now it is.

Wrap dashboard quick select with scrolling

---

CHANGELOG.md
ui/src/hosts/apis/index.js
ui/src/hosts/containers/HostPage.js

Improve query for host page to populate dropdown

---

ui/package.json
ui/src/data_explorer/components/Table.tsx
ui/yarn.lock

fixed-data-table is no longer maintained and was introducing
deprecation warnings on data explorer

Replace fixed-data-table with fixed-data-table-2

---

ui/src/dashboards/constants/index.ts
ui/src/dashboards/utils/tableGraph.ts
ui/src/shared/components/SingleStat.tsx
ui/src/shared/components/WidgetCell.tsx
ui/src/types/dashboard.ts
ui/src/types/query.ts

Closes #3472 
Also fixes missing cell types on WidgetCell.tsx

refactor: type remaining non-tempvar dashboard constants & fix CellType type errors

---

ui/src/dashboards/components/AxesOptions.js
ui/src/dashboards/components/GraphTypeSelector.js

Closes #3480 
A path for a constant was wrong. 
Fixed path

Correct paths to GRAPH_TYPES

---

ui/src/shared/components/CustomTimeIndicator.tsx

Check for query text in CustomTimeIndicator

---

kapacitor.go
ui/src/kapacitor/components/handlers/KafkaHandler.tsx
ui/src/kapacitor/constants/index.ts

Fixes topic saving for kafka handler

---

ui/src/CheckSources.tsx

Use get to find role

---

ui/src/ifql/components/TimeMachine.tsx
ui/src/shared/components/threesizer/Division.tsx
ui/src/shared/components/threesizer/DivisionMenu.tsx
ui/src/shared/constants/index.tsx
ui/src/style/components/threesizer.scss
ui/src/style/layout/page.scss

Vertical handles are now `20px` instead of `30px`

Shrink Threesizer Vertical Handles

---

ui/src/ifql/actions/index.ts
ui/src/ifql/apis/index.ts
ui/src/ifql/constants/editor.ts
ui/src/ifql/containers/IFQLPage.tsx
ui/src/ifql/reducers/script.ts
ui/src/localStorage.ts
ui/src/store/configureStore.js
ui/src/types/localStorage.ts
ui/src/types/services.ts
ui/test/ifql/containers/IFQLPage.test.tsx
ui/test/resources.ts

Co-authored-by: Andrew Watkins <andrew.watkinz@gmail.com>
Co-authored-by: Chris Henn <chris.henn@influxdata.com>

Persist ifql script

---

ui/src/logs/actions/index.ts

Fix import of get to getDeep

---

ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/logs/components/LogsGraphContainer.tsx
ui/src/logs/components/LogsTableContainer.tsx
ui/src/logs/containers/LogsPage.tsx
ui/src/side_nav/containers/SideNav.tsx
ui/src/style/chronograf.scss
ui/src/style/pages/logs-viewer.scss

I added scaffolding components for the graph and table containers as well as a stylesheet for the logs viewer page

Layout Scaffolding for Logs Viewer

---

CHANGELOG.md
ui/src/shared/apis/query.ts
ui/src/shared/components/AutoRefresh.tsx
ui/src/shared/components/Layout.js
ui/src/shared/components/LayoutCell.tsx
ui/src/shared/components/RefreshingGraph.js
ui/src/shared/constants/index.tsx
ui/src/types/dashboard.ts

Closes #1973
If there are template variables in CellTitle, the value of the template variable will be displayed instead of the template variable.

Template Variables in Cell Titles

---

ui/src/localStorage.ts
ui/src/logs/actions/index.ts
ui/src/logs/components/LogsTable.tsx
ui/src/logs/components/TimeRangeDropdown.tsx
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/reducers/index.ts
ui/src/logs/utils/index.ts
ui/src/types/localStorage.ts
ui/src/types/query.ts
ui/src/utils/wrappers.ts

Calculate bin size for log viewer

---

ui/src/logs/actions/index.ts
ui/src/logs/components/LogsSearchBar.tsx
ui/src/logs/components/LogsTable.tsx
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/reducers/index.ts
ui/src/logs/utils/index.ts
ui/src/style/pages/logs-viewer.scss
ui/src/types/localStorage.ts
ui/src/utils/influxql.ts

Implements basic log viewer search

---

ui/src/logs/actions/index.ts
ui/src/logs/components/LogsTable.tsx
ui/src/side_nav/containers/SideNav.tsx

Fixes fancy scrollbars in log viewer

---

ui/src/ifql/components/TableSidebar.tsx
ui/src/ifql/components/TimeMachineTable.tsx
ui/src/ifql/constants/vis.ts
ui/src/style/components/time-machine/visualization.scss

Enable filtering of Flux table sidebar

---

ui/src/logs/actions/index.ts
ui/src/logs/components/LogsFilter.tsx
ui/src/logs/components/LogsFilterBar.tsx
ui/src/logs/components/LogsTable.tsx
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/reducers/index.ts
ui/src/logs/utils/index.ts
ui/src/types/localStorage.ts
ui/src/types/logs.ts

Log viewer/filtering

---

ui/src/flux/components/BodyBuilder.tsx
ui/src/flux/components/FuncArgs.tsx
ui/src/flux/components/FuncArgsPreview.tsx
ui/src/flux/components/FuncNode.tsx
ui/src/flux/components/VariableName.tsx
ui/src/style/components/time-machine/add-func-button.scss
ui/src/style/components/time-machine/flux-builder.scss

Make Flux Builder Stack Vertically

---

ui/src/localStorage.ts
ui/src/logs/actions/index.ts
ui/src/logs/components/LogViewerHeader.tsx
ui/src/logs/components/LogsFilterBar.tsx
ui/src/logs/components/LogsSearchBar.tsx
ui/src/logs/components/LogsTable.tsx
ui/src/logs/components/QueryResults.tsx
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/reducers/index.ts
ui/src/logs/utils/index.ts
ui/src/style/pages/logs-viewer.scss
ui/src/types/logs.ts

Message column width changes with window size

---

ui/src/flux/components/FluxForm.tsx
ui/src/kapacitor/components/KapacitorFormInput.tsx

Fix misaligned kapacitor form

---

ui/src/side_nav/containers/SideNav.tsx

_Make Time Machine FQI again:_
Was not named FQI
Name it FQI

Update the name to fqi

---

ui/src/logs/actions/index.ts
ui/src/logs/components/LogsFilter.tsx
ui/src/logs/components/LogsTable.tsx
ui/src/logs/components/QueryResults.tsx
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/reducers/index.ts
ui/src/logs/utils/table.ts
ui/src/side_nav/containers/SideNav.tsx
ui/src/style/pages/logs-viewer.scss
ui/src/style/unsorted.scss
ui/src/types/logs.ts

Performance enhancements for log viewer

---

ui/src/logs/actions/index.ts

Select default telegraf database

---

CHANGELOG.md
ui/src/style/components/custom-time-range.scss

Closes #3561 
Arrow icons for changing month in date picker got garbled
use proper arrow icons and make other minor aesthetic adjustements

Fix Date Picker Icons

---

ui/src/flux/components/TimeMachine.tsx
ui/src/flux/components/TimeMachineVis.tsx
ui/src/flux/containers/FluxPage.tsx
ui/src/shared/components/threesizer/Division.tsx
ui/src/shared/components/threesizer/DivisionHeader.tsx
ui/src/shared/constants/index.tsx
ui/src/shared/copy/notifications.ts
ui/src/style/components/code-mirror/_time-machine.scss
ui/src/style/components/threesizer.scss
ui/src/style/components/time-machine/flux-explorer.scss
ui/src/style/components/time-machine/visualization.scss
ui/test/flux/components/TimeMachine.test.tsx

- Make `Threesizer` handles/headers not look janky when in horizontal mode
- Match background color of script panel with its scrollbars
- Style `yield` panel name in builder

Minor Flux Editor Polish

---

ui/src/style/components/query-editor.scss

I threw the baby out with the bathwater, but now the baby is back. The
bathwater is still gone though.

Fix Appearance of Text Area in CEO

---

ui/src/sources/components/ConnectionLink.tsx

Strip prefix for data source links

---

ui/src/tempVars/components/TemplateVariableEditor.tsx
ui/src/tempVars/constants/index.ts

Preserve template variable name when editing type

---

CHANGELOG.md
ui/src/style/components/table-graph.scss

Closes #3466 
Ascending arrows point up.
Descending arrows point down.

Change Ascending arrows to point up instead of down

---

chronograf.go
influx/templates.go
server/templates.go
server/templates_test.go
ui/src/dashboards/actions/index.ts
ui/src/dashboards/apis/index.js
ui/src/shared/parsing/showSeries.ts
ui/src/tempVars/components/MetaQueryTemplateBuilder.tsx
ui/src/tempVars/components/TemplateVariableEditor.tsx
ui/src/tempVars/constants/index.ts
ui/src/tempVars/utils/parsing.ts
ui/src/types/tempVars.ts

Add "Custom Meta Query" template variable type 

---

ui/src/tempVars/components/TemplateControlBar.tsx
ui/src/tempVars/components/TemplateControlDropdown.tsx
ui/test/tempVars/components/TemplateControlBar.test.tsx
ui/test/tempVars/components/TemplateControlDropdown.test.tsx

- Assert that clicking the "Add Template Variable" button shows the template variable editor
- Assert that clicking the settings icon for a template variable shows the template variable editor

Add two tests for template variables

---

ui/src/flux/components/FilterTagListItem.tsx

Fix filter popup aesthetics

---

ui/src/admin/containers/AdminInfluxDBPage.js
ui/src/hosts/containers/HostsPage.js
ui/src/shared/components/PageHeader.tsx
ui/test/admin/containers/AdminInfluxDBPage.test.tsx
ui/test/hosts/containers/HostsPage.test.tsx
ui/test/shared/components/PageHeader.test.tsx

Fix missing page titles

---

ui/src/admin/containers/chronograf/AdminChronografPage.js
ui/src/hosts/containers/HostsPage.js

Closes #3756 
PageHeader was not receiving the `titleText` prop in `AdminChronografPage`
Change `title` to `titleText`

Update title to titleText in Admin page

---

ui/src/shared/annotations/helpers.ts
ui/src/shared/components/Annotations.tsx
ui/src/shared/components/Dygraph.tsx
ui/src/shared/components/DygraphLegend.tsx
ui/src/shared/components/LayoutRenderer.js

Co-authored-by: Brandon Farmer <bthesorceror@gmail.com>
Closes #3711 
Lots of performance issues causing Chronograf to crash on dashboard page
A few small optimizations and removing some deep equals comparisons in a componentShouldUpdate() function

Fix dashboards crashing by making some performance optimizations

---

ui/src/side_nav/components/UserNavBlock.js
ui/src/style/layout/sidebar.scss

Make User Nav Icon Consistent

---

ui/src/index.template.html

Resurrect the Favicon

---

ui/src/logs/components/LogsTable.tsx
ui/src/logs/utils/table.ts

Handle case when log message is empty

---

ui/src/shared/apis/databases.ts

Provide empty namespace array on error fetching

---

CHANGELOG.md
ui/src/shared/components/Layout.js
ui/src/shared/components/LineGraph.js
ui/src/shared/components/RefreshingGraph.js
ui/src/shared/components/SingleStat.tsx
ui/src/shared/graphs/helpers.ts
ui/src/style/chronograf.scss
ui/src/style/components/dygraphs.scss
ui/src/style/components/single-stat.scss

Closes #2928 
Closes #3326 
Dynamically change single-stat font size from cell dimensions. Preserves existing Single Stat + Line behavior and styles.

Make Single Stat Responsive

---

ui/src/logs/actions/index.ts

Stub out log config requests till server work is done

---

ui/src/admin/containers/AdminInfluxDBPage.tsx
ui/src/admin/reducers/influxdb.js
ui/src/types/auth.ts
ui/src/types/index.ts
ui/src/types/notifications.ts
ui/src/types/sources.ts
ui/test/admin/containers/AdminInfluxDBPage.test.tsx
ui/test/fixtures/index.ts
ui/test/resources.ts

Closes #1791 
Closes #3578 
Does not display the "Roles" and "Users" tabs in the "InfluxDBAdmin" page if connected to an LDAP authenticated source.

Frontend LDAP integration

---

ui/src/logs/components/LogsFilter.tsx
ui/src/logs/components/LogsFilterBar.tsx
ui/src/logs/components/LogsTable.tsx
ui/src/style/pages/logs-viewer.scss

Small aesthetic changes: Filter blocks stack more nicely, severity text aligns with dot, easier to exit editing of filters

Logs page polish

---

ui/src/dashboards/components/AxesOptions.tsx
ui/src/dashboards/components/DisplayOptions.tsx
ui/src/dashboards/components/GraphOptionsDecimalPlaces.tsx
ui/src/dashboards/components/SingleStatOptions.tsx
ui/src/shared/components/LineGraph.tsx
ui/src/shared/components/RefreshingGraph.js
ui/src/shared/components/SingleStat.tsx

Decimal Places Single Stat

---

ui/src/logs/actions/index.ts
ui/src/logs/components/ColorDropdown.tsx
ui/src/logs/components/LogsTable.tsx
ui/src/logs/components/OptionsOverlay.tsx
ui/src/logs/components/SeverityOptions.tsx
ui/src/logs/constants/index.ts
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/reducers/index.ts
ui/src/logs/utils/colors.ts
ui/src/logs/utils/config.ts
ui/src/shared/components/HistogramChart.tsx
ui/src/shared/components/HistogramChartBars.tsx
ui/src/shared/components/HistogramChartTooltip.tsx
ui/src/types/histogram.ts
ui/src/types/logs.ts
ui/test/fixtures/index.ts
ui/test/logs/utils/config.test.ts
ui/test/shared/components/HistogramChart.test.tsx
ui/test/shared/components/__snapshots__/HistogramChart.test.tsx.snap

Closes #3713 
Use colors of severity column to set the colors of severity format dot and histogram bars

Logs viewer Configs - severity colors

---

ui/src/shared/components/LayoutCell.tsx

Closes #1973 
Replacement was using selected value instead of locally selected value. 
Use the locally selected value and not the default value for temp var replacement

Fix temp vars in title

---

chronograf.go
server/templates.go
ui/src/dashboards/containers/DashboardPage.tsx
ui/src/style/components/template-control-bar.scss
ui/src/tempVars/components/TemplateControl.tsx
ui/src/tempVars/components/TemplateControlBar.tsx
ui/src/tempVars/components/TemplateDropdown.tsx
ui/src/tempVars/components/TemplateVariableEditor.tsx
ui/src/tempVars/components/TextTemplateBuilder.tsx
ui/src/tempVars/components/TextTemplateSelector.tsx
ui/src/tempVars/constants/index.ts
ui/src/types/tempVars.ts
ui/test/tempVars/components/TemplateControl.test.tsx
ui/test/tempVars/components/TemplateControlBar.test.tsx
ui/test/tempVars/components/TextTemplateBuilder.test.tsx
ui/test/tempVars/components/TextTemplateSelector.test.tsx

Introduce new “text” template variable type

---

ui/src/logs/components/LogsFilter.tsx
ui/src/logs/utils/index.ts

Closes #3880
Add the ability to filter out with regex with the `!~` operator

Allow filtering out with regex in logs table

---

ui/src/logs/actions/index.ts
ui/src/logs/components/LogsTable.tsx
ui/src/logs/components/PointInTimeDropDown.tsx
ui/src/logs/components/TimeRangeDropdown.tsx
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/data/serverLogData.ts
ui/src/logs/data/timePoints.ts
ui/src/logs/reducers/index.ts
ui/src/logs/utils/index.ts
ui/src/logs/utils/table.ts
ui/src/shared/components/CustomSingularTime.tsx
ui/src/shared/components/CustomTimeRange.js
ui/src/shared/utils/time.ts
ui/src/types/logs.ts

Initial log viewer infinite scroll behaviour

---

ui/src/CheckSources.tsx

Bugfix: Notification on unconnected source

---

ui/src/localStorage.ts
ui/src/logs/containers/LogsPage.tsx

Add scroll reset and local storage defaults for log viewer

---

ui/src/dashboards/reducers/ui.ts
ui/src/dashboards/utils/tempVars.ts
ui/src/tempVars/components/TemplateControl.tsx
ui/src/tempVars/components/TextTemplateSelector.tsx
ui/test/tempVars/components/TextTemplateSelector.test.tsx

Closes #3913
Updating the text in the text template variable updated the db which caused an error if the user was a visitor.
Updating the text in the text template variable updates the locally selected value and the url param but does not overwrite the value in the db.

Fix viewers getting logged out when changing text temp var

---

ui/src/logs/actions/index.ts
ui/src/logs/components/LogsTable.tsx
ui/src/logs/containers/LogsPage.tsx

Fetch more when scrolling

---

ui/src/hosts/apis/index.js

Supply database to request for hosts

---

ui/src/hosts/containers/HostPage.js

Fix refreshing on HostPage

---

ui/src/dashboards/components/ImportDashboardOverlay.tsx
ui/src/shared/components/DragAndDrop.tsx
ui/src/tempVars/components/CSVTemplateBuilder.tsx
ui/src/tempVars/components/MapTemplateBuilder.tsx

Fix dismissal of overlay on uploading dashboards

---

ui/src/dashboards/containers/DashboardPage.tsx

Bugfix: Annotations not appearing until auto refresh tick

---

CHANGELOG.md
ui/src/logs/components/LiveUpdatingStatus.tsx
ui/src/logs/components/LogViewerHeader.tsx
ui/src/logs/containers/LogsPage.tsx

When play is press go to now in logs

---

ui/src/data_explorer/components/QueryEditor.tsx

Change UX of query submission and newlines

---

ui/src/flux/components/TableSidebar.tsx
ui/src/flux/components/TableSidebarItem.tsx
ui/src/shared/parsing/flux/response.ts
ui/src/types/flux.ts
ui/test/shared/parsing/flux/constants.ts
ui/test/shared/parsing/flux/results.test.ts

Change #partition to #group

---

Makefile
ui/package.json
ui/src/CheckSources.tsx
ui/src/dashboards/utils/tableGraph.ts
ui/src/flux/containers/CheckServices.tsx
ui/src/flux/containers/FluxPage.tsx
ui/src/shared/components/LineGraph.tsx
ui/test/kapacitor/containers/KapacitorPage.test.tsx
ui/yarn.lock

Closes #3996 
Our continuous integration process did not take JavaScript linting, TypeScript linting, and TypeScript errors into account.
Fail CI if any linter or TS errors occur.

Fail continuous integration upon JS & TS linter errors and TS check errors

---

platform_migrate.md

Adds documentation of how to migrate changes into platform.

Add documentation on how to migrate changes to platform

---

ui/src/logs/actions/index.ts
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/utils/index.ts
ui/src/logs/utils/table.ts

Log viewer/scroll performance

---

ui/src/logs/components/LogsFilterBar.tsx
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/utils/index.ts
ui/src/logs/utils/table.ts
ui/src/style/pages/logs-viewer.scss

Move histogram count to make it more clear

---

ui/src/logs/components/LogsTable.tsx
ui/src/logs/components/expandable_message/ExpandableMessage.tsx
ui/src/logs/containers/LogsPage.tsx

Pause log viewer when message is expanded

---

CHANGELOG.md
ui/src/style/components/graph.scss

Size laser spinners based on their container

---

ui/src/dashboards/components/DashboardHeader.tsx
ui/src/shared/components/TimeRangeDropdown.js

Store selected time in state on dashboard header

---

ui/src/reusable_ui/components/form_layout/Form.scss
ui/src/reusable_ui/components/form_layout/Form.tsx
ui/src/reusable_ui/components/form_layout/FormDivider.tsx
ui/src/reusable_ui/components/form_layout/FormElement.tsx
ui/src/reusable_ui/components/form_layout/FormElementError.tsx
ui/src/reusable_ui/components/form_layout/FormFooter.tsx
ui/src/reusable_ui/components/form_layout/FormHelpText.tsx
ui/src/reusable_ui/components/form_layout/FormLabel.tsx
ui/src/reusable_ui/types/index.ts
ui/src/sources/components/SourceForm.tsx

This PR is a subset of the work outlined in https://github.com/influxdata/chronograf/issues/3946
Provide a set of simple and modular components for making all our forms look consistent. Also laying the foundation for improved form validation throughout the UI.
To use the form layout components:
```
import Form from 'src/reusable_ui/components/form_layout/Form'
import {Columns} from 'src/reusable_ui/types'
<Form>
<Form.Element colsSM={Columns.Six} label="Username" >
// input goes here
</Form.Element>
<Form.Element colsSM={Columns.Six} label="Password" errorMessage="Password is incorrect" >
// input goes here
</Form.Element>
<Form.Footer>
// Submit button(s) go here
</Form.Footer>
</Form>
```
Available child components:
```
<Form> // establishes a grid
<Form.Element> // Used to wrap …
```

Reusable Form Layout Component Family

---

ui/src/reusable_ui/components/dropdowns/DropdownButton.scss

Cleaning up oversight from the Buttons PR

Fix Dropdown Buttons

---

ui/src/dashboards/components/DashboardHeader.tsx
ui/src/kapacitor/components/RuleGraph.tsx
ui/src/shared/components/Dygraph.tsx
ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/time_series/TimeSeries.tsx

Ensure spinners show up when date is changed

---

ui/src/reusable_ui/components/dropdowns/test/Dropdown.test.tsx

Closes https://github.com/influxdata/chronograf/issues/4074

Stub out console.error during test that raises error

---

ui/src/dashboards/actions/index.ts
ui/src/shared/copy/notifications.ts

Show error if invalid template variable value in query string

---

ui/src/logs/components/LogsTable.tsx
ui/src/logs/components/OptionsOverlay.tsx
ui/src/logs/constants/index.ts
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/reducers/index.ts
ui/src/logs/utils/config.ts
ui/src/logs/utils/table.ts
ui/src/style/pages/logs-viewer.scss
ui/src/types/logs.ts
ui/test/logs/utils/config.test.ts

Closes #3930 
Log lines should have an option to toggle truncation
Add an option in the Log viewer to toggle on and off truncation.

Add log viewer truncation option

---

ui/src/flux/components/FuncArgs.tsx
ui/src/flux/components/FuncNode.tsx

On filter element use current db from 'from' field

---

ui/src/sources/components/KapacitorStep.tsx

Add ability to update as well as create

Add ability to update as well as add on click of continue

---

ui/src/reusable_ui/components/wizard/WizardProgressBar.tsx
ui/src/sources/components/CompletionStep.tsx
ui/src/sources/components/ConnectionWizard.tsx
ui/src/sources/components/KapacitorDropdown.tsx
ui/src/sources/components/KapacitorStep.scss
ui/src/sources/components/KapacitorStep.tsx
ui/src/style/chronograf.scss

Kapacitor styling

---

ui/src/dashboards/components/DashboardHeader.tsx

Somehow did not push this commit to my previous PR #4164

Add tooltips to header buttons

---

ui/src/shared/components/AnnotationTagEditorLi.tsx
ui/src/style/components/annotation-editor.scss

Replace annotation tag editor equals sign with arrow

---

ui/src/dashboards/utils/tableGraph.ts
ui/src/shared/components/Layout.tsx
ui/src/shared/components/MultiGrid/MultiGrid.tsx
ui/src/shared/components/TableGraph.tsx

Refactor table graph and multi grid to remove unused functionality

---

CHANGELOG.md
ui/src/hosts/apis/index.js

Closes #4206
Scan only the latest shard by specifying a time range
Was not doing this
Do this

Check only the latest shard for host data

---

ui/src/shared/components/MultiGrid/MultiGrid.tsx

Fix hover time issues in table graph

---

CHANGELOG.md
ui/src/logs/components/LiveUpdatingStatus.tsx
ui/src/logs/components/LogViewerHeader.tsx
ui/src/logs/containers/LogsPage.tsx
ui/src/reusable_ui/components/Button/index.tsx
ui/src/style/pages/logs-viewer.scss
ui/src/types/logs.ts

Hard to tell which radio button is active when only 2 are present
Use a single button instead

Logs Single Play / Pause Button

---

ui/src/shared/components/MultiGrid/MultiGrid.tsx

Ensure that scrolling does not go out of bounds for table graph

---

ui/src/shared/components/MultiGrid/MultiGrid.tsx

- Handle scrolling after hover state has changed

Update state management for table graphs

---

chronograf.go
server/influx.go
server/influx_test.go
server/swagger.json
ui/src/data_explorer/components/Table.tsx
ui/src/shared/apis/query.ts
ui/src/shared/components/time_series/TimeSeries.tsx
ui/src/utils/queryUrlGenerator.ts

Pass uuid to proxy requests for determining which responses are relevant

---

CHANGELOG.md
ui/src/logs/components/LogsTable.tsx
ui/src/logs/components/expandable_message/ExpandableMessage.tsx
ui/src/logs/components/logs_message/LogsMessage.scss
ui/src/logs/components/logs_message/LogsMessage.tsx
ui/src/logs/containers/LogsPage.tsx
ui/src/shared/copy/notifications.ts
ui/src/style/chronograf.scss

Closes #4200 
A log message could not be quickly copied to the clipboard
Add a copy to clipboard button to untruncated log lines and expanded messages

Add copy for log messages

---

ui/src/reusable_ui/components/wizard/WizardButtonBar.scss
ui/src/reusable_ui/components/wizard/WizardController.scss
ui/src/reusable_ui/components/wizard/WizardFullScreen.scss
ui/src/reusable_ui/components/wizard/WizardProgressBar.scss
ui/src/reusable_ui/components/wizard/WizardStep.scss
ui/src/reusable_ui/components/wizard/WizardStep.tsx
ui/src/reusable_ui/components/wizard/test/WizardStep.test.tsx
ui/src/reusable_ui/components/wizard/test/__snapshots__/WizardStep.test.tsx.snap

Closes #4172
Fix issue with content not scrolling.
Refactor to remove fancy scrollbar till broader issues can be addressed.
Refactor to remove fancy scrollbar till broader issues with the plugin can be addressed.

Fix issue with wizard content not scrolling

---

ui/src/dashboards/containers/DashboardPage.tsx
ui/src/shared/actions/annotations.ts
ui/src/shared/components/AddAnnotationToggle.tsx
ui/src/shared/components/AnnotationControlBar.tsx
ui/src/shared/components/AnnotationsDisplaySettingDropdown.tsx
ui/src/shared/reducers/annotations.ts
ui/src/shared/selectors/annotations.ts
ui/src/style/components/annotation-control-bar.scss
ui/src/types/annotations.ts
ui/test/annotations/reducers/annotations.test.ts

Add ability to hide annotations

---

ui/src/shared/components/RefreshingGraph.tsx

Force timeseries update when visualization options change

---

ui/src/shared/components/RefreshingGraph.tsx

Don't force update time series when there are no time series (aka when the cell is a note)

Fix Note Cell Type Bug

---

ui/src/shared/components/AddAnnotationToggle.tsx
ui/src/shared/reducers/annotations.ts

Make add annotation button always enabled

---

ui/src/admin/actions/influxdb.js
ui/src/admin/components/QueryRow.js
ui/src/admin/containers/QueriesPage.js
ui/src/shared/apis/metaQuery.js
ui/src/shared/parsing/showQueries.js

Fix kill query UI on clustered InfluxDB

---

ui/src/dashboards/actions/index.ts
ui/src/dashboards/containers/DashboardPage.tsx
ui/src/dashboards/reducers/dashTimeV1.ts
ui/src/dashboards/selectors/index.tsx
ui/src/shared/actions/annotations.ts
ui/src/shared/components/AnnotationControlBar.tsx
ui/src/shared/components/AnnotationPoint.tsx
ui/src/shared/components/AnnotationTagsDropdown.tsx
ui/src/shared/components/AnnotationTooltip.tsx
ui/src/shared/copy/notifications.ts
ui/src/shared/data/timeRanges.ts
ui/src/style/components/annotations.scss

 Enable adding annotation tag filters via clicking

---

kapacitor/client.go

Closes #4289
This is the same fix as #942, just for for a Kapacitor client rather than a `http.Client`. 
Every Kapacitor client (`github.com/influxdata/kapacitor/client/v1`) instantiates its own `http.Transport`, unless one is provided. A `http.Transport` will cache socket connections for future use, which leaves connections open.
Chronograf creates a new Kapacitor client upon every request for several endpoints. Thus each time these endpoints were hit, new connections would be opened but never closed until Chronograf is shut down.
These changes pass a singleton `http.Transport` when creating new Kapacitor clients, so that connections are reused while Chronograf is running.

Fix leaking sockets in Kapacitor client

---

ui/src/dashboards/components/CellEditorOverlay.tsx
ui/src/shared/components/FillQuery.tsx
ui/src/shared/components/TimeMachine/TimeMachine.tsx

Allow CEO dropdowns to change queries

---

ui/src/shared/components/QueryTabList.tsx
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/style/components/query-maker.scss
ui/src/style/unsorted.scss

Shrink horizontal threesizer handle size. Shrink query maker tabs.

Polish DE/CEO

---

ui/src/dashboards/components/GraphOptionsTimeFormat.tsx
ui/src/dashboards/constants/index.ts
ui/src/dashboards/utils/tableGraph.ts
ui/test/dashboards/components/GraphOptionsTimeFormat.test.tsx

Add unix time formatting option to table graphs

---

ui/src/shared/components/MultiGrid/MultiGrid.tsx
ui/src/shared/components/TableGraph.tsx

Ensure that sorting indicators reflect sorted table

---

ui/src/shared/decorators/errors.tsx
ui/src/style/unsorted.scss

Enhance appearance of uncaught errors message

---

CHANGELOG.md

Changelog should be updated for 1.6.2 release
It wasn't
Make it so

Update changelog for 1.6.2 release

---

ui/src/dashboards/components/SourceSelector.tsx

Fix issue with hidden SourceSelector

---

ui/src/sources/components/InfluxTableRow.tsx
ui/src/sources/containers/ManageSources.tsx

Update ConnectionLink to reflect current default

---

CHANGELOG.md
ui/src/data_explorer/containers/DataExplorer.tsx

Allow flux scripts in query string for DE

---

ui/src/data_explorer/containers/DataExplorer.tsx

Duplicate service getters (with the same code) added to Data Explorer
Remove duplicate

Remove duplicate service getter from DE

---

ui/src/data_explorer/containers/DataExplorer.tsx

Remove duplicated getter for services

---

ui/src/flux/components/FluxGraph.tsx
ui/src/shared/components/LineGraph.tsx
ui/src/shared/parsing/flux/dygraph.ts
ui/src/shared/parsing/flux/response.ts
ui/src/types/flux.ts
ui/src/worker/JobManager.ts
ui/src/worker/jobs/fluxTablesToDygraph.ts
ui/src/worker/worker.ts
ui/test/shared/parsing/flux/constants.ts
ui/test/shared/parsing/flux/dygraph.test.ts

Closes https://github.com/influxdata/applications-team-issues/issues/64
Update the way we are parsing the flux tables to dygraph and move this into a web worker job.

Update flux dygraph parsing

---

ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/shared/components/TimeMachine/TimeMachine.tsx

Ensure that flux cells have correct type

---

CHANGELOG.md
ui/src/flux/components/BodyBuilder.tsx
ui/src/flux/components/ExpressionNode.tsx
ui/src/flux/components/FuncArg.tsx
ui/src/flux/components/FuncArgs.tsx
ui/src/flux/components/FuncNode.tsx
ui/src/flux/components/FuncSelector.tsx
ui/test/flux/components/FuncArg.test.tsx
ui/test/flux/components/FuncSelector.test.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/73

Maintain focus on Flux Editor text area when adding nodes via code

---

ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/data_explorer/reducers/queries.ts
ui/src/flux/components/FuncArgs.tsx
ui/src/flux/constants/editor.ts
ui/src/tempVars/utils/replace.ts

- Remove unused build button
- Handle missing `query` query param
- Better default for queryDrafts

Fix various errors with data explorer

---

ui/src/shared/components/InvalidData.tsx
ui/src/shared/decorators/errors.tsx

Add stack traces to issues created on error

---

ui/src/flux/components/BodyBuilder.tsx
ui/src/flux/components/FluxQueryBuilder.tsx
ui/src/flux/components/FuncArgsPreview.tsx
ui/src/flux/helpers/scriptBuilder.ts
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/style/components/time-machine/flux-builder.scss

Closes #4465
- Addresses some of the issues in #4465—I'll open up issues for the remaining bits
- Also does some general clean up
See commits for details.

Flux builder fixes

---

ui/src/flux/apis/index.ts
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/shared/components/time_series/TimeSeries.tsx
ui/src/utils/ajax.ts

Only query flux when done typing and valid ast

---

ui/src/dashboards/utils/tableGraph.ts
ui/src/shared/components/GaugeChart.tsx
ui/src/shared/components/LineGraph.tsx
ui/src/shared/components/SingleStat.tsx
ui/src/shared/components/TableGraph.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/86
Table assumed there would always be a time field in the table causing data without time to have a column where all values became `InvalidDate`. Other vis types would show a spinner forever if there was no time.
Update table to not assume there is always time. And show invalid data state for other vis types.

Update Vis Types to not assume there is always a time

---

server/flux.go
ui/src/flux/apis/index.ts
ui/src/flux/helpers/scriptBuilder.ts

Display more error information in flux editor

---

ui/src/shared/components/LineGraph.tsx
ui/src/shared/components/RefreshingGraph.tsx

Check response uuid for updating linegraph

---

ui/src/flux/ast/walker.ts
ui/src/flux/components/TimeMachineEditor.tsx

Properly handle negative numbers in flux

---

ui/src/dashboards/utils/cellGetters.ts
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/shared/copy/notifications.ts
ui/src/shared/utils/TimeMachineContainer.ts
ui/yarn.lock

Closes https://github.com/influxdata/applications-team-issues/issues/91
This removes some legacy cruft concerning query strings and their associated query configs.

Fix issue with unwanted template var replacement

---

ui/src/shared/parsing/flux/dygraph.ts

Enable changing vis colors for Flux queries

---

ui/src/style/components/query-maker.scss
ui/src/style/components/source-selector.scss
ui/src/style/unsorted.scss

Tighten up DE/CEO padding and alignment

---

ui/src/flux/components/TableSidebar.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/108

Fix inability to select Flux table from sidebar

---

ui/src/dashboards/components/CellEditorOverlay.tsx
ui/src/dashboards/containers/DashboardPage.tsx
ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/data_explorer/containers/DataExplorerPage.tsx
ui/src/index.tsx
ui/src/shared/utils/TimeMachineContainer.ts
ui/src/shared/utils/localStorage.ts
ui/test/shared/utils/TimeMachineContainer.test.ts

- Fixes a runtime error that prevents users from adding a cell to a dashboard.
- Cleans up our general approach towards unstated `Provider` / `Subscribe`ers in the DE and CEO

Remove explicit injection of TimeMachineContainer

---

ui/src/reusable_ui/components/card_select/CardSelectCard.scss
ui/src/reusable_ui/components/card_select/ProtoboardIcon.scss
ui/src/reusable_ui/components/card_select/ProtoboardIcon.tsx
ui/src/reusable_ui/components/wizard/WizardController.scss

Hovering on Dashboard selection cards would cause the whole page to jitter. 
Fixed css things with @alexpaxton

Fix the jitters

---

ui/src/shared/graphs/helpers.ts

Check if time ranges are different

---

ui/src/flux/constants/builder.ts
ui/src/flux/helpers/scriptBuilder.ts
ui/src/shared/components/TimeMachine/FluxQueryMaker.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/95
Default from script required you to take actions instead of using the connected source's defaults.
Use defaults

Update default from script

---

ui/src/status/actions/index.ts
ui/src/status/apis/index.ts

Handle cors feed request with fetch api

---

ui/src/dashboards/components/CellEditorOverlay.tsx

you had to change and submit a query in order to save a cell
always allow flux cell to be saved

Allow Flux query cell to always be saved

---

ui/src/reusable_ui/components/wizard/WizardFullScreen.scss
ui/src/reusable_ui/components/wizard/WizardFullScreen.tsx
ui/src/reusable_ui/components/wizard/WizardStep.scss
ui/src/reusable_ui/components/wizard/test/WizardFullScreen.test.tsx
ui/src/reusable_ui/components/wizard/test/__snapshots__/WizardFullScreen.test.tsx.snap
ui/src/sources/components/WelcomeStep.scss
ui/src/sources/components/WelcomeStep.tsx
ui/src/sources/containers/OnboardingWizard.tsx
ui/src/style/chronograf.scss

Closes influxdata/applications-team-issues#146
Closes influxdata/applications-team-issues#147
Closes influxdata/applications-team-issues#148
Closes influxdata/applications-team-issues#154
Removes icon and header from top of all wizard cards and changes copy in footer.
Fixes styling on screens with limited vertical space.
Adds Welcome step.
Removes skip button from final step.

Onboarding updates

---

ui/src/reusable_ui/components/card_select/CardSelectCard.scss
ui/src/reusable_ui/components/card_select/ProtoboardIcon.scss
ui/src/reusable_ui/components/wizard/WizardController.tsx
ui/src/reusable_ui/components/wizard/WizardFullScreen.scss
ui/src/reusable_ui/components/wizard/WizardStep.scss
ui/src/reusable_ui/components/wizard/test/__snapshots__/WizardController.test.tsx.snap
ui/src/sources/components/ConnectionWizard.tsx
ui/src/sources/components/DashboardStep.scss
ui/src/sources/components/DashboardStep.tsx
ui/src/sources/components/WelcomeStep.scss
ui/src/sources/containers/OnboardingWizard.tsx

Closes influxdata/applications-team-issues/issues/#149
Closes influxdata/applications-team-issues/issues/#151
Closes influxdata/applications-team-issues/issues/#153
Closes influxdata/applications-team-issues/issues/#153
Closes influxdata/chronograf/issues/#4581
Correct color of protoboard cards to be different from background.
Make protoboard icons larger, move text up within card.
Remove "Suggest Dashboards" button. Automatically suggest dashboards.
Count number of selected dashboards in next button.
Change skip link to go to completion step instead of exiting wizard.

Protoboard wizard updates

---

ui/src/kapacitor/components/RuleGraph.tsx
ui/src/shared/components/AutoRefresh.tsx
ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/time_series/TimeSeries.tsx

Closes application-team-issues#141
- Time range changes now reloads graph in flux editor

Refactor TimeSeries Component to simplify refresh

---

ui/src/shared/components/MeasurementList.tsx

Closes https://github.com/influxdata/chronograf/issues/4582

Just let browser handle remembering the scroll

---

ui/src/dashboards/actions/index.ts

Match by key when tempvar is a map type

---

CHANGELOG.md
ui/src/utils/influxql.ts

Fix issue with disappearing alias'

---

ui/src/shared/utils/TimeMachineContainer.ts

Closes: https://github.com/influxdata/applications-team-issues/issues/165
Previously, when the user had no queries in the Data Explorer, they would be shown a page reading "add a query" with a button to do so. Instead, we wanted them to open the Data Explorer to an empty query. 
In the reset function of `TimeMachineContainer`, we check if the queryDrafts in local storage are empty. If so, we set the queryDrafts to be an array containing one default query draft.

Add a default query draft if the query drafts are empty

---

ui/src/shared/components/Dygraph.tsx

Closes influxdata/applications-team-issues#195

Fix static legend overlap

---

ui/src/dashboards/components/DisplayOptions.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/205
previous changes to the threesizer meant that on resize was now required
add an on resize handler and store sizes
Note this does not store the size in local storage. It will reset every time.

Fix visops error on resize

---

ui/src/shared/components/TimeMachine/FluxQueryMaker.tsx

Closes https://github.com/influxdata/chronograf/issues/4623

Replace Script wizard text with large blue button

---

ui/src/logs/components/LogsTable.tsx
ui/src/style/pages/logs-viewer.scss

Closes https://github.com/influxdata/applications-team-issues/issues/183
Remove mouse over for currentRow tracking
Setting state on each cell mouseover caused many renders
Remove the currentRow state and mouseover handling

Improve logs table rendering

---

ui/src/flux/components/TimeMachineEditor.tsx
ui/src/flux/helpers/autoComplete.ts
ui/src/shared/components/TimeMachine/FluxQueryMaker.tsx
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/shared/components/threesizer/Division.tsx
ui/src/shared/components/threesizer/Threesizer.tsx
ui/src/style/components/time-machine/flux-editor.scss

Closes influxdata/applications-team-issues#209
Closes #4618
See commits.

Miscellaneous Flux bugfixes 

---

ui/src/dashboards/components/CellEditorOverlay.tsx
ui/src/dashboards/components/SourceSelector.tsx
ui/src/data_explorer/components/DEHeader.tsx
ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/shared/components/TimeMachine/FluxQueryMaker.tsx
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/shared/utils/TimeMachineContainer.ts

Closes https://github.com/influxdata/applications-team-issues/issues/216
Closes https://github.com/influxdata/applications-team-issues/issues/217

Flux tweaks

---

ui/src/shared/components/Dygraph.tsx
ui/src/shared/components/NewAnnotation.tsx

Closes influxdata/applications-team-issues#221
Closes influxdata/applications-team-issues#212

Two plot bugfixes

---

ui/package.json
ui/src/shared/actions/sources.ts

Closes https://github.com/influxdata/applications-team-issues/issues/219

Remove source immediately rather than wait for reload

---

ui/src/sources/containers/OnboardingWizard.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/224

Fix switch organization in onboarding

---

ui/src/shared/actions/sources.ts
ui/src/shared/apis/flux/query.ts

Closes https://github.com/influxdata/chronograf/issues/4637
Flux was only checking for db version and whether or not it was enterprise.
Execute flux query to see if the flux not enabled response status (403) comes back. Also, remove the check for enterprise since flux will be allowed there.

Update flux detection by adding check for flux-enabled

---

ui/src/shared/utils/TimeMachineContainer.ts

Flip the starting proportions for flux since the order of the panels changed.

Update default flux proportions

---

ui/src/shared/components/DygraphLegend.tsx
ui/src/shared/graphs/helpers.ts

Closes https://github.com/influxdata/applications-team-issues/issues/213

Properly calculate min and max X value for legend

---

ui/src/shared/components/Crosshair.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/188

Only show crosshair when in dygraph timerange

---

ui/src/flux/helpers/templates.ts
ui/src/shared/components/TimeMachine/FluxScriptWizard.scss
ui/src/shared/components/TimeMachine/FluxScriptWizard.tsx
ui/src/shared/constants/fluxScriptWizard.ts
ui/src/shared/utils/fluxScriptWizard.ts

Closes influxdata/applications-team-issues#218
Closes influxdata/applications-team-issues#227

Add aggregation dropdown to Script Wizard

---

canned/mongodb.json

fix(canned_dash): switch page_faults to commands

---

ui/src/shared/apis/query.ts
ui/src/shared/utils/downloadTimeseriesCSV.ts

Closes influxdata/applications-team-issues#229
Fixes a regression introduced in #4652.

Fix InfluxQL CSV export

---

ui/src/flux/components/DatabaseListItem.tsx
ui/src/flux/components/FieldList.tsx
ui/src/flux/components/FieldListItem.tsx
ui/src/flux/components/MeasurementList.tsx
ui/src/flux/components/MeasurementListItem.tsx
ui/src/flux/components/SchemaItemCategory.tsx
ui/src/flux/components/TagKeyList.tsx
ui/src/flux/components/TagKeyListItem.tsx
ui/src/flux/components/TagValueList.tsx
ui/src/flux/components/TagValueListItem.tsx
ui/src/shared/utils/TimeMachineContainer.ts
ui/src/style/components/time-machine/flux-explorer.scss

Add filter button in flux schema explorer

---

ui/src/shared/components/Layout.tsx
ui/src/shared/components/LayoutCell.tsx
ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/time_series/TimeSeries.tsx
ui/src/shared/utils/downloadTimeseriesCSV.ts

Closes influxdata/applications-team-issues#232

Enable downloading CSV data from Flux cells

---

ui/src/flux/constants/functions.ts

Add more functions to Flux Functions Toolbar

Add new functions to toolbar

---

ui/src/shared/components/Layout.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/230
We were getting the raw data, but never telling refreshing graph to use it.
If vistype is table, show raw data.

Fix show raw data in dashboard cell

---

ui/src/shared/components/threesizer/Division.tsx
ui/src/shared/components/threesizer/DivisionHeader.tsx
ui/src/shared/components/threesizer/Threesizer.tsx

Closes influxdata/applications-team-issues#242

Add option to reset Threesizer

---

ui/src/shared/apis/databases.ts

show databases you have rights to

Fetch retention policies individually

---

ui/src/flux/components/flux_functions_toolbar/FluxFunctionsToolbar.scss
ui/src/flux/components/flux_functions_toolbar/FluxFunctionsToolbar.tsx
ui/src/flux/components/flux_functions_toolbar/FunctionTooltip.tsx
ui/src/flux/components/flux_functions_toolbar/SearchBar.tsx
ui/src/flux/components/flux_functions_toolbar/ToolbarFunction.tsx
ui/src/flux/components/flux_functions_toolbar/TooltipLink.tsx
ui/src/flux/components/flux_functions_toolbar/TransformToolbarFunctions.tsx
ui/src/flux/constants/functions.ts
ui/src/shared/components/TimeMachine/FluxQueryMaker.tsx

Closes #influxdata/applications-team-issues/issues/236
Closes #influxdata/applications-team-issues/issues/237
Closes #influxdata/applications-team-issues/issues/244
Closes #influxdata/applications-team-issues/issues/246
Change titles of Threesizer columns
Add search bar to filter functions
Fix issue where clicking the tooltip added the function to script
Change Text for documentation link
Add new functions provided from docs
Fix issue where caret and tooltip were misaligned
This PR replaces #4720

Flux toolbar search

---

ui/src/flux/components/flux_functions_toolbar/FluxFunctionsToolbar.tsx
ui/src/flux/components/flux_functions_toolbar/FunctionCategory.tsx
ui/src/flux/components/flux_functions_toolbar/ToolbarFunction.tsx

Closes #4737
Disconnected the mapped components from unstated and provided connected state only to the toolbar itself.
The threesizer resized slowly
disconnect the mapped components to speed up re-render

Fix Slow Threesizer

---

ui/src/shared/apis/flux/metaQueries.ts

Closes influxdata/applications-team-issues#233
Also see influxdata/platform#1304

Fix Flux tag keys metaquery

---

ui/src/flux/components/FluxScriptEditor.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/228

Properly handle update script in code mirror

---

etc/build.py

Closes https://github.com/influxdata/applications-team-issues/issues/262

Add protoboards to build script

---

CHANGELOG.md
ui/src/logs/actions/index.ts
ui/src/logs/api/index.ts
ui/src/logs/components/loading_status/LoadingStatus.tsx
ui/src/logs/containers/LogsPage.tsx
ui/src/types/logs.ts

Closes https://github.com/influxdata/applications-team-issues/issues/249
Add loading status for missing syslog measurement
Syslog measurements could be missing for a selected source and namespace and logs searching would be attempted unnecessarily
Check source and namespace have a syslog measurement

Add missing measurement status

---

ui/src/shared/components/Dygraph.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/263

Make sure dygraph is available to resize

---

ui/src/flux/components/FluxScriptEditor.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/264
clicking to add was not updating script any more, this was due to multiple sources of truth in fluxscript editor

Fix click to add for flux functions

---

ui/src/shared/components/Dygraph.tsx

Ensure resizable element has a parent in dygraph component

---

ui/src/data_explorer/constants/index.ts

Closes influxdata/applications-team-issues#243

Add cardinality metaquery templates to dropdown

---

CHANGELOG.md
etc/scripts/chronograf.service
etc/scripts/init.sh

Add protoboards environment variables to build

---

CHANGELOG.md
Dockerfile

Update dockerfile for protoboards

---

CHANGELOG.md
Dockerfile

Add PROTOBOARDS_PATH to dockerfile

---

CHANGELOG.md
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/utils/fetchUntil.ts
ui/src/types/logs.ts

Fix hide scroll loading indicator

---

CHANGELOG.md
ui/src/shared/components/TimeMachine/TimeMachine.tsx
ui/src/shared/components/TimeMachine/TimeMachineControls.tsx
ui/src/style/unsorted.scss

adds back ability to manually refresh when paused

fix(de): show manual refresh if paused

---

protoboards/apache.json
protoboards/kubernetes_node.json
protoboards/kubernetes_overview.json
protoboards/kubernetes_pod.json
protoboards/mysql.json
protoboards/system.json
protoboards/vmware_vsphere_cluster_overview.json
protoboards/vmware_vsphere_cluster_vms.json
protoboards/vmware_vsphere_hosts.json

Remove hardcoded database/retention period from protoboards

---

CHANGELOG.md
server/mux.go
ui/src/flux/constants/functions.ts
ui/src/utils/basepath.ts

Handle basepath issue with missing slash

---

canned/ping.json

Closes #4793
Briefly describe your proposed changes:
What was the problem?
What was the solution?

Fix ping canned dashboard

---

CHANGELOG.md

No changelog entry for 4798
There wasn't one
Add one

Add changelog entry for pr 4798

---

protoboards/docker.json
protoboards/elasticsearch.json
protoboards/influxdb.json
protoboards/ping.json
protoboards/postgresql.json
protoboards/rabbitmq.json
protoboards/varnish.json

Update docker, influxdb and postresql protoboards

---

ui/src/dashboards/utils/tableGraph.ts
ui/src/shared/components/RefreshingGraph.tsx
ui/src/shared/components/TableGraph.tsx

Fix issue with UUIDs in table graph, fix issue with cell notes momentarily displaying

---

CHANGELOG.md
ui/src/flux/constants/functions.ts

Update flux functions

---

ui/.npmrc

Remove .npmrc file

---

CHANGELOG.md
ui/src/shared/components/RefreshingGraph.tsx

Provide a default for type and data in RefreshingGraph

---

kapacitor/client_test.go
kapacitor/tickscripts_test.go
kapacitor/vars.go

Provide valid characters for idVar with Sensu

---

CHANGELOG.md
ui/src/shared/components/TimeMachine/FluxScriptWizard.scss

Improve display of Flux Wizard on small screens

---

ui/src/shared/decorators/errors.tsx

Closes https://github.com/influxdata/applications-team-issues/issues/279

Update the error issue template with questions

---

.bumpversion.cfg
CHANGELOG.md
Makefile
server/swagger.json
ui/package.json
ui/src/admin/components/DatabaseRow.js
ui/src/admin/components/DatabaseTable.js
ui/src/flux/constants/functions.ts

Review changelog and cherry pick changes
----

Fix 1.7.x changelog

---

.bumpversion.cfg
CHANGELOG.md
Makefile
server/swagger.json
ui/package.json

Update ui version to 1.7.4
Updates master to reflect changes from 1.7.x https://github.com/influxdata/chronograf/pull/4882/commits/951b585aa1ed81a5ac47a48feca07749012d6df1

Update version to 1.7.4

---

ui/package.json

fix: update chronograf version to 1.7.6

---

CHANGELOG.md
ui/src/flux/constants/functions.ts

updating functions for flux 0.12

---

ui/src/shared/apis/flux/metaQueries.ts
ui/src/shared/utils/fluxScriptWizard.ts

Fix meta query group calls

---

server/flux.go

Use JWT in enterprise for authentication

---

CHANGELOG.md
ui/src/shared/apis/metaQuery.js

Escape injected meta query values

---

CHANGELOG.md
ui/src/dashboards/components/ReactCodeMirror.tsx
ui/src/flux/helpers/templates.ts
ui/src/shared/apis/query.ts
ui/src/shared/components/time_series/TimeSeries.tsx
ui/src/shared/constants/index.ts
ui/src/shared/parsing/flux/durations.ts
ui/src/shared/utils/downloadTimeseriesCSV.ts
ui/src/tempVars/utils/replace.ts
ui/test/shared/parsing/flux/durations.ts
ui/test/tempVars/utils/replace.test.ts

- backport logic from v2 line
Closes #5070

Be less aggressive on windowInterval

---

README.md

Fixed versions and links in readme

---

CHANGELOG.md
ui/src/flux/constants/functions.ts

Closes https://github.com/influxdata/chronograf/issues/5082

Fixed the window function

---

ui/package.json

Update chronograf version number

---

ui/src/flux/components/flux_functions_toolbar/FluxFunctionsToolbar.tsx
ui/src/flux/components/flux_functions_toolbar/FunctionCategory.tsx
ui/src/flux/components/flux_functions_toolbar/ToolbarFunction.tsx
ui/src/flux/constants/functions.ts
ui/src/flux/constants/index.ts
ui/src/flux/helpers/suggestions.ts

fix(flux/ui): fix union

---

CHANGELOG.md
ui/src/style/components/code-mirror/_time-machine.scss

Connect https://github.com/influxdata/influxdb/issues/12503

Fix scrollbars from overlaying flux editor text

---

ui/src/worker/jobs/get.ts
ui/src/worker/jobs/proxy.ts

If one user created a dashboard then another user with admin permissions was unable to open to open that dashboard. The request for fetch from database was failing in Safari.
Using Axios instead of fetch for the request on get and proxy which fixes displaying dashboard on Safari.

Fix dashboard to display for another user

---

CONTRIBUTING.md

change google groups link to community

---

CHANGELOG.md

Updated changelog for 1.7.9

---

ui/src/flux/helpers/templates.ts
ui/src/shared/parsing/flux/extractImports.ts

fix: imports in flux scripts

---

CHANGELOG.md

Updated changelog for 1.7.10

---

CHANGELOG.md
ui/package.json

bump version

---

ui/src/worker/worker.ts

- Addresses issues when workers are running in IE11

Add polyfill for workers

---

ui/src/dashboards/actions/index.ts
ui/src/dashboards/containers/DashboardPage.tsx

Properly handle time selection when zoomed in

---

ui/src/flux/components/FluxScriptEditor.tsx
ui/src/reusable_ui/components/form_layout/Form.tsx
ui/src/reusable_ui/components/panel/Panel.tsx
ui/src/shared/components/LayoutCell.tsx
ui/src/shared/parsing/diskBytes.js

Be more defensive where we split text from responses

---

Makefile
README.md

Update chronograf version to 1.7.11

---

ui/src/dashboards/components/AxesOptions.tsx

Allow values for min to be negative

---

ui/src/kapacitor/components/AlertTabs.tsx

chore: fix PagerDuty deprecation message

---

ui/src/dashboards/components/DashboardHeader.tsx
ui/src/dashboards/containers/DashboardPage.tsx

feat(dashboards): add time zone toggle

---

.github/stale.yml

fixing the closeComment
Closes #

Updating stale.yml

---

.github/stale.yml

changing staleLabel to stale

---

canned/influxdb_database.json

fix(canned): group by database for numSeries and numMeasurment queries

---

CHANGELOG.md
protoboards/mysql.json
protoboards/postgresql.json
protoboards/system.json

Changed recieved for received.

Fix dashboard typos

---

docs/slides/mnGo/Makefile

Cleaning up gdm references in several repos.

chore: remove gdm

---

.circleci/config.yml
CHANGELOG.md
etc/Dockerfile_build

Closes #5302
Closes #5285
* Update dockerfile's dependencies:
* Update the linux version to ~current lts~ bionic
* Update node to 12.13.0
* Update golang to 1.12.10
* Update some install commands in dockerfile

chore: update chronograf dependencies

---

ui/src/utils/influxql.ts
ui/test/utils/influxql.test.ts

fix: boolean joins for tag key / value pairs

---

CHANGELOG.md
ui/src/flux/components/flux_functions_toolbar/FluxFunctionsToolbar.tsx
ui/src/flux/components/flux_functions_toolbar/FunctionCategory.tsx
ui/src/flux/components/flux_functions_toolbar/ToolbarFunction.tsx
ui/src/flux/constants/functions.ts
ui/src/flux/helpers/scriptInsertion.ts
ui/src/shared/components/TimeMachine/FluxQueryMaker.tsx
ui/src/types/flux.ts

This updates the flux functions list and also the logic for inserting the functions to support import packages.
Closes #

feat(flux): updated functions list for latest flux

---

cmd/chronoctl/migrate.go

feat: add note to migrate command about id generation

---

cmd/chronoctl/migrate.go

fix: fail if migrating from non-existant boltdb

---

Makefile

Closes https://github.com/influxdata/chronograf/issues/5396
Signed-off-by: Matthew McGinn <mamcgi@gmail.com>
Closes #

build: fix up Makefile variable quoting for build

---

cmd/chronoctl/token.go

Closes #5418
This pr adds the cli flag option `-k` or `--skip-verify` to `chronoctl token`, allowing `chronoctl` to generate a token for a chronograf running with self-signed, or otherwise "insecure", TLS certs.

fix(chronoctl): allow token generation against self-signed api

---

CHANGELOG.md
ui/src/flux/constants/functions.ts

feat(fluxFunctions): updates for latest flux lib

---

ui/src/flux/constants/functions.ts

fix(fluxFunctions): updated for flux v65

---

dist/dist.go

All recommendations of https://qualys-secure.force.com/discussions/s/question/0D52L00004TnvvaSAB/how-to-resolve-qid11827 are addressed in this PR.

fix(ui): add HTTP security headers

---

cmd/chronoctl/migrate.go

Closes #5573 
User migration was not fully implemented, this pr finishes that implementation.

fix(chronoctl): migrate users also

---

CHANGELOG.md
ui/src/shared/constants/index.ts

fix(ui): disable default dashboard auto refresh

---

CHANGELOG.md

updates 1.8.9 Changelog
#5610 #5611 #5612 #5613 #5616 #5618 #5619

chore: 1.8.9 changelog [ci skip]

---

CHANGELOG.md
dist/dist.go

fix(windows): programtically assign text/javascript content type

---

.circleci/config.yml
etc/build.py
etc/scripts/docker/run.sh

Closes #5405
A build script is repaired according to https://github.com/golang/go/issues/20127

fix(build): repair ARM v5 build

---

ui/src/logs/containers/LogsPage.tsx

Closes #5629 
The code was changed to stop async executions after LogsPage is destroyed.

fix(ui): do not schedule next operations on unmounted LogsPage

---

CHANGELOG.md
ui/src/kapacitor/components/AlertTabs.tsx

fix(ui): open event handler config from link hash

---

CHANGELOG.md
ui/package.json
ui/src/dashboards/actions/index.ts
ui/src/data_explorer/apis/index.ts
ui/src/logs/utils/config.ts
ui/src/shared/copy/notifications.ts
ui/src/tempVars/utils/graph.ts
ui/yarn.lock

chore: upgrade to typescript 4

---

CHANGELOG.md
ui/src/flux/components/TagKeyList.tsx

fix(ui): exclude _start and _stop tags

---

CHANGELOG.md
enterprise/meta.go

Closes #5695 
* reduce dialer (connection establishment) timeout to 10 seconds to fail quickly on networking error
* always use the configured meta URL to ensure proper failover
* _+_ keep the campground cleaner

fix(server): improve communication with InfluxDB enterprise

---

CHANGELOG.md
server/sources.go
server/sources_test.go
ui/src/shared/apis/index.ts
ui/src/sources/components/SourceStep.tsx

Closes #5707 
* changes to username and password also trigger detection of InfluxDB server type
* server type is detected without actually persisting the source
* leave the campground cleaner

fix: improve server type detection in Connection Wizard

---

CHANGELOG.md
ui/src/alerts/containers/AlertsApp.tsx
ui/src/worker/jobs/proxy.ts

Closes #5705
* no errors were visible to the user, the UI got stuck in a loading state
* the details of the error were hard to determine
* console logs were improved to show full error details
* the page shows an error to the user

fix(ui): add error handling to Alert History page

---

CHANGELOG.md
ui/src/data_explorer/actions/view/write.ts
ui/src/data_explorer/apis/index.ts
ui/src/data_explorer/components/WriteDataForm.tsx
ui/src/data_explorer/components/WriteDataHeader.tsx
ui/src/data_explorer/constants/index.ts

Closes #4419
* allow specifying write precision (s, ms, u, ns)

feat(ui): allow to change write precision

---

ui/src/dashboards/containers/DashboardPage.tsx
ui/src/shared/components/AnnotationTagsDropdown.tsx
ui/src/shared/components/Annotations.tsx
ui/src/shared/components/NewAnnotation.tsx

Closes #5709
This PR fixes redux+router upgrade issues that appear in Chronograf 1.9.

fix(ui): repair redux + router usage after upgrade

---

ui/src/tempVars/utils/graph.ts

Closes #5743
This PR fixes a regression defect introduced by `1.9`'s #5697 .

fix(ui): repair default fetcher

---

ui/src/tempVars/utils/index.ts

fix(ui): avoid undefined error

---

CHANGELOG.md
ui/src/flux/components/DatabaseList.tsx

Closes #5776
Flux Bucket list component now detects source change to refresh bucket list.

fix(ui/explorer): refresh flux bucket list on source change

---

CHANGELOG.md
ui/src/shared/components/TableGraph.tsx

Closes #5800
Wrong detection of time row.

fix(ui): repair time rendering in horizontal table

---

.github/workflows/chronograf-cypress-tests-report.yaml

fix: always generate report

---

.github/workflows/chronograf-cypress-tests-report.yaml

This PR
- fixes the path test-reporter reads from

Report path fix

---

ui/cypress/integration/queryBuilder.test.ts

This PR:
- fixes data-test attribute

fix: fix data-test attribute

---

etc/oauth2-server-mock/src/index.mjs
ui/cypress.json
ui/cypress/fixtures/routes.json
ui/cypress/index.d.ts
ui/cypress/integration/admin.test.ts
ui/cypress/integration/dashboard.test.ts
ui/cypress/integration/queryBuilder.test.ts
ui/cypress/integration/welcome.test.ts
ui/cypress/support/commands.ts
ui/githubActions-config.json
ui/src/admin/components/DatabaseManager.js
ui/src/admin/components/DatabaseRow.js
ui/src/admin/components/DatabaseTable.js
ui/src/admin/components/DatabaseTableHeader.js
ui/src/admin/components/RoleEditingRow.js
ui/src/admin/components/RoleRow.js
ui/src/admin/components/UserRow.tsx
ui/src/admin/components/UserRowEdit.tsx
ui/src/admin/containers/influxdb/UserPage.tsx
ui/src/admin/containers/influxdb/UsersPage.tsx
ui/src/shared/components/ConfirmButton.tsx

This PR adds:
- Users manager as well as Databases manager tests
- data-test attributes to elements used in those tests

test(cypress): add tests for database and user managers

---

.github/workflows/chronograf-cypress-tests-report.yaml
ui/.eslintrc
ui/cypress/integration/admin.test.ts
ui/package.json
ui/src/admin/components/RoleRow.tsx
ui/src/admin/components/influxdb/CreateRoleDialog.tsx
ui/src/admin/containers/influxdb/RolePage.tsx
ui/src/admin/containers/influxdb/RolesPage.tsx
ui/src/reusable_ui/components/slide_toggle/SlideToggle.tsx
yarn.lock

This PR adds:
- new roles management test
- `data-test` attributes to elements used in test

test(cypress): role management test

---

ui/cypress/README.md
ui/cypress/fixtures/influxDB.json
ui/cypress/index.d.ts
ui/cypress/integration/admin.test.ts
ui/cypress/integration/dashboard.test.ts
ui/cypress/integration/queryBuilder.test.ts
ui/cypress/integration/welcome.test.ts
ui/cypress/support/commands.ts

This PR adds:
- README for Cypress test suite
- add custom Cypress functions
- improve overall structure of tests

chore(cypress): improve e2e tests

---

ui/cypress/integration/admin_chronograf.test.ts

This PR:
- fixes flaky parts of the admin_chronograf.test.ts

fix(cypress): improve flaky parts of the test

---

CHANGELOG.md
ui/src/admin/containers/influxdb/AdminInfluxDBScopedPage.tsx

Closes #5964 
The error message is herein enhanced to be:

fix(ui): inform the user to use v2 administration

---

ui/cypress/integration/admin_chronograf.test.ts

This PR: 
- adds user SuperAdmin toggle assertion

chore(cypress): add user SuperAdmin toggle assertion

---

ui/cypress/integration/dashboard.test.ts

This PR:
- adds more assertions to Dashboard test

chore(cypress): add assertions to Dashboard test

---

ui/src/shared/components/AnnotationTooltip.tsx

This PR repair a permission check for editing annotation, so it works properly for authenticated users.

fix(ui): repair condition that checks if the user can edit annotation

---

etc/scripts/docker/run.sh

Need to use the right docker image to build with the correct go version.

chore: update docker version for release

---

CHANGELOG.md
server/swagger.json
ui/package.json

1.10.2 release is going to be made with this

chore: prepare for 1.10.2

---

.circleci/config.yml
.github/workflows/chronograf-cypress-tests.yaml
CHANGELOG.md
etc/Dockerfile_build
etc/scripts/docker/run.sh

Closes https://github.com/influxdata/edge/issues/583

chore(build): upgrade Go to 1.20.13

---

CHANGELOG.md
server/swagger.json
ui/package.json

This PR merge changes from release branch into master branch.

chore: sync 1.10.3 release to master

---

.circleci/config.yml
.github/workflows/chronograf-cypress-tests.yaml
CHANGELOG.md
etc/Dockerfile_build
etc/scripts/docker/run.sh

Closes https://github.com/influxdata/edge/issues/644

chore(build): upgrade Go to 1.21.9

---

.circleci/config.yml
.github/workflows/chronograf-cypress-tests.yaml
CHANGELOG.md
etc/Dockerfile_build
etc/scripts/docker/build.sh
etc/scripts/docker/run.sh

Closes https://github.com/influxdata/edge/issues/676

chore(build): upgrade Go to 1.21.10

---

.circleci/config.yml
.github/workflows/chronograf-cypress-tests.yaml
CHANGELOG.md
etc/Dockerfile_build
etc/scripts/docker/run.sh

Closes https://github.com/influxdata/edge/issues/708

chore(build): upgrade Go to 1.21.12
