influxdata/chronograf

CHANGELOG.md
canned/postgresql.json

Some graphs were broken on the Postgres layout
Because the host page now adds group by time()s to queries
automatically, all queries need to have aggregates. This adds aggregates
to the fields used by the Rows and the Throughput graphs on the Postgres
layout.

Add aggregates to Postgres layout

---

CHANGELOG.md
README.md
canned/varnish.json

Connect #556
Users want to monitor Varnish!
This adds a varnish layout with a single graph for monitoring cache hits
vs. misses. The varnish plugin in Telegraf is able to collect far more
statistics on Varnish (complete list:
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/varnish).
However, by default only hits, misses, and uptime are present in the
configuration. We don't currently have a way for a layout to inspect the
fields present for a particular measurement for it to decide which cells
to show, so this will be necessary if we wish to add monitoring for
things like ESI errors, backend connects, memory stats, threads, etc.

Add Varnish Layout

---

ui/src/App.js
ui/src/alerts/containers/AlertsApp.js
ui/src/chronograf/containers/Header.js
ui/src/hosts/containers/HostPage.js
ui/src/hosts/containers/HostsPage.js
ui/src/kapacitor/components/RuleHeader.js
ui/src/kapacitor/containers/KapacitorPage.js
ui/src/kapacitor/containers/KapacitorRulesPage.js
ui/src/kapacitor/containers/KapacitorTasksPage.js
ui/src/shared/components/NoClusterLinksError.js
ui/src/sources/containers/ManageSources.js
ui/src/sources/containers/SourceForm.js
ui/src/style/chronograf/layout/_main.scss
ui/src/style/enterprise_style/_enterprise-custom.scss
ui/src/style/enterprise_style/hosts.scss
ui/src/style/enterprise_style/kapacitor.scss
ui/src/style/modules/_sizes.scss

Connect #490 
This removes most references to Enterprise, changing them to Chronograf.
We still have a `_enterprise-custom.scss` file, and the `/enterprise_style` directory. There's already a `/chronograf` directory for styles from the old chronograf project, so I wasn't sure how to rename it without being confusing.

remove references to enterprise

---

ui/spec/utils/timeSeriesToDygraphSpec.js
ui/src/shared/components/AutoRefresh.js
ui/src/shared/components/Dygraph.js
ui/src/utils/timeSeriesToDygraph.js

Connect #544 
Before:
After:
The `identifier` in the `timeSeriesToDygraph` function is a relic from old-chronograf.  No longer needed.  [See old test](https://github.com/influxdata/chronograf-old/blob/master/ui/spec/timeSeriesToDygraphSpec.js#L38) for reference.
Remove relic.  Add updated tests. Works empirically in DE, and layouts.

Remove identifier (host) from timeSeriesToDygraph converter

---

ui/src/hosts/apis/index.js
ui/src/hosts/containers/HostPage.js

Connect #494 
We are populating the host view with empty layouts because we are not detecting whether a particular host even has a layout's measurement.
Get the measurements for a host and filter the layouts based on said measurements.

Fix layout being displayed when measurement not present

---

ui/src/alerts/containers/AlertsApp.js
ui/src/kapacitor/actions/view/index.js
ui/src/kapacitor/containers/KapacitorRulesPage.js
ui/src/shared/components/NoKapacitorError.js

Connect #536
The kapacitor rules page does not direct users to add a kapacitor if the chosen source does not have one.
I've extracted the notification that we show on the alerts page and shared it with the rules page.

extract kapacitor error to separate component, share it with rules page

---

ui/src/sources/containers/CreateSource.js

Connect #586 
User cannot type into the telegraf text input field. 
The solution can be summed up pretty well by the console warning 
Failed form propType: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`. Check the render method of `CreateSource`.
I also updated the `sourceURL` and source `name` as per a previous request from @nathanielc

Fix uneditable telegraf text input 

---

circle.yml

Fix #631
Master was not pushing `latest` docker container tag
When master is built it will update the latest tag on quay

Update circle to push latest tag for master builds

---

ui/src/hosts/components/HostsTable.js

Apps were not showing up on the host list because of the new `shouldComponentUpdate` for a host list item. This was because hosts we modify the hosts in place, meaning `this.props.host !== nextProps.host` was given us a fraudulent result.
Actually compare the keys of the two hosts

Fix bug that stopped apps from displaying

---

docs/dashboards.md

Connect #621
Design Dashboards API
This is a simple solution that allows us to begin work on the first implementation of dashboards.  
The API will include two new routes using our standard REST style:
1. /chronograf/v1/dashboards
2. /chronograf/v1/queries
`/dashboards` contains visualization meta-data and links to the queries
`/queries` contain raw InfluxQL commands.  This means that we cannot edit the queries at the moment with the explorations interface.
However we've designed in the ability to support much more comprehensive set of InfluxQL UI editing support.  In follow-on work, we can enhance the `/queries` endpoint feature by feature to structure InfluxQL as JSON.

Dashboard api spike

---

server/swagger.json

Noticed this while working on the dashboards endpoint:
Our swagger docs describe a `/users` `GET`, which does not exist. This PR removes it from our documentation.

removing unimplemented endpoint from swagger

---

CHANGELOG.md
dist/dist.go
server/assets.go

Fix #664 
I'm using http.FileServer to serve the site from our bindata.  To facilitate a single-page react-app with its own router, index.html is returned for all unknown routes.  
However, some of those routes could end with a file extension that causes http.FileServer's mime-type discovery to return the incorrect `Content-Type` header.  For example, in the case of a route that ended in `.com` it would return `application/x-msdos-program`.
If the route returns the default content (index.html) the `Content-Type` header is set to `text/html; charset=utf-8`

Fix Content-Type of the index.html page to be text/html

---

cmd/chronograf/main.go

Previously, using the version switch (`chronograf --version`) would
yield no version or commit information. This was because those two
package vars were exported, when the build script expects them to be
package private. To keep the build script as consistent as possible
across repos, the solution was to just make those package vars private
Connect #679

Fix missing version

---

chronograf.go
kapacitor/tickscripts_test.go
kapacitor/triggers.go
kapacitor/vars.go

Connect #708
I paired on this with @goller.
This adds support for range alerting with kapacitor.
When creating or updating an alert through the API, we've added optional `RangeOperator` and `RangeValue` strings to send in the request body.
So, for setting a range alert that's greater than 10 but less than 20, you'd send something like this (not a valid request body, but to you give an idea):
```javascript
{
operator: "GreaterThan",
range_operator: "LessThan",
value: "10",
range_value: "20"
}
```

add kapacitor range alerting to API

---

etc/build.py

It's difficult to create the markdown table for a release.
Minor update to the python build script to print the markdown to be used in the release notes.

Add markdown to be used in a release

---

chronograf.go
kapacitor/operators.go
kapacitor/tickscripts_test.go
kapacitor/triggers.go
kapacitor/vars.go
server/swagger.json

Connect #706 
Connect #707 
Connect #725
No way to specify if kapacitor alert needed to be out of a range.
Simplified the API to allow `is inside range` and `is outside range` as kapacitor operators.  
If using these two operators, then, the `rangeValue` parameter is checked.  
I updated the swagger documentation in this PR as well.

Update kapacitor alert rules to accept inside and outside range

---

CHANGELOG.md
README.md
docs/auth.md
server/dashboards.go
server/github.go
server/mux.go
server/server.go

Connect #732
Chronograf would allow any authenticated github user access.  We need to restrict this by organization.
With the `-o` cli option or `GH_ORGS` environment variable, chronograf can now restrict access to users that are in a set of organizations.

Add Github organization restriction to authentication

---

ui/spec/utils/timeSeriesToDygraphSpec.js
ui/src/utils/timeSeriesToDygraph.js

Connect #719 
Legend was difficult to parse visually.
Sort it

Sort graph legend alphabetically

---

ui/spec/utils/timeSeriesToDygraphSpec.js
ui/src/chronograf/components/Visualization.js
ui/src/shared/components/LineGraph.js
ui/src/utils/timeSeriesToDygraph.js

Connect #734 
Connect #703  
Copying an InfluxQL query from an auto-generated query caused a couple of problems:
1)  There was some visual grossness caused by multiple axes rendering weirdly.
2)  `timeSeriesToDygraph` could not differentiate two separate responses that had the same field and measurement names.  This would cause one of the similar series to not be rendered.  
1)  For reasons I explained here: https://github.com/influxdata/chronograf/commit/7cbdb700f2dd45c63cc17b4ba3cc7d59666a6692, I removed multiple axes from the DataExplorer.  
2) In `timeSeriesToDygraph` when two or more Influx responses share the same field and measurement names, I append an id to the end of the legend string / dygraphSeries key.  
The `timeSeriesToDygraph` now has three concerns: 
1) parse Influx …

Graph weirdness

---

CHANGELOG.md
server/proxy.go

Fix #754
Kapacitor authentication was not proxied correctly.
Proxying the basic auth via URL path was not working, so, this places it directly into the header.

Fix kapacitor auth with basic auth in header

---

CHANGELOG.md
etc/build.py
etc/scripts/chronograf.service
etc/scripts/post-install.sh

This removes the posttrans scriptlet from the RPM packaging so the `/etc/scripts/post-install.sh` script is not called twice.
Adds a step to remove any existing symlinks to the systemd service before linking the unit file.
Also removes the `Alias` from the unit file, which is superfluous.
@rossmcdonald

Remove RPM posttrans scriptlet and small fixes

---

ui/src/kapacitor/components/RuleGraph.js
ui/src/kapacitor/components/ValuesSection.js
ui/src/style/theme/bootstrap-theme.scss
ui/src/style/theme/theme-dark.scss
ui/webpack/devConfig.js
ui/webpack/prodConfig.js

Previously fixed an issue in which users could not tell if text was selected or not, but it was limited to just inputs. Now all selected text is styled uniformly.
Made some minor copy changes to be more consistent. "Metric" --> "Time-Series"
Lastly, realized the built stylesheet is just called `style.css` while the uncompiled sheet is called `chronograf.scss` so I changed it to match. Not much of a measurable benefit other than making the product slightly more branded.

Misc UI Polish

---

CHANGELOG.md
ui/src/sources/containers/ManageSources.js

Connect #702
When visiting the Sources page, any InfluxDB sources that had a
configured Kapacitor would not show them. This turned out to be racey
logic. Kapacitors for a particular source are fetched from the API. The
update to the component state happened outside of the promise chained
onto the API call, so the state update was racing against the fetch from
the API (and would always win, pushing the empty object).
Instead, the chained promises for each API fetch are collected, and each
promise updates a single kapacitors object. The final promise that
updates the state is then blocked on all those promises by Promise.all.
Performing updates like this saves some allocations, since we aren't
allocating an object for each source<->kapacitor pairing to send to
setState. It also reduces …

Fix missing Kapacitor on Source index page

---

CHANGELOG.md
ui/src/kapacitor/components/RuleMessage.js
ui/src/kapacitor/constants/index.js
ui/src/shared/constants/index.js
ui/src/style/pages/kapacitor.scss

There was some ugliness. 
@alexpaxton and I made it less ugly. No more confusing UX
The template items below rule message had a `pointer` cursor on hover which lead people to believe they could click and something would happen. This is not the case so it was confusing for users.

Rule template

---

CHANGELOG.md
ui/src/data_explorer/components/FieldList.js
ui/src/shared/apis/metaQuery.js

Connect #731 
When attempting to extract fields from a non-default retention policy in
the Data Explorer, fields would not appear. This was because the query
was sent without an explicit RP, which would use the default RP instead.
This adds an explicit RP to the SHOW FIELDS query.

Fix missing fields from non-default RP

---

CHANGELOG.md
Makefile
server/server.go
server/version.go

The rest of the TICK stack reports a version header. Now Chronograf does too. (This is helpful for pings and debugging)

Add X-Chronograf-Version header

---

CHANGELOG.md
README.md
canned/diskio.json

diskio are counters that give the total reads/writes since a system reboot.
Fix #776 
Layout for telegraf's diskio needed.
Telegraf does not have documentation about diskio, but, it uses [github.com/shirou/gopsuti/disk](https://github.com/shirou/gopsutil/blob/master/disk/disk_linux.go#L276).   In turn `disk_linux.go` uses `/proc/diskstats`.  `/proc/diskstats` are documented [here](https://www.kernel.org/doc/Documentation/iostats.txt)
Because the stats are long running counters, I'm using `non_negative_derivative`.  Additionally, I'm scaling the queries from bytes to megabytes.  Finally, I'm grouping by the name of the device.

Add layout for telegraf's system diskio plugin

---

ui/package.json
ui/spec/shared/reducers/sourcesSpec.js
ui/src/shared/reducers/sources.js

Add reducer spec for shared/sources. Add nodemon script to package.json to help with TDD. Fix actual issue: duplicate defaults in sources.
Connect #769 
Duplicate defaults appear when managing them in the InfluxDB configuration screen.
Defaults are properly exclusionary when adding or updating them. The expected behavior for removing a default is a bit ambiguous, however, and that functionality was not corrected in this branch.

Duplicate defaults appearing in InfluxDB configuration

---

CHANGELOG.md
canned/net.json
canned/new_apps.sh

Connect #774
Connect #775 
Telegraf's `input.net` measurement needs to be rendered.

Add layout for telegraf's net meassurement

---

CHANGELOG.md
ui/src/hosts/containers/HostPage.js

Fix #774
If layouts had multiple cells the autoflow logic would create gaps.
Fix by using a counter for all cells.

Fix layout autoflow to handle multiple cells per layout

---

circle.yml

This will update our builds to use go 1.7.5 and node 6.9.4

Update circle's docker build tag to chronograf-20170127

---

server/server.go

Connect #721
New option to set basepath did not have an environment variable override.
Add env var `BASE_PATH` to override chronograf's base path for the assets.

Add BASE_PATH env var to -basepath cli option

---

ui/src/style/components/page-header-dropdown.scss
ui/src/style/pages/hosts.scss

Fixes #842 
- Dropdown menu is always 250px wide
- Dropdown menu items are truncated with … when they are too long

Fix jank in hosts dropdown

---

README.md

Connect #845
Basepath was specified with a single dash in the readme.  This causes problems with the boltdb option
Add the double dash.

Fix basepath documentation to have double dash

---

CHANGELOG.md
bolt/alerts_test.go
chronograf.go
kapacitor/tickscripts_test.go
kapacitor/triggers.go
kapacitor/vars.go
server/swagger.json
ui/spec/kapacitor/reducers/rulesSpec.js
ui/src/kapacitor/actions/view/index.js
ui/src/kapacitor/components/RuleMessage.js
ui/src/kapacitor/reducers/rules.js
ui/src/style/pages/kapacitor.scss

Connect #838
Kapacitor supports adding an email body via the `.details()` chaining method.
Added `detail` to rules endpoint.

Update kapacitor alert rule to have detail field

---

README.md
chronograf.go
kapacitor/alerts.go
kapacitor/alerts_test.go
kapacitor/validate.go
kapacitor/validate_test.go
server/swagger.json

Connect #625 
Connect #639 
Connect #713 
Connect #724
Connect #782 
Connect #793 
Connect #801 
Connect #834
Backend wasn't able to render any alerts with arguments or parameters
Support for every kapacitor alert service in backend (frontend needs the various input boxes).
New key `alertNodes` added to rule.  Here is the JSON
```json
"alertNodes": [
{
"name": "AlertNode Name Here",
"args": ["args", "to", "alert", "node"],
"properties": [
{
"name": "name of kapacitor properties",
"args": [
"args", "to", "kapacitor", "properties",
]
}
]
}
]
```
Here are JSON examples for kapacitor's tcp and post alert node types:
```json
{
"alertNodes": [
{
"name": "post",
"args": [
"http://post.com/here"
],
"properties": []
}
]
}
```
```json
{
"alertNodes": [
{
"name": "tcp",
"args": [],
"properties": [
{ …
```

Backend support for Kapacitor Alert arguments and Properties

---

CHANGELOG.md
kapacitor/tickscripts_test.go
kapacitor/vars.go
kapacitor/vars_test.go

Connect #865 
If threshold alert rule's critical value was a string, the tickscript wasn't generated correctly.
This checks if the critical value is a string and formats it with kapacitor's single-quotes.
This patch does not address string inequality nor threshold ranges.

kapacitor threshold critical value strings

---

CHANGELOG.md
Godeps
LICENSE_OF_DEPENDENCIES.md
dist/dist.go
server/mux.go
server/url_prefixer.go

Connect #860 
Server was not respecting `Accept-Encoding` for gzip.
Server was not adding cache information to static assets
Server now will gzip compress all responses if accepted.
For production assets server now adds cache control for one hour and etags based on file size and modtime.

Add gzip compression to all of our server responses and caching for assets

---

ui/src/style/pages/data-explorer/query-editor.scss

When using the DE at a small size the query builder lists do not scroll, hard to use.
Now they scroll properly

Fix Scrolling Issue on DE Lists

---

CHANGELOG.md
README.md
docs/tls.md
server/hsts.go
server/server.go

Connect #
Chronograf server did not have the option to host certs.  This is important for OAuth2 if one doesn't have TLS termination in some other location.
Add two CLI options (`--cert and --key`) and corresponding environment variables (`TLS_CERTIFICATE` and `TLS_PRIVATE_KEY`).
The two parameters specify files container the certificate and the private key.  If the private key is in the certificate file then only `--cert` needs to be specified.
Additionally, [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) middleware was added to require https if TLS is turned on.

Add TLS options to server

---

CHANGELOG.md
ui/spec/shared/parsing/getRangeForDygraphSpec.js
ui/src/shared/parsing/getRangeForDygraph.js

Connect #881 
Graph did not properly display highlighted range when value for "greater than" rule exceeded local data peak value. This bug also showed up in "inside range" and "outside range".
* Fixed the math for adding and subtracting padding.
* Removed incorrect and arbitrary "top" argument to allow "range" rules to display correct highlighting regardless of which value was greater.
Fixed display for "greater than":

Fix y-axis graph padding

---

CHANGELOG.md
ui/src/style/mixins/mixins.scss

Connect #843 
User reported having difficulty navigating a long host list and having difficulty grabbing the scrollbar because it was so small.
Made the scrollbar thumb element bigger.

Make the scrollbar thumb element larger

---

CHANGELOG.md
ui/src/index.js

Connect #906 
An unnecessary and unconventional usage of `useBasename` was being used to set a basepath when creating initial history.
The updated v2.0 docs call for `useRouterHistory` to create a history with a custom basepath: https://github.com/ReactTraining/react-router/blob/master/docs/guides/Histories.md.

Fix react-router warning

---

CHANGELOG.md
ui/src/dashboards/containers/DashboardsPage.js
ui/src/side_nav/components/SideNav.js

- Icons were not clear enough
- Organization scheme not obvious
- Lots of nested nav items
- Goal was to flatten the nav tree a bit
- Moved `Kubernetes` dash into `Dashboards` table
- Flattened `Infrastructure` into 1 top level item `Hosts List`, removed `Kubernetes`
- Flattened `Data` into 2 top level items `Data Explorer` `Dashboards`
- New icon for `Alerting` (Alert Triangle)
- New icon for `Configuration` (Cog)
- New icon for `Host List` (Cubo Node)
- New icon for `Dashboards` (Cog)

Side Nav Simplification

---

canned/docker.json

Connect #920 
Previously I updated the canned Docker layouts JSON manually. It was recommended that I do this via the Chronograf API, i.e. a PUT request.
Performed the PUT request. Thus the change will be cached to the database, and the schema will follow the most up-to-date formatting.

Update canned Docker layouts via PUT request

---

CHANGELOG.md
ui/src/shared/components/Dygraph.js
ui/src/shared/components/LineGraph.js

Connect #927 
Kapacitor rule graphs were not displaying. They had 0 height.
Give both container divs 100% height to expand to the parent height.

Fix Kapacitor rule graph display

---

chronograf.go
enterprise/enterprise.go
enterprise/enterprise_test.go
enterprise/mocks_test.go
influx/permissions.go
mocks/timeseries.go
server/admin.go
server/admin_test.go
server/swagger.json

Connect #933 
The front-end needs to know what permissions are scoped to `all` or `database`
The schema has now changed to:
```json
{
"permissions": [{
"scope": "all",
"allowed": ["READ", "WRITE"]
}, {
"scope": "database",
"allowed": ["READ", "WRITE"]
}],
"links": {
"self": "http://example.com/chronograf/v1/sources/1/permissions",
"source": "http://example.com/chronograf/v1/sources/1"
}
}
```
Permissions with scope `all` represent the set of permissions that can be scoped with `all`.
Permissions with scope `database` represent the set of permissions that can be scoped to a specific database.

Update schema for /permissions endpoint to have scopes

---

CHANGELOG.md
influx/influx.go

Connect #936
http.Transport not being reused by http.Client for queries to InfluxDB
Reuse http.Transport

Fix influx querying to prevent leaking sockets

---

ui/.eslintrc
ui/src/kapacitor/actions/view/index.js
ui/src/kapacitor/components/KapacitorRules.js
ui/src/kapacitor/components/KapacitorRulesTable.js
ui/src/kapacitor/containers/KapacitorRulesPage.js
ui/src/shared/components/NoKapacitorError.js

Connect #847 
Users could only enable/disable the first rule's alerts.
Each checkbox's id and label was hardcoded to 'kapacitor-enabled'.  Since id's must be unique the DOM just had no idea which element we actually wanted to work on.
Also refactored this component quite a bit to conform to more modern patterns and enhance readability.

Fix rule disable bug

---

CHANGELOG.md
ui/src/dashboards/components/Dashboard.js

Connect #968
Dashboard defaulted to use the telegraf db.
Dashboard queries now use the database specified in the dashboard resource.
Used this command to test:
```sh
curl -X POST -H "Content-Type: application/json" -d '{
"cells": [
{
"name": "Write Errors",
"queries": [
{
"db": "_internal",
"rp": "monitor",
"label": "count",
"query": "SELECT max(\"writeFailures\") AS \"max_writeFailures\" FROM \"_internal\".\"monitor\".\"subscriber\"",
"wheres": [],
"groupbys": []
}
],
"type": "line"
}
],
"name": "internal subscriber test"
}' "http://localhost:8888/chronograf/v1/dashboards"
```

Fix dashboards to use specified database

---

chronograf.go
kapacitor/validate.go
log/log.go
server/server.go
server/url_prefixer.go

We weren't logging internal `http.Server` errors.
Get `io.PipeWriter` from logrus and send to `http.Server`

Add structured logging to underlying http server

---

server/roles.go
server/roles_test.go

Connect #984
Appears as if plutonium does not check if role already exists (or doesn't send an error)
Get the role first to check if it exists.

Update roles to check if role already exists

---

CHANGELOG.md
ui/spec/dashboards/reducers/uiSpec.js
ui/src/dashboards/actions/index.js
ui/src/dashboards/components/Dashboard.js
ui/src/dashboards/containers/DashboardPage.js
ui/src/dashboards/reducers/ui.js
ui/src/shared/components/LayoutRenderer.js
ui/src/shared/components/NameableGraph.js

Connect #954 
Users weren't able to edit the name of their cells on dashboards, so they all had the name "Graph"
Users are now able to edit cells by clicking on the title, changing the name and either clicking elsewhere or hitting "Enter" to submit changes to the cell's name.

Allow Renaming Cells on Dashboards

---

ui/src/shared/components/NameableGraph.js

Connect #1023 
The Host Page was entirely devoid of graphs
This was because the `NameableGraph` component introduced in #1020 required certain handler functions whenever it was invoked. This PR removes the hard requirement of those functions and instead uses their presence to signal whether or not this cell should be editable. On the `HostPage`, these functions are not provided, so the cell becomes static.

Fix Broken Host Page

---

ui/src/admin/components/DatabaseRow.js

The delete RP button was not rendered if
there was only one RP for that RP's database.
This caused the table columns to render in different
sizes.  Hiding the button keep the same functionality but
preserves the sizing for the table.

Fix DB manager table column sizing

---

CHANGELOG.md
ui/src/dashboards/components/DashboardHeader.js
ui/src/hosts/containers/HostPage.js
ui/src/shared/components/LayoutRenderer.js
ui/src/shared/components/NameableGraph.js
ui/src/style/pages/dashboards.scss

Connect #1066 
The new editable graph styles and context menu made their way onto Host Page graphs. This should not be the case.
(Hotfix) Remote them by passing down an explicit boolean.

Graphs are no longer editable from a Host Page

---

CHANGELOG.md
ui/src/style/pages/dashboards.scss

Connect #1078 
Dashboard cells became unresizable, despite the handle for it at the bottom-right corner.
Change the z-index of the new `dash-graph` container `div` in the recently added NameableGraph component.

(Fix) Graphs are now resizable again

---

CHANGELOG.md
ui/src/hosts/components/HostsTable.js
ui/src/hosts/containers/HostsPage.js

Connect #1003 
If there are zero hosts available, often this isn't a sign of an error, it just means there are actually zero hosts available. If there is an actual error, it was not displayed.
Separate the branching conditions so hosts and errors are handled separately. Loading is handled separately as well.

Bugfix/1003: Hosts Loading Messaging

---

CHANGELOG.md
server/sources.go
ui/spec/shared/reducers/sourcesSpec.js
ui/src/CheckSources.js
ui/src/shared/actions/sources.js
ui/src/shared/reducers/sources.js
ui/src/sources/containers/ManageSources.js

Connect #1008 
Users that deleted a source they were connected to would be unexpectedly redirected to the create sources page.
Users are redirected to the default source when deleting sources. If the default source is deleted, the API chooses a new default source and the user is directed to that one. If all sources are deleted, the user is prompted to create a new one.

Redirect to default source when deleting sources

---

CHANGELOG.md
ui/spec/dashboards/reducers/uiSpec.js
ui/src/dashboards/actions/index.js
ui/src/dashboards/apis/index.js
ui/src/dashboards/containers/DashboardPage.js
ui/src/dashboards/containers/DashboardsPage.js
ui/src/dashboards/reducers/ui.js
ui/src/shared/constants/index.js

Connect #1080 
User could not delete a dashboard via the UI.
Add UI button, action creators, reducers, and tests for dashboard deletion and error handling. This required some refactoring of DashboardsPage to load `dashboards` and `dashboard` from redux state.

Add ability to delete a dashboard

---

CHANGELOG.md
server/swagger.json
ui/src/admin/actions/index.js
ui/src/admin/apis/index.js
ui/src/admin/components/AdminTabs.js
ui/src/admin/components/ChangePassRow.js
ui/src/admin/components/DatabaseRow.js
ui/src/admin/components/UserRow.js
ui/src/admin/components/UsersTable.js
ui/src/admin/containers/AdminPage.js
ui/src/shared/components/DeleteConfirmButtons.js
ui/src/style/pages/admin.scss

Connect #939
Users can't change user passwords right now via the admin page.
Add a "change password" option to the user management page:
- I updated the swagger docs, which were missing some information for the `/users` endpoint.
- some minor refactoring of our user patching, so that we aren't patching with the entire user object but just the relevant keys to update.
- the one thing I'm not happy with is that `OnClickOutside` should be wrapping the confirm buttons, and not the entire component. The way it is right now, we have event listeners that trigger a state change for every `UserRow` whenever a user clicks anywhere on the page, because `ChangePassRow` is always being rendered, even when it isn't visible. The same is true for `DeleteRow`.
- could probably use some style cleanup >>

Add ability to change a user's password via Admin page

---

CHANGELOG.md
ui/src/alerts/containers/AlertsApp.js

Connect #1054 
The Alert History page does not show a spinner when the data is loading.
Add a spinner to the component.

Add simple loading spinner to Alert History page.

---

CHANGELOG.md
ui/src/side_nav/components/NavItems.js

Connect #1040
A `NavBlock` determines whether to apply the `active` by comparing the current browser location to the links attached to its `NavLinkItem` children. This assumes that all `NavBlocks` in the sidebar will contain at least one `NavLinkItem` child, which isn't the case currently. It is also valid for a `NavBlock` to contain a single child of type `NavHeader`. Clicking on that `NavHeader` should activate the `NavBlock`. 
Remove the `NavListItem` type check

Active sidebar items should have a blue indicator

---

CHANGELOG.md
server/proxy.go

Connect #1133
The kapacitor authentication header is incorrect as it was base64 encoding the wrong part of the string.
Using the standard library basic auth generation.

Fix kapacitor base64 auth as header was built incorrectly.

---

CHANGELOG.md
ui/src/kapacitor/components/TelegramConfig.js

Connect #862 
Telegram config was always showing `Disable Notification` to be checked after saving, regardless of whether it was checked when saved.
Assign `disableNotification` the proper `options` value from the Telegram config section.

Fix Kapacitor Telegram config to display correct disableNotification setting

---

CHANGELOG.md
ui/src/index.js

Connect #1051
When a user clicks the back button while in presentation mode, presentation mode does not end.
Watch changes to the location and disable presentation mode when it changes.
This could be improved upon by only registering the listener when presentation mode becomes active.

Escape presentation when using back button

---

CHANGELOG.md
server/builders_test.go
server/server_test.go
server/url_prefixer.go
server/url_prefixer_test.go

Connect #972
In certain situations, the http.ResponseWriter passed to the URLPrefixer
may not be an http.Flusher. A simple case where this may occur is if the
Prefixer has been wrapped up in a middleware where the above middleware
wraps the ResponseWriter in a ResponseWriter that doesn't implement the
Flush method.
Previously, the Prefixer would error, which would cause the request to
fail with a 500. Instead, the condition is logged and the request is
passed unmodified to the next middleware in the chain. This effectively
disables prefixing for requests where the above ResponseWriter is not an
http.Flusher.

Bypass URLPrefixer if http.Flusher is unavailable

---

CHANGELOG.md
ui/src/dashboards/components/CellEditorOverlay.js

Connect #1105
Queries added via the InfluxQL mode will lack a queryConfig representation, having only a `rawText` value to send to the server. In these cases, we can't craft a Cell Label by inspecting a queryConfig.
If `rawText` is all we have to go on, we should provide a blank Cell Label to the server.

Restore ability to save raw queries to a Dashboard Cell

---

CHANGELOG.md
ui/src/kapacitor/components/RuleMessageAlertConfig.js

Connect #1100 #1156 
Kapacitor alerts failed to save email address entered by user.
Fix how form data is captured.

Fix saving email in Kapacitor alerts

---

CHANGELOG.md
server/databases.go
server/swagger.json

Connect #1170
The frontend expected databases to have a `retentionPolicies` key, even if the value is an empty array. The server is omitting the key if the value is empty.
The server now keeps the `retentionPolicies` key, even if its value is `[]`.

Admin Databases Page no longer breaks if a db is missing an rp

---

CHANGELOG.md
chronograf.go
server/mountable_router.go
server/mountable_router_test.go
server/mux.go
server/server.go

Connect #1033 
Some load balancers will remove the --basepath prefix before forwarding traffic onto the Chronograf backend. Other load balancers leave the route unmodified. The existing `--basepath` parameter doesn't work for users when load balancers leave the prefix intact.
I introduced a new option, `--prefix-routes`, that causes all chronograf routes to be mounted under the `--basepath`. I introduced an interface to wrap the existing router and a new implementation of that interface which takes a mounting point. Method calls to each of `chronograf.Router`'s methods on the `MountableRouter` will prefix the route and dispatch the method call to its configured `Delegate`.
Note that the `assets` handler still required removing the prefix ahead of time since it is unaware of any prefixing …

Prefix all Chronograf routes with Basepath when configured

---

ui/src/style/pages/dashboards.scss

We've seen a couple of UI issues recently that have been solved by modifying the `z-index` of a `.react-grid-item` descendant. There are a couple of remaining related UI issues, and I am resistant to adding more `z-index` bandaids -- ideally we could identify/remove one or two problematic `z-index`es, hopefully making `.react-grid-item` less hairy overall.  Specific remaining issues:
Notice that the right side of the menu dropdown is clipped by the neighboring cell. Currently, when we hover over a cell, its `z-index` is upgraded to `8000`.
When clicking Edit, the dropdown closes and the overlay opens. But the cell remains top of the render stack. When you move your mouse out of the cell boundary, it disappears back behind the Overlay.
I drew out a `.react-grid-item`'s DOM. Black means …

Pare down stacking contexts in .react-grid-item

---

.gitattributes

Even with the team converging on true Markdown numbering (i.e all `1`s instead of `1`, `2`, etc.), we still seem to be running into per-PR merge conflicts in our CHANGELOG. This is still happening because:
```
1. one
1. two
1. three
```
```
1. one
1. two
1. three
1. four
```
```
1. one
1. two
1. three
1. five
```
The default merge strategy sees `1. four` and `1. five` occupying the same spot, and it doesn't know which to choose. So it delegates to a human to decide. We can do better.
For `CHANGELOG.md` ONLY, use the `union` merge strategy. This will identify two conflicting changes:
`1. four`
`1. five`
And keep them both, though their order is not guaranteed.

Resolve CHANGELOG.md conflicts by keeping both changes

---

CHANGELOG.md
ui/src/shared/apis/metaQuery.js

Connect #979 
The `SHOW TAG` queries did not use retentionPolicies so the schema explorer would have empty tags.
Add retentionPolicies to 'em
However, I'm pretty sure `SHOW MEASUREMENTS` isn't working like we want it to work.  It seems to show all measurements rather than just those for a specific retention policy.

Update schema exploration to support non-default rp

---

CHANGELOG.md
ui/src/admin/components/DatabaseManager.js
ui/src/admin/components/DatabaseTable.js

Connect #1160 
As a user begins to collect more databases, it can be tough to find a particular database in the database page. Sorting alphabetically should alleviate most of the pain for now.
Alphabetically sort databases on the DB page. Within each DB, sort RPs alphabetically.

Admin Databases Page should be sorted alphabetically

---

CHANGELOG.md
ui/src/shared/components/NameableGraph.js

Connect #1146 
If a user were to click on the cell header when editing, they would get kicked out of edit mode, which prevents text selection.
Prevent kicking out of edit mode if the cell is being edited.
Also, add a blur feature with the escape key. It doesn't cancel and reset to prior state, however. That should be addressed in the separate issue, #1188

Prevent Blur when Clicking Inside Graph Name

---

CHANGELOG.md
ui/src/shared/components/LayoutRenderer.js
ui/src/shared/components/NameableGraph.js
ui/src/style/pages/dashboards.scss

cc: @alexpaxton 
Connect #1194
When
1) A user enters a super long name for a cell
2) A user enters a reasonable name for a cell, and then makes the cell smaller
the name of the cell will overflow its reserved space, and push the ContextMenu carat off to the right.
And so we tried to rework the spacing in the header, but it turns out that the header is really too busy and should be simplified. Namely,
1. The header needs to have a clickable area for the ContextMenu dropdown. When clicking this area, a user should not be able to drag the cell
2. The header needs a clickable area for the name -- clicking the name enters you into a "rename" mode. Clicking out, or pressing enter, will return you to "normal" mode.
3. The header needs a clickable area for a drag handle. Hovering over this will …

Move Rename Cell functionality to ContextMenu dropdown; Restyle cell header

---

server/dashboards.go

Dashboard cell error responses did not give good information
Add cell id and operation to the message.

Update cell dashboard error messags to be descriptive

---

ui/src/dashboards/actions/index.js
ui/src/dashboards/reducers/ui.js

cc: @jademcgough 
Connect #1210
We removed the `dashboard` key from Redux in favor of `dashboards`, which contains an array of all dashboards. Not all action creators were updated.
Pass the current dashboard to `addDashboardCell` around to action creators.

Current dashboard no longer comes from local Redux store

---

CHANGELOG.md
server/proxy.go

Connect #1206 
Thank you @johngilden for this patch!
The kapacitor reverse proxy preserves the Host header from the original request,
causing issues with vhosts using SNI.
Use the configured kapacitor host instead of host from the original request.
For more context on this issue see https://github.com/golang/go/issues/5692

Use the Host header from the original Kapacitor URL

---

ui/src/dashboards/containers/DashboardPage.js

The current dashboard wasn't being passed into `editDashboardCell`, which now required it as a parameter. As a result, pressing enter or clicking out of the name input field would not save the name. The input would remain present.
Pass it

EditDashboardCell now requires dashboard be provided

---

ui/src/data_explorer/components/FieldList.js
ui/src/data_explorer/components/Visualization.js
ui/src/data_explorer/containers/DataExplorer.js
ui/src/shared/components/LineGraph.js
ui/src/shared/components/ResizeContainer.js
ui/src/style/components/resizer.scss
ui/src/style/pages/dashboards.scss
ui/src/style/pages/data-explorer/font-scale.scss
ui/src/style/pages/data-explorer/query-builder.scss
ui/src/style/pages/data-explorer/query-editor.scss
ui/src/style/pages/data-explorer/visualization.scss

All the important UI is at the bottom, graph is over-emphasized
Flip the halves of the DE such that the query builder is on top. Draws a lot more attention to the query box, and editor as a whole

Flip the Data Explorer

---

CHANGELOG.md
chronograf.go
ui/src/dashboards/components/Dashboard.js

Seen below. A cell element's `key` was calculated anew per `LayoutRenderer.render()` execution as we mapped over the dashboard's cells. This means the `key` was not guaranteed to be an invariant. And so if the key value changes, then the `GridLayout` component may decide to reposition more than it has to.
Each cell has an ID on the server -- use this value instead of the cell's index in the array. This should be relatively more invariant.

Use Cell ID returned by the server

---

ui/src/shared/components/ConfirmButtons.js

Connect #1216 
Console issued an errored when editing a Dashboard's name because ConfirmButtons component wanted an Object, and was being passed a String.
Make ConfirmButtons accept Objects and Strings.

Clear console error on ConfirmButtons by fixing propTypes

---

ui/src/style/pages/data-explorer/font-scale.scss
ui/src/style/pages/data-explorer/query-builder.scss
ui/src/style/pages/data-explorer/raw-text.scss

Fixes #1230
- Dropdown inline with status bar
- Dropdown menu wider, aligns to right edge
- Query preview / raw text always the same height (slightly larger)
- Query tabs never gets more wide (more space for schema exploration)

Polish meta queries UX

---

CHANGELOG.md
ui/src/kapacitor/components/RuleMessage.js
ui/src/style/pages/kapacitor.scss

Connect #982 
See #982
We replace the vertical Dropdown with a horizontal Radio Button Group:

Replace Kapacitor Alert Endpoint Dropdown with Radio Buttons

---

CHANGELOG.md
Makefile
server/queries.go
ui/src/shared/components/MultiSelectDropdown.js

Connect #1257 
Connect #1269 
1) In the multi-select dropdown, it was not possible to select multiple items. This was because `componentWillReceiveProps` was unnecessarily setting the localSelectedItems state. Specifically, the `nextProps.selectedItems` collection will always be blank until onApplyFunctions is called. 
2) If a user typed a syntactically valid, fully qualified SELECT statement without an RP, Chronograf had no idea how to parse that into a query config.
1) The setState in `componentWillReceiveProps` was unnecessary because as soon as onApplyFunctions is called, the selection state is persisted via the query string and query config. Experimented with other uses of the multiSelectDropdown in admin UI and it works 👍 
2) Add default RP to queryConfig when no RP is present. …

Fix function application bug

---

CHANGELOG.md
oauth2/cookies.go
oauth2/cookies_test.go
oauth2/jwt.go
oauth2/jwt_test.go
oauth2/mux.go
oauth2/mux_test.go
oauth2/oauth2.go
oauth2/oauth2_test.go
oauth2/time.go
server/auth.go
server/auth_test.go

Connect #1266 
JWTs would last the length of the cookie.  
JWTs will only life five minutes into the future.  Any time
the server receives an authenticated request, the JWT's expire at time
will be extended into the future.

Add JWT refresh on validation.

---

CHANGELOG.md
ui/src/style/components/dropdown.scss
ui/src/style/components/query-maker.scss
ui/src/style/modules/influx-colors.scss

There was no yellow spectrum in the color palette. Was using purple as the color for warnings in the Query Editor and it felt mismatched. Purple is used on other non-warning contexts so this is a little odd.
There is a yellow spectrum. Currently using yellow for Query Editor warnings, but I am sure we will need these colors in the future. Taste the rainbow.

Mellow Yellow

---

CHANGELOG.md
ui/src/kapacitor/components/AlertTabs.js
ui/src/kapacitor/components/config/AlertaConfig.js
ui/src/kapacitor/components/config/HipChatConfig.js
ui/src/kapacitor/components/config/OpsGenieConfig.js
ui/src/kapacitor/components/config/PagerDutyConfig.js
ui/src/kapacitor/components/config/RedactedInput.js
ui/src/kapacitor/components/config/SMTPConfig.js
ui/src/kapacitor/components/config/SensuConfig.js
ui/src/kapacitor/components/config/SlackConfig.js
ui/src/kapacitor/components/config/TalkConfig.js
ui/src/kapacitor/components/config/TelegramConfig.js
ui/src/kapacitor/components/config/VictorOpsConfig.js
ui/src/style/chronograf.scss
ui/src/style/components/redacted-input.scss

Connect #923
Sanitized settings (such as API tokens) show up as "true" (with an explanation) for kapacitor configuration. This is kind of an odd user experience.
Hide the value unless the user requests to change it.

improve UX for sanitized kapacitor config

---

CHANGELOG.md
ui/src/shared/components/NoKapacitorError.js

The Link on the view presented to the Alerts page when no Kapacitors exist is broken
Update the link to point to the correct route.

Fix broken link to add a Kapacitor when none exist

---

CHANGELOG.md
README.md
canned/phpfpm.json

No phpfpm canned dashboard 😢 
Added a phpfpm dash 😄

add canned dashboard for phpfpm

---

CHANGELOG.md
ui/src/side_nav/containers/SideNav.js

Connect #1363 
This is basically the only link in the app not using the React Router Link component that properly prefixes basepath when a basepath is available.
Fix link.
```shell
make clean
make
./chronograf --basepath /chronograf --prefix-routes
```

Home Logo Link missing basepath support

---

CHANGELOG.md
ui/src/hosts/components/HostsTable.js

Connect #1346
The Hosts Page would display a critical (red) indicator for an offline host if that host had a _negative_ uptime value. Not sure that can happen in the first place (@rkuchan reports that the query includes a `non_negative_derivative`). But even if it could, an uptime value of 0 should also result in a critical indicator.
Report green if uptime is positive. Otherwise, report red.

Show red indicator when a host is down

---

CHANGELOG.md
ui/src/shared/middleware/errors.js

Connect #1336 
User was receiving an error notification to "Please login to use Chronograf." if they had not logged in yet, on the Login page.
Remove that notification. The only remaining notification related to session is for session timeouts.

Remove notification to login outside of session timeout

---

CHANGELOG.md
ui/src/style/pages/dashboards.scss

Menu Options looks ok above a second Y-axis:
But I overlooked that the legend was clipping behind other graphs:
Promote the Menu Options in z-index
Remove the stacking context from `.dash-graph--container`

Promote dash-graph--options, demote dash-graph--container

---

CHANGELOG.md
influx/query.go
influx/query_test.go

Connect #1325 
In parsing InfluxQL binary expressions in the fields were considered valid.
An example would be to divide the fields by 3 in #1325.
If the fields are not `Varref` or `Call` then the parsing will use RawText.

Fix AST influxql for parsing binary expressions in fields

---

CHANGELOG.md
chronograf.go
influx/query.go
influx/query_test.go
server/dashboards_test.go
server/swagger.json

Connect #1377
The legacy `queryConfig` data structure does not support time ranges for queries.  
Extend `queryConfig` with `range`.
Here is the queryConfig fragment from the `/queries` endpoint for the query `select usage_user from howdy where time > now() - 15m`: 
```json
...
"queryConfig": {
"database": "",
"measurement": "howdy",
"retentionPolicy": "",
"fields": [
{
"field": "usage_user",
"funcs": []
}
],
"tags": {},
"groupBy": {
"time": "",
"tags": []
},
"areTagsAccepted": false,
"rawText": null,
"range": {
"upper": "now",
"lower": "15m"
}
...
```

Add Range.Lower and Range.Upper to query config to persist custom ranges

---

CHANGELOG.md
ui/src/hosts/components/HostsTable.js
ui/src/kapacitor/components/KapacitorRule.js
ui/src/kapacitor/components/KapacitorRules.js
ui/src/kapacitor/components/KapacitorRulesTable.js
ui/src/kapacitor/components/ValuesSection.js
ui/src/side_nav/containers/SideNav.js

Fix for #602 
- Alerts Rules Page
- Changed `Trigger` to `Rule Type` in the alert rules table
- Title bar changed from `Kapacitor Rules` to `Alert Rules`
- Changed Side nav item `Kapacitor Rules` to `Alert Rules`
- Alert Config page
- Changed `Values` to `Rule Conditions`
- Changed empty state text to `Please enter a value in the Rule Conditions section`
- Host List page
- Changed `Hostname` to `Host` in table header
- Changed `Filter by Hostname...` to `Filter by Host`

Terminology Terminus

---

influx/query.go
influx/query_test.go
server/dashboards_test.go

Connect #1377 
Front end does not want durations but rather entire binary expressions for time conditionals
Output of `/queries`
```json
{
"queries": [
{
"id": "",
"query": "SELECT \"queryFail\" FROM \"_internal\".\"monitor\".\"cq\" WHERE time > :tmpltime:",
"queryConfig": {
"database": "_internal",
"measurement": "cq",
"retentionPolicy": "monitor",
"fields": [
{
"field": "queryFail",
"funcs": []
}
],
"tags": {},
"groupBy": {
"time": "",
"tags": []
},
"areTagsAccepted": false,
"rawText": "SELECT \"queryFail\" FROM \"_internal\".\"monitor\".\"cq\" WHERE time > :tmpltime:",
"range": {
"upper": "",
"lower": "now() - 15m"
}
},
"queryAST": {
"condition": {
"expr": "binary",
"op": ">",
"lhs": {
"expr": "reference",
"val": "time"
},
"rhs": {
"expr": "binary",
"op": "-",
"lhs": {
"expr": "call", …
```

Update influxql AST parsing to return full binary exprs

---

CHANGELOG.md
ui/spec/data_explorer/reducers/timeRangeSpec.js
ui/src/dashboards/reducers/ui.js
ui/src/data_explorer/actions/view/index.js
ui/src/data_explorer/reducers/timeRange.js
ui/src/hosts/containers/HostPage.js

Connect #1389 
Default timeRange in a Host Page, Data Explorer, or Dashboard was `now() - 15m`. This is shorter than would be expected.
Make the default timeRange `now() - 1 hour`.

Change default global time range to past 1 hour

---

CHANGELOG.md
ui/src/style/pages/kapacitor.scss

Connect #1345 
The styles for alert level color were removed some time ago. In addition, there were specificity issues that could only be solved with !important, since there were already overrides of the bootstrap theme.
With the help of @alexpaxton, add styles back, fix specificity, and also fix hover state.

Fix alert level colors, in addition to hover state color.

---

CHANGELOG.md
ui/src/dashboards/components/TemplateVariableRow.js

Connect #1399 
A user could create a blank template variable by clicking Add Variable and then clicking outside of it.
Have `handleClickOutside` call `handleCancelEdit`.

Make handleClickOutside on TemplateVariableRow work the same as handleCancelEdit

---

CHANGELOG.md
chronograf.go

Connect #1041
LineGraph and Dygraphs were depending on `ruleValues` having a `rangeValue` to ensure that the y-axis was large enough to encompass a defined threshold. If this value was omitted when empty, Dygraphs seems to respect only the range of data. Thus, with a defined threshold far above or below the nominal range of data, the threshold overlay was being hidden.
Don't omit when empty. On a fresh page load, the threshold now appears:

Need RangeValue to correctly calculate Alert graph range

---

ui/src/dashboards/components/CellEditorOverlay.js
ui/src/dashboards/constants/index.js
ui/src/shared/apis/index.js
ui/src/shared/components/AutoRefresh.js

If a query contains a template variable (e.g. `SELECT :tvar: FROM db.rp.meas ...`), then when we ask the server for its queryConfig, we must also provide the current values for those template variables. Otherwise the server understandably can't parse the query in the first place, and returns a syntax error. (Even though the following `proxy` request will succeed, and the user will get data back.)
Submit tvar values along with the query when requesting a queryConfig

Submit tvars when asking for a queryConfig

---

CHANGELOG.md
ui/src/kapacitor/components/KapacitorForm.js
ui/src/kapacitor/containers/KapacitorPage.js

Connect #1271
When previously invalid kapacitor configuration is updated, the alerts section doesn't show until after a refresh. This fixes that.

validate kapacitor connection after updating config

---

CHANGELOG.md
docs/auth.md
oauth2/mux.go
oauth2/mux_test.go
server/logger.go
server/logout.go
server/mountable_router.go
server/mux.go
server/prefixing_redirector.go
server/routes.go
server/routes_test.go
server/server.go
ui/src/index.js
ui/src/shared/actions/auth.js
ui/src/shared/reducers/auth.js
ui/src/side_nav/containers/SideNav.js
ui/src/utils/ajax.js

Connect #1369 
The `--basepath` option didn't work with authentication enabled.
There were several issues with this. The first is that in many places, we were performing string concatenation of paths, which caused strange and unexpected behavior. This can happen with trailing slashes on URLs, and when concatenating fragments like `/foo/` and `/bar/` to yield `/foo//bar/`. The places where we used string concatenation or `fmt.Sprintf` to build paths have been eliminated with extreme prejudice and replaced with `path.Join`.
There's still some situations where the `bouk/httprouter` cares about trailing slashes, and it mostly deals with them by itself. However, because it's unaware of any prefixing that we do, a middleware needed to be added to prefix the `Location` header of 3XX class …

Fix OAuth when using a Basepath

---

CHANGELOG.md
ui/src/index.js

Connect #1393 
Escape does not exit presentation mode when using the safari brower.
Safari `keyup` events do not include a `key` key. To ensure better browser compatibility, we should use the keycode for escape.

support escaping from presentation mode with safari

---

CHANGELOG.md
ui/src/index.js

Connect #1418 
Modern react-router / history usage breaks the app currently because they deprecated a feature that turned a search string into a query object. See: https://github.com/ReactTraining/react-router/issues/4410
Revert to old usage pattern. If we want to use the new pattern, we'll need to add a new package that parses search strings to query objects. There are also a variety of ways to do that, and we'll want to decide on one.

Fall back to useRouterHistory method.

---

CHANGELOG.md
server/prefixing_redirector.go
server/prefixing_redirector_test.go

Connect #1442
When using a basepath of /chronograf, the app would present a
never-ending spinner when visiting the root route. This was because the
prefixingRedirector middleware which is responsible for appending the
basepath to redirects from downstream http.Handlers thought that the
prefix was already appended since it saw `/chronograf/v1`. In reality,
it should have produced a location like `/chronograf/chronograf/v1`.
The solution was to look beyond the first instance of a prefix and check
for the presence of another prefix to detect if a prefix was already
applied by a downstream handler.

Fix infinite spinner with /chronograf basepath

---

CHANGELOG.md
kapacitor/alerts.go
kapacitor/alerts_test.go
kapacitor/ast.go
kapacitor/ast_test.go
ui/src/kapacitor/constants/index.js
ui/src/kapacitor/reducers/rules.js

Kapacitor alerts cannot be set up to write to a log file.
The log alert type is especially useful when experimenting with things locally as it is really cheap to set up.
Add the ability to send alerts to a log file

Add ability to log alerts

---

CHANGELOG.md
ui/src/data_explorer/components/QueryEditor.js

Connect #1462 
In Query Editor, template variable autocomplete would filter based on partial string match at any location within existing template variables, ex. typing `:al` would yield options to autocomplete with `:halpmi:` and `:albertcadalbert:`
Filter based on exact matches from front of string only, so that `:al` would only yield `:albertcadalbert:` and would exclude `:halpmi:`.

Change behavior of Template Variables autocomplete in Query Editor to match from front of string only

---

CHANGELOG.md
ui/src/dashboards/components/TemplateVariableRow.js

Connect #1415 
User could enter empty, whitespace, or duplicate CSV values in template variable manager.
Make entered values a set (uniques only) and remove whitespace entries. This also applies to any values returned via meta queries for the other template variable types (i.e. `Databases`, `Measurements`, `Field Keys`, etc.).

Filter out any template variable values that are empty, whitespace, or duplicates

---

CHANGELOG.md
canned/influxdb_queryExecutor.json

Connect #1362 
Canned influx dashboard queries were in nanoseconds of duration
Update to milliseconds and add label

Update canned influx layout to use milliseconds of duration

---

CHANGELOG.md
ui/src/data_explorer/components/VisView.js

Connect #1463 
When no queries had been entered and the Visualization Type `SingleStat` was selected in Cell Editor Overlay, the user could not then click the `Add Query` button -- rather, it would do nothing. Whereas, when the user would select another Visualization Type without any queries, the `Add Query` button would still work.
Clean up the input to `queries` in the <VisView> component for when there are not yet any queries.

Fix bug on selecting single-stat Visualization Type when no queries

---

CHANGELOG.md
ui/src/index.js
ui/src/localStorage.js
ui/src/shared/actions/errors.js
ui/src/shared/middleware/errors.js

Connect #1498 #1443 #1458
User's localStorage would be cleared on Chronograf version upgrade with only a console notification, so they may be confused as to why they no longer have their queries in Data Explorer and other user settings (time range, auto refresh) are no longer there.
Notify the user via the UI (purple `warning` notification) when local settings have been cleared.

Notify user via UI if their local storage is cleared

---

influx/query.go

Connect #1502
While we were putting `:dashboardTime:` back in the queryConfig, we were neglecting to replace it in the original query string. Turns out the original query string is what eventually becomes `rawText`.
Replace `now() - 15m` with `:dashboardTime:` in the original string as well

After the query is parsed, return query string to :dashboardTime:

---

CHANGELOG.md
ui/src/alerts/components/AlertsTable.js
ui/src/dashboards/components/TemplateControlBar.js
ui/src/data_explorer/components/MeasurementList.js
ui/src/data_explorer/components/QueryEditor.js
ui/src/data_explorer/components/TagListItem.js
ui/src/hosts/components/HostsTable.js
ui/src/shared/components/Dropdown.js
ui/src/style/components/dropdown.scss
ui/src/style/components/template-control-bar.scss

Connect #1462 
- Sometimes a dropdown will have a large amount of items in the list, and manually scrolling is frustrating
- Also, there was some confusion between #1462 and the PR #1474 that got merged, so this PR also reverts those changes and then updates them to be consistent with how filtering is now being done app-wide.
- Option for any dropdown to use autocomplete
- Switches to a text input on click, matches as you type
- Can use up/down arrows to change selection
- Esc cancels the action
- Enter confirms selection (if there is one)
**Thanks to @jaredscheib for helping me do the javascripts for this one**

Dropdown Autocomplete

---

ui/src/dashboards/components/TemplateControlBar.js
ui/src/dashboards/components/TemplateVariableRow.js

Connect #1415
User could input whitespace and duplicate values into CSV when adding a Template Variable. The Previous PR (#1485) did not actually prevent the values from being saved, rather just removed them from view in the Template Variable Manager.
- Actually remove the values from their respective data set altogether.
- Changes the `Loading...` text in an empty TV selector to `(No values)`
- Makes the `v => v.value` syntax change requested by @lukevmorris in the previous PR.

Actually dedupe and remove whitespace characters from Template Variable input (and selectors)

---

CHANGELOG.md
ui/src/dashboards/components/DashboardHeaderEdit.js

Connect #1420 #1421 
Pressing escape for cancel or enter for submit doesn't do the expected thing when renaming a dashboard.
Use a form and onSubmit handler for the title, and add a onKeyUp handler that detects escape and returns the contents of the component to its original state while canceling editing.

Enable expected Enter/Escape keys on Dashboard rename

---

CHANGELOG.md
ui/src/kapacitor/components/KapacitorForm.js
ui/src/kapacitor/components/config/AlertaConfig.js
ui/src/kapacitor/components/config/HipChatConfig.js
ui/src/kapacitor/components/config/OpsGenieConfig.js
ui/src/kapacitor/components/config/PagerDutyConfig.js
ui/src/kapacitor/components/config/SMTPConfig.js
ui/src/kapacitor/components/config/SensuConfig.js
ui/src/kapacitor/components/config/SlackConfig.js
ui/src/kapacitor/components/config/TalkConfig.js
ui/src/kapacitor/components/config/TelegramConfig.js
ui/src/kapacitor/components/config/VictorOpsConfig.js
ui/src/kapacitor/containers/KapacitorPage.js

Connect #1496 
- Language in the UI is a little confusing
- Followed @nhaugo's suggestions and rewrote the micro copy
- Success alert now reads `Kapacitor Created! Configuring endpoints is optional`
- When creating a new kapacitor, the connection details button reads `Connect`, when editing a kapacitor the button reads `Update`
- Instead of the giant blue `Save` button, it now reads (for example) `Update OpsGenie Config` which more accurately describes what the button does

Kapacitor UI/UX improvements

---

CHANGELOG.md
influx/query.go
influx/query_test.go

Connect #1158 
Query config fields were assumed to remain in the same order as they were submitted, but their order could arbitrarily change.
Server now preserves the order of the field keys by preserving the initial order of the field keys instead of using a `map`, which randomly reorders.

Update query config field ordering to always match input query

---

CHANGELOG.md
kapacitor/client.go
kapacitor/client_test.go
server/kapacitors.go
server/kapacitors_test.go
ui/spec/kapacitor/reducers/rulesSpec.js
ui/src/kapacitor/actions/view/index.js
ui/src/kapacitor/components/DataSection.js
ui/src/kapacitor/components/KapacitorRule.js
ui/src/kapacitor/constants/index.js
ui/src/kapacitor/containers/KapacitorRulePage.js
ui/src/kapacitor/reducers/rules.js

Connect #1531
- In the Chronograf client, a user could not update an existing Kapacitor rule's field to use a function, if a function had not been applied when that rule was created.
- The client was including a default `30s` value for `.every` without respect to whether a field had yet been applied to the query (or a function to a field).
- The server was returning the Kapacitor rule request object to the client as the response, rather than the rule as it was actually persisted to the database.
- Server wasn't performing request validation (unlike other data coming to server)
- Explicitly set the `.every` property of a rule to `30s` or `null` when adding a function to a field, or removing that field from the alert query, via dedicated Redux action creators.
- Return the persisted …

Enforce Kapacitor alert schema agreement between client and server

---

CHANGELOG.md
ui/src/dashboards/components/CellEditorOverlay.js
ui/src/dashboards/components/OverlayControls.js
ui/src/shared/components/ConfirmButtons.js
ui/src/shared/components/LayoutRenderer.js

Connect #1429 
When using the CEO, if a user selected a db and measurement and then saved the app got into a funky state.
Only allow the user to save if a queryConfig is 'fully qualified' or contains `rawText`.  A fully qualified query is one which contains a db, measurement, and field.  These are the minimum data required for InfluxDB to retrieve time series. 
Better feedback as to why a user cannot save. Would like to add a tooltip or more descriptive title message.

Save CEO only with fully qualified queries

---

CHANGELOG.md
influx/query.go
influx/query_test.go

Connect #1529
InfluxQL with several tag values for a specific tag key was not parsing correctly into queryConfig
Check for `OR` statements in binary expression depth first walk.

Fix parsing of InfluxQL with multiple tag values

---

CHANGELOG.md
ui/src/localStorage.js

Connect #1580 
On fresh install of Chronograf, localStorage would be `null` and the user would receive a warning of failure to load local storage. This apparently led one user to not even use Chronograf: https://twitter.com/gkreimer/status/870388663573729280.
Update `null` localStorage state handling logic in `loadLocalStorage` to simply load a clean slate on fresh install.

Fix load localStorage and warning UX on fresh Chronograf install

---

CHANGELOG.md
ui/src/App.js

Connect #1583 
Submenus would not appear after stopping an InfluxDb source while connected to it. It turned out that this was due to a z-index issue stemming from the ordering of top-level components in the DOM, so that while an alert notification was on-screen, the submenus would be hidden. If you x-ed out of the notification, the submenus would appear.
Switch the order of the `<Notifications>` and `<SideNav>` components in `index.js` -- voilà!

Fix hidden submenus when alert notification on screen

---

.bumpversion.cfg
docs/release.md

To help with the release run this:
```sh
bumpversion --allow-dirty   --new-version=1.3.2.0 patch
```
Allow dirty just means that you files that are not checked in.

Update bumpversion and documentation for release

---

CHANGELOG.md
ui/src/dashboards/containers/DashboardsPage.js
ui/src/data_explorer/containers/Header.js
ui/src/external/dygraph.js
ui/src/hosts/components/HostsTable.js
ui/src/hosts/constants/tableSizing.js
ui/src/kapacitor/components/KapacitorForm.js
ui/src/kapacitor/containers/KapacitorPage.js
ui/src/shared/components/LayoutRenderer.js
ui/src/shared/components/LineGraph.js
ui/src/sources/components/InfluxTable.js
ui/src/style/components/dygraphs.scss
ui/src/style/components/tables.scss
ui/src/style/pages/admin.scss
ui/src/style/pages/dashboards.scss
ui/src/style/pages/kapacitor.scss
ui/src/style/pages/overlay-technology.scss
ui/src/style/theme/bootstrap-theme.scss
ui/src/style/unsorted.scss

Connect #1566 
Connect #1528 
Connect #1595 
- See above issues
- The theme had its own autoprefixer before being added to the project
- Kapacitor flow slightly confusing
- Unclear if deleting influxdb source or kapacitor
- Delete button too close to connect
- Clarity over which source is connected could be improved
- If a Kapacitor config has a really long name it overlaps with the icons:
- If a Kapacitor shares a name with another Kapacitor (scoped to the same source) the dropdown menu shows all as active
- Remove autoprefixer from theme repo, so that when it comes into Chronograf it is unprefixed, this way there is only one level of autoprefixer and Chronograf's implementation is preferred over the one in the theme
- Also chopped out more excess styles from the theme
- `218kb` --> …

Misc Aesthetic & UX Improvements

---

docs/GETTING_STARTED.md
docs/INSTALLATION.md
docs/auth.md
docs/tls.md
docs/use_cases.md
ui/src/data_explorer/components/WriteDataForm.js
ui/src/kapacitor/components/config/TelegramConfig.js

Connect #1615 #1613 
Docs links were hard-coded to specific version numbers.
Better future-proof these links by updating to `/latest`.

Better future-proofs docs links by using 'latest' in URL

---

CHANGELOG.md
bolt/internal/internal.go
chronograf.go
influx/influx.go
influx/influx_test.go
influx/query.go
influx/templates.go
influx/templates_test.go
server/queries.go
server/templates_test.go
ui/spec/data_explorer/reducers/queryConfigSpec.js
ui/src/dashboards/containers/DashboardPage.js
ui/src/data_explorer/actions/view/index.js
ui/src/data_explorer/components/FieldList.js
ui/src/data_explorer/components/GroupByTimeDropdown.js
ui/src/data_explorer/components/QueryBuilder.js
ui/src/data_explorer/constants/index.js
ui/src/data_explorer/data/groupByTimes.hson
ui/src/data_explorer/reducers/queryConfigs.js
ui/src/shared/actions/timeSeries.js
ui/src/shared/components/AutoRefresh.js
ui/src/shared/components/Dygraph.js
ui/src/shared/components/LineGraph.js
ui/src/shared/constants/index.js
ui/src/utils/influxql.js
ui/src/utils/queryTransitions.js
ui/src/utils/queryUrlGenerator.js

Connect #1471 
It's far too easy to select more data than your monitor can actually display.
This introduces a new template variable, `:autoGroupBy:`, which calculates a group by time based off of the available resolution for rendering a graph (per @goller 's math in #829). This is supplied by Dygraphs along with the query.
This introduces another "type" of template variable, a `GroupByVar`, which handles this calculation and is instantiated by a custom `UnmarshalJSON`, capable of determining Template Variable types. Also, Template Variables now have varying precedence, as `GroupByVar` must be applied after all template variables so that it can see the selected time range in the query.
1. This currently works only with data reporting at the Telegraf default of 10s. There is some follow-on …

Add auto group by functionality using :interval: template variable

---

ui/src/shared/data/timeRanges.hson
ui/src/status/reducers/ui.js

Connect #1608 
Somewhere along the line, a 90d timeRange was being used for testing purposes and accidentally got committed and included in the PR, so the Status Page bar graph and Alerts are based on a 90d time window, despite saying "30 days".
- Fix the status reducer to use `30d` instead of `90d`
- Remove the 90d option from timeRanges.hson

Fix Status Page timerange to be 30d again

---

CHANGELOG.md
ui/src/status/apis/index.js
ui/src/utils/ajax.js

Connect #1640 
If a user was using the server options to prefix their routes with a basepath, a prefixed basepath was being added to the new external news feed link, resulting in an incorrect URL and failure to load the news feed.
- Implement an option to exclude basepath from urls in `ajax.js`.
- Have `fetchJSONFeed` in `/status/apis` utilize this exclusion.
- get your `<provider-client-id>` and `<provider-client-secret>` from your OAuth provider settings and use them below
- run Chronograf via `./chronograf -d -i <provider-client-id> -s <provider-client-secret> -t supersecret2 --auth-duration=15m --prefix-routes -p <your-basepath>`
- make sure your OAuth provider settings (such as on GitHub/settings) use the same basepath that you used in `<your-basepath>` above (i.e. `/chronograf`) in …

Do not prefix basepath to external link for news feed

---

CHANGELOG.md
ui/src/shared/components/LineGraph.js

Connect #1651 
A regression was introduced where the x and y axes were removed and other stylistic changes were modified for Line + Single Stat graphs.
Add both axes and grid back in.

Revert removal of x and y axes and some style changes on Line + Single Stat graphs

---

CHANGELOG.md
oauth2/auth0.go
server/server.go

Auth0 is an OpenID Connect compliant OAuth2 provider, so we're able to
re-use the generic OAuth2 provider to implement it. The routes required
by Auth0 have been hardcoded for user convenience.
Also, Auth0 requires users to register a subdomain of auth0.com when
signing up. This must be provided to chronograf through the
`--auth0-domain` parameter (or `AUTH0_DOMAIN` ENV). This is **distinct**
from the `PUBLIC_URL`. For example, for a Chronograf hosted at
`http://www.example.com`, and an Auth0 domain of
`http://oceanic-airlines.auth0.com`, a client-id of `notpennysboat` and a
client-secret of `4-8-15-16-23-42`, the command line options would look
like:
```
chronograf \
--auth0-domain=http://oceanic-airlines.auth0.com \
--auth0-client-id=notpennysboat \
--auth0-secret=4-8-15-16-23-24 …
```

Add Auth0 to supported OAuth2 providers

---

CHANGELOG.md
ui/src/alerts/components/AlertsTable.js
ui/src/alerts/constants/tableSizing.js
ui/src/alerts/containers/AlertsApp.js
ui/src/style/components/tables.scss
ui/src/style/unsorted.scss

Connect #1630 
- Once a user has accrued a large volume of alert events, the table headers become unusable
- Similarly, when the table appears in the Status Page it is even smaller and the headers disappear sooner
- Make the table stretch to fill height of its parent
- Make the table body scrollable instead of the table's container
- Make sure the table looks and feels great in both instances
- Initially tried setting `<tbody>` to `overflow: scroll` and in order to achieve that `<table>`,`<thead>`, and `<tbody>` all need their `display` CSS property changed away from the table standards
- This breaks the only major benefit of using HTML tables: columns stayed the same width between the header and body
- Used `<div>` with fixed % widths to imitate a table
- Set the cell text wrap style to …

Sticky Alert Table

---

CHANGELOG.md
ui/src/shared/components/DatabaseDropdown.js

Connect #1570 
Users should not write to \_internal, or generally any other database preceeded with an '\_', as we take that to mean a system-internal database of some kind. This filters the list of databases to remove those with names preceeded by a '\_' character.
Also 'SHOW DATABASES' can return an error if users are not authorized to do that, so it's important to throw that so it can be properly handled / displayed to the user.
EDIT: It was decided that the only system database is the `_internal` database, so a patch was added to explicitly remove just that database name instead of all database names prefixed with an underscore.

Remove system databases from "Write Data" dropdown

---

oauth2/auth0.go

Connect #1667 
We need the email address from OIDC when using auth0 for authentication.

add email to auth0 required scopes

---

CHANGELOG.md
ui/src/admin/components/DatabaseRow.js

Connect #1678
Validation logic in the "DatabaseRow" component made some optimistic
assumptions about the presence of the "replication" in state.
Replication won't be present in OSS or Influx Relay sources, so when
users tried to update other properties of a retention policy, it failed
with an error that indicated "replication" was undefined.
Since this is expected and desired behavior, this patch uses the
existing "isRFVisible" property to determine whether or not we should
process the "replication" part of the component's state, or simply
replace it with a "1", which is the only allowed value for
non-Enterprise sources.

Fix RP duration editing on admin page

---

CHANGELOG.md
ui/package.json
ui/src/dashboards/components/TemplateControlBar.js
ui/src/style/components/template-control-bar.scss
ui/yarn.lock

@timhallinflux pointed out this UI issue with the Template Variable dropdowns
Depending on the variety of string lengths in a Template Variable dropdown menu, it resizes in unexpected ways
Determines the required length in pixels based on the length of the
longest item in the menu and only sets it if it is greater than the
minimum dropdown width. Using [this package](https://github.com/schickling/calculate-size) as per @cryptoquick's recommendation. 
There is a maximum width of `300px` for the dropdowns. This number is somewhat arbitrary as I have no idea how it relates to common string lengths in the menu during actual use. if it makes sense later to increase the max width it will easy to adjust. If an item exceeds max width it just wraps text:

Prevent TempVar Dropdown Size Jitter

---

ui/src/shared/components/NameableGraph.js
ui/src/style/pages/dashboards.scss

Connect #1604 
It is hard for users to discern which cells are not using `:dashboardTime:` at a glance. This can be problematic when changing the global time range
Cell headers show a little indicator with the custom time range in it
Currently this will only show 1 indicator. I tried building a graph with two queries, each with a different custom time range, and it breaks dygraph. I am operating under the assumption that users are not using multiple time ranges in a single cell.

Display Custom Time Range on Cell

---

ui/package.json
ui/yarn.lock

Connect: No issue
node-sass breaks the build / install process with Node 8.
node-sass needed to be upgraded in order for chronograf to build on Node 8.

Fix node-sass version for Node 8 support.

---

CHANGELOG.md
oauth2/auth0.go
oauth2/auth0_test.go
server/server.go

Users were previously unable to categorize Auth0 users into organizations like
they have been able to with other OAuth2 providers, like Github, Google, and
Heroku. This limits the usefulness of the Auth0 integration.
Unlike other providers, Auth0 allows greater flexibility in what is returned to
applications. Many plugins exist which modify Auth0's responses. Knowing this,
it was important to adopt something light-weight which could be supported both
by human administrators as well as automation.
This requires operators to configure Auth0 to apply an "organization" key to
each user in the "app_metadata" section of each of their users ("app_metadata"
is read-only by users). The value of this key should be a string identifying
the organization that the user belongs to. This can either be …

Add support for Auth0 organizations

---

CHANGELOG.md
chronograf.go
chronograf_test.go
cmd/chronograf/main.go
mocks/logger.go
mocks/servers.go
server/server.go
server/url_prefixer_test.go

Connect #1555 
Upon spinning up new installation of Chronograf, a user had to manually configure a new InfluxDb source and respective Kapacitor server as their first task. This was a jarring experience, as it would be much nicer to be dropped directly into a functional application, assuming default source and kapacitor settings.
Add a server flag to allow new sources to be added automatically (and idempotently) when server runs, which can be set via CLI (`--new-sources`) or ENV var (`NEW_SOURCES`). This way default sources and kapacitors can be added to a fresh installation of Chronograf. (This could also be seen as allowing a kind of safety for source persistence, in case a user were to delete a Chronograf source that would automatically be re-persisted upon re-running the server.)
``` …
```

Add server flag to add new InfluxDb source and Kapacitor server

---

CHANGELOG.md
ui/src/style/pages/dashboards.scss

Connect #1643
Due to the z-index being set for the entire .dash-graph--options div, when the context menu is shown and overlaps another caret, the caret will display above the context menu.
Move the z-index declaration to the .dash-graph--options-menu ul (removing it from .dash-graph--options div). The z-index is unnecessary for the entire div, it is only needed for the ul so that it displays above the other elements.
P.S. This is my first open source contribution. Pretty excited! Please let me know if I did anything incorrectly

Fix z-index for options context menu

---

CHANGELOG.md
ui/.eslintrc
ui/src/kapacitor/actions/view/index.js
ui/src/kapacitor/components/KapacitorRules.js
ui/src/kapacitor/components/KapacitorRulesTable.js
ui/src/kapacitor/components/TICKscriptOverlay.js
ui/src/kapacitor/constants/tableSizing.js
ui/src/kapacitor/containers/KapacitorRulePage.js
ui/src/kapacitor/containers/KapacitorRulesPage.js
ui/src/shared/apis/index.js
ui/src/style/components/tables.scss
ui/src/style/unsorted.scss

Connect #1663 
Users can build TICKscripts with our Kapacitor Rule generator but there's no way to see the sweet scripts in the UI!
Add some UI!
Removed a silly eslint rule for no setState in componentDidMount.  We do this everywhere but they weren't triggered when in a `then` block.  Even airbnb thinks its [silly as a standard](https://github.com/airbnb/javascript/issues/684#issuecomment-284392220).

View server generated TICKscripts

---

CHANGELOG.md
server/server.go

Connect #1716 
The example path for configuring the BoltPath server flag could have been misleading, since the example gave a path that was not the same as what the default value for that flag is.
Make the example flag the same as the default value.

Clarify BoltPath server flag help text by making example the default path

---

CHANGELOG.md
kapacitor/ast.go

Connect #1748 
Adding a PagerDuty Kapacitor node may have been broken due to a typo.
Fix the typo.

Fix PagerDuty kapacitor node typo bug

---

CHANGELOG.md
ui/src/data_explorer/components/GroupByTimeDropdown.js
ui/src/kapacitor/components/DataSection.js
ui/src/kapacitor/components/KapacitorRule.js
ui/src/utils/queryTransitions.js

Connect #1730 
`auto` was appearing as an option (and the default option) in Kapacitor rule builder when a user would apply a function a field. This doesn't make sense and also would cause an unspecific error notification to the user (unless they looked at the console) when they tried to save their alert, if they had applied a function to a field and didn't change their GROUP BY away from the default option of 'auto', resulting in confusion and no insight into how to successfully save an alert.
Make `10s` the default option for Kapacitor rule builder function field GROUP BY dropdown, and prevent 'auto' from appearing.

Prevent 'auto' GROUP BY option in Kapacitor rule builder

---

CHANGELOG.md
kapacitor/ast.go
ui/src/kapacitor/components/RuleMessage.js
ui/src/kapacitor/constants/index.js
ui/src/kapacitor/containers/KapacitorRulePage.js
ui/src/kapacitor/reducers/rules.js

Connect #1755 
Connect #1761 
- New Kapacitor alert refactoring caused some services to go away that were previously implemented generically.
- The `alertNodes` property of a rule was being modified incorrectly in its Redux state.
- Add all supported Kapacitor alert types, with as many optional properties as are currently understood or known. Some seem to require special formatting and have had `TODO`s placed next to them.
- Make the `UPDATE_RULE_ALERT_PROPERTY` reducer update state correctly so that multiple Kapacitor alert services for different rules can be added without error or breaking.
There are a number of `TODO`s and commented-out properties added to `/ui/src/kapacitor/constants/index.js` that make the set of properties and arguments for each supported service comprehensive, but …

Restore and add all supported Kapacitor alert services; fix Kapa alert state bug

---

ui/README.md
ui/karma.conf.js
ui/package.json
ui/yarn.lock

Fine-grained insight into tests that have been run is missing – we only see `dots`.
Add a dev dependency for karma verbose reporting, and comment two options for more detailed reporting in karma config.

Add option for verbose reporting in client unit tests

---

CHANGELOG.md
ui/src/sources/containers/ManageSources.js

Connect #1671 
It wasn't fully clear what product `Version x.x.x.x` referred to on the Sources page, for the Chronograf version, since it was in the context of configuring InfluxDB and Kapacitor as well.
Explicitly state `Chronograf Version x.x.x.x`.

Specify that version is for Chronograf on Sources page

---

CHANGELOG.md
ui/src/style/components/fancy-scrollbars.scss

Connect #1706 
Connect #1692 
- Occasionally scrollbars in the browser render in an unexpected way
- Unclear whether this is a chrome issue or `react-custom-scrollbars`
- `margin-right: -16px !important` is set on the scroll containers but when the scrollbars don't render properly this becomes a UI bug affecting all instances of `react-custom-scrollbars`
- Remove the negative margin fix until the intermittent nature of `react-custom-scrollbars` can be diagnosed

Fix clipped scroll containers

---

.bumpversion.cfg
CHANGELOG.md
README.md
server/swagger.json
ui/package.json

Release 1.3.5.0
1. [#1708](https://github.com/influxdata/chronograf/pull/1708): Fix z-index issue in dashboard cell context menu                                                                                            
1. [#1752](https://github.com/influxdata/chronograf/pull/1752): Clarify BoltPath server flag help text by making example the default path                                                                   
1. [#1703](https://github.com/influxdata/chronograf/pull/1703): Fix cell name cancel not reverting to original name                                                                                         
1. [#1751](https://github.com/influxdata/chronograf/pull/1751): Fix typo that may have affected PagerDuty node creation in Kapacitor …

Release 1.3.5.0

---

ui/src/data_explorer/containers/Header.js
ui/src/kapacitor/components/RuleHeader.js
ui/src/shared/components/TimeRangeDropdown.js
ui/src/style/components/custom-time-range.scss

Connect #1764 
Connect #1784
- Custom Time Ranges was broken in Data Explorer and would show an Invalid Date message as its value.
- Custom Time Ranges should not have appeared as an option in Alert Rules.
- Fix Invalid Date bug in Data Explorer by using custom time ranges when provided to component
- Allow Custom and Preset time ranges in Data Explorer
- Preserve custom timeRange in Data Explorer when valid dates
- Remove Custom Time Range as an option from Rule Alerts

Fix Custom Time Range and Preset options in Data Explorer; remove CTR option from Rule Builder

---

CHANGELOG.md
ui/src/dashboards/containers/DashboardPage.js

Connect #1669 
Console error spam from dygraph's synchronize function.  
Don't synchronize graphs if there's only one graph ya silly goose.

Dont sync graphs if there is only one graph

---

CHANGELOG.md
ui/src/data_explorer/components/Visualization.js

Connect ##1611
In the CEO, the domain for the visualization did not update when a user updated the timeRange in InfluxQL.  
Give preference to a `queriesConfig`s `range`.

Give preference to queryConfig range

---

CHANGELOG.md
ui/src/status/actions/index.js

Connect #1628 
If a JSON Feed failed to be retrieved, the error message was generic.
Improve the error message by providing the URL and a slightly more specific message when a failure occurs.
It turns out that, given that we are attempting to access the JSON Feed resource directly from the Chronograf client, we are not provided with a status code for failure, even though the browser knows why the XHR failed. So it's not possible to use the status code for a greater variation of error messages. It may be that there is some tweaking that can be done to the XHR, including handling possible pre-flights performed, in order to gain access to this error code. I drilled into Axios pretty deeply, and it doesn't appear that updating to https://github.com/mzabriskie/axios/releases/tag/v0.16.2 (which …

Improve error message on JSON Feed GET fail

---

CHANGELOG.md
ui/src/alerts/components/AlertsTable.js

Connect #1813 
Console error and dropped items would occur in AlertsTable due to assigning the same `key` to multiple items.
Generate and assign a UUID for each AlertsTable key.

Use UUID for AlertsTable element keys to prevent overlap

---

CONTRIBUTING.md
Makefile
ui/README.md
ui/karma.conf.js
ui/package.json

While `npm` is still installed as part of the build process, most of the
scripts and documentation should be using yarn.
Change `npm` to `yarn` where appropriate.
Signed-off-by: Nathan L Smith <smith@nlsmith.com>
Some places in docs and scripts still use `npm` where `yarn` is more appropriate.
Change these occurrences.

Change some remaining npm mentions to yarn

---

ui/src/data_explorer/components/VisView.js
ui/src/shared/components/RefreshingGraph.js

Connect #1850 
No more sweet error / success messages in the DataExplorer or Chart Creator (what do you think of that instead of CellEditorOverlay?)
Looks like somewhere down the line of refactor the `editQueryStatus` action wasn't being passed along.

Success / error messages for queries not displaying

---

CHANGELOG.md
ui/src/style/components/ceo-display-options.scss
ui/src/style/pages/overlay-technology.scss

- On small screens the gutter around the lower half of the CEO feels unnecessary
- Remove the space

Make lower half of CEO flush to the viewport

---

CHANGELOG.md
server/server.go

Connect #1861 
It was not fully clear that a user could set their `type` for their Chronograf source from the sample given in the server flag for `--new-sources`.
Add `type: influx-enterprise` to that part of the help section.

Add 'type' to new-sources server flag example

---

CHANGELOG.md
server/cells.go
server/cells_test.go

Because we are now creating new instances of dashboards when we create a
response, it's critical to copy every element of Dashboards from the
previous to the new instance.
We were not previously copying the Type field of cells, so this was
defaulting to the empty string zero value. This patch adds "Type" to the
tests and ensures that it's properly copied
Connect #1865

Fix missing cell type

---

chronograf.go
chronograf_test.go

Previously, users of the :interval: macro were restricted to using a
relative time range in their queries, or the :dashboardTime: macro. This
permits users to also supply an absolute time range in the form of:
time > '2017-01-01T00:00:00Z' and time < '2017-06-01T00:00:00Z'
Connect #1700

Add absolute time range support to :interval:

---

CHANGELOG.md
ui/src/dashboards/components/Dashboard.js
ui/src/shared/components/AutoRefresh.js
ui/src/shared/components/NameableGraph.js

Connect #1765 
- New users don't immediately know how to edit a cell
- Add a nice big button to make the `edit` feature discoverable

Add button to cell for improved user experience

---

CHANGELOG.md
ui/src/data_explorer/components/QueryMaker.js

Connect #
Fixes QueryMaker not updating query time range when a the time range was changed through the time range dropdown.
Prevent the queryConfig range from superseding the supplied range argument.

Fix Data Explorer Raw Query time range not getting updated through dropdown

---

CHANGELOG.md
ui/src/dashboards/graphics/graph.js
ui/src/style/components/ceo-display-options.scss
ui/src/style/components/opt-in.scss
ui/src/style/unsorted.scss

Connect #1918 
Connect #1873 
Connect #1923 
- Safari has weird flexbox quirks that work fine everywhere else
- `OptIn` component renders strangely in Safari
- Using a less elegant but more cross-browser compatible positioning approach
- Position `OptIn` gradient more explicitly

Add missing attributes for safari compatibility

---

canned/mem.json

Connect #1892 
Unsing line-stacked in mem.json could be more meaningful given that used + available = tota
Change type in mem.json

Use line stacked in mem.json (#1892)

---

CHANGELOG.md
ui/package.json
ui/spec/shared/parsing/getRangeForDygraphSpec.js
ui/src/shared/parsing/getRangeForDygraph.js
ui/yarn.lock

Connect #1857 
Connect #1900 
When y-values were the same throughout all time ranges the graph got into a very ugly state.  
Respect selected range when calculated ranges are equal, and be a bit smarter about what to do by default if min and max are equal.
Run the shell script in #1857 and follow the instructions locally.

Fix equal min max bug

---

CHANGELOG.md
ui/src/kapacitor/components/RuleMessageOptions.js
ui/src/style/pages/kapacitor.scss

Connect #1875 
- Optional Alert Parameters visually inconsistent
- Styles inline instead of in a stylesheet
- Modified design such that the section that appears is always labelled `Optional Alert Parameters`
- Wrote some styles specifically for form groups in this section

Polish Optional Alert Parameters

---

CHANGELOG.md
ui/src/side_nav/components/NavItems.js
ui/src/side_nav/containers/SideNav.js
ui/src/style/layout/sidebar.scss

Connect #1760 
Connect #1690 
- Logo tile for `Status` page has no `active` state
- Mousing from a hovered nav item to a sub-nav item can sometimes cause a hover on the item below (undesired)
- Make an active state for the logo tile
- Insert an invisible triangle between the nav item and nav menu when there are sub-nav items present
_NOTE: The red triangle is actually transparent, but for the sake of illustrating where the helper area is I have made it red_

Sidebar Polish

---

CHANGELOG.md
ui/src/kapacitor/containers/KapacitorPage.js

Connect #1919 
Could not add a kapacitor from source page with a clean chonograf-v1.db
The `kapacitors` list on `source` was not yet defined.  So, I added
a default empty array to the `kapacitors` key.  
Cleaned up some logic regarding the prevention of dup of kapacitor names.

Fix inability to add kapacitor from source page

---

CHANGELOG.md
ui/spec/data_explorer/reducers/queryConfigSpec.js
ui/src/shared/components/FieldList.js
ui/src/utils/queryTransitions.js

Connect #1576
It appears the queryConfig in the `DataExplorer` got into a state where the `fields` key was missing.  
Toughen up the happy path of query creation in the `FieldList` component and `toggleField` function in `/queryTransitions`
1) Go to `DataExporer`
2) Build a query with a field
3) Go into console
4) Go to Application tab
5) Delete the `fields` key from localStorage
6) Navigate away from DE and back again try clicking on fields and watch everything break
Really we should be validating every qC that gets saved to localStorage and preventing bogus state from getting saved in the first place.

BUGFIX: 'fields' property missing from queryConfig in DataExplorer

---

ui/src/alerts/components/AlertsTable.js

Connect #1953 
If no host was provided in an alert, the alert would disappear when the component updated
Fix the filtering function

Fix alerts table to display if alerts are missing a host, name, or level

---

CHANGELOG.md
ui/src/shared/components/Dygraph.js
ui/src/shared/parsing/getRangeForDygraph.js

Connect #1766 
Connect #1460  
Stacked graphs ranges were incorrect and resulted in entire visualization not being displayed.
Allow Dygraphs to do the proper range calculation while respecting user defined ranges.

BUGFIX: Stacked graph bug

---

CHANGELOG.md
ui/package.json
ui/src/shared/middleware/resizeLayout.js
ui/yarn.lock

Connect #1208 
One of our users is linking to Chronograf in iframes. If one could enter presentation mode automatically from simply adding a param to the URL, that'd be really useful.
If `present` is present on the URL search property, the application will automatically enter presentation mode on just about any page it's used on. This was done by adding that detection to the middleware, which I think is the most appropriate solution.

Add 'present' url param detection to presentation mode middleware

---

CHANGELOG.md
ui/src/dashboards/actions/index.js
ui/src/dashboards/containers/DashboardPage.js
ui/src/data_explorer/actions/view/index.js
ui/src/shared/middleware/queryStringConfig.js
ui/src/shared/middleware/resizeLayout.js
ui/src/store/configureStore.js

Connect #1968 #1815 
There have been several query string issues, and additional query string functionality was requested.
Enough things were needing to use queryStrings that it makes sense to find a place for them in one middleware dedicated to just query string configurations. A file for this was made, and query string config domains were consolidated (presentation mode, select template variable by name, and the new data explorer query config).
Update: I'm removing the DE QC `query` query string code in order to take a different approach for that feature.

Refactor query string middleware

---

CHANGELOG.md
ui/src/kapacitor/components/DataSection.js
ui/src/kapacitor/components/Deadman.js
ui/src/kapacitor/components/KapacitorRule.js
ui/src/kapacitor/components/Relative.js
ui/src/kapacitor/components/Threshold.js
ui/src/kapacitor/components/ValuesSection.js
ui/src/kapacitor/containers/KapacitorRulePage.js
ui/src/shared/components/Tabs.js
ui/src/shared/parsing/getRangeForDygraph.js
ui/src/style/pages/kapacitor.scss

Connect #1890 
The UI is lying to our users.
Chronograf makes it appear that you can set a deadman rule for a specific field. However, in Kapacitor this is not the case. Kapacitor considers something dead if a database, retentionPolicy, measurement and set of optional tags have not reported over a specified time interval. Put another way, for a deadman trigger Kapacitor doesn’t care about which fields exist, only that one exists.
Do not reveal fields or a graph to the user if the deadman trigger is selected.

WIP BUGFIX: deadman

---

CHANGELOG.md
LICENSE_OF_DEPENDENCIES.md
ui/spec/shared/parsing/resultsToCSVSpec.js
ui/src/data_explorer/components/VisHeader.js
ui/src/data_explorer/components/VisView.js
ui/src/data_explorer/components/Visualization.js
ui/src/data_explorer/containers/DataExplorer.js
ui/src/external/download.js
ui/src/shared/parsing/resultsToCSV.js
ui/src/style/unsorted.scss

Connect [#1405](https://github.com/influxdata/chronograf/issues/1405)
Users would like to be able to download their data from the data explorer in .csv format. 
Users are able to download their data in .csv format. The .csv download button calls an action to receive the most updated data available.

Add .csv download button to data explorer

---

CHANGELOG.md
ui/src/shared/components/QueryStatus.js

Connect [#1972](https://github.com/influxdata/chronograf/issues/1972)
Query Templates dropdown is not visible for a newly created query editor window, until some data is selected- it also disappears after being used. 
Query Templates dropdown is now visible at query creation, and remains visible after it is used.

Display Query Templates dropdown even when status is null

---

CHANGELOG.md
ui/spec/admin/reducers/adminSpec.js
ui/src/admin/components/DatabaseManager.js
ui/src/admin/constants/index.js
ui/src/admin/containers/DatabaseManagerPage.js
ui/src/admin/reducers/admin.js

Connect [#1283](https://github.com/influxdata/chronograf/issues/1283)
No visual feedback that db creation has failed when user tries to create a database with a name that already exists in databases
Show alert when new db has a name that matches an existing db name

Display error if new db name matches an existing db name

---

CHANGELOG.md
ui/src/shared/components/RefreshingGraph.js
ui/src/shared/copy/cell.js
ui/src/style/components/graph.scss

Connect #1986 
See #1986 
In `Dashboard` => `DisplayOptions`.  If a user selected a visualization type before creating a query, the `CellEditorOverlay` component and corresponding `Cell` in that dashboard would become unresponsive.
I'm really happy that this bug was discovered as it provided the perfect opportunity to fix some UX.  You see, when a user goes to edit a cell for the first time, the first thing they see is:
'No results'?!?  From what?!? I didn't do anything.  Or did I?  I don't understand.  I am sad.
So now, when a user doesn't have any queries.  Instead of making calls to a 'host' with a non-existent query we now return more fun and useful guidance like: 
Which, as a lovely side-effect stops the overlay and cell from freezing up.

BUGFIX: Unresponsive query builder, display options, and cell

---

CHANGELOG.md
ui/src/kapacitor/containers/KapacitorPage.js

Connect #1999 
This error would flash when editing a kapacitor source:
Only fire that error when creating a new kapacitor source.

BUGFIX: Fix improper banner error for duplicate kapacitor name

---

CHANGELOG.md
ui/src/hosts/apis/index.js

Connect #2014 
Chronograf permanently shows "critical" status for windows hosts when metrics are saved in non-default database:
In this PR I removed hardcoded "telegraf" database from the query.

Chronograf shows real status for windows hosts when metrics are saved in non-default db

---

CHANGELOG.md
chronograf.go

Single value custom ranges do not return a duration
Fix that

Fix for single value custom time ranges

---

CHANGELOG.md
ui/src/shared/components/Dygraph.js
ui/src/style/components/dygraphs.scss

Connect #2024 
- When hovering over a cell at the bottom of the screen the legend appears on top of the graph, making it hard to actually see what you are doing
- Position the legend above the graph instead of on top of the graph
- Add indicator arrows to make it more clear which cell the legend is pointing to
Normal legend below a graph (has arrow on top)
Legend above a graph (has arrow on bottom)
Only potential issue here is that the crosshair does not line up with the arrows, which I find slightly distracting

Fix Legend Positioning

---

CHANGELOG.md
ui/src/external/dygraph.js

Connect #2039 
Dygraph's current `findClosestPoint` method technically finds the closest point to the cursor.  However, that's not really how human eyes expect hovering to work.  When hovering horizontally, users expect the hover line to highlight the nearest point that intersects with the hover line.  
Prioritize the closest x-value first. Then, if there is an x-value tie use the y-value as the tie breaker.  This results in a smoother and less 'jumpy' and 'jagged' hovering experience.  The smoothness is a bit difficult to display in a GIF, but take a look at the differences...
Notice how only the peaks get highlighted:
Notice how the troughs are now highlighted:

UI-IMPROVEMENT: Add custom findClosestPoint method

---

ui/src/shared/components/Dygraph.js
ui/src/shared/components/DygraphLegend.js
ui/src/style/components/dygraphs.scss

Connect #2024 
- When a cell is the height of the entire dashboard, the legend gets clipped above the cell
- When the legend cannot fit above or below a cell, it will either appear to the right or left of the crosshair based on available space
- Didn't update changelog as my previous entry for the same issue still encapsulates this fix
Legend positioned to left of crosshair on full height cell
Legend positioned to right of crosshair on full height cell

UI IMPROVEMENT: More complete fix of legend positioning

---

etc/scripts/chronograf.service

Chronograf does not have a default env override to the chronograf.service systemd service config
Add a default that matches other TICK products

Add env override to chronograf.service

---

CHANGELOG.md
ui/src/admin/components/DatabaseManager.js
ui/src/admin/components/DatabaseTableHeader.js
ui/src/admin/components/FilterBar.js
ui/src/dashboards/components/DashboardsPageContents.js
ui/src/dashboards/components/DashboardsTable.js
ui/src/kapacitor/components/KapacitorRules.js
ui/src/shared/components/EmptyQuery.js
ui/src/shared/components/LayoutCell.js
ui/src/sources/components/InfluxTable.js

Connect #2026 
- Most buttons with an add or create action do not have matching icons
- All add/create buttons have a plus icon

UI IMPROVEMENT: Add Plus Icon to all Add/Create buttons

---

ui/src/dashboards/components/OverlayControls.js
ui/src/dashboards/components/SourceSelector.js

- CEO options toggle becomes uncentered when no queries present
- CEO options toggle always centered

Prevent CEO toggle from de-centering when no queries present

---

CHANGELOG.md
ui/src/style/components/query-maker.scss

Connect #2110 
- Query tabs are fairly tiny
- Tough to distinguish each tab by the truncated query string
- Increase maximum tab width from `135px` to `340px`
- Decrease tab font size from `15px` to `14px` (allows more of the string to be visible)
- Adjust how the tabs fill available space; prevent overflow of tabs
Behaves just like browser tabs
Larger `max-width` is nice
More of each query string is visible

Style query tabs to utilize available space more effectively

---

CHANGELOG.md
ui/src/kapacitor/components/Tickscript.js
ui/src/kapacitor/components/TickscriptHeader.js

Connect #2096 
Could not cancel editing or creating a Tickscript.
Add a cancel button that returns users to the rules/tickscript index.

UX-IMPROVEMENT: Add Cancel button for tickscript editor

---

chronograf.go
influx/templates_test.go

Connect #1449 
Group by time rounded up to the second on sub-second queries
Add support for millisecond group bys

Add support for millisecond groupbys

---

CHANGELOG.md
ui/src/kapacitor/components/RuleGraph.js
ui/src/kapacitor/components/Threshold.js
ui/src/kapacitor/constants/index.js
ui/src/kapacitor/helpers/ruleGraphUnderlay.js
ui/src/shared/parsing/getRangeForDygraph.js

Connect #1131 
Incorrect highlighting of the `not-equal-to` operator.  
Visualize the inverse of the `equal-to` operator.

BUGFIX: Fix display of not-equal-to on rule graph

---

CHANGELOG.md
chronograf.go
chronograf_test.go
ui/src/data_explorer/containers/Header.js
ui/src/shared/components/CustomTimeRange.js
ui/src/shared/components/CustomTimeRangeOverlay.js
ui/src/shared/components/TimeRangeDropdown.js
ui/src/style/components/custom-time-range.scss

Connect #1825 
Users would like to specify a lower time besides the ones we provide them. now() - 5m etc just isn't enough.
Allow users to specify an absolute lower bound with a specific date and time and an upper time relative to `now()`.
The chronograf server needs to actually use template variables types rather than what is used now

FEATURE: Toggle now() in date picker

---

CHANGELOG.md
ui/package.json
ui/yarn.lock

Connect #1449 
Chronograf graphs in UI wouldn't label millisecond or sub-millisecond axes.
Fork Dygraphs to our own company GItHub account and apply changes from https://github.com/danvk/dygraphs/pull/777, and then point our project use that repository.

Dygraph Fork for Milliseconds

---

ui/src/style/pages/dashboards.scss

Connect
the edit button is being obscured by the custom time indicator, when a custom time is set on cell 
css magic.

Fix overlay of custom time indicator and csv download button

---

CHANGELOG.md
ui/src/sources/components/SourceForm.js
ui/src/sources/containers/SourcePage.js

Connect #1497 
Source url's that do not begin with `http://` are being passed without being changed.
Prepends the string `http://` upon blurring of the source.url field.

Prepend 'http://' to source url

---

CHANGELOG.md
ui/src/data_explorer/components/WriteDataForm.js

Connect #2047
The file input value wasn't getting reset on cancel, so some users couldn't upload a different file.
Reset the input value on cancel.

BUGFIX: Drag n drop cancelling

---

ui/webpack/devConfig.js

Using webpacks `noParse` module.  Found the solution [here](https://stackoverflow.com/questions/39768099/how-to-ignore-seems-to-be-a-pre-built-javascript-file-try-to-require-the-orig/39768100)
@cryptoquick this look okay to you?

Fix prebuilt warning with webpacks noParse

---

CHANGELOG.md
ui/src/dashboards/components/DashboardHeader.js
ui/src/dashboards/components/DashboardHeaderEdit.js
ui/src/dashboards/components/DashboardSwitcher.js
ui/src/dashboards/components/VisualizationName.js
ui/src/dashboards/constants/index.js
ui/src/dashboards/containers/DashboardPage.js
ui/src/hosts/containers/HostPage.js
ui/src/style/components/graph.scss
ui/src/style/unsorted.scss

Connect #1991 
Connect #2064 
Connect #2097 
- Running out of space in the Dashboard page header
- Renaming a dashboard does not automatically select text in input (unexpected behavior)
- Remove `Rename` button
- Add dashboard switching dropdown next to Dashboard name (preserve switching functionality)
- Click on dashboard name to rename
- `ESC` cancels rename
- `Enter` or `Blur` saves rename
- Maximum length of dashboard name is 50 characters (based on `1440x900` screen size)
- Dashboard name input automatically selects all text on edit
More space efficient
Switching between dashboards (is alphabetically sorted as well)
Click to rename dashboard
- This fundamentally changes how users will accomplish 2 tasks, will add a learning curve for existing users
- Users previously clicked on the …

Redesign Dashboard Naming Interaction

---

chronograf.go
influx/query.go
influx/query_test.go
kapacitor/ast.go
kapacitor/ast_test.go
kapacitor/client_test.go
kapacitor/data.go
kapacitor/influxout_test.go
kapacitor/tickscripts_test.go
kapacitor/vars.go
kapacitor/vars_test.go
server/dashboards_test.go
server/kapacitors.go
server/kapacitors_test.go
server/swagger.json

Connect #2067 
queryConfig does not support alias nor functions.
This PR adds alias and functions to the backend.
The response to the query below is now changed:
```sql
SELECT mean("usage_user") AS "mean_usage_user" FROM "cpu"
```
```json
"fields": [
{
"value": "mean",
"type": "func",
"alias": "mean_usage_user",
"args": [
{
"value": "usage_user",
"type": "field"
}
]
}
]
```

server update to queryConfig to support field aliases and functions

---

ui/src/data_explorer/components/Table.js

Connect #1787 
When grouping by tags, the DataExplorer table tabs all had the same title.
Use the corresponding tag values in tab titles as well.

Use tag value in TableTag title

---

ui/src/kapacitor/components/Threshold.js

Connect #2147 
Kapacitor rule builder attempting to access a field with the old shape
Update it to use the new shape

Fix field name not displaying in KapacitorRule builder

---

ui/src/dashboards/components/QueryMaker.js
ui/src/data_explorer/components/GroupByTimeDropdown.js
ui/src/shared/components/FieldList.js

Connect #2150 
In the GroupByTimeDropdown menu, auto was being displayed and automatically selected in the Data Explorer. This probably broken on the Rule Builder also, once a function had been selected.
Remove isInDataExplorer props. Refactor GroupByTimeDropdown to SFC. Fix isInDataExplorer and isInRuleBuilder methods.

Fix GroupByTimeDropdown

---

chronograf.go
kapacitor/client.go
kapacitor/client_test.go
server/kapacitors.go
server/kapacitors_test.go
server/swagger.json

Connect #2139
No support for insecure, self-signed certificates for https connections to kaapcitor
Added `insecureSkipVerify` to the kapacitor REST interface

Add insecure ssl support to connect to kapacitor

---

ui/src/external/dygraph.js
ui/src/shared/components/Dygraph.js
ui/src/shared/components/DygraphLegend.js
ui/src/shared/graphs/helpers.js

Connect #2109 
If a graph at the bottom of the page was hovered, the highlightPoint series circles did not show up.  See #2109 for a GIF.  
I really don't know what caused this problem.  I found that if I removed the positioning logic for the legend, the circles came back.  That wouldn't work because then we would have a static legend.  So, I moved the logic for calculating the legend position into the legend itself and that appears to have brought back the circles.  I don't know what that worked.

Highlight circles are back

---

CHANGELOG.md
ui/spec/shared/parsing/resultsToCSVSpec.js
ui/src/shared/parsing/resultsToCSV.js

Connect #2141 
The resolution of csv download timestamps are on the order of seconds, even when sub-second grain data is available.
Added fractional second granularity to timestamps.

Adds fractions of seconds to time field in csv export

---

CHANGELOG.md
ui/src/dashboards/actions/index.js
ui/src/shared/parsing/index.js

Connect #2129 
When cells on a dashboard are all individually connected to a source that does not have the same template variable resources as another source.   i.e. a source does not have a 'telegraf' database and template variables are dynamically generated from telegraf's tagKeys.  A "cannot connect to source" error is displayed. 
Don't blindly key into `tagValues`, `fieldKeys`, or `measurements` when parsing them for template variables.  If they do not exist return their respective empty states: `[]`

Fix cannot connect to source false error flag

---

CHANGELOG.md
ui/src/dashboards/components/AxesOptions.js
ui/src/shared/components/ClickOutsideInput.js
ui/src/shared/components/Dygraph.js
ui/src/shared/components/OptIn.js

Connect #2094 
There's a Dygraph bug when provided only one point, it will calculate a negative min y range padding and take the log of a negative number. 
Protect against this very specific case. 
I added some small guards against provided negative numbers with logscale.  If we want to be more aggressive with this we can.

 Logscale single point

---

CHANGELOG.md
ui/src/hosts/apis/index.js

Added Avg Ping to hosts table
Added last packet loss capture
Updated status to check the ping statistics when the cpu statistics are not available. Before marking the host as down.
- [x ] CHANGELOG.md updated with a link to the PR (not the Issue)
- [x ] Rebased/mergable
- [x ] Tests pass
- [x ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
Connect #

Fixes #1077 by removing win_system and system from the select query.

---

etc/scripts/logrotate

Chronograf would create zero sized log files rather than ignore
Chronograf will not rotate unless there are logs.

Update chronograf logrotate policy to not rotate if file is 0 bytes

---

bolt/organizations.go
bolt/organizations_test.go
chronograf.go
mocks/organizations.go
noop/organizations.go
server/auth.go
server/auth_test.go
server/dashboards.go
server/dashboards_test.go
server/kapacitors.go
server/layout.go
server/me.go
server/me_test.go
server/sources.go

Encodes DefaultOg logic into the OrganizationsStore interface.
Prevents user from removing default organization.
Connect #2202 
Connect #2209

Remove explicit default org ID use

---

CHANGELOG.md
server/queries.go
server/queries_test.go

Connect #2161
The /queries endpoint was not rendering the template variables  because it was not unmarshaling the payload correctly
The endpoint now renders templates and has significant tests.

Fix rendering of templated queries to the /queries endpoint

---

ui/package.json
ui/webpack/devConfig.js
ui/yarn.lock

Connect #1607 
Webpack leaves unused files around each time it does  a build.  This patch removes stale files each time a dev build is created.
cc @jaredscheib

Add cleanup step to js dev builds to remove unused files

---

Makefile
ui/package.json
ui/webpack/devConfig.js

Slower to develop javascript than it should be because chronograf didn't have hot module reloading.
Add hot module reloading to webpack configuration.
If you are make inclined:
```sh
make run-hmr
```
or if you are npm inclined:
```sh
npm run start:hmr
```
This starts the webpack dev server with HMR on port 8080.  It proxies API requests to the normal chronograf server (`make run-dev`)

Add hot module reload to dev builds (make run-hmr)

---

CHANGELOG.md
etc/scripts/chronograf.service
etc/scripts/init.sh

Minor change to the init script to source a /etc/defaults/chronograf file, which will allow you to specify extra startup command line options.
Connect #
Can't override chronograf command line options when starting it as a service.
Modification to init / LSB script to source a file to add extra options.

Source extra command line options from defaults file

---

CHANGELOG.md
etc/build.py

Connect #2302 
RPM generation via fpm did not have shadow-utils
Added shadow-utils as a dependency.

Add shadow-utils to release RPM generation

---

server/organizations.go
server/organizations_test.go

Note that this merges into multitenancy_context_refactor
Previously, when an org was created it had no users. Now when an
organization is created, the user that made the request is added to the
organization with the admin role.
If there are any errors when adding the user the organization, we make a
best effort attempt to delete the organization. However it is still
possilbe that an organization would be created, but have no users if our
best effort fails.
Connect #2307

Add user that made the request to organization

---

server/auth.go
server/auth_test.go
server/context.go
server/me.go
server/me_test.go
server/organizations.go
server/organizations_test.go
server/stores.go
server/users.go
server/users_test.go

This PR adds the entire user to the context that is passed down to lower layers. This way we can prevent a user from deleting themselves by checking that ID of the user on context is the same as the user being deleted.
Additionally, all users, including super admins only see users that are scoped to their current organization.
Previously, the server just hijacked the super admin context in order to
get raw access to the underlying data stores, this introduces a way to
specify the it is explicitly the server making the request and no longer
hijack the super admin context.
This also adds test coverage to ensure that the correct values are being
set on context in the AuthorizedUser method.
Connect #2227 
Connect #2297 
Connect #2238 
Attempted to solve …

Put entire user on context and Prevent user from deleting themselves

---

server/sources.go
server/sources_test.go
server/stores_test.go

Previously, `ValidSourceRequest` did not take in a pointer and as a result, any attributes we tried to set on it were not actually set. This PR changes `ValidSourceRequest` so that it now takes in a pointer and can update non empty fields. This should fix #2299.
Additionally, tests were added to `server/store_tests.go` that ensure the behavior of the facades on the sources store. 
Connect #2299

Fix ValidSourceRequest to modify pointer when needed

---

bolt/users.go
bolt/users_test.go
chronograf.go

The PR adds a check in the boltdb implementation of a `UsersStore` to ensure users are unique up to name, provider, and scheme. This addition is to prevent the addition of possibly unreachable users.
Connect #2226

Ensure users name, provider, and scheme are unique

---

organizations/organizations.go
organizations/organizations_test.go
server/auth.go
server/me.go
server/mux.go
server/organizations_test.go
server/stores.go

Connect #2225 
- Exposes GET `/organizations` to Admins. Route should return their current organization and the default organization
- Exposes PATCH `/organizations/:id` to Admins
- Exposes GET `/organization/:id` to Admins

Expose some organization routes to admins

---

bolt/organizations.go
bolt/organizations_test.go
server/organizations.go
server/organizations_test.go
server/stores.go
server/stores_test.go
ui/src/admin/actions/chronograf.js
ui/src/admin/components/chronograf/OrganizationsTable.js
ui/src/admin/components/chronograf/OrganizationsTableRow.js
ui/src/admin/components/chronograf/OrganizationsTableRowDefault.js
ui/src/admin/components/chronograf/OrganizationsTableRowNew.js
ui/src/admin/containers/OrganizationsPage.js

Connect #2341 
Connect #2274
1. Bolt OrganizationsStore was not properly updating all attributes
2. The organizationRequest `ValidUpdate` method did not properly validate the role
2. The new DefaultRole property was not set in UpdateOrganization

Fix organizations UpdateHandler and OrganizationsStore Update method

---

ui/src/side_nav/components/UserNavBlock.js
ui/src/style/layout/sidebar.scss

Connect #2248 
- Moving the admin nav items out of the user nav block requires a redesign
- When there are a lot of orgs, menu will extend off the screen

Multitenancy User Nav Polish

---

bolt/client.go
bolt/dashboards.go
bolt/layouts.go
bolt/servers.go
bolt/sources.go
server/dashboards.go
server/dashboards_test.go
server/me.go
server/me_test.go
server/server.go
server/service.go

When users upgrade, all of their bolt resources will not belong to any
organization. This PR introduces a migration path where any orphaned,
resources without an organization, will become owned by the default
organization.
Connect #2198 
Connect #2311

Migrate all orphaned resources to DefaultOrg

---

ui/src/CheckSources.js
ui/src/shared/actions/auth.js
ui/src/shared/actions/sources.js

Connect #2241 
Sources were refreshing, but a network request caused by a `showDatabases` invocation in `componentWillUpdate` in `CheckSources` was causing an unexpected error notification to appear upon switching organizations because sources hadn't been refreshed yet.
This effectively rounds out #2241 and makes switching orgs a seamless UX.
Add `shouldComponentUpdate` logic to prevent `CheckSources` from invoking `componentWillUpdate` if what has changed is `me.currentOrganization`, so that the subsequent `router.push('')` in both places where `meChangeOrganization` is invoked can be invoked before the component updates.

Prevent sources error notification on org switch

---

ui/spec/shared/reducers/authSpec.js
ui/src/CheckSources.js
ui/src/admin/containers/OrganizationsPage.js
ui/src/index.js
ui/src/shared/actions/auth.js
ui/src/shared/actions/sources.js
ui/src/shared/apis/auth.js
ui/src/shared/apis/index.js
ui/src/shared/reducers/auth.js

Should be considered after #2392, since this branch was rebased on top of that branch.
Connect #2344 
User nav didn't reflect current state of organizations, after creating, updating, or deleting an organization. The user should:
1. be able to switch into new orgs immediately but couldn't;
2. see the names of orgs that they belong to match any updates to organization names;
3. not be able to switch into an org if it was just deleted.
Refactor how me is gotten, and refresh user side nav organizations  after updating organizations.

Refresh organizations in User nav after updating organizations

---

ui/src/style/layout/sidebar.scss

Connect #2394 
- Invisible triangle does not appear for the user nav menu when on a small screen
- Added a style for the triangle when the screen is smaller and the menu inverts

Add invisible hover triangle for user menu on small screens

---

CHANGELOG.md
ui/src/utils/influxql.js

Connect #2369 
Query config rendering to InfluxQL did not support wildcard, integer, number and regex types
returned from the chronograf server.
Added support to render wildcard, integer, number and regex.

Update queryConfig render to support wildcard, re, int, num

---

chronograf.go
server/cells.go
server/cells_test.go
server/dashboards_test.go
server/swagger.json

We need to store colors for all cells.  This PR sets the table for all cells, but, this is focused on gauge.
```javascript
{
colors: [
{
type: 'min'
hex: '#123456',
id: 'dididi',
name: 'laser',
value: '0',
},
{
type: 'threshold'
hex: '#22ADF6',
id: 'foo',
name: 'pool',
value: '20',
},
{
type: 'threshold'
hex: '#4591ED',
id: 'bar',
name: 'ocean',
value: '40',
},
{
type: 'max',
hex: '#12345',
id: 'howdy',
name: 'laser',
value: '100',
},
]
}
```

Add colors to all cells

---

CHANGELOG.md
ui/src/dashboards/containers/DashboardPage.js

Connect #2152 
When renaming a dashboard, the old name would still exists in the `DashboardSwitcher` list
Use props instead of state to calculate the names and links for the `DashboardSwitcher`.  All the data we need to calculate the information is already provided as props by Redux state.  No need to diverge into local component state.

Use props instead of state for Dashboard name list

---

CHANGELOG.md
oauth2/generic.go
oauth2/generic_test.go
server/server.go

Connect #2387
Azure oauth2 uses the key `userPrincipalName` rather than `email`
Expose a CLI option to allow people to override the key to extract the value.
`GENERIC_API_KEY` or `--generic-api-key`
Here is an example for azure:
```
export TENENT=YOUR_TENTENT
export GENERIC_NAME=azure
export GENERIC_CLIENT_ID=YOUR_ID
export GENERIC_CLIENT_SECRET="YOUR_SECRET"
export GENERIC_SCOPES=openid
export GENERIC_AUTH_URL="https://login.microsoftonline.com/$TENENT/oauth2/authorize?resource=https://graph.windows.net"
export GENERIC_TOKEN_URL=https://login.microsoftonline.com/$TENET/oauth2/token
export GENERIC_API_URL="https://graph.windows.net/$TENET/me?api-version=1.6"
export GENERIC_API_KEY="userPrincipalName"
export TOKEN_SECRET=secret
export PUBLIC_URL=http://localhost:8888
```

Add GENERIC_API_KEY to override of oauth2 responses to support azure

---

CHANGELOG.md
ui/src/dashboards/components/template_variables/RowButtons.js
ui/src/shared/components/DeleteConfirmButtons.js
ui/src/style/components/template-variables-manager.scss

Connect #2010 
- When the screen is smaller the `Edit`/`Delete` buttons disappear
- Refactor styles to scale down gracefully
- Make all row buttons square to conserve space
This is at `750px` screen width

Make Template Variables Manager More Responsive

---

CHANGELOG.md
ui/spec/shared/presenters/presentersSpec.js
ui/src/shared/presenters/index.js

Connect #2312 
The default y-axis label was generated from the old queryConfig field shape
Update `buildDefaultYAxisLabel` to use new `field` shape on `queryConfig`

Update y-axis label to handle new queryConfig field shape

---

bolt/users.go
bolt/users_test.go
chronograf.go
enterprise/users.go
enterprise/users_test.go
influx/users.go
influx/users_test.go
mocks/users.go
noop/users.go
organizations/users.go
organizations/users_test.go
server/me.go
server/me_test.go
server/server.go
server/service.go

Connect #2429 
Connect #2211 
Previously, the first user of authed chronograf was not necessarily a super admin. This created a bad UX for the first users. As a result, the first user is always made to be a super admin.
In this process, we had to add a `Num` function to the `UsersStore` interface.

Make first user superadmin when using `superadmin-first-user-only` CLI flag

---

CHANGELOG.md
ui/src/dashboards/containers/DashboardsPage.js

Connect #2424 
`this` was not bound properly in `handleCreateDashboard`, causing a runtime error when `this.props` was attempting to be accessed. 
Changed handlers in DashboardsPage to use arrow functions for proper this
binding.

Fix 'Create Dashboard' button

---

CHANGELOG.md
Makefile

This fixes issue #2404 
Since `LDFLAGS` being exported in the calling environment causes an issue with some part of the call to `yarn`, we should `unexport LDFLAGS` in the Makefile to avoid conflicts.

Fix exported LDFLAGS causes .jsdep build step to fail

---

ui/src/dashboards/components/DashboardsTable.js
ui/src/shared/components/NoKapacitorError.js
ui/src/style/unsorted.scss

I added these two items to #2146 retroactively.
1. Configure Kapacitor button mistakenly showed on empty Alerts table for Viewers.
1. Create Dashboards button mistakenly shows on empty Dashboards table.
Show both only to Editors and above.

Prevent render of Configure Kapacitor & Create Dashboard buttons to Viewer users

---

CHANGELOG.md
server/sources.go

Connect #2000 
Users would see role based views, even when no `metaURL` was provided. 
Do not return a role link for sources with no `metaURL`

Enterprise no metaURL - no rbac

---

ui/src/admin/components/chronograf/AdminTabs.js
ui/src/admin/components/chronograf/UsersTable.js
ui/src/admin/components/chronograf/UsersTableRow.js
ui/src/admin/containers/AdminChronografPage.js
ui/src/shared/components/DeleteConfirmButtons.js

Add propTypes definition for 'users' in Chronograf AdminTabs
Add 'disabled' prop to DeleteConfirmButtons
Connect #2227
User could click `Remove` button for themselves in the Chronograf Users table, which is no longer possible to do.
Disable that button for self only.

Disable 'Remove' button for self in Chronograf UsersTable

---

bolt/organizations.go
bolt/organizations_test.go
chronograf.go
organizations/users.go
organizations/users_test.go
ui/src/admin/actions/chronograf.js
ui/src/admin/reducers/chronograf.js

Previously, the organizations store did not check to see if the user
that a user was being "added" had a role in the organization, it simply
filtered out a users roles that did not belong to that organization and
blindly appended the new ones that were supplied.
This resulted in users being able to change another users role during
new Add request for the same user.
Connect https://github.com/influxdata/chronograf/issues/2226#issuecomment-348020617
Connect #2402

Prevent unintended update of existing user on Add; fix duplicate User & Org creation client UX

---

ui/src/kapacitor/apis/index.js

Connect #2073 
Connect https://github.com/influxdata/kapacitor/pull/1703
Kapacitor logs wouldn't show when using OAuth.
Send cookies along with fetch.
Also, added @nathanielc 's recommended "Accept" header.

Fix headers sent to Kapacitor proxy endpoint by clientside fetch

---

CHANGELOG.md
canned/mysql.json

Connect #2315
Mysql pre-canned dashboard wasn't using a bounded derivative giving incorrect results.
Add a time boundary for the derivative and change from max to last.

Update mysql pre-canned dashboard to use last value over a second derivative

---

ui/webpack/devConfig.js

Connect #2476 
Build directory would get cluttered. We wrote a modern ES7-style async/await/promisified solution, but it didn't work on older Node.js.
Refactor webpack file cleanup script to use Node-style, error-first callback fs method calls.
Continues to keep build directory consistently clean.

Node-style callbacks instead of async/await/promisify in webpack build dir cleanup code

---

server/sources.go

Currently, if an empty source is supplied, then the source's meta url
will not be updated. Now, if the MetaURL is supplied and is different
than the one that is currently on the source, the value will be updated.
Even in the case of empty string meta urls.
Connect #2000 
Related to https://github.com/influxdata/chronograf/pull/2457

Allow for empty MetaURL in UpdateSource

---

CHANGELOG.md
ui/src/dashboards/containers/DashboardPage.js
ui/src/shared/components/Dygraph.js

Connect #2258
1) Due to the async nature of this.setState(), not all of the graphs were being passed to Dygraph's public `synchronize` function 
2) The guard clause over `Dygraph.synchronize` was catching if there was a non-Dygraph type visualization in the Dashboard
For repro steps see the connected issue.  We also improved the performance of the hoverline rendering the `<Dygraph>` component's `pageX` state off of state and into a class property.  This would update quite frequently (which it should) and cause slow / async `setState` calls.  A quick performance evaluation changes most calls of `hightlightCallback` to drop from 90ms to 30ms.

Fix the hoverline

---

CHANGELOG.md
enterprise/enterprise.go
enterprise/enterprise_test.go
enterprise/meta.go
enterprise/meta_test.go
influx/authorization.go
server/service.go

Connect #2389
Meta queries did not use basic auth or bearer JWT tokens
Use the data node username and password or JWT token to authenticate to the meta nodes.
To test add these sections to enterprise configurations:
```toml
[meta]
meta-auth-enabled = true
```
```toml
[meta]
meta-auth-enabled = true
```

Add basic auth or JWT tokens for meta queries

---

ui/src/sources/containers/ManageSources.js
ui/src/sources/containers/SourcePage.js

Connect #2432 
The sources page was refactored earlier and had a small bug in it that prevented the sources page from refreshing upon adding or updating a source.
Make it so the bound action creator is called from props so that the thunk is called and the Redux store is updated instead of simply calling the action creator alone.

Fix Sources Update on Source Creation or Updation

---

ui/src/kapacitor/containers/TickscriptPage.js
ui/src/localStorage.js
ui/src/shared/actions/notifications.js
ui/src/shared/components/Notifications.js
ui/src/shared/reducers/index.js
ui/src/shared/reducers/notifications.js

Connect #2473 
Showing a warning every time someone went to the TICKScript logging page can get tiresome, for instance.
A persisted reducer was added to keep track of any notification that passes the "once" option.

You're Only Warned Once

---

ui/package.json
ui/yarn.lock

Connect #2413 
Now that dygraphs has support for millisecond-level granularity, we can depend on the dygraphs project again.

Re-depend on main dygraphs repo

---

CHANGELOG.md
influx/templates.go
influx/templates_test.go

Connect #2527 
The app sends in stale template variables to the data explorer and the server did not weed them out.
Server now does not try to render a template variable if the template variable is not in the query.
There may be some follow on app bugs regarding why the app is sending stale data.

Fix template rendering to ignore template if not in query

---

ui/src/admin/components/chronograf/OrganizationsTableRowNew.js

Connect #2531 
Users could not create organizations with spaces in the name.
Allow organizations to be added with any number of spaces, and only trim whitespace upon submit rather than upon input value change.

Allow new Organization names to include spaces

---

ui/src/sources/components/InfluxTable.js
ui/src/style/unsorted.scss

Connect #2422 
- Viewers are able to switch active Kapacitor configs
- Viewers see static text instead of a dropdown

Render static text instead of kapacitor switching dropdown for Viewers

---

CHANGELOG.md
ui/src/shared/parsing/getRangeForDygraph.js

Connect #2541 
When a user supplied a `min` y-axis range that is greater than the automatically generated `max` the graph inverted.  This seemed like odd behavior.  
@nhaugo and I talked about what to do should the user put themselves in that position and settled on adjusting the calculation of max in that case to be min + 1.  This prevents the jarring experience of seeing the graph invert, while also mathematically making sense so a graph can display in the first cartesian plane.  
Create a cell on a dashboard.  Pick a time series that has a consistent range that is easy to work with.  Might I suggest telegraf, cpu, usage_user.  Click the visualization tab in the Cell Editor Overlay.  Put in a min > 100.  Observe the graph no longer flipping.
It was also suggested by @ebb-tide that we …

Prevent inversion of graph

---

ui/src/style/layout/sidebar.scss

Connect #2561
I introduced this when I changed how the navs were constructed. I intended to change only the user nav dropdown, so this PR wraps all the css I introduced beneath `.sidebar-menu--user-nav`

Invert only the user nav; leave alerting/admin untouched

---

CHANGELOG.md
ui/spec/shared/presenters/presentersSpec.js
ui/src/dashboards/components/AxesOptions.js
ui/src/shared/presenters/index.js

Connect #2516 
The queryConfig being passed to the function creating these labels was empty.
Added functionality to the `buildDefaultYLabel` function to return if the queryConfig is 'empty'. 
It should be noted that the reason this queryConfig is empty appears to be another bug regarding the parsing / saving of queries into queryConfigs.  Will update #2516 to elaborate.

y axis title undefined

---

CHANGELOG.md
ui/src/admin/components/chronograf/AdminTabs.js
ui/src/admin/components/chronograf/UsersTable.js
ui/src/admin/components/chronograf/UsersTableRowNew.js
ui/src/admin/containers/AdminChronografPage.js

Connect #2537 
The 'currentOrganization' namespaced in the auth reducer does not get
updated when chronograf organizations reducer gets updated.  This
results in temporarily stale state until `/me` is hit and the 'me auth'
state trickles through the application.
Force an update to `/me` in the `componentDidMount` of the `UsersTable`.  
This is a temporary solution.  I've opened up a ticket to solve this f.o.r.e.v.e.r.

Fix organization default role being stale on chrono users page

---

server/me.go
server/me_test.go

Previously, if an organization was private and a user was removed from
the default organization, then they would be re-added. This behavior was
so left over from when we thought of the default organization as the
place where all users would exist. This PR removes that behavior, unless 
the a user is a SuperAdmin or the organization is public.
Connect #2524

Prevent user joining private default org

---

organizations/users.go
organizations/users_test.go
server/users.go
server/users_test.go
ui/src/admin/components/chronograf/UsersTableRowNew.js
ui/src/style/pages/users.scss

Previously, a users super admin status was disregarded in the Add facade. This was problematic when new users were added with a super admin status, because they would not be granted the status. This created an odd user experience.
Add diff check to Organization UsersStore Add tests
Connect #2540

Only promote user to super admin in user org store

---

integrations/server_test.go
server/users.go

When we introduced #2552 I failed to realize that this would actually prevent admin users from being able to create new users.
Connect https://github.com/influxdata/chronograf/issues/2583
We look up server configuration using the request context in `NewUser`. If the requesting user is not a SuperAdmin the request to access the Config will fail. This means that Admins will not be able to create any new users.
Use the server context to request access to the config.

Use serverContext for getting Config in NewUser

---

ui/src/shared/middleware/errors.js

Connect #2568 
When ERROR_THROWN actions were created by non-AJAX requests, the errors middleware would fail. This is because we were destructuring `error.data.message` on every error, rather than only failed AJAX requests.
This bug was introduced in our client work in #2399.
- Only access error.data.message upon AJAX requests (and actually only 403s currently)
- Use lodash to avoid nested destructuring altogether

Prevent console error from failed ES6 destructuring when ERROR_THROWN is not from HTTP

---

ui/src/dashboards/containers/DashboardPage.js

Connect #2544
When explicitly navigating to `/sources/:source_id/dashboards/:dashboard_id` for a `dashboard_id` that doesn't exist yet, Chronograf would render a blank page and spit out errors in the dev console.
Check for the dashboard on DashboardPage#componentDidMount, and redirect to `/sources/:source_id/dashboards` if missing.

Attempting to access missing dashboard should redirect user to `/sources/:sources_id/dashboards`

---

integrations/server_test.go
server/users.go
server/users_test.go
ui/src/admin/components/chronograf/UsersTableRow.js
ui/src/shared/components/SlideToggle.js
ui/src/style/components/slide-toggle.scss

Previously it was possible for SuperAdmins to remove their own status.
This could create an application state where there were no super admins.
This is not an acceptable application state.
Connect #2638

Prevent SuperAdmin from modifying their own status

---

CHANGELOG.md
integrations/server_test.go
server/me.go
ui/src/admin/components/chronograf/OrganizationsTable.js
ui/src/admin/components/chronograf/OrganizationsTableRow.js
ui/src/shared/actions/auth.js
ui/src/shared/constants/index.js
ui/src/sources/containers/SourcePage.js

Previously, SuperAdmins were given the admin role in an organization
when they switched into it (via a PUT to /me). This is undesireable for
the comonitoring organization. This PR gives SuperAdmins the default
role for the organization when they switch into it.
Additionally, this makes it so that when any user switches organizations, they see a longer-displayed notification that clarifies which organization and what role they have switched into, using the terminology `logged in`. And this will happen regardless of whether they were a SuperAdmin or not, and whether (if SuperAdmin) that SuperAdmin had a role in the org before or not.
Connect #2641
Connect https://github.com/influxdata/chronograf/issues/2636

Give SuperAdmin DefaultRole on PUT /me

---

CHANGELOG.md
ui/src/sources/containers/SourcePage.js

Connect #2649
Connect #2651
1. The Source edit page was no longer rendering successfully.
1. The Source edit page did not communicate direction to the user as to what to do when adding their initial source, and the styles of the page header were inconsistent with the rest of the app.
1. Fix the rendering by removing the outer `<div>` & make `<Notifications />` a sibling component on `<SourcePage>`.
1. Narrow the scope of rendering logic for `isInitialSource` to ensure a Page Header with `Add a new source` copy is always included when the user is adding their initial source.

Fix SourcePage render & render Page Header for user context when adding initial source

---

chronograf.go
server/env.go
server/env_test.go
server/mux.go
server/routes.go
server/routes_test.go
server/server.go
server/service.go
ui/src/hosts/apis/index.js
ui/src/hosts/containers/HostsPage.js
ui/src/shared/actions/auth.js
ui/src/shared/apis/env.js
ui/src/utils/ajax.js

Connect #2662 
Cloud needs this to make the status indicators on the Hosts Page useful.  
Provide a env option via the cli
This should remain an undocumented feature until we allow users to set the queries which generate the info the the HostsPage in a clearer / useful way.  
`./chronograf --telegraf-system-interval <goduration>`
Navigate to the sources page, and check the chronograf logs to see your custom duration.

ENV variable TELEGRAF_SYSTEM_INTERVAL

---

CHANGELOG.md
ui/src/shared/components/LayoutCell.js
ui/src/shared/components/LayoutCellHeader.js
ui/src/shared/components/LayoutCellMenu.js
ui/src/shared/components/LayoutRenderer.js
ui/src/style/pages/dashboards.scss

Connect #2661 
This hasn't been the only time we have had to fix the `CustomTimeIndicator`.  This is mostly due  (IMHO) to it being in the wrong place.  For easy-peasy styling the `CustomTimeIndicator` should really be a sibling with the rest of the display flexed context menu buttons.  So, should the button sizes change, adjust, or be plain ol' removed the CTI can change along with it.  
I think the original decision to not put the CTI where it was was to make it 'draggable'.  Fortunately, the `ReactGridLayout` API makes it super easy to indicate which elements should be draggable with an arbitrary classname.  I chose `dash-graph--draggable` whose only job is to indicate which elements are draggable (in this case the cell header and the CTI) and style the cursor with 'move'.  
A quick …

Fix positioning of CustomTimeIndicator

---

CHANGELOG.md
server/influx.go
server/proxy.go

Connect #2139 
Our reverse proxy to influxdb's write and kapacitor's ping and config did not respect self-signed or insecure certificates.
Allows self-signed certificates for influxdb/kapacitor proxy

Add support for insecure (self-signed) certificates for kapacitor proxy and influxdb write

---

CHANGELOG.md
integrations/server_test.go
server/server.go

Previously, users had to place all canned resources (layouts,
dashboards, sources, kapacitors, and organizations) in a single
directory. This work introduces a way to specify two directories.
One for application layouts and one for the other resources.
Users may still place all resources in a single directory if they'd
like.
Connect #

Allow for different canned resource paths

---

CHANGELOG.md
ui/src/kapacitor/components/AlertTabs.js
ui/src/kapacitor/components/KapacitorForm.js
ui/src/kapacitor/components/config/AlertaConfig.js
ui/src/kapacitor/components/config/HipChatConfig.js
ui/src/kapacitor/components/config/OpsGenieConfig.js
ui/src/kapacitor/components/config/PagerDutyConfig.js
ui/src/kapacitor/components/config/PushoverConfig.js
ui/src/kapacitor/components/config/RedactedInput.js
ui/src/kapacitor/components/config/SMTPConfig.js
ui/src/kapacitor/components/config/SensuConfig.js
ui/src/kapacitor/components/config/SlackConfig.js
ui/src/kapacitor/components/config/TalkConfig.js
ui/src/kapacitor/components/config/TelegramConfig.js
ui/src/kapacitor/components/config/VictorOpsConfig.js
ui/src/shared/apis/index.js
ui/src/style/unsorted.scss

Connect #428 
Chronograf did not expose the ability to test Kapacitor alert configurations.
Added a button to Kapacitor Config sections which makes an API call to `/kapacitor/v1/service-tests/{service}` as described in: https://docs.influxdata.com/kapacitor/v1.3/api/api/#testing-services. Also made changes to the behavior of the `save configuration` button for a unified experience.

Testable kapacitor configs

---

CHANGELOG.md
ui/src/index.js
ui/src/kapacitor/components/AlertTabs.js
ui/src/kapacitor/components/HandlerOptions.js
ui/src/kapacitor/components/KapacitorForm.js
ui/src/kapacitor/components/KapacitorRule.js
ui/src/kapacitor/containers/KapacitorPage.js

Connect #2535  
All links from alert handler tabs in alert rule builder go to the same config panel. taking user out of context of their workflow. 
Send a state object during router.push and pass it down in order to lookup initial Alert Tab while loading kapacitor configuration page.

Link directly to the right config tab from handler section in rule creator.

---

CHANGELOG.md
ui/src/hosts/containers/HostsPage.js

Connect #
There is no auto refresh widget on the hosts list page. 
This prevents having a real time summary of hosts and their status.
This PR just adds the widget on the hosts list page as well as the required bindings.

Add auto refresh widget to hosts list page

---

etc/build.py

PR [#2690](https://github.com/influxdata/chronograf/pull/2690)
introduced a --resources-path flag, but forgot to update the build.py
to properly account for the distributions.

Add resources dir to build.py

---

CHANGELOG.md
ui/src/kapacitor/actions/view/index.js
ui/src/kapacitor/components/LogsToggle.js
ui/src/kapacitor/components/Tickscript.js
ui/src/kapacitor/components/TickscriptEditorConsole.js
ui/src/kapacitor/components/TickscriptHeader.js
ui/src/kapacitor/containers/TickscriptPage.js
ui/src/shared/components/ConfirmButton.js
ui/src/style/chronograf.scss
ui/src/style/components/confirm-button.scss
ui/src/style/pages/tickscript-editor.scss

Connect #2674 
Connect #2747
Connect #2709 
It was difficult to iterate on TICKscripts because saving any changes routed user to Alert Rules page.  Also, TICKscript errors from Kapacitor were not being reported to user. 
Separate Save and Exit buttons, and display Kapacitor response messages in TICKscript editor console.

Saving tickscript

---

CHANGELOG.md
etc/scripts/init.sh

Connect #2165
Sysvinit used cli defaults instead of env vars
Change the cli options to env vars

Remove cli defaults form sysvinit

---

CHANGELOG.md
server/users.go
server/users_test.go

Previously users were prevented from removing themselves.
Connect https://github.com/influxdata/chronograf/issues/2711

Allow user to delete themselves

---

CHANGELOG.md
cmd/chronoctl/add.go
cmd/chronoctl/list.go
cmd/chronoctl/main.go
cmd/chronoctl/util.go

This PR introduces two new commands:
1. `list-users` which lists all users in boltdb
2. `add-superadmin` which can be user to promote existing users to
superadmins, or creates new users that are superadmins
**Currently this work was done as a separate binary, but the intention is
to make it a part of the `chronograf` binary.**
Connect https://github.com/influxdata/chronograf/issues/2744

Add commands to users & create superadmin

---

cmd/chronoctl/add.go

This flag allows users to have a comma delimited list of organization
IDs that the user should given a role in.
Connect #2744 
Previously users couldn't specify organizations that the superadmin user should be added to. This created a situation where super admins could not auth into the application.
Allow users to specify a comma separated list of organization IDs that the user should be a part of.

Add organization flag to chronoctl for orgs

---

CHANGELOG.md
ui/src/data_explorer/components/VisHeader.js

Connect #2795
CSV download query in data explorer has template variables that are not defined, causing fetchTimeSeriesAsync to error
pass default template variables with data explorer call to fetchTimeSeriesAsync.

Set default tempVar :interval: with data explorer csv download call.

---

CHANGELOG.md
enterprise/enterprise.go
enterprise/enterprise_test.go
enterprise/meta.go
enterprise/users.go
server/service.go

Closes #2801 
Meta nodes queries are not respecting `InsecureSkipVerify`.  `InsecureSkipVerify` allows sign-signed certs.
Wire `InsecureSkipVerfiy` into meta node queries

Update meta nodes to respect insecure skip verify

---

ui/src/dashboards/components/CellEditorOverlay.js
ui/src/shared/components/Dropdown.js
ui/src/style/theme/bootstrap-theme.scss

Connect #2817 
- In some cases the user has to hit `Escape` twice to fully exit the Cell Editor
- Focusable elements besides inputs weren't being taken into account (Dropdowns & Buttons) so now they are
- Dropdowns are now a focusable element, and after selecting an item from a dropdown its parent DOM node is forced into focus state
- Added some styles into the theme so focused Dropdowns don't look bad

Fix Cell Editor keyboard shortcut

---

CHANGELOG.md
oauth2/generic.go
oauth2/generic_test.go

Connect #2827
The `Group` method did was not updated to use the `APIKey` to look up the authorizing users email. It instead used to old standard `email` key.
Use the `APIKey` instead of `email`.

Use Generic APIKey for Oauth2 group lookup

---

ui/spec/dashboards/reducers/cellEditorOverlaySpec.js
ui/src/dashboards/actions/cellEditorOverlay.js
ui/src/dashboards/components/AxesOptions.js
ui/src/dashboards/components/CellEditorOverlay.js
ui/src/dashboards/components/DisplayOptions.js
ui/src/dashboards/components/GaugeOptions.js
ui/src/dashboards/components/GraphTypeSelector.js
ui/src/dashboards/components/SingleStatOptions.js
ui/src/dashboards/components/Visualization.js
ui/src/dashboards/components/VisualizationName.js
ui/src/dashboards/containers/DashboardPage.js
ui/src/dashboards/reducers/cellEditorOverlay.js
ui/src/shared/components/RefreshingGraph.js
ui/src/store/configureStore.js

Connect #2802 
This was making me crazy so even though it's not on the roadmap I put in some extra-curricular time to tackle it. Should be much better to work with now.
- The CellEditorOverlay has become a monster sized component that is really hard to reason about
- Ran into a lot of unnecessary friction when extending single-stat functionality
- Concerned that as we add more cell types it will become even more unweildy
- Moved most of the state in `CellEditorOverlay` into redux and the handlers into their associated child components
```
cellEditorOverlay: {
cell: {}, // selected cell to edit -  name, axes, and type are stored in here
singleStatType: '',
singleStatColors: [],
gaugeColors: [],
}
```
- Child components only grab the state they care about
- CEO is much cleaner and nicer to …

Refactor CellEditorOverlay State

---

CHANGELOG.md
ui/src/kapacitor/components/KapacitorRules.js
ui/src/kapacitor/components/KapacitorRulesTable.js
ui/src/kapacitor/components/TasksTable.js
ui/src/kapacitor/constants/tableSizing.js
ui/src/side_nav/containers/SideNav.js
ui/src/style/theme/bootstrap-theme.scss

Connect #2749 
- Delete / Edit buttons do not follow the *appear on hover* pattern seen in other tables
- TICKscripts do not follow the *click name to edit* pattern seen in the rules table
- Alert Rules do not show in TICKscripts table even though they are technically TICKscripts beneath the surface
- Delete buttons do not require confirmation
- The name of the page in the page header does not match the side nav
- Unclear what the difference between TICKscripts and Alert Rules is
- Delete buttons only appear on row hover and require confirmation
- Removed the `Edit TICKscript` button from both tables
- TICKscript names are links that take you to the editor (matches pattern found in Alert Rules table)
- TICkscripts table shows both Alert Rules and TICKscripts (although it shows the `name` …

Polish Alerts Page Design

---

CHANGELOG.md
ui/src/dashboards/components/AxesOptions.js
ui/src/dashboards/components/GaugeOptions.js
ui/src/dashboards/components/SingleStatOptions.js
ui/src/shared/components/Gauge.js
ui/src/shared/components/GaugeChart.js
ui/src/shared/components/RefreshingGraph.js

Connect #2779 
- Unable to set a Prefix or Suffix on Gauge cells
- Unable to set a Prefix on Single Stat cells 
- User can set a Prefix & Suffix on both Gauge & Single Stat cell types

Add Prefix & Suffix to Gauge & Single Stat

---

ui/src/shared/components/Annotation.js
ui/src/shared/components/AnnotationPoint.js
ui/src/shared/components/AnnotationSpan.js
ui/src/shared/components/AnnotationWindow.js
ui/src/shared/components/NewAnnotation.js
ui/src/shared/constants/index.js

Closes #2868 
Omitted changelog entry as this is part of the Annotations and Static Legend features
- Annotations overlap with Static Legend
- Annotation markers and spans factor in Static Legend height

Factor in staticLegendHeight when determining marker and span heights

---

ui/src/dashboards/components/CellEditorOverlay.js
ui/src/dashboards/components/DisplayOptions.js
ui/src/dashboards/components/GaugeOptions.js
ui/src/dashboards/components/SingleStatOptions.js

Closes #2817 
- If the user deletes a threshold the CEO loses focus and can't listen for keyboard events
- If the user adds the max number of thresholds the CEO loses focus
- Force the CEO to refocus after adding & deleting thresholds

Actually fix Cell Editor keyboard shortcuts

---

ui/src/shared/components/RefreshingGraph.js

- Single Stat & Gauge cells were broken (always display 0, thresholds not working)
- Pass `inView` into Single Stat and Gauge cells (was previously only being passed to line graphs)

Fix Single Stat & Gauge Cells

---

ui/src/shared/components/AnnotationSpan.js
ui/src/shared/components/Dygraph.js
ui/src/shared/components/LineGraph.js
ui/src/shared/components/SingleStat.js
ui/src/style/components/dygraphs.scss

- in `single-stat-plus-line` graphs the single stat text is obscured by the graph axes & lines
- Clone `SingleStat` inside `Dygraphs` to place it in the same stacking context
- `SingleStat` z-indexed above graph, annotations, and static legend
- Pass `staticLegendHeight` into `SingleStat` so it doesn't obscure the static legend

Fix Single Stat Line Graph Appearance

---

CHANGELOG.md
oauth2/heroku.go

Connect #2511 
- Heroku OAuth was broken. This is because a required Header when making a GET request to the api url was missing.
- We didn't have insight into the error because we weren't checking the response status code for that request.
- Fix Heroku OAuth by adding the required header.
- Add a simple status code checker and log any non-200-range HTTP responses.
It may be useful to add status code checker logic for non-Heroku, such as GitHub, Google, Generic, etc. so that users (and we) can easily know what's failing, in case their APIs change or require headers in the future that they don't currently require. Created #2912 for this.

Fix Heroku OAuth

---

CONTRIBUTING.md

Clarify and make consistent the difference & usage of
frontend vs backend dependency management.
Connect #2676 
- Our Contributing guide cited the obsolete use of `gdm` for Go dependency management.
- The language around frontend vs backend dependencies was inconsistent.
- A note about a known issue with `dep` was missing.
Fix and clarify the above.

Fix CONTRIBUTING to cite 'dep' for Go dependency management

---

CHANGELOG.md
bolt/internal/internal.go
bolt/internal/internal_test.go

Closes #2920, #2919
Legacy dashboard cells have no type assigned to them, which prevents annotation
If dashboard cell type is empty then fallback to line type

Legacy dashboard cells default to type 'line'

---

bolt/users.go

We had inconsistent use of argument names.

Use consistent argument names for bolt users

---

ui/src/dashboards/components/DisplayOptions.js
ui/src/dashboards/components/TableOptions.tsx
ui/src/dashboards/graphics/graph.js
ui/test/dashboards/components/TableOptions.test.tsx

Makes query configs available for work on table graphs

Make query configs available in table options on visualization tab

---

CHANGELOG.md
canned/docker.json
canned/mesos.json
chronograf.go
server/layout.go
server/layout_test.go

Addresses a change that requires single stat graphs to have an array of
colors, specifically  in the case of canned dashboards. An empty array
is acceptable but an undefined value will break the page.
Closes #2862
Closes #2841 
When a user attempts to open a docker dashboard for a host the browser locks up.
Ensure that we always return colors for a single stat graph in host dashboards.

Always return colors for single stat graphs

---

ui/src/dashboards/components/GraphOptionsTimeFormat.tsx
ui/src/shared/components/TableGraph.js
ui/src/shared/components/ThresholdsList.js
ui/src/style/components/table-graph.scss

Connect #1686 
- Janky looking scrollbars
- Odd empty space on the right half of tables with only a few cells
- When using thresholds on a table the highlight styles conflict and do not appear
- Thresholds list sometimes has a tiny `+ Add` button
- Time format dropdown is tiny
- Polish scrollbar appearance
- Use the `ColumnSizer` HOC provided by `react-virtualized`
- This accepts a min & max width for columns which I have arbitrarily set to `90 / 400`
- Fills the available space with columns as much as possible
- Looks much nicer than before
- If cell contents get truncated, you can hover on the cell for a second or two to see the full contents
- Restyle column/row highlight styles
- Fix appearance of Thresholds list `+ Add` button
- Make Time Format dropdown the same size as other …

Polish Table Styles

---

Makefile
ui/package.json

People don't want to think about how to fix linter / formatting errors
Provide scripts for `eslint`, `tslint`, `prettier`, and all three together. 
- fix all things: `yarn run lint:fix`
- fix eslint: `yarn run eslint:fix`
- fix tslint: `yarn run tslint:fix`
- fix prettier: `yarn run prettier`

Add linting fix scripts

---

ui/src/dashboards/components/TableOptions.tsx
ui/src/shared/components/LineGraph.js
ui/src/shared/components/TableGraph.js

Connect #1686 
When switching from a non table to a table or creating a new cell and after creating a query, there were no fields available to hide or rename.

New tables have a populated customized fields

---

CHANGELOG.md
server/mapping.go
server/me.go
server/me_test.go
server/server.go
server/service.go

Connect #2963
Currently there isn't a way to have a general class of user that can be granted superadmin status.
Allow users from specific Auth0 organizations to be granted superadmin status. This feature is added a CLI option where users could specify specific Auth0 organizations that would grant users superadmin status.

Add server flag to grant SuperAdmin status to users authenticating from a specific Auth0 Organization

---

CHANGELOG.md
ui/src/admin/components/RoleRow.js
ui/src/admin/components/UserRow.js
ui/src/shared/components/MultiSelectDropdown.js

Connect #2980 
- If the Multi-Select Dropdown is open for more than brief moment the selected options appear to reset to previous values
- I removed `componentWillReceiveProps` from the component as it was setting state and forcing a re-render
- Somewhere higher up a re-render happens and the original props get passed down which causes the state change since the unsaved state is different
- Removing this shouldn't affect the functionality at all

Prevent Multi-Select Dropdown in InfluxDB Admin Users and Roles tabs from losing selection state

---

ui/src/shared/components/FeatureFlag.tsx
ui/webpack/dev.config.js

Closes #3072 
We would like a way to hide features in production and show them in development
Create a component which will show its children only if the user is in development. 
```
<FeatureFlag name="ifql-builder">
...new sweet feature
</FeatureFlag>
```
Name prop is optional and does nothing but convey which feature is flagged.

Feature Flag with this one weird trick

---

CHANGELOG.md
ui/src/shared/components/LineGraph.js

Connect #3026 
LineGraph was not passing the proper prop '`fillGraph: true`' to Dygraph.  
Add it

Fix graph fill bug: Other graphs hate him

---

CHANGELOG.md
ui/src/admin/components/chronograf/AllUsersTableRow.js
ui/src/admin/components/chronograf/UsersTableRow.js

Connect #2813 
- Deleting a user from the `All Users` table throws an error
- Used a plain JS arrow function instead of lodash's `.curry`
- Made current org table delete UX consistent with all users table

Fix Delete Button in All Users Admin Table

---

ui/jest.config.js
ui/test/setup.js
ui/test/setupTests.js

React virtualized imported react with `*` this causes deprecation warnings.  Please see [this](https://github.com/facebook/flow/issues/4673) issue for more info.  
Hack that I found [here](https://github.com/bvaughn/react-virtualized/issues/1037#issuecomment-371615531).  Basically, before tests run, remove `createClass` and `PropTypes` from the React API.  
This only effects tests, will still get warnings in dev / prod builds.

Fix test warning spam

---

CHANGELOG.md
ui/src/dashboards/reducers/ui.js
ui/test/dashboards/reducers/ui.test.js

Runtime error in the 'EDIT_TEMPLATE_VARIABLE_VALUES' reducer
was causing the list not to populate
Co-authored-by: Andrew Watkins <andrew.watkinz@gmail.com>
Co-authored-by: Brandon Farmer <bthesorceror@gmail.com>
Connect #1551 
Was [this line](https://github.com/influxdata/chronograf/pull/3101/files#diff-1fa97645dc91f23845c492c6de56cf76L292) causing a runtime error if there were no template variable values to index upon.
- Add a test for this particular case
- Refactor [this line](https://github.com/influxdata/chronograf/pull/3101/files#diff-1fa97645dc91f23845c492c6de56cf76L292) to use `_.get`
Most of the changes in the non-test code is a refactor to make the reducer a bit more readable.

Fix templateVariables not loading properly.  Other variables were amazed

---

CHANGELOG.md
ui/src/dashboards/actions/index.js
ui/src/dashboards/components/DashboardsPageContents.js
ui/src/dashboards/components/DashboardsTable.js
ui/src/dashboards/containers/DashboardsPage.js
ui/test/dashboards/reducers/ui.test.js

Closes #3102 
- Creating dashboards from scratch every time is time consuming and frustrating
- User can "Clone" dashboards from the dashboards index view

Add Ability to Clone Dashboards

---

.github/PULL_REQUEST_TEMPLATE

This is mainly to update `Connect` to `Closes` so that GH automatically closes issues when their corresponding PRs are merged. Second, I've moved the checklist to the bottom because I believe that they're less important than the description that the author puts forth. Third, I expanded the description prompts to something slightly more friendly.

Update PR template: Use GH Keyword; Reorganize/compact sections

---

ui/src/dashboards/components/template_variables/Row.js

- Dropdown and TemplateQueryBuilder components require that a function
is passed to them, where as TableInput requires that a function builder
is passed to them for starting editing

Fixes template variable editing not allowing saving

---

CHANGELOG.md
ui/src/kapacitor/components/TickscriptEditorControls.js
ui/src/kapacitor/containers/TickscriptPage.js

Closes #3019 
Since new TICKscripts do not yet have IDs, the router uses `/new` as a placeholder. When the newly created TICKscript response comes back I use the ID and redirect to the editor
When you create a new TICKscript you are stuck in the "New" mode and any changes don't affect the script you think it does
Redirect user to the location of their new script

Fix saving of new TICKscripts

---

CHANGELOG.md
ui/src/dashboards/components/VisualizationName.js

Closes #3065 
In the Cell Editor Overlay the cell's name is always an input. Confirming or cancelling changes can be handled by closing the overlay
Users want more freedom when editing a cell's name. Having to hit enter to save was too restricting
Replace the fancy input with a plain input

Improve Cell Renaming

---

bolt/change_interval_to_duration.go

In each migration we save a snapshot of the protobuf type information present in the codebase at the time the migration is defined. In an effort to cut down on the _amount_ of content that's copied/pasted, we've opted to obscure some of the non-pertinent type information. This allows us to include just as much of the type tree as is necessary to run the migration, while also keeping the signal-to-noise ratio high in the file.
To gloss over type information, we can replace it with `[]byte`. I was under the impression that `string` is effectively the same thing in go, but I am wrong! The former allows the marshal/unmarshal steps of the migration to pass a field through untouched, whereas the latter will effectively erase it.

Correct type information in migration

---

CHANGELOG.md
influx/queries/select.go
influx/queries/select_test.go

- \. was not being escaped properly
Closes #3115

Fixes literal expression json serialization

---

CHANGELOG.md
ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/index.tsx
ui/src/utils/basepath.ts
ui/src/utils/nodes.ts
ui/test/utils/basepath.test.ts

Closes #3141 
Factor out getting the root node and getting basepath into dedicated utils functions. Ensure that if basepath prefix is set, that it is properly stripped when using `router.push` in Data Explorer.
Data Explorer couldn't be used when basepath prefix was set and on, when passing in an InfluxQL query via URL query param, because when the component would mount it would double the prefix accidentally.
Strip the prefix so that it only appears once, as intended, when passing in a query to Data Explorer.

Ensure correct basepath prefix in URL pathname when passing InfluxQL query param to Data Explorer

---

ui/src/dashboards/components/CellEditorOverlay.js
ui/src/dashboards/components/DisplayOptions.js
ui/src/dashboards/components/GraphOptionsCustomizableField.tsx
ui/src/dashboards/components/TableOptions.tsx
ui/src/dashboards/components/Visualization.js
ui/src/shared/components/RefreshingGraph.js
ui/src/shared/components/TableGraph.js
ui/src/utils/timeSeriesTransformers.js
ui/test/dashboards/components/GraphOptionsCustomizableField.test.tsx
ui/test/dashboards/components/TableOptions.test.tsx
ui/test/utils/timeSeriesTransformers.test.js

In TableGraphs and TableOptions, use the query configs to get the fieldNames instead of dataLabels. 
FieldNames weren't getting populated until a user clicked on Visualization.
Use QueryConfigs instead of getting the labels from the timeSeriesTransform functions.

Table/Get FieldNames from query config

---

ui/src/dashboards/constants/cellEditor.js
ui/src/shared/components/Dygraph.js
ui/src/shared/components/SingleStat.js
ui/src/shared/constants/colorOperations.js
ui/src/shared/parsing/lastValues.js

Closes #2738 
When the user chooses a `line-plus-single-stat` cell type there is some unexpected behavior. This is partially because the behavior is not accurately reflected in the UI. Choosing a color set from the dropdown has to apparent effect.
`line-plus-single-stat` cells now use line colors instead of single stat colors. Additionally, the single stat inside gets its coloration from the first color in the selected line colors set.

Polish/Line+SingleStat Colors

---

ui/src/style/components/dygraphs.scss

Closes #3171 
Legend timestamp occasionally wraps, is large font size
Prevent timestamp from wrapping, make font size slightly smaller

Prevent legend text from wrapping

---

CHANGELOG.md
oauth2/generic.go
oauth2/generic_test.go
oauth2/github.go
oauth2/github_test.go

If an account had multiple emails, the current implementation would
always select the first one regardless of any other settings. This fixes
it so it only chooses the primary email address that is verified.

Require that emails on GitHub & Generic OAuth2 principals be verified & primary, if those fields are provided

---

CHANGELOG.md
ui/src/dashboards/actions/index.js
ui/src/shared/copy/notifications.js

Closes #3197 
Display notification when user adds, deletes, or clones a cell.
In some cases the location for a new or cloned cell is below the visible area and it is unclear if the action succeeded
Display a notification for cell actions (add/delete/clone) so there is more consistent system feedback

Notify when User adds, deletes, or clones a cell

---

bolt/change_interval_to_duration.go

declaring all migration-irrelevant types as []byte may erase data
for repeated protobuf fields. we hoped that "obscuring" the original
types of these columns with []byte would pass-through their values
unchanged, allowing us to omit entire types (and their descendent
trees) that were not being operated on in a migration. Fewer imported
types would lead to a more expressive migration file whose intent was
more clear to the reader. We will need to experiment with other ways
to achieve this in the future.
fixes #3200

fix(migration): Snapshot all struct types

---

ui/src/kapacitor/components/TickscriptEditorControls.js

Render TICKscript name instead of ID, but render ID if there is no name
Closes #3166
Render the TICKscript name instead of ID in the editor
Editor controls were rendering the `id` of the script, which in the case of editing an Alert Rule is a long unfriendly string
Render the TICKscript name instead of ID in the editor

bugfix/TICKscript name instead of ID

---

CHANGELOG.md
ui/src/dashboards/containers/DashboardPage.js
ui/src/dashboards/utils/time.ts
ui/test/dashboards/utils/time.test.ts

Fixes now() time parsing when requesting annotations

---

ui/src/dashboards/utils/cellGetters.js

Add new/cloned cells to the next available space in the dashboard, instead of always forcing it to the bottom
New/cloned cells appear to stack along the left side when there is plenty of space available to the right
Locate the bottom-right cell and depending on the new cell's size and available space to the right, add it there or to the bottom

Improve box packing for New and Cloned cells

---

.github/PULL_REQUEST_TEMPLATE

Our swagger docs are very out of date, defeating their purpose. We've discussed making this a requirement for any PR that modifies Go structs or the API. Now the PR Template will include a checkbox for doing so where relevant.

Update PR template to include checkbox for Swagger docs

---

CHANGELOG.md
ui/src/shared/graphs/helpers.js
ui/src/style/components/dygraphs.scss
ui/src/style/components/static-legend.scss
ui/src/style/components/table-graph.scss
ui/src/style/pages/dashboards.scss

After a cursory survey it seems that smaller font sizes in the dashboard are still legible. The advantage is a slight increase is space efficiency

Shrink Dashboard Text

---

CHANGELOG.md
ui/src/admin/components/chronograf/OrganizationsTableRow.tsx
ui/src/dashboards/components/TableOptions.tsx
ui/src/kapacitor/components/KapacitorForm.tsx
ui/src/kapacitor/components/TickscriptEditor.js
ui/src/kapacitor/components/TickscriptID.js
ui/src/kapacitor/containers/TickscriptPage.tsx
ui/src/shared/components/Crosshair.js
ui/src/shared/components/Notification.js
ui/src/shared/copy/notifications.js

Allows users to select tickscript editor with mouse

---

ui/src/style/components/code-mirror-theme.scss

Closes #3257 
Update the codemirror theme styles to use the classname provided by the newest version of codemirror
- TICKscript editor overflows, obscuring the console below it
- TICKscript editor no longer overflows

Fix TICKscript Editor Overflow

---

ui/src/dashboards/actions/index.js
ui/src/dashboards/constants/index.js
ui/src/dashboards/containers/DashboardsPage.js
ui/src/dashboards/utils/cellGetters.js
ui/src/shared/copy/notifications.js
ui/test/dashboards/reducers/cellEditorOverlay.test.js

Closes #3258 
Show the newly created cell's name in the corresponding notification
When a new dashboard is created, ensure its included cell has a name
- The new cell notification assumed all new cells have the same name
- The untitled cell constants were defined ahead of their use in the new dashboard template, causing the included cell to have an empty string for a name
- Pass new cell's name into notification
- Move a bunch of constants from `cellGetters` to where they belong in `dashboards/constants/index`

Show New Cell's Name in Notification

---

ui/src/dashboards/constants/templateControlBar.js

Closes #3275 
Ensure template variable dropdowns are sized correctly
The dropdown's size isn't getting calculated correctly
Pass the `value` key into `calculateSize` instead of passing the whole object

Fix Jittery Template Variable Dropdowns

---

ui/src/kapacitor/components/AlertTabs.js
ui/src/shared/apis/index.js

Fix deprecation typo
Ran prettier

Fix Deprecation to say PagerDuty v1 instead of v2

---

ui/src/shared/apis/index.js
ui/src/shared/components/AutoRefresh.js

Closes #3293
Dygraphs were calling a function on update that updated a grand parent component's state which tickles down to updating the dygraph and calling the function again

Prevent dygraph from continously updating

---

ui/src/data_explorer/containers/DataExplorer.tsx
ui/src/shared/components/InvalidData.tsx
ui/src/shared/components/LineGraph.js

Closes #3251
Special error handling for line graphs, specifically addressing when there is non numerical data returned from the query

Add custom error handling for line graphs

---

CHANGELOG.md
ui/src/dashboards/containers/DashboardPage.js

Closes #3332
Populate the template variable values as the last thing that happens after DashboardPage mounts so that the values do not get overwritten.
The dashboard was getting saved to the server and updated in redux after the template variable values were getting populated. During that save to the server, all but the selected template variable values were getting removed, and since that was also getting saved into redux, the dashboard that was rendered had only the selected values in the template variables.

Load all template variable values

---

ui/src/shared/components/Dygraph.js

Closes #3359 
Crosshairs need refs to render, but refs are not set until componentDidMount, after which a re-render does not happen until user interaction. 
force a single rerender at the end of componentDidMount, by setting state on an "isMounted" variable.

Rerender dygraph after ref is set to render crosshairs

---

ui/src/shared/components/TableGraph.js

Closes #3364
fieldOptions were not getting set at mount
set fieldOptions at mount.

Set redux field options at table mount

---

ui/src/kapacitor/containers/TickscriptPage.tsx

Closes #3224 
We are logging warnings in an expected and needed catch.
Stop throwing the warning and spamming the console.

Remove logging for expected failure states

---

ui/src/dashboards/components/TagKeyDropdown.js
ui/src/dashboards/components/template_variables/TemplateQueryBuilder.js

TagKeyDropdown uses source provided by props instead of context

---

CHANGELOG.md
Gopkg.lock
Gopkg.toml
kapacitor.go
server/kapacitors.go
server/kapacitors_test.go
ui/src/kapacitor/components/AlertTabs.js
ui/src/kapacitor/components/AlertTabs.tsx
ui/src/kapacitor/components/HandlerOptions.js
ui/src/kapacitor/components/config/AlertaConfig.tsx
ui/src/kapacitor/components/config/HipChatConfig.tsx
ui/src/kapacitor/components/config/OpsGenieConfig.tsx
ui/src/kapacitor/components/config/PagerDutyConfig.tsx
ui/src/kapacitor/components/config/PushoverConfig.tsx
ui/src/kapacitor/components/config/RedactedInput.tsx
ui/src/kapacitor/components/config/SlackConfig.tsx
ui/src/kapacitor/components/config/TalkConfig.tsx
ui/src/kapacitor/components/config/TelegramConfig.tsx
ui/src/kapacitor/components/config/VictorOpsConfig.tsx
ui/src/kapacitor/constants/index.js
ui/src/shared/components/Tabs.tsx
ui/src/types/kapacitor.ts
vendor/github.com/influxdata/kapacitor/CHANGELOG.md
vendor/github.com/influxdata/kapacitor/Dockerfile_build_ubuntu32
vendor/github.com/influxdata/kapacitor/Dockerfile_build_ubuntu64
vendor/github.com/influxdata/kapacitor/alert.go

Closes #2929
Add config in UI for OpsGenie v2
Update kapacitor dependency to 1.5 rc 2

Add OpsGenie v2 to UI

---

CHANGELOG.md
oauth2/generic.go
oauth2/generic_test.go

In #3168, 43c5afe7 introduced the same change to GitHub-specific OAuth as it did for Generic OAuth based on assumption that Generic Oauth would benefit from the same `.Primary` and `.Verified` checks, but it ended up breaking GitHub Enterprise via Generic OAuth. The change should only have been applied to GitHub-specific OAuth. This PR reverts the changes made only to Generic OAuth, which was confirmed to fix the issue for the user.
Closes #3388

Fix Generic OAuth bug for GitHub Enterprise where the principal was incorrectly being checked for email being Primary and Verified

---

ui/src/shared/components/AutoRefresh.tsx
ui/src/shared/components/Layout.js
ui/src/shared/components/LayoutCell.js

Closes #
AutoRefresh would preprocess data for csv download before it was required, and block render during expensive calculation. 
Perform data transformation for csv download at button click.

Perform expensive transformation for csv data at time of request

---

ui/src/shared/copy/notifications.js

Closes #3197 
cloning a cell notified the user that a cell with _original_ cell's name was added to dasboard. 
cloning a cell notifies the user that a cell with _cloned_ cell's name was added to dashboard.

Change clone cell notification to reflect cloned cell name

---

ui/src/kapacitor/components/DataSection.js
ui/src/shared/components/FieldList.tsx

Closes #3355 
- The FieldList component was broken, and the Kapa rule builder page would thus go blank, due to a change in React 16 context API.
- Update the `DataSection` & `FieldList` components to use React 16's context API.

Fix consuming source from context in FieldList

---

CHANGELOG.md
ui/src/style/pages/tickscript-editor.scss

Closes #3324
The editor of TICKScripts wasn't adjusted to window's width and it created scroll on all the UI instead of just in the editor.
Adding a max-width in the container of the editor

Limit max-width to TICKScript editor

---

ui/src/kapacitor/components/handlers/KafkaHandler.tsx

Closes #3448 
Kafka alert handler UI was missing a `Save/exit this rule and go to Config` button.
Add it, just like the others.

Add 'go to config' button to Kafka alert handler

---

ui/src/kapacitor/components/LogsTableRow.js

Closes https://stackoverflow.com/questions/50274447/how-to-debug-batch-query-in-kapacitor
Previously only "msg" field was displayed for kapacitor "batch point" with `| log()` (https://docs.influxdata.com/kapacitor/v1.4/nodes/log_node/) which is inconvenient for debugging batch query
Now we see all tags and values for "batch point" too and we don't need to run `kapaciot watch <task_id>` for debugging

Show kapacitor batch point info in log panel

---

ui/src/kapacitor/components/RuleHandlers.tsx

When a new alert rule was getting built, the code didnt take into account that there isnt a selected handler
Check to make sure there is a handler

Fix NewRuleHandler Bug

---

CHANGELOG.md
ui/src/kapacitor/components/TasksTable.tsx
ui/test/kapacitor/components/TasksTable.test.tsx

Closes #3455
Rows were being sorted by task id instead of by name
Sort rows by task id

Order tickscript names

---

kapacitor.go
server/swagger.json
ui/src/kapacitor/components/AlertTabs.tsx
ui/src/kapacitor/components/HandlerTabs.tsx
ui/src/kapacitor/components/config/SlackConfig.tsx
ui/src/kapacitor/components/config/SlackConfigs.tsx
ui/src/types/kapacitor.ts

Fixes remaining bugs with multi slack handlers

---

ui/src/shared/components/LayoutCell.tsx

Closes #
TS error following merge of tables to TS PR. 
Use common type definitions for same data.

Use predefined TimeSeriesServerResponse type in LayoutCell

---

ui/src/shared/components/TableGraph.js

Closes #
Changing table options sorting would not change sort order in tables. 
Fix logic in props comparison for tables.

Fix sorting bug in tables

---

CHANGELOG.md
ui/src/shared/data/timeRanges.ts
ui/src/utils/buildQueriesForLayouts.ts

Closes #3517
Update the buildQueriesForLayouts function to add upper bounds to queries when necessary.
Cells with queries that were not parseable into a query config were not getting an upper time bound like cells with query config parseable queries. Therefore, the upper time bound was defaulting to now().
If a query was not able to be parsed into a query config, it was using 'time > :dasbhoardTime:' in the query, and it was not already using :upperDashboardTime", an upper bound of 'time < :upperDashboardTime:' is added to the WHERE clause of the query.

Ensure Cells show only data from TimeSelector Constraints

---

ui/src/shared/components/ColorScaleDropdown.tsx

Closes #3557 
Color scale dropdown in line graphs does not open, which prevents the user from changing the color scale
Add a `maxHeight` prop to the fancy scrollbar inside the dropdown

Fix Color Scale Dropdown

---

CHANGELOG.md
ui/src/dashboards/components/GaugeOptions.js

Closes #3569 
User cannot change colors in Gauge thresholds. Color Dropdown was working fine but the handler function passed into it had an extra closure which prevented the update from firing.
Remove the extra closure

Fix Gauge Color Selection

---

ui/webpack/dev.config.js

When using a devtool (verified in Chrome or Firefox), source maps were not mapping back to the actual code as-written. Instead, an ES5 transpilation was being shown. This made debugging using the devtools a huge headache, and effectively untenable.
Change webpack's source map option to make the dev tools (verified in Chrome and Firefox) reflect exactly the code as-written. Specifically, the solution was to switch from `devtool: cheap-eval-source-map` to `devtool: eval-source-map` in `ui/webpack/dev.config.js`.
The only cost of this that I see is, as stated in the webpack docs, that initial build may take slightly longer. However, rebuilding should be quicker, and this is a minor cost in the scheme of the ability to debug effectively. See …

Fix source maps to exactly reflect code instead of es5 transpilation

---

ui/src/flux/components/TagListItem.tsx
ui/src/flux/components/TimeMachineEditor.tsx
ui/src/flux/containers/FluxPage.tsx
ui/src/style/components/time-machine/flux-editor.scss

- Updates the AST as the user types.  This provides almost instantaneous feedback to the user for syntax error reporting.  Additionally, this 'builds' the builder as the user types.
- Adds more robust error reporting:

Flux Page Error Robustness

---

ui/src/flux/apis/index.ts
ui/src/flux/components/TimeMachineTable.tsx
ui/src/flux/constants/index.ts
ui/src/flux/containers/FluxPage.tsx
ui/src/shared/copy/notifications.ts
ui/src/shared/parsing/flux/response.ts
ui/test/shared/parsing/flux/constants.ts
ui/test/shared/parsing/flux/results.test.ts

A user can enter a Flux query that returns a response too large to render. For example,
```
from(db: "telegraf") |> range(start: -24h)
```
will crash or lock up the browser. We would like to implement pagination in the table visualization as a way to limit the size of responses, but the necessary prerequisites aren't available from platform.
This PR implements a stopgap solution—we only parse the first 10 MB of data returned by a Flux query, and drop the rest. When dropping data, we display a notification to the user:
This PR also includes a performance enhancement to the `TimeMachineTable`, so that it can render 10 MB of data smoothly. Previously, a bottleneck in the `TimeMachineTable` meant each scroll took several seconds:
With these changes, a scroll event now takes about 20ms:

Improved handling of large Flux query responses

---

ui/src/flux/components/DatabaseListItem.tsx
ui/src/flux/components/TagList.tsx
ui/src/flux/components/TagListItem.tsx
ui/src/flux/components/TagValueListItem.tsx
ui/src/style/components/time-machine/flux-explorer.scss

Every list item in the Flux schema explorer is either open or closed, and each list item can contain as children many other list items. Previously, closing a list item would close all of it's children. Reopening a child that had been closed because one of its ancestors had been closed would still trigger a meta-query request and subsequent loading state, even though that necessary data had been previously fetched.
This PR changes the schema explorer so that the open state of a child item is persisted even its ancestors are opened and closed. This is best explained in pictures:
Before:
After:
These changes eliminate duplicate meta-query requests and result in a better UX.

Preserve schema tree children open state

---

ui/src/style/components/time-machine/flux-explorer.scss

The “Copy” button in the Flux schema explorer was being hidden on small screens.
Before:
After:
Closes #3610

Ensure schema explorer copy button visible

---

influx/templates.go
influx/templates_test.go

Closes #3317.
Template variables used within an InfluxQL regular expression would be improperly quoted in certain cases. For example, the query:
```
SELECT "usage_active" FROM "telegraf"."autogen"."cpu" WHERE host =~ /:host:/ AND time > :dashboardTime: FILL(null)
```
would render as
```
SELECT "usage_active" FROM "telegraf"."autogen"."cpu" WHERE host =~ /'my-host.local'/ AND time > now() - 15m FILL(null)
```
but it should have rendered as
```
SELECT "usage_active" FROM "telegraf"."autogen"."cpu" WHERE host =~ /my-host.local/ AND time > now() - 15m FILL(null)
```
Only certain kinds of template variables may used in an InfluxQL regular expression, according to the docs [here](https://docs.influxdata.com/influxdb/v1.5/query_language/spec/#regular-expressions). For these types of template …

Fix rendering of template variables within regexes

---

ui/src/shared/components/Dygraph.tsx

Closes #3632 
- Typescript has built in support for a React component's `children` prop.
- The `children` prop is [“opaque”](https://reactjs.org/docs/react-api.html#reactchildren), meaning in the most general case it is best accessed via the `React.Children` helpers.

Fix line graph + single stat dygraphs

---

ui/src/dashboards/actions/cellEditorOverlay.ts
ui/src/dashboards/components/Visualization.tsx
ui/src/types/dashboard.ts

Closes #
There was a redundant interface defined. 
Removed it.

Remove redundant FieldName in favor of FieldOption interface

---

ui/src/flux/components/ExpressionNode.tsx
ui/src/flux/components/FuncArg.tsx
ui/src/flux/components/FuncArgInput.tsx
ui/src/flux/components/FuncArgs.tsx
ui/src/flux/components/FuncNode.tsx
ui/src/style/components/time-machine/flux-builder.scss
ui/test/flux/components/FuncArg.test.tsx

Closes #3679 
Closes #3675 
Closes #3674 
Hovering over a function node no longer triggers a tooltip, and instead reveals two buttons to the right of the node: `Toggle Yield` and `Delete`. Clicking the function node now toggles edit mode, which appears below the function. When a new function is created it is in edit mode by default (for discoverability purposes)

Improve Flux Editor UX

---

CHANGELOG.md
ui/src/kapacitor/components/KapacitorRulesTable.tsx
ui/src/style/theme/_tables.scss

Closes #3641 
When an alerts have long message contents the index table becomes difficult to use
Create a CSS helper class for truncating text in tables and implement on the alert rules table

Truncate Alert Rule Message Preview

---

CHANGELOG.md
ui/src/data_explorer/components/QueryEditor.tsx
ui/src/external/codemirror.js
ui/src/shared/constants/codeMirrorModes.ts
ui/src/style/components/code-mirror/_influxql.scss
ui/src/style/components/code-mirror/theme.scss
ui/src/style/components/query-editor.scss

Replace the (very restrictive) `<textarea>` in the Data Explorer query field with a Code Mirror instance while maintaining existing functionality. Added a basic syntax highlighter. You can create new lines in the query but they disappear when the page is refreshed. Pressing the `Enter` key creates a new line and `Ctrl+Enter` or `Cmd+Enter` will submit the query. As a fallback I have added a manual `Submit Query` button.
Inability to implement syntax highlighting or true type suggestions
Use codemirror for maximum awesome

Upgrade Data Explorer Query Field with CodeMirror2

---

ui/src/kapacitor/components/KapacitorRule.js
ui/src/shared/copy/notifications.ts

Kapacitor Rule creation fails without clear message to the user ("_Alert could not be created_").   for example, create a rule with an invalid template (no dot), e.g. `{{TaskName}}`.       No way for the user to know what happened unless one looks at the dev-tools.
Proper response, like rule edit.

fix(alert): alert creation detailed response

---

CHANGELOG.md
server/server.go
server/server_test.go

Closes #3687
A user reported that removing `-` as a valid char in basepath broke their basepath configuration. This PR is a stopgap until we implement all valid URL paths, which is in flight. I've opened up https://github.com/influxdata/chronograf/issues/3699 for the full fix.
Update the basepath validator regex to include hyphens, and test for numbers, hyphens, and underscores.

Fix allowing hyphens in basepath

---

ui/src/tempVars/constants/index.ts

The default template for a CSV template was missing a `query` property (since it's not relevant to a CSV template variable). This caused the following error when attempting to rehydrate a CSV template variable:
```
TypeError: Cannot read property 'influxql' of undefined
at eval (index.ts:722)
at Array.filter (<anonymous>)
at _callee13$ (index.ts:720)
at tryCatch (runtime.js:62)
at Generator.invoke [as _invoke] (runtime.js:296)
at Generator.prototype.(:8080/sources/1/dashboards/anonymous function) [as next] (webpack-internal:///./node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
at eval (tslib.es6.js:85)
at new Promise (<anonymous>)
at Module.__awaiter (tslib.es6.js:81)
at eval (index.ts:710)
_callee13$ @ index.ts:754
```
_What was the …

Fix template variables missing query bug

---

ui/src/dashboards/utils/tempVars.ts

_What was the problem?_ 
Function assume template variables had a value. Now uses a getter to take into account of when it does not.

Fix type error when temp vars have no values

---

ui/src/flux/components/FilterArgs.tsx
ui/src/shared/apis/flux/metaQueries.ts
ui/src/types/promises.ts
ui/src/utils/promises.ts

Closes #3638 
A handler for an AJAX request made by the `FilterArgs` was creating errors in the console because it was attempting to update state on an unmounted component.
Introduce a `makeCancelable` utility for promises and use this to wrap the AJAX request and reject the AJAX response promise when the component is unmounted.

Cancel FilterArgs response on unmount

---

ui/src/tempVars/components/TemplateVariableEditor.tsx

Displays different copy in the template variable editor depending on whether a user is creating a new template variable, or editing an existing one.

Improve save button copy in TemplateVariableEditor

---

ui/src/flux/apis/index.ts
ui/src/flux/components/ExpressionNode.tsx
ui/src/flux/components/FuncArg.tsx
ui/src/flux/components/FuncArgInput.tsx
ui/src/flux/components/FuncArgs.tsx
ui/src/flux/components/FuncNode.tsx
ui/src/flux/containers/FluxPage.tsx
ui/src/shared/parsing/flux/response.ts
ui/src/types/flux.ts

Closes #3681
Toggling a yield func before filter and range funcs require a `last()` before the yield to avoid crashing the browser. The implicit yield functionality was conflicting with toggling a yield with last() before it.
It was not previously handling yields manually entered in the script  before a filter and range.
No longer showing implicit yields
Checking the next index func in script to see if it's a yield before rendering to avoid duplicate yields.

Fix unable to toggle yields

---

ui/src/flux/components/ExpressionNode.tsx
ui/src/flux/components/FuncNode.tsx
ui/src/flux/containers/FluxPage.tsx
ui/src/types/flux.ts

Closes #3665
When a func node was deleted it would not remove the yield node. This could cause a yield to run on part of a script unexpectedly and could be slow if it didn't follow a filter and range.
Deleting a func node removes an associated yield node from the script or toggles the index of a yield with last in the expression node state.

Delete func node and yield in builder

---

ui/src/flux/components/ExpressionNode.tsx

A change in [`ExpressionNode`](https://github.com/influxdata/chronograf/pull/3730/files#diff-0e4c943c072bd44f822dee6e638560c6) rendering in 3730 did not include the yield node from the script when present and yielded results were not displaying their name from the script.
Check for yield node in script and render `YieldFuncNode` with this func so it can derive the correct `yieldName`.

Fix expressions to display yield name in script

---

ui/src/flux/components/YieldFuncNode.tsx

Rendered yield data only currently happens on component mount and this
update checks for a script update to fetch yield results.
Yield nodes were receiving new script props but data was not getting rendered. Scripts would change and users would have to toggle yields to see new results.
Check when the script prop did update, fetch the script results, and update yield node state to see the results.

Render data when yield node receives new script

---

ui/src/style/components/edit-template-variable.scss
ui/src/tempVars/components/TemplateVariableEditor.tsx

Before:
Move... that... bus! After:

Fix display of TemplateVariableEditor header

---

CHANGELOG.md
ui/src/shared/components/Crosshair.tsx

Closes #3715
Dygraph was figuring out where the crosshair would be on a graph even if that time was past or before the range of the current graph.
Ensure that the hovertime is within the time range on the graph and don't display it otherwise.

Ensure hoverTime is a valid time range for the dygraph

---

ui/src/index.template.html

Signed-off-by: Lorenzo Fontana <lo@linux.com>
The body template was closed twice
Close the body template only once

Fix: Close main template body only once

---

CHANGELOG.md
ui/src/dashboards/components/AxesOptions.js

Closes #3746
Add raw as the default option for base instead of having an unselected tabs. To get rid of the other two formats, select raw.
Set default for scale to be linear so deselection.

Change axes options to have valid defaults

---

ui/src/shared/components/OverlayTechnology.tsx
ui/test/tempVars/components/TemplateControlDropdown.test.tsx

Check out this bit of the `OverlayTechnology` component:
https://github.com/influxdata/chronograf/blob/3e046839e1e59d328c6cf64f39d59af47e21934a/ui/src/shared/components/OverlayTechnology.tsx#L25-L37
This happens right after a render. The call to `this.showChildren()` sets some state, which schedules another render that will read the state and actually display the children.
The test was [attempting to assert after the first render](https://github.com/influxdata/chronograf/blob/3e046839e1e59d328c6cf64f39d59af47e21934a/ui/test/tempVars/components/TemplateControlDropdown.test.tsx#L42), but before the second. Thus the children had not rendered yet and the assertion failed.
I fixed the test by reducing the double render in the `OverlayTechnology` component to a single render via the use of …

Tweak OverlayTechnology lifecycle and fix test

---

ui/src/shared/components/DragAndDrop.tsx
ui/src/style/components/drag-and-drop.scss

Co-authored-by: Alex Paxton <thealexpaxton@gmail.com>
Co-authored-by: Deniz Kusefoglu <deniz@influxdata.com>
Closes #
drag and drop was creating a new div with a high z-index to listen to drag and drop events on, the high z-index would block functionality buttons or other ui elements underneath. We added event listeners to window instead. It works, and is better :)

Refactor drag and drop to listen for events directly on window.

---

server/swagger.json

Closes #3777.
This is an API proposal for solving: https://github.com/influxdata/chronograf/issues/3713 and https://github.com/influxdata/chronograf/issues/3714. 
The user needs a way to configure their log viewer display settings and persist it on the backend per organization. 
This PR uses the existing config/:section endpoint and introduces a Swagger definition (`LogViewerConfig`) for a new section (`logViewer`). This config has two properties: a `columns` array and a `columnOptions` object with a `severity` property that defines the colors and names for the severity levels associated with logs.

Add a swagger definition for UI config settings and API Routes

---

ui/src/logs/actions/index.ts
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/reducers/index.ts
ui/src/shared/components/HistogramChart.tsx
ui/src/style/components/histogram-chart.scss
ui/src/types/logs.ts
ui/test/shared/components/HistogramChart.test.tsx
ui/test/shared/components/__snapshots__/HistogramChart.test.tsx.snap

Should be merged after #3785
Previously, the loading state for the histogram and table in the log viewer were separate. This PR unifies the loading states so that the loading spinner will display if _either_ the table or histogram is loading.

Unify log viewer loading state

---

CHANGELOG.md
ui/src/dashboards/containers/DashboardPage.tsx
ui/src/hosts/containers/HostsPage.js

Closes #3763
in hosts page, set interval was happening after async requests and if component was unmounted before the interval was set, the intervalID was undefined and clearinterval wasn't clearing the interval
add a property to the class to keep track of whether the component is mounted. If the component is getting unmounted before the interval is set, don't set the interval

Stop querying old sources

---

ui/src/data_explorer/components/Table.tsx
ui/src/data_explorer/components/VisView.tsx
ui/src/data_explorer/components/Visualization.tsx

Closes #3800 
Table Component was still using the vestigial `host` string
Use app source object for proxy requests for the table

Bugfix Meta Query DataExplorer

---

CHANGELOG.md
server/mux.go
server/server.go

Add profiling routes to chronograf server.
[Dashboards are slow](https://github.com/influxdata/chronograf/issues/3602) and in order to be able to diagnose the issue, we'll need access to the debug rotues.
Add profiling routes.

feat(server): add profiling routes to chronograf server

---

ui/src/shared/components/AutoRefresh.tsx

Closes #3576 
Multiple duplicate queries were being made in Dashboard cells after template variable values were loaded. 
The auto refresh wrapper compares current and previous templates, but filters out values that aren't selected or picked.

Fix each cell making multiple queries

---

ui/src/dashboards/containers/DashboardPage.tsx
ui/src/types/actions/dashboards.ts

Types and state that didn't seem to be used
Removing types and state related to dashboard page names that were not
caught by typescript.

Remove unused dashboardNames types and state

---

ui/src/status/containers/StatusPage.tsx

Status page was not making queries because its template Vars did not have localSelected values.

Add localSelected value to StatusPage constant template variables

---

ui/src/dashboards/utils/tableGraph.ts

Closes #3801 
The `columnWidths` object did not include / consider that times could be columns.  
Add times to the `columnWidths` object when they are in the 'topRow'.
Debugging this issue makes me sad.  There is SO much untested code that does SO much data transformation.  I have no idea if my solution breaks something else.
@russorat I recommend that we put aside dev time to test the `utils/tableGraph` at a minimum.

Fix table time as horizontal

---

ui/src/shared/components/AutoRefresh.tsx

The changes in #3829 removes the need for a guard in AutoRefresh componentDidMount and componentDidUpdate
Remove the check for localSelected values in AutoRefresh

Remove AutoRefresh check for local selected values

---

ui/src/dashboards/actions/index.ts
ui/src/dashboards/apis/index.ts
ui/src/dashboards/components/DashboardHeader.tsx
ui/src/dashboards/components/DashboardSwitcher.tsx
ui/src/dashboards/containers/DashboardPage.tsx
ui/src/dashboards/utils/dashboardSwitcherLinks.ts
ui/src/types/apis/dashboards.ts
ui/src/types/dashboards.ts
ui/test/dashboards/utils/dashboardNameLinks.ts

Putting dashboards in redux state from `DashboardPage` was clobbering the state for template variables.
Remove the redux dispatch for loading dashboards and replace it with an internal request to get dashboard links.

Add util for loading dashboard switcher links

---

ui/src/dashboards/actions/index.ts
ui/src/dashboards/containers/DashboardPage.tsx
ui/src/shared/copy/notifications.ts
ui/src/tempVars/apis/index.ts
ui/src/tempVars/components/TemplateControlBar.tsx

Closes #3833 
When a template variable used in a nested template variable is deleted, an error was thrown and the dashboard didnt render
Catch error and send notification of error

Handle deletion of a tempVar used in nested tempVar

---

ui/src/alerts/components/AlertsTable.tsx
ui/src/hosts/components/HostsTable.js
ui/src/style/components/tables.scss

Use span elements for icons instead of pseudo classes to be less susceptible to breakage when the icon font is changed

Bring back sort indicators in Hosts and Alerts tables

---

server/sources.go

Closes #3851
When a user ran a production build of Chronograf for the first time, the API for `GET /sources` returned
```
{"sources": null}
```
The client expects `“sources”` to be an empty array in this case (as documented by the [API docs](https://github.com/influxdata/chronograf/blob/dd7f8c2ecd0accd9b1a1fcfbc77e037df36849dd/server/swagger.json#L40-L45)). An app-breaking error ensued.
This PR ensures that `GET /sources` now returns
```
{"sources": []}
```
in the empty sources case.

Fix encoding of empty source responses

---

ui/src/data_explorer/apis/index.ts
ui/src/shared/apis/query.ts

Closes #3861
After #3782, the Chronograf server is no longer capable of handling queries with the “auto group by” template variable `:interval:`. Attempting to export a CSV for a query including `:interval:` from the Data Explorer would result in a `400` error.
If a query in the Data Explorer contains an `:interval:`, render that interval first before attempting to fetch data for a CSV export.

Support auto group by queries in Data Explorer

---

ui/src/shared/components/DatabaseList.tsx

Closes #3863
An infinite loop caused the Data Explorer to crash: `DatabaseList.componentDidUpdate` called a function which set state which triggered `DatabaseList.componentDidUpdate`. 
Guard against the function call better. I also removed an superfluous `setTimeout`.

Prevent infinite looping of API call

---

ui/src/data_explorer/components/Table.tsx
ui/src/data_explorer/components/VisView.tsx
ui/src/shared/actions/timeSeries.ts
ui/src/shared/apis/query.ts

Closes #3862 
Fetching cell data was using a `fetchTimeSeriesAsync` action that wasn't replacing `:interval:` in queries. 
Remove `fetchTimeSeriesAsync` and use `fetchTimeSeries` to retrieve results for a Table's cell data and replace `:interval:`. The `fetchTimeSeriesAsync` was also only used directly by `Table` and `fetchTimeSeries` so the most natural refactor was to move the `fetchTimeSeriesAsync` logic into the API call.

Fix Data Explorer fetch cell data

---

ui/src/shared/components/LayoutCell.tsx

If a template variable had no values, it replaced the string with the entire title instead of just the template variable name.
Replace the template variable with the template variable name if no values are used.

Fix template variables in title when no values

---

CHANGELOG.md
server/sources.go
server/swagger.json

Closes #3207 
Update health endpoint to return Status No Content.
The health endpoint was returning Status OK causing firefox to complain there was no content.  
Once the server returns a No Content, firefox is happy.

fix(server): health for source returns status no content

---

CHANGELOG.md
integrations/server_test.go
server/links.go
server/routes.go
server/routes_test.go
ui/src/logs/actions/index.ts
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/utils/config.ts
ui/test/fixtures/index.ts
ui/test/logs/utils/config.test.ts

Closes #3821
Changes to the log viewer (such as severity format and column name) were not being persisted on the backend.
Upon saving changes to the Log Viewer config in the Options Overlay, send a request to the server to update the Log Viewer property of the Organization Config with the new config.

Connect Logs Viewer page to API

---

ui/src/dashboards/apis/index.ts
ui/src/dashboards/containers/DashboardPage.tsx
ui/src/dashboards/utils/dashboardSwitcherLinks.ts
ui/test/dashboards/utils/dashboardSwitcherLinks.test.ts

Closes #3886
Dashboard links were stale after rename and had a stale active link when switching between dashboards.
Ensure dashboard links are updated when a dashboard is renamed. Also, ensure the active dashboard link is updated when a new dashboard is fetched using `updateDashboardLinks` which avoids an request using `getDashboards`.

Fix stale dashboard switcher

---

ui/src/logs/constants/index.ts
ui/src/logs/containers/LogsPage.tsx
ui/src/shared/components/HistogramChart.tsx
ui/src/shared/components/HistogramChartBars.tsx
ui/src/types/histogram.ts
ui/test/shared/components/HistogramChart.test.tsx
ui/test/shared/components/__snapshots__/HistogramChart.test.tsx.snap

Closes #3857 
Bars were sorted in order of how many counts of each severity level there were.
Sort bars by severity level.

Sort histogram bars and tooltip in the order of severity

---

ui/src/logs/components/LogViewerHeader.tsx
ui/src/logs/components/LogsTable.tsx
ui/src/logs/components/PointInTimeDropDown.tsx
ui/src/logs/containers/LogsPage.tsx
ui/src/logs/data/timePoints.ts

I am combining the time selector in the logs table with the time selection in the page header to form a single UI for selecting time in the logs viewer. Clicking a histogram bar also updates the logs table, and clicking a timestamp in the logs table updates the histogram. Both halves of the experience are more closely tied together now.

Unify Log Viewer Time Selection UI

---

ui/src/logs/components/LogsTable.tsx
ui/src/logs/components/expandable_message/ExpandableMessage.scss
ui/src/logs/components/expandable_message/ExpandableMessage.tsx
ui/src/style/pages/logs-viewer.scss

Closes Issue verbally discussed by @nhaugo.
Each row in logs table has set height and long messages are truncated. When the user clicks on a message, it opens in overlay on row.
The variable row height from wrapped log messages were problematic for the virtualized list.
Truncate long messages and display longer message in overlay.

Truncate log messages & display overlay when clicked

---

ui/src/shared/components/HistogramChart.tsx
ui/src/style/components/histogram-chart.scss
ui/test/shared/components/__snapshots__/HistogramChart.test.tsx.snap

This PR exposes a more powerful public API on the `HistogramChart` component, to facilitate some upcoming needs of @alexpaxton and @danielnelson. 
Scaling functions, dimensions, and other data computed by the `HistogramChart` is now passed to optional child render props. 
As an [example](https://github.com/influxdata/chronograf/commit/344a7aff8e9f99ada602cd452b3023139bbf403d) of how this can be used, we can now render a red line centered in the middle of the `HistogramChart` by doing something like:
```jsx
<HistogramChart
data={histogramData}
width={width}
height={height}
colorScale={colorForSeverity}
colors={histogramColors}
onBarClick={this.handleBarClick}
sortBarGroups={this.handleSortHistogramBarGroups}
>
{({adjustedWidth, adjustedHeight, margins}) => {
const x = margins.left + …
```

Yield histogram plot data to children

---

ui/src/tempVars/components/KeysTemplateBuilder.tsx
ui/src/tempVars/components/TagValuesTemplateBuilder.tsx

Closes #3830
Creating a “tag values” template variable, a user is presented a UI with three dropdowns:
Selecting the value of a dropdown triggers an asynchronous request to populate the subsequent dropdowns. When these requests complete, they set state on the `TagValuesTemplateBuilder`. 
Selecting dropdowns in rapid succession creates race conditions between asynchronous requests. If the requests fulfill in the wrong order, the draft template state (i.e. the template created when a user clicks “Create”) may be invalid (#3830).
This also happens with the two `KeysTemplateBuilder`s.
The final update to the draft template state now collects the appropriate values (stored as component state up until then), which ensures that the saved template …

Create / update template variables correctly
